### ISSUE TITLE
Zooming/panning on axis not working with AutoAdjustPlotMargins = false

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#10]
**Imported from [http://oxyplot.codeplex.com/workitem/9595](http://oxyplot.codeplex.com/workitem/9595)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2011-11-18 06:23
bug introduced with implementation of PositionTier

**[anomistu](http://www.codeplex.com/site/users/view/anomistu)** 2011-11-24 14:07
Other issues with AutoAdjustPlotMargins = false (you probably know about) are overlapping of tiers and axis title displayed within the plot area.

**[joemoorhouse](http://www.codeplex.com/site/users/view/joemoorhouse)** 2012-07-14 22:47
Seems to be just that the AdjustPlotMargins method of PlotModel does not get called with AutoAdjustPlotMargins = false. This should be called in the Render method (in PlotModel.Rendering.cs) in order to set PositionTierMinShift etc (which are ultimately
 required for zooming and panning). I tried rewriting the method slightly so that these properties can be set without adjusting the margin and it seems to do the trick. I now need to create a branch and figure out how to run tests to make sure all is well.

**Comment by tibel** [comment]
I cannot reproduce the issue in WPF.

Tested with:
```plotModel.PlotMargins = new OxyThickness(60, 4, 4, 40);```
