### ISSUE TITLE
Remove Avalonia XAML classes and the `Plot` control

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1006]
Since it will be a lot of work to maintain all these classes and examples/tests.
Keep the `PlotView` control of course.
Other XAML platforms (Xamarin.Forms, Silverlight) only implements the `PlotView`.

**Comment by jkoritzinsky** [comment]
The main goal of the Avalonia project is to provide equivalent APIs as WPF. Would you be interested in having the XAML classes if I can auto-generate most (if not all) of the code for the XAML classes that aren't the `Plot` control? I could make it extensible to other XAML platforms such as Xamarin.Forms (not sure about Silverlight).

**Comment by objorke** [comment]
I prefer to have the `PlotView` only at this time. All functionality of OxyPlot can be used without defining the plot in XAML. 
Code generation was discussed in #39.

**Comment by jkoritzinsky** [comment]
I see that #39 is still open. Is that still something on the roadmap? Would you be interested in me sending in a PR with codegen support?

**Comment by objorke** [comment]
It is in the backlog, but in my opinion it is not high priority. If it is not possible to generate 100% of the code, how would you define which properties/classes should not be generated? I guess custom  properties can be defined in partial classes. How would you create the tool? Console application? MSBuild task? T4 template? Regarding platforms, I think WPF, Avalonia, UWP, Xamarin Forms should be supported. No need to worry about Silverlight.

**Comment by jkoritzinsky** [comment]
Ok. I'll start drafting a possible spec for generating XAML classes. I'll comment again here once I've got something that seems solid.

**Comment by objorke** [comment]
The Avalonia code has been moved to https://github.com/oxyplot/oxyplot-avalonia

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-avalonia
