### ISSUE TITLE
Possible issue with UWP implementation

### ISSUE THREAD

**Issue by pawanvermadreamorbit** [oxyplot/oxyplot#1014]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.
2.
3.

Platform:
.NET version:

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by GeertvanHorrik** [comment]
@pawanvermadreamorbit we really need more info than this. I am using this library in UWP apps myself and it works fine.

**Comment by pawanvermadreamorbit** [comment]
Which version r u using tell me and version so that I would try that with Nuget manager

**Comment by GeertvanHorrik** [comment]
1.0.0 works fine. If you believe there is a problem, please follow the steps in the initial post (screenshot, ways to reproduce, etc).

**Comment by pawanvermadreamorbit** [comment]
its insalled in my app but how to call it in xaml page and registring in app file?

**Comment by GeertvanHorrik** [comment]
You can check out the Windows 10 examples in the repository. Did you write UWP apps before?

**Comment by pawanvermadreamorbit** [comment]
:) Yes  , I worked on UWP apps , Its working and implemented. Thanks :)
