### ISSUE TITLE
How do I use the mouse to draw line in the plotview? 

### ISSUE THREAD

**Issue by flypigeon** [oxyplot/oxyplot#1026]
I want to draw line  by the move mouse (Enviroment : Wpf ). How do I use the mouse to draw line in the plotview? And How do I Add Right click menu in the plotview?

**Comment by kuch3n** [comment]
Using the PlotController see: [source](https://github.com/oxyplot/oxyplot/tree/develop/Source/OxyPlot/PlotController). BindMouseDown for Events and use a MouseManipulator to draw the line (see PanManipulator) or draw a menu from code behind
And you have to use OxyPlot not OxyPlot.Wpf, support is pretty meh

**Comment by objorke** [comment]
I think there is an example in the example browser. 
Can we close this issue, I don´t think this is a bug or new feature.

**Comment by flypigeon** [comment]
thanks, i will try it .
