### ISSUE TITLE
Zoom reset behaviour with double-middle-click

### ISSUE THREAD

**Issue by dave2pi** [oxyplot/oxyplot#1027]
Back in OxyPlot 2014.1.240.1 double-middle-click on an axis would reset the zoom on that axis only. (In contrast to double-middle-click on the plot area, which reset the zoom on the whole plot).

Now in Oxyplot 1.0.0.0 double-middle-click on an axis resets the zoom on the whole plot.

Is this a regression? Or a new default property?

### Steps to reproduce
1. Generate a PlotType.XY plot.
2. Zoom in with scroll wheel over the middle of plot area.
3. Double-middle-click on a single axis.

### Expect
Expect zoom of clicked axis to reset. Expect zoom of other axes to be unaffected.

Platform:
WindowsForms
.NET version: 4.5.2

**Comment by objorke** [comment]
To me this sounds like a regression!
