### ISSUE TITLE
Possible Infinite Loop in LineAnnotation.GetPoints() when ActualMinimum=ActualMaximum

### ISSUE THREAD

**Issue by nzain** [oxyplot/oxyplot#1029]
### Steps to reproduce

1. Create a y-axis has StartPosition=EndPosition=0, but do not use LinearAxis (derived classes hit this issue, too)
2. Create a vertical LineAnnotation

Platform: any
.NET version: any

### Expected behaviour

No exception is thrown. Infinite loops have to be avoided at all times either by checking the increment or using a maximum iteration count.

### Actual behaviour

When either the X or Y Axis are _not_ instances of LinearAxis (thus, bool curvedLine is true), the line annotation produces not two but many points in LineAnnotation.GetPoints(). It produces an infinite "while (true)" loop because the increment is zero because ActualMaximum=ActualMinimum.

The result is a OutOfMemoryException:
![image](https://cloud.githubusercontent.com/assets/13961979/20960582/6e345480-bc61-11e6-9d40-4978c7cd7719.png)

### Suggested Fix Strategy
When ActualMaximum=ActualMinimum the GetPoints() method can quickly return an empty result.

**Comment by objorke** [comment]
That´s an interesting axis :-) There should be an example in the ExampleLibrary with start and end position at zero.
I agree this should be handled, no exception thrown.

**Comment by bryanfree66** [comment]
Can I take this one?

**Comment by nzain** [comment]
Feel free to take it.

The "interesting" axis was a simple trick to hide it. I think there is a "IsVisible" property, too - not sure why I did it this way. However, infinite loops are a no-go (even if you're "holding it wrong") and easy to avoid, too. Great library nevertheless :1st_place_medal:

**Comment by bryanfree66** [comment]
I'm ready to push the bug fix, but I get permission denied. I'm pushing to upstream branch bugfix-1029.

![git](https://cloud.githubusercontent.com/assets/6587437/25396443/69a24c7e-2999-11e7-896a-402b5caf40fd.png)
