### ISSUE TITLE
Graphs are not displaying every second time

### ISSUE THREAD

**Issue by MannusEtten** [oxyplot/oxyplot#1040]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. i made an uwp app, fill in a view the graph
2. move to another page in the app
3. go back to the page with the graph and the graph is missing
4. repeat step 3 & 4 and the graph is back...

Platform:
.NET version:

UWP
### Expected behaviour

always showing the graph 

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?
![screenhunter_71 dec 20 15 39](https://cloud.githubusercontent.com/assets/3999790/21354476/8be55074-c6ca-11e6-9533-2f4317917b52.jpg)
![screenhunter_72 dec 20 15 39](https://cloud.githubusercontent.com/assets/3999790/21354478/8be89ffe-c6ca-11e6-8cc7-f32e55eae825.jpg)
![screenhunter_73 dec 20 15 39](https://cloud.githubusercontent.com/assets/3999790/21354477/8be8b3ea-c6ca-11e6-8962-983fac6a28eb.jpg)

**Comment by objorke** [comment]
did you use the latest version from myget?

**Comment by MannusEtten** [comment]
i will check which version is in use now

**Comment by GeertvanHorrik** [comment]
Could it be related to #1079  ?

**Comment by MannusEtten** [comment]
i dont know the version anymore, i moved away from oxyplot to the library of telerik
