### ISSUE TITLE
Incorrect NuGet dependencies

### ISSUE THREAD

**Issue by MrCapuchino** [oxyplot/oxyplot#1041]
### Steps to reproduce

If you get oxyplot nuget packages from 
https://www.myget.org/F/oxyplot

When you install Oxyplot.XamarinForms, Oxyplot.Android and Oxyplot.iOS they required Oxyplot.Core 1.0 but for UWP it requires Oxyplot 2.0. This creates a conflict because I cannot install the libraries to work on all my projects (Android, iOS and UWP). Is this normal? If I install Oxyplot.Core 2.0 then I can't use Android or iOS since they throw an error stating that Oxyplot.Core 1.0 is needed.

The only version that does not conflict is Oxyplot.XamarinForms unstable 669 but using it in UWP it does not display anything.

Is there a workaround for this? Am I missing something?

**Comment by objorke** [comment]
There should not be such a version conflict, something must be wrong?
In this repo (OxyPlot.Windows?) or in oxyplot-xamarin (OxyPlot.Xamarin.Forms.Platform.UWP)?

https://github.com/oxyplot/oxyplot-xamarin/blob/develop/Source/OxyPlot.Xamarin.Forms/OxyPlot.Xamarin.Forms.nuspec#L25

Maybe this issue should be moved to https://github.com/oxyplot/oxyplot-xamarin?

**Comment by MrCapuchino** [comment]
Hi,

I solved my issue by downloading the source code and getting the assemblies from there instead of the nuget packages.

If I try to install OxyPlot.Xamarin.Forms prerelease unstable 680 there were several issues. Maybe I should not get it from there but I could not find this library in any other repository.

I don't know how to move it to the other topic, I'm not very familiar with github.

Thanks

**Comment by MrCapuchino** [comment]
objorke, one last question, should the prerelase unstable 680 version be the same as the one in the source code? Why it does not let me install xamarin forms in all three projects without showing dependency issues?

Thanks,
Regards

**Comment by objorke** [comment]
Yes, 1.0.0-unstable.680 should be the latest
https://ci.appveyor.com/project/objorke/oxyplot-xamarin
I think this issue should be covered by
https://github.com/oxyplot/oxyplot-xamarin/milestone/1

**Comment by objorke** [comment]
This is covered by https://github.com/oxyplot/oxyplot-xamarin/issues/43
