### ISSUE TITLE
End support for Windows Phone 8 and Windows Phone Silverlight

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1050]
Let us focus on Windows Universal...

**Comment by GeertvanHorrik** [comment]
I can remove the files for this one if you want.

**Comment by objorke** [comment]
@GeertvanHorrik I can handle this
Should we also remove support for Windows 8 apps?

**Comment by GeertvanHorrik** [comment]
I think so. Don't forget there is still OxyPlot 1.0 for people that really need windows 8 support. I would just go UWP only at this stage.
