### ISSUE TITLE
Movable/Resizable rectangle annotation

### ISSUE THREAD

**Issue by sap087** [oxyplot/oxyplot#1063]
*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

I am using OxyPlot to show a rectangle annotation to the user, so it can select a range. However , I want to make this RectangleAnnotation Movable across the X-axis. Besides that, the user should be able to change the range by dragging the two sides of the rectangle (MinimumX and MaximumX).  Is this even possible? Any ideas or starter points for me to do this?

**Comment by ch-hristov** [comment]
Just a protip : you should probably move most of the title into the main body.
