### ISSUE TITLE
Change from linear to logarithmic axis does not work

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1067]
### Steps to reproduce

1. Create a plot with linear axes and a line series with data from 0.05 to 0.99
2. Change the axis to logarithmic
3. Invalidate the plot (with updateData = false)

### Expected behaviour

The line series should be within the view

### Actual behaviour

The line series is outside the view and the log axis shows the wrong range.

### Code to reproduce the issue
```csharp
            var m = new PlotModel();
            m.Axes.Add(new LinearAxis { Position = AxisPosition.Bottom });
            m.Axes.Add(new LinearAxis { Position = AxisPosition.Left });
            var s = new LineSeries();
            s.Points.Add(new DataPoint(0.005, 0.005));
            s.Points.Add(new DataPoint(0.99, 0.99));
            m.Series.Add(s);

        public void ToggleAxis()
        {
            var currentIsLogarithmic = Model.Axes[1].GetType() == typeof(LogarithmicAxis);
            if (currentIsLogarithmic)
                Model.Axes[1] = new LinearAxis {Position = AxisPosition.Left};
            else
            {
                Model.Axes[1] = new LogarithmicAxis {Position = AxisPosition.Left};
            }

            Model.InvalidatePlot(true);
        }
```

**Comment by shnaramn** [comment]
Looks like Axis.DataMinimum and Axis.DataMaximum are initialized by default to 0. When computing the DataMinimum, 0 is still lower than 0.005 so DataMinimum remains 0. This is causing the issue in log scale. Initializing them both to double.NaN seems to fix the issue.
