### ISSUE TITLE
Adding GTK PlotView control to ToolBox

### ISSUE THREAD

**Issue by seijikun** [oxyplot/oxyplot#1071]
Platform: Linux
.NET version: Any

### Expected behaviour

The GTK# PlotView control should show up in the Ui Editor ToolBox (XamarinStudio / MonoDevelop), but it does not. Trying to manually adding it by loading the assembly fails because it does not find any control within the assembly.

### Actual behaviour

XamarinDevelop / MonoDevelop do not find the Ui control contained within the generated GtkSharp assembly. The user has no other choice but to add it with code.

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-gtksharp
