### ISSUE TITLE
AbsoluteMinimum AbsoluteMaximum AreaSeries different behavior on Android and iOS Xamarin Forms

### ISSUE THREAD

**Issue by chaselal** [oxyplot/oxyplot#1073]
### Steps to reproduce
Sample solution: https://drive.google.com/file/d/0B8YvbPIswXQ4aklmYU0xaXR1Yjg/view?usp=sharing

The gist is to plot an `AreaSeries` that has endpoints defined outside of the X-axis's minimum and maximum values. If `AbsoluteMinimum` and `AbsoluteMaximum` are set on the X-axis, then the series will be filled on iOS, but not on Android.

1. Create a plot with a `TimeSpanAxis` and a `LinearAxis`. Set `Minimum`, `Maximum`, `AbsoluteMinimum`, and `AbsoluteMaximum` value on the `TimeSpanAxis` and `Minimum` and `Maximum` on the `LinearAxis`.
1. Add an `AreaSeries` to the plot. Add two `DataPoint`s to the `AreaSeries`, one with `X` less than the `TimeSpanAxis`'s `Minimum` and one with `X` greater than the `TimeSpanAxis`'s `Maximum`. Set `Y` values on the `DataPoint`s. Set a fill color.
1. Render the plot in a `PlotView`.

Platform: Xamarin.Forms Android and iOS
.NET version: 4.5

### Expected behaviour
The area series should be filled.

### Actual behaviour
The area series is filled on iOS, but not on Android.

Android:
<img width="540" alt="android" src="https://cloud.githubusercontent.com/assets/3928875/24126491/352a90fa-0d9c-11e7-93c8-f67755178a86.png">

iOS:
<img width="578" alt="ios" src="https://cloud.githubusercontent.com/assets/3928875/24126490/3339999e-0d9c-11e7-8fbc-840343b592bf.png">

**Comment by objorke** [comment]
Good description of the bug!
I think this belongs to https://github.com/oxyplot/oxyplot-xamarin/issues

**Comment by chaselal** [comment]
Should I close this and create a copy in the oxyplot-xamarin issues?

**Comment by chaselal** [comment]
Closing because I created a duplicate in the oxyplot-xamarin repository. https://github.com/oxyplot/oxyplot-xamarin/issues/57
