### ISSUE TITLE
Thin line series shown blurry

### ISSUE THREAD

**Issue by kjorsh** [oxyplot/oxyplot#1077]
### Steps to reproduce

1. m_srs = new FunctionSeries( Math.Sin, -100, 100, 0.5, "sin(x)" );
    m_srs.StrokeThickness = 1;

Platform:
.NET version: 4.5 (but should affect at least any Windows)

### Expected behavior

Normal line with 1 pixel width should be shown:
![oxyplot-expected](https://cloud.githubusercontent.com/assets/27141627/24837487/58eda808-1d03-11e7-8828-1d4e5ea87780.jpg)

### Actual behavior

Blurry line is shown instead - you can see change in color
![oxyplot-current](https://cloud.githubusercontent.com/assets/27141627/24837484/4dd705a4-1d03-11e7-8914-af153dcc101b.jpg)

This may be related to an issue #145 

### Proposed solution:
Currently Line Series is rendered using this code where 'aliased' parameter in rc.DrawClippedLine always set to false (meaning anti-aliasing is always on): 

protected virtual void RenderLine(IRenderContext rc, OxyRect clippingRect, IList<ScreenPoint> pointsToRender)
{
...
            rc.DrawClippedLine(clippingRect, pointsToRender, 
this.MinimumSegmentLength * this.MinimumSegmentLength, this.GetSelectableColor(this.ActualColor), 
this.StrokeThickness, dashArray, this.LineJoin, 
**_false_**, this.outputBuffer);
}

Anti-aliasing should be turned off for lines with 1 pixel width. Expected behavior screenshot was made with following changes:

rc.DrawClippedLine(clippingRect, pointsToRender, 
this.MinimumSegmentLength * this.MinimumSegmentLength, this.GetSelectableColor(this.ActualColor), 
this.StrokeThickness, dashArray, this.LineJoin, 
**_this.StrokeThickness<2_**, this.outputBuffer);

**Comment by objorke** [comment]
I agree it doesn't look good - but should it disable anti-aliasing automatically, or should it be a property on the line series?

**Comment by kjorsh** [comment]
Honestly, I am not sure... Ideally I can imagine it will be three-state (on/off/auto) Antialias property with default behavior false for 1pixel lines and to true for thicker lines. User can override this behavior by explicitly assigning true or false to it.
