### ISSUE TITLE
XAML properties values overwritten by the PlotModel

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#108]
**Imported from [http://oxyplot.codeplex.com/workitem/10128](http://oxyplot.codeplex.com/workitem/10128)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-02-04 19:19
Combine plotmodel with XAML properties. 

The properties defined in XAML should 'win'. 

<a href="https://oxyplot.codeplex.com/discussions/528726" rel="nofollow">https://oxyplot.codeplex.com/discussions/528726</a>

**Comment by tibel** [comment]
This was fixed with #239
