### ISSUE TITLE
Unable to scroll page when adding OxyPlot to ContentPage In Xamarin.Forms [IOS]

### ISSUE THREAD

**Issue by naveeng2228** [oxyplot/oxyplot#1092]
### Steps to reproduce

1. Create a cross-platform (Xamarin Pages) project in VS 2015 with 4.0 Framework.
2. Now add multiple charts to your ContentPage. And Add guester listeners to few charts.
3. Now try to launch your app on IOS devices either Iphone or Ipad.
4. Now try to scroll the page.
5. At-least try to perform tap on the charts those are having tap guster listeners.

Platform: Xamarin.Forms
.NET version: 4.0

### Expected behaviour

Page should scroll and can perform tapping operations which are working smooth in Android.

### Actual behaviour

Unable to scroll the page. Or even Can't perform click operations on charts.

**Comment by objorke** [comment]
this issue should be posted on https://github.com/oxyplot/oxyplot-xamarin :-)
