### ISSUE TITLE
Implement mouse events

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#11]
**Imported from [http://oxyplot.codeplex.com/workitem/9798](http://oxyplot.codeplex.com/workitem/9798)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2012-01-10 09:08
Implement events for

<ul>
<li>MouseDown </li><li>MouseMove </li><li>MouseUp

</li></ul>
on 

<ul>
<li>Plot area </li><li>Series </li><li>Axes </li><li>Annotations </li></ul>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-02-16 13:29
could be handled by new "PlotController", see <a href="https://oxyplot.codeplex.com/workitem/9625" rel="nofollow">
https://oxyplot.codeplex.com/workitem/9625</a>

**Comment by tibel** [comment]
contrary to #111

**Comment by tibel** [comment]
I will close this in favor of #111

**Comment by objorke** [comment]
Should we then consider to remove all mouse events? (breaking change)
