### ISSUE TITLE
JpegDecoder doesn't implement IImageDecoder interface

### ISSUE THREAD

**Issue by javagg** [oxyplot/oxyplot#1101]
the method `public OxyColor[,] Decode(Stream s)` is inconsistent with the one specified in the IImageDecoder with incorrect signiture.

**Comment by objorke** [comment]
this should now be fixed:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Imaging/Jpeg/JpegDecoder.cs#L422

note that the jpeg decoder is just implementing the image info!
