### ISSUE TITLE
In OxyPlot.Avalonia PlotBase's OnPointerReleased has the argument of wrong type

### ISSUE THREAD

**Issue by javagg** [oxyplot/oxyplot#1102]
Avalonia has changed this argument's type from PointerEventArgs to PointerReleasedEventArgs.

**Comment by objorke** [comment]
please add this to https://github.com/oxyplot/oxyplot-avalonia/issues
we have split up this repo :-)

**Comment by javagg** [comment]
I have repost this issue in oxyplot-avalonia repo.
