### ISSUE TITLE
Package OxyPlot.Xamarin.Forms 1.0.0 is not compatible with netstandard1.4.

### ISSUE THREAD

**Issue by egillanton** [oxyplot/oxyplot#1120]
Xamarin.Forms has a support for netstandard1.4, so why dont Oxyplot as well?
### Steps to reproduce

1. Create [Xamarin Froms running on .NET standard 1.4 ](https://blog.xamarin.com/building-xamarin-forms-apps-net-standard/)
2. Open NuGet Manager
3. Try install OxyPlot.Xamarin,Forms

Platform:
.NET Standard 1.4

**Comment by objorke** [comment]
please move to https://github.com/oxyplot/oxyplot-xamarin
