### ISSUE TITLE
OxyPlot sometimes does not render last line of title

### ISSUE THREAD

**Issue by bucvic13** [oxyplot/oxyplot#1124]
OxyPlot does not show the whole titles (diagram and legend title), even though it generates and adds them correctly to the PlotModel. To clarify, sometimes the last line of the title will not be rendered. However, which title is not correctly shown depends on the computer OxyPlot is running on.

I tried to debug OxyPlot and after changing in the GraphicsRenderContext class the StringFormatFlags from LineLimit to FitBlackBox or NoClip the whole title is shown. (StringFormatFlags Enumeration: https://msdn.microsoft.com/en-us/library/system.drawing.stringformatflags(v=vs.110).aspx )

Since there is no recognizable difference between FitBlackBox and NoClip it can be suspected that the size of the precalculated container is just a few pixels too small. Due to this observation the calculation of the size might be incorrect. This could be the fault of Graphics.MeasureString() (https://stackoverflow.com/questions/1203087/why-is-graphics-measurestring-returning-a-higher-than-expected-number ).

### Steps to reproduce
This bug might not be reproducable on every PC. 
1. Create a PlotModel and add a title with multiple lines
2. Add some signals to the PlotModel
3. Add a title to the legend with multiple lines

Using the following code I achieved to reproduce the bug, but I am unsure if this is producable on every PC.
```
using OxyPlot.Series;

namespace ExampleGenerator
{
  using System;              
  using System.IO;
  using System.Reflection;
  using OxyPlot;
  using OxyPlot.WindowsForms;

  public static class Program
  {
    public static string OutputDirectory { get; set; }

    public static bool ExportPng { get; set; }

    public static void Main(string[] args)
    {
      var model = new PlotModel();
      model.Title = string.Join(Environment.NewLine, "TitleTopRow", "TitleMiddleRow", "TitleLastRow");

      var lineSeries = new LineSeries();
      lineSeries.Points.Add(new DataPoint(0, 0));
      lineSeries.Points.Add(new DataPoint(10, 4));
      lineSeries.Points.Add(new DataPoint(30, 2));
      lineSeries.Points.Add(new DataPoint(40, 12));
      lineSeries.Title = "Signal1";

      model.Series.Add(lineSeries);

      model.LegendTitle = string.Join(Environment.NewLine, "FirstLine", "LastLine");


      ExportPng = true;
      OutputDirectory = @".";
      if (args.Length > 0)
      {
        OutputDirectory = args[0];
      }                                   

      foreach (var type in Assembly.GetExecutingAssembly().GetTypes())
      {
        foreach (var method in type.GetMethods(BindingFlags.Static | BindingFlags.Public))
        {
          var exportAttribute = method.GetCustomAttribute<ExportAttribute>();
          if (exportAttribute == null)
          {
            continue;
          }

          Export(model, exportAttribute.Filename.Replace('/', Path.DirectorySeparatorChar));
        }
      }
    }

    private static void Export(PlotModel model, string name)
    {
      var fileName = Path.Combine(OutputDirectory, name + ".png");
      var directory = Path.GetDirectoryName(fileName) ?? ".";

      if (!Directory.Exists(directory))
      {
        Directory.CreateDirectory(directory);
      }

      if (ExportPng)
      {
        Console.WriteLine(fileName);
        using (var stream = File.Create(fileName))
        {
          var exporter = new PngExporter {Width = 600, Height = 400};
          exporter.Export(model, stream);
        }
      }
    }
  }
}

```

Platform: Windows 10 Enterprise, 64 bit, Intel(R) Core(TM) i5-4300 CPU @ 1.90GHz 2.50GHz
.NET version: 4.0.30319.0

### Expected behaviour

Every line of the title is rendered.

### Actual behaviour

The last line of the PlotTitle and the LegendTitle is not rendered in the .png-File. (See the following screenshot)
![lineseries](https://user-images.githubusercontent.com/12292973/28620759-a75c709a-720e-11e7-990b-a2583b656614.png)

### Possible solution

The error could be fixed by always setting the StringFormatFlags to noClip in GraphicsRenderContext line 71 (`this.stringFormat.FormatFlags = StringFormatFlags.NoClip;`). However, I am not sure if that's the best way to tackle this problem.

**Comment by VisualMelon** [comment]
This should be resolved now (example works as expected).
