### ISSUE TITLE
Can't load OxyPlot.csproj in Visual Studio 2015

### ISSUE THREAD

**Issue by zhyongquan** [oxyplot/oxyplot#1134]
I use visual studio 2015 to test oxyplot, but it can't load OxyPlot.csproj.
And I open OxyPlot.csproj by notepad, find that it's different with other csproj file.
Do you have this problem? thanks.

**Comment by ShannonZ** [comment]
You need to use VS2017 to open the latest version of OxyPlot.
VS2015 will work with the order version.

**Comment by ShannonZ** [comment]
@zhyongquan  VS2017 involved a new XML parser.

**Comment by objorke** [comment]
VS 2017 is required to build the latest version
