### ISSUE TITLE
GetAxisOrDefault throws InvaidOperationException when key is not found

### ISSUE THREAD

**Issue by Cheesebaron** [oxyplot/oxyplot#1137]
### Steps to reproduce

1. Create PlotModel
2. Try to call `GetAxisOrDefault` with a key for an axis that doesn't exist
3. Boom

Platform: Xamarin.iOS
.NET version:

### Expected behaviour

With methods that have the OrDefault postfix, I'd expect them to return the default value in case of what I query is not present and not throw an exception.

For instance in a LINQ query where I have an enumerable where I use FirstOrDefault, in case first is not found, I just get the default value.

### Actual behaviour

InvalidOperationException is thrown telling me that the key is not present.

This means that the default value can never be obtained and the `OrDefault` postfix is very silly to have in this case.

**Comment by objorke** [comment]
agree with you on the expected behaviour!

**Comment by objorke** [comment]
And expected default value of `GetAxisOrDefault` should be `null` right?
And a `GetAxis` method with an invalid key should throw an exception, right?

I think we could change to simply a `GetAxis(key, defaultAxis)` that returns `defaultAxis` if `key` is `null`, or throws an exception if the key is not found.

Or should we handle this case with invalid key? It is nice with a more forgiving library...

**Comment by objorke** [comment]
Se also #992...

**Comment by tersers** [comment]
It really depends on the use case. How often will the user be requesting an axis that doesn't exist? Why would they be in the situation where that could happen? Maybe they can ask for input via some GUI element which can introduce some error.

Perhaps it's better to split it into two functions:

- ```HasAxis``` which returns true/false depending on if the axis exists
- ```GetAxis``` which returns the actual axis, or throws if it doesn't exist.
