### ISSUE TITLE
How to implement an scrollable chart

### ISSUE THREAD

**Issue by ShannonZ** [oxyplot/oxyplot#1139]
### Expected behaviour
![capture-4](https://user-images.githubusercontent.com/7865691/30041058-4f41cb0a-9219-11e7-835c-96069306e453.gif)

*Scrollable Chart:*

###a thumb+a scroll panel+a data plotview

When a lots of points need to draw, the UI interaction responses slowly. So I want to using this Scrollable Chart to improve UX. 
How to implement this using OxyPlot?
Or is there any alternatives to Scrollable Chart? I have 10,000,000 points to draw and I want to use a parameter panel which could change some properties of the plotting at nearly real time.

**Comment by praful-hunde** [comment]
I think you can use panning feature here. Panning works in oxyplot using arrow keys and  mouse drag with right mouse button pressed.  You can change/remove default key or mouse bindings for any action. Also you should be able to override how panning works. For ex. only allow panning or X-Axis and disable for Y axis. I hope this helps.

**Comment by objorke** [comment]
I think the scroll panel at the bottom could be implemented as a separate control. It could work with the zoom/panning functionality of the horizontal axis.

**Comment by ShannonZ** [comment]
Thank you very much @objorke  @praful-hunde 
It works.

**Comment by alessandrofrancesconi** [comment]
> I think the scroll panel at the bottom could be implemented as a separate control. It could work with the zoom/panning functionality of the horizontal axis.

Can you elaborate this? I would like to implement it, too. Any example?
