### ISSUE TITLE
Is it possible to render in memory and save to bitmap image without displaying in UI?

### ISSUE THREAD

**Issue by ShannonZ** [oxyplot/oxyplot#1144]
I want to draw about 100 charts but the UI should show 1 chart only at a time.
Each chart contains about 10,000 points. If I draw the chart immediately, frame-skips are obvious. So I want to drawing background into memory stream. How to implement this with OxyPlot?

**Comment by VisualMelon** [comment]
The [PngExporter](http://docs.oxyplot.org/en/latest/export/export-png.html) may of interest.

Take a look at the [OxyPlot Fiddle](https://github.com/oxyplot/oxyplot-fiddle/blob/master/Source/Fiddle/PlotController.cs) implementation to see it in action.

**Comment by ShannonZ** [comment]
@VisualMelon  Thanks for your answer. The PngExporter can only save the Model which has displayed in UI . If the PlotModel has never been visualized in UI, the saved images will contain nothing.

**Comment by VisualMelon** [comment]
Which UI Framework is this? I seem to be able to produce a well-formed PNG from Winforms or WPF without attaching the PlotModel to a PlotView with the latest development branch and the binaries from NuGet. [Gist of the Code Snippets](https://gist.github.com/VisualMelon/475e3f966054d9a54e67dca44fa0754e)

**Comment by ShannonZ** [comment]
@VisualMelon  I used WPF. Thanks very much. I put a PlotView in the UI using xaml, that's why the pngexporter exports nothing to image. I delete this part of xaml code and now the PngExporter works well.
