### ISSUE TITLE
Is there a way to plot a "X = some constant" line ?

### ISSUE THREAD

**Issue by bviala** [oxyplot/oxyplot#1148]
Basically I just want to plot something like this:

https://www.wolframalpha.com/input/?i=x+%3D+pi

Very basic, but I fail to find anything appropriate in the doc :/

**Comment by objorke** [comment]
I think you can use a `LineAnnotation` to achieve this.

PS. Please use the forum for questions :-)

**Comment by objorke** [comment]
there is also an `ExtraGridLines` property on the axis classes
