### ISSUE TITLE
Remove SL4 and NET35 builds

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#115]
**Imported from [http://oxyplot.codeplex.com/workitem/10139](http://oxyplot.codeplex.com/workitem/10139)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-02-26 08:41
Support for XP ends April 8, 2014 

<a href="http://www.microsoft.com/en-us/windows/enterprise/endofsupport.aspx" rel="nofollow">http://www.microsoft.com/en-us/windows/enterprise/endofsupport.aspx</a>

I would like to end support for Silverlight 4, .NET 3.5 and .NET 4.0 in OxyPlot to make maintenance and build of the solution easier.

I suggest to set the date to December 31, 2014.

**[tibel](http://www.codeplex.com/site/users/view/tibel)** 2014-03-01 06:58
I would remove SL4 and NET35 now, as:

<ul>
<li>don't support PCL </li><li>are not part of nuget packages </li><li>newer versions are available that work on WinXP

</li></ul>
And only keep NET40 till the end of the year.

**Comment by tibel** [comment]
I have removed SL4 and NET35.

Also I would like to remove SL5 and NET40 from the portable core project to prepare for future changes (e.g support INotifyCollectionChanged).

Portable profile 259 seems to be the must suitable (future proof):
![portable_profile259](https://cloud.githubusercontent.com/assets/387395/7630124/701615be-fa33-11e4-9a7c-998de787bd80.PNG)

**Comment by objorke** [comment]
I agree SL5 support can be dropped from the PCL. But then we need to create a SL5 core project. Silverlight should still be supported!

**Comment by tibel** [comment]
@objorke That was the idea.

**Comment by objorke** [comment]
Can this be closed? I think removing OxyPlot_NET40.csproj should be a new issue, but I don't think this should be done yet - still many projects are using NET40...
