### ISSUE TITLE
How Can I Draw Many LineSeries or ScatterSeries Group Show In Legend 

### ISSUE THREAD

**Issue by flypigeon** [oxyplot/oxyplot#1159]
How Can I Draw Many LineSeries or ScatterSeries Group Show In Legend

**Comment by objorke** [comment]
See the example library! Please use the forum or gitter for questions :-)
https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Series/LineSeriesExamples.cs
