### ISSUE TITLE
Add a tracker on the iOS platform

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#116]
Add a tracker on the iOS platform. 

See <a href="https://oxyplot.codeplex.com/discussions/532131" rel="nofollow">https://oxyplot.codeplex.com/discussions/532131</a>

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.

**Comment by objorke** [comment]
The tracker is not implemented for iOS.
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.Xamarin.iOS/PlotView.cs
There is a TODO in the `ShowTracker` method.

**Comment by tibel** [comment]
@objorke Sorry, thought this was a bug and not a feature request.

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/26
