### ISSUE TITLE
NETStandard version of oxplot?

### ISSUE THREAD

**Issue by dfarrNTST** [oxyplot/oxyplot#1168]
Is there a NETStandard version of this tool available or on the roadmap?

**Comment by objorke** [comment]
The core is .NET Standard 1.0:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/OxyPlot.csproj#L4

**Comment by dfarrNTST** [comment]
Awesome...do you have a rough estimate for the release?

**Comment by objorke** [comment]
There are currently 12 open issues that we would like to include in the release: https://github.com/oxyplot/oxyplot/milestone/2
