### ISSUE TITLE
Linear Bar Series Stacked

### ISSUE THREAD

**Issue by sktyjd** [oxyplot/oxyplot#1172]
Is there any way to make the LinearBarSeries show stacked plots like ColumnSeries? It seems as if I have two plots at the same X-Axis with different Y-Axis values the larger value will cover the smaller one.

**Comment by VisualMelon** [comment]
The Bar and Column series have been combined, which should cover this requirement.

**Comment by sershe-ms** [comment]
Is it possible to provide a pointer to the class to use? LinearBarSeries doesn't have IsStacked property, and BarSeries doesn't appear to work with DateTimeAxis.

**Comment by VisualMelon** [comment]
@sershe-ms If you need a stacked plot against time, you'd have to use a `CategoryAxis` with time labels: as you noticed, you must use `BarSeries` for stacked bars, and they only work with a `CategoryAxis`.
