### ISSUE TITLE
How to add different color to each bar in Bar Chart.?

### ISSUE THREAD

**Issue by SonamKamble** [oxyplot/oxyplot#1176]

**Comment by eohlde** [comment]
When adding a BarItem, change the Color property.

    var series = new BarSeries
        {
                Title = "Test Bar Series"
        };
    var item = new BarItem(2, 1);
    item.Color = OxyColor.FromRgb(255,255,255);
    series.Items.Add(item);

**Comment by wahrendt** [comment]
What if you're plotting a Histogram and the BarItems are bound to an ItemSource?

**Comment by wahrendt** [comment]
> What if you're plotting a Histogram and the BarItems are bound to an ItemSource?

I figured it out. I need to have a property in the ItemSource I can reference with "ColorField"
