### ISSUE TITLE
Pan/Zoom doesn't work on touch devices

### ISSUE THREAD

**Issue by scastria** [oxyplot/oxyplot#1184]
GeertvanHorrik introduced a bug with commit:  https://github.com/oxyplot/oxyplot/commit/4edac8250db56a183c50002fae645a1b6f7291fa#diff-475cc427b3b23fc83502b42b11f06316 by introducing a new protected property called bool SetHandledForPanOrZoom but NOT setting the default value to true.  He overrides the value to false in TouchTrackerManipulator but forgot to set the base class TouchManipulator to true.

**Comment by scastria** [comment]
There is another part to this bug in GeertvanHorrik's commit:  https://github.com/oxyplot/oxyplot/commit/4bdd6556a6c01c1c54df984b643779ba80d329c2#diff-475cc427b3b23fc83502b42b11f06316 where he added a new BindTouchDown to the default PlotController constructor.  Touch events do not have any modifiers like keyboard and mouse so you can only have 1 touch binding.  The second BindTouchDown is replacing the first binding.  The first binding handles pan/zoom and the second handles the tracker.  You can't have both.

**Comment by objorke** [comment]
Thanks for the fix and good explanations!
