### ISSUE TITLE
How to combine candlestick + area?

### ISSUE THREAD

**Issue by acidos** [oxyplot/oxyplot#1189]
It's actually question. I am curious if it's possible to plot candlestick and Bollinger Bands(BB) on top of it. To me it looks like BB should be area series, but not sure. So it will look like this.

![image](https://user-images.githubusercontent.com/298480/35476759-bd4a5000-03b5-11e8-86c0-942e0704606b.png)

Basically BB consists of moving average line in the middle(line series?) and area series. If that is possible, how can I combine those series? It will be very valuable for technical analysis.

**Comment by dodikk** [comment]
@acidos , I am not a maintainer, but your question seems inappropriate in its current form. 
What exactly are you unable to do? What's your current progress? Can you show your code (one which is causing troubles).
** no offense. I am just trying to help and asking for more information.


The library seems to have both the candlestick series and the area series.
Have you considered the examples in this repo?

https://github.com/oxyplot/oxyplot/blob/fe84b034c1105fd0cd679d8cedd88d9c20fde417/Source/Examples/ExampleLibrary/Axes/DateTimeAxisExamples.cs#L192

https://github.com/oxyplot/oxyplot/blob/fe84b034c1105fd0cd679d8cedd88d9c20fde417/Source/Examples/ExampleLibrary/Series/FinancialSeries/OldCandleStickSeriesExamples.cs#L20

**Comment by acidos** [comment]
@dodikk,
Indeed I've tried something, but stuck at creating candlestick charts. [Here](https://stackoverflow.com/questions/48497877/blank-chart-when-using-candlesticks) are more details. If you think it's more appropriate to close this one and open new one here, just let me know, since I really can't push this forward and need help. The code example also there.
