### ISSUE TITLE
PlotModel.Render should support destination rectangle

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#120]
**Imported from [http://oxyplot.codeplex.com/workitem/10149](http://oxyplot.codeplex.com/workitem/10149)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-03-06 20:49
This can make it possible to draw multiple plots to the same output device. 

See <a href="https://oxyplot.codeplex.com/discussions/538208" rel="nofollow">https://oxyplot.codeplex.com/discussions/538208</a>

**Comment by VisualMelon** [comment]
Can this be closed?
