### ISSUE TITLE
Series.IsVisible is not working

### ISSUE THREAD

**Issue by thecco** [oxyplot/oxyplot#1210]
"Series.IsVisible = true" is not working after Set "IsVisible = false" on constructor.
but set "IsVisible=true" on constructor is work.

I tested the LineSeries  and ColumnSeries.

Platform: WPF
.NET version: 4.5

**Initialize PlotModel** 
```
private void UpdatePlotModel()
{
    ....

    ColumnSeries cs = new ColumnSeries()
    {
        IsVisible = false
    }

    ....
}
```

**My custom legendbox checkbox_checked event**
```
private void UpdateLegendState()
{
    PlotModel.Series[0].IsVisible = SeriesData.Visibility;
    // PlotModel.InvalidatePlot's parameter always false.
    // Because this methods call from my custom legendbox's checkbutton.
    // it's only change visibility.

    PlotModel.InvalidatePlot(false);
}
```

**Comment by Nick135** [comment]
change
`PlotModel.InvalidatePlot(false)`
 to 
`PlotModel.InvalidatePlot(true);`

**Comment by thecco** [comment]
@Nick135 

I can't set parameter to true because I have may large series.
And when I set IsVisble to true in constructor, It works well with PlotModel.InvalidatePlot(false).
The problem occurs only when I set IsVisble to false within the constructor.

**Comment by VisualMelon** [comment]
I believe this was resolved at some point (this is how legends work). Closing, but feel free to reopen with an example if the issue persists.

**Comment by Lucaa83** [comment]
Hi, I still get the bug.
Steps to reproduce the error:
1) Initialize a series with IsVisible = false:

```
LineSeries power = new LineSeries();
                  power.Title = $"Zone {zone.Id}";
                  power.ItemsSource = _myListOfObjects_;
                  power.IsVisible = false;
```

2) Execute PlotModel.InvalidatePlot(true)
3) Click on the legend of the hidden series:

![image](https://github.com/oxyplot/oxyplot/assets/115703176/1db632fd-31a8-4a30-9adf-ccede4ae7f72)

4) Crash:

![image](https://github.com/oxyplot/oxyplot/assets/115703176/a598ce3e-fd0a-49e2-ac43-9b8742356bc0)

**Comment by VisualMelon** [comment]
@Lucaa83 can you confirm the version you are using? I'll try to look into this over the weekend.

**Comment by Lucaa83** [comment]
Thanks. I'm using the latest version (2.1.2).

Il Gio 15 Giu 2023, 18:04 VisualMelon ***@***.***> ha scritto:
