### ISSUE TITLE
SVG Exporter isDocument hard-coded to true

### ISSUE THREAD

**Issue by calrsom** [oxyplot/oxyplot#1212]
### Steps to reproduce

1. Call any of `SvgExporter.Export` methods.
2. Pass `isDocument` value of `false`.

### Expected behaviour

Not get XML headers, as described in documentation.

### Actual behaviour

Get XML headers.

```
<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"no\"?>
<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\">
```

Is there a reason this parameter is not passed through, and instead card-coded to `true`?  See [Line 65 of SvgExporter](https://github.com/oxyplot/oxyplot/blob/bbc87bb7114d20997cc706665c1febf4119018b1/Source/OxyPlot/Svg/SvgExporter.cs#L65).  I'd really like this feature.

**Comment by objorke** [comment]
I think this is a bug! It should be simple to fix!

**Comment by jmagnette** [comment]
It seems I was not the only one to see that.
I just changed the code and made a pull request => [https://github.com/oxyplot/oxyplot/pull/1354](url)

I hope it will be accepted, shouldn't be an issue.
