### ISSUE TITLE
Gridlines and axis labels behind HeatMapSeries

### ISSUE THREAD

**Issue by propuls1on** [oxyplot/oxyplot#1218]
I tried to recreate the SeriesHeatMap example from the documentation, but with gridlines and with the axis crossing at zero. However, the SeriesHeatMap is plotted over the gridlines and axis labels, making them invisible. Is there a solution for this? 

![capture](https://user-images.githubusercontent.com/11997325/41600624-b1541556-73d6-11e8-8525-70c15243a9da.PNG)

**Comment by VisualMelon** [comment]
You can try setting the public `Layer` property on your Axes to `AxisLayer.AboveSeries`, the default being `AxisLayer.BelowSeries`.

**Comment by propuls1on** [comment]
@VisualMelon That's exactly what I wanted, thanks!

![capture](https://user-images.githubusercontent.com/11997325/41601787-90f3f364-73d9-11e8-8a54-772dfdedaa2e.PNG)
