### ISSUE TITLE
Polar Plot AngleAxis StartAngle EndAngle degrees/radians bug

### ISSUE THREAD

**Issue by AlexeiScherbakov** [oxyplot/oxyplot#1222]
### Steps to reproduce

1. Use PolarHeatMapSample
2. replace line 
`model.Axes.Add(new AngleAxis { StartAngle = 0, EndAngle = 360, Minimum = 0, Maximum = 360, MajorStep = 30, MinorStep = 15 });`
`model.Axes.Add(new AngleAxis { StartAngle = Math.PI, EndAngle = Math.PI + 360, Minimum = 0, Maximum = 360, MajorStep = 30, MinorStep = 15 });`

Platform:
.NET version: 4.7

### Expected behaviour

Expected shift on 3.14 degrees of grid and 3.14 degress of series

### Actual behaviour

Grid is shifted on 3.14 degrees, but data is shifted on 360 degrees

**Comment by AlexeiScherbakov** [comment]
![default](https://user-images.githubusercontent.com/8665915/42184130-13584a62-7e4d-11e8-9769-cf4ace051ecf.JPG)

**Comment by AlexeiScherbakov** [comment]
For inversed angle axis (360 to 0) result is much more unexpected
![default](https://user-images.githubusercontent.com/8665915/42184376-fc1afa7e-7e4d-11e8-8fc2-07c86a7583e1.JPG)

**Comment by AlexeiScherbakov** [comment]
Fix is replace line 
`y = (th / angleAxis.Scale) + angleAxis.Offset;`
to
`y = (th / angleAxis.Scale) + angleAxis.Offset*Math.PI/180;`
in MagnitudeAxis.cs
```
public override DataPoint InverseTransform(double x, double y, Axis yaxis)
        {
            var angleAxis = yaxis as AngleAxis;
            if (angleAxis == null)
            {
                throw new InvalidOperationException("Polar angle axis not defined!");
            }

            x -= this.MidPoint.x;
            y -= this.MidPoint.y;
            y *= -1;
            double th = Math.Atan2(y, x);
            double r = Math.Sqrt((x * x) + (y * y));
            x = (r / this.Scale) + this.Offset;
            y = (th / angleAxis.Scale) + angleAxis.Offset*Math.PI/180;
            return new DataPoint(x, y);
        }
```

I added commit which fixes it, please check that it will not break something

**Comment by AlexeiScherbakov** [comment]
Resolved in https://github.com/oxyplot/oxyplot/commit/e41a53957fb05cf8b7512ba0c631d460ebcdea1a

**Comment by SujithSaravanan** [comment]
Why 270  label only placed inside the polarplot in 0 to 360 image. am also having the same problem is any reason behind that
