### ISSUE TITLE
OxyPlot.SharpDX.WPF package on myget is outdated

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1224]
I was just wondering if there is a particular reason why the latest version of OxyPlot.SharpDX.WPF on myget is 2.0.0-unstable0998 from over a year ago, while there is already 2.0.0-unstable1054 of OxyPlot.Core.

I would love to use the new HistogramSeries, but I need OxyPlot.SharpDX for speed and therefore I'm stuck with the 2.0.0-unstable0998 version.

Is there a quick way to update this? Thanks a lot!

**Comment by objorke** [comment]
I think this should be posted on https://github.com/oxyplot/oxyplot-sharpdx
