### ISSUE TITLE
Fill with Brush 

### ISSUE THREAD

**Issue by rubyzhao** [oxyplot/oxyplot#1228]
How to fill the AreaSeries with TextBrush in oxyplot? 
For example, the code below

            `g= pictureBox1.CreateGraphics();
            Image image = new Bitmap("HouseAndTree");
            TextureBrush tBrush = new TextureBrush(image);
            g.FillRectangle(tBrush, new Rectangle(0, 0, 200, `200));`
will fill the Rectangle(0, 0, 200, 200) with 
![houseandtree](https://user-images.githubusercontent.com/12829001/42833939-400479de-89fe-11e8-8f2e-1cdc6ca005a1.gif)
And get below:
![capture](https://user-images.githubusercontent.com/12829001/42834036-88e1472c-89fe-11e8-8f26-1fe7fc4948b6.PNG)

**Comment by objorke** [comment]
Sorry, we are not intending to support such brush types in OxyPlot.
