### ISSUE TITLE
OxyPlot.WindowsForms.GraphicsRenderContext leaks SolidBrush objects

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1230]
### Steps to reproduce

1. Plot a lot of filled in polygons
2. Use a machine which doesn't finalize often
3. Watch the memory usage hike

![leakanon](https://user-images.githubusercontent.com/5646475/44087151-52c51608-9fae-11e8-88b1-0c0ab6ae43bc.png)

Platform: WindowsForms (only observed on Windows 10, Win7 machine seems to be finalising more aggressively)
.NET version: .NET Framework (not sure)

### Partial Proposed Solution

Some parts of `GraphicsRenderContext` clearly produce `SolidBrush` objects without disposing them: [`GraphicsRenderContext.DrawPolygon`](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.WindowsForms/GraphicsRenderContext.cs#L174)

Replacing all calls to `ToBrush(this OxyColor)` with `GetCachedBrush(OxyColor)` (excepting those within `GetCachedBrush`, and `PngExporter`) seems an easy and reasonable solution; there is no apparent pattern to which methods explicitly cache their brushes and which do not.

Cached `Brushes` are correctly disposed by `PngExporter`, __but seemly not when used as part of a `PlotView`__ (which warrants discussion). The `GraphicsRenderObject` is also not disposed by the winforms `SvgExporter`, which it should be, though this won't be leaking `SolidBrush` objects as it is only employed for text-measuring.

### Other Related

Currently the `GraphicsRenderContext` only caches `Brush` objects. With some care, it could cache `Pen` objects also. I'm also not convinced by the method [`CleanUp`](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.WindowsForms/GraphicsRenderContext.cs#L353), which is the only place that removes elements from `imagesInUse`, which I think means it will only clean up images the _second_ time it is called, meaning single-use instances (such as in `PngContext`) will not dispose `Image` objects.

I don't understand the rationale behind the existing code here, so I won't attempt to suggest an alternative, but `imagesInUse` appears to at the centre of the problem.

**Comment by VisualMelon** [comment]
Solution implemented on [BrushDisposal branch](https://github.com/VisualMelon/oxyplot/commits/brushdisposal), as well as overriding `Dispose(bool)` for `PlotView`, so that it disposes its `GraphicsRenderContext` when it is disposed. Confirmed it resolves memory issues with my application.

(I used the StyleCop Roslyn analyser, as I can't presently install StyleCop)

**Comment by VisualMelon** [comment]
You are happy for me to make a pull request from that branch? (after appropriate rebasing)

**Comment by VisualMelon** [comment]
Finally rebased this and checked it with StyleCop (no issues in changed files).

@objorke is there anything further I need to do/change, or else if this a suitable candidate for a PR? It's not terribly important, but there should be no dependence on the finalizer for clean-up.

**Comment by VisualMelon** [comment]
The pens are never cached, and they all seem to be correctly disposed on usage. (i.e. they are all in `using` blocks)

**Comment by objorke** [comment]
Is there a reason for not handling pens and brushes the same way? I guess we have less calls to CreatePen, but I guess there could also be a small performance improvment.

https://stackoverflow.com/questions/3532914/should-i-create-new-pens-brushes-per-paint-request-or-keep-them-throughout-the-a

**Comment by VisualMelon** [comment]
Implemented `Pen` caching and disposal (also added clearing of cache dictionaries, which shouldn't be necessary but seems sensible just incase something is holding onto an instance.

Comments:
 - Added a `GraphicsPenDescription` class in `OxyPlot.WindowsForms` to use as key in the cache (can't use OxyPen because it's mutable)
 - `double[]` equality check and hash-code generation is not ideal
 - No obvious degradation of performance (or correctness) in ExampleBrowser (but that's not very scientific); I figure brushes must have been more of a priority because heat-maps can render thousands of rectangles independently (many with the same colours), while there are rarely that many pens ever needed, let alone of the same style. I had a quick searc through the commit history, but my poor git skills didn't turn anything of interest up.
 - I think my StyleCop is broken... I'm sure it used to complain about more things, so I'll have to look into that. (no violations to declare)

Any feedback of course welcome.
