### ISSUE TITLE
Chinese cannot be displayed

### ISSUE THREAD

**Issue by mzy666888** [oxyplot/oxyplot#1231]
*使用过程中，设置标题中文无法显示*

**Comment by objorke** [comment]
Google translate: The title Chinese cannot be displayed during use.

**Comment by qq543139310** [comment]
default font "helvetica" not support Chinese, 
try font "times" and "courier".

**Comment by kwokngaiwai** [comment]
System.Drawing.StringFormat.GenericTypographic.FormatFlags &= ~StringFormatFlags.LineLimit;
var model = new PlotModel();

这么操作下好像可以了，原理还不知道.
(add line as above ,dont know why)
