### ISSUE TITLE
Direct2D based rendering

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#124]
Use Direct2D (SharpDX) to speed up rendering for WPF.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-03-17 09:33
See see https://oxyplot.codeplex.com/workitem/10134

Code reference:
- [D3DImage](http://referencesource.microsoft.com/PresentationCore/a.html#8badc06a64f86901)
- [D3D11Image](https://github.com/sharpdx/Toolkit/blob/master/Source/Toolkit/SharpDX.Toolkit.Game/Desktop/D3D11Image.cs)
- [SharpDXElement](https://github.com/sharpdx/Toolkit/blob/master/Source/Toolkit/SharpDX.Toolkit.Game/Desktop/SharpDXElement.cs)

TODOs:
- [ ] fix zoom with mouse wheel not working
- [ ] remove PlotHeight, PlotWidth and IScrollInfo
- [ ] code cleanup and formatting
- [ ] implement renderer factory (#869)
- [ ] create nuget package
- [ ] add to appveyor build
- [ ] fallback to canvas rendering on remote desktop (see [StackOverflow](http://stackoverflow.com/questions/29416141/how-to-host-c-direct2d-in-wpf-without-d3dimage-and-hwndhost))

Another possible option for WPF would be to check if implementing a custom ImageSource (without Direct3D9) and only Direct2D would help:
- http://stackoverflow.com/questions/27879561/redirect-direct2d-rendering-to-a-wpf-control
- https://blogs.msdn.microsoft.com/dwayneneed/2008/06/20/implementing-a-custom-bitmapsource/

**Comment by Soarc** [comment]
Hi. I`ve implemented SharpDX context renderer and WPF control for it, can you review my code and give me comments like namespaces, or project names that i used? I`m new with SharpDX, so there might be many stupid things done. If there is any comments about it, i will appreciate it.

Here is link to my fork - https://github.com/Soarc/oxyplot . Or I should create pull request instead?

**Comment by Soarc** [comment]
Let me explain, why i`ve added PlotHeight/PlotWidth properties.

I need tall plots with multiple YAxises. This may not fit to screen, so i placed PlotView in scrollViewer. At this point i can control height with Controls regular Height/Width properties. The problem begins with plots, that should be bigger than 2^16 pixels. Here starts working DirectX limitation, that Texture2D dimensions should be lesser than 2^16 pixels. In the WPF this can be solved using IScrollInfo interface (what is currently done), but now i can`t use FrameworkElement`s Width/Height properties, so i added new. Also this allow me to render only plots visible part, which gives performance boost.

SharpDXRenderContext recreate DirectX resources (like geometries) every time, when rendering required (on each frame). This can be useful, if we want to create Direct WIC based image exports. Actual drawing on RenderTarget performs each time IPlotModel.Render method called.

On the other hand, CacherRenderContext on  IPlotModel.Render stores resources and actual rendering on render target can be done later. This is much better for redrawing plot different regions (when scrolling for example).

**Comment by tibel** [comment]
2^16 pixels is 65536
Full-HD is 1920x1080 = 2073600 pixels
not to speak of 4k screens
This would mean we can't render a full screen plot. how does scollinfo help in this case?

**Comment by GeertvanHorrik** [comment]
You could also consider using SkiaSharp (see https://github.com/mono/SkiaSharp) to take care of the rendering.

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-sharpdx

**Comment by Allover2000** [comment]
Resource Limits (Direct3D 11) Texture2D U/V dimension - D3D11_REQ_TEXTURE2D_U_OR_V_DIMENSION (16384) which makes a max 2D texture of 16384*16384 pixels. This is enough to cover eight 8K monitors.
