### ISSUE TITLE
Insert additional labels on axis

### ISSUE THREAD

**Issue by khokm** [oxyplot/oxyplot#1241]
# Feature
Allow to insert custom values on axis.
It can be useful for such things like on my screenshot.

![image](https://user-images.githubusercontent.com/25861783/45589085-2a5fdc80-b939-11e8-902a-649e4399d717.png)

**Comment by a5rGithub** [comment]
Got the same use case. Can be resolved by using pointannotations or lineannotations although I think simple displaying points of interest on the axis is cleaner. 
![stressstrain](https://user-images.githubusercontent.com/8037791/46312485-7eb7bd00-c5c5-11e8-9441-cfa727c02ce0.PNG)

**Comment by wkoeter** [comment]
You can create a custom Linear Axis, override GetTickValues, and change the out value of majorValueLabels..
```cs
public override void GetTickValues(out IList<double> majorLabelValues, out IList<double> majorTickValues,
            out IList<double> minorTickValues)
        {
            //Get all the original tick values and pass trough the minor and major ticks
            base.GetTickValues(out var majorLabels, out var majorTicks, out var minorTicks);
            majorTickValues = majorTicks;
            minorTickValues = minorTicks;



            majorLabelValues = new List<double>();
           // do something with your major label values
        }
```

**Comment by objorke** [comment]
I think it could also be properties to "always show minimum label" and "always show maximum label" on the axis base class.
