### ISSUE TITLE
iOS Adding an Axis to Model then Rendering Throws NullReferenceException

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#125]
**Imported from [http://oxyplot.codeplex.com/workitem/10161](http://oxyplot.codeplex.com/workitem/10161)**

**[benhysell](http://www.codeplex.com/site/users/view/benhysell)** 2014-03-18 13:37
See discussion - <a href="https://oxyplot.codeplex.com/discussions/538962" rel="nofollow">
https://oxyplot.codeplex.com/discussions/538962</a> 

See the running example code in the OxyPlot.XamarinIOS Example Browser app in the fork
<a href="https://oxyplot.codeplex.com/SourceControl/network/forks/benhysell/PlotViewModelIssue" rel="nofollow">
https://oxyplot.codeplex.com/SourceControl/network/forks/benhysell/PlotViewModelIssue</a>

With <code>PlotView</code> unsealed I can now do the following:

<pre><code>public class GraphViewBad : PlotView
    {

        public GraphViewBad ()
        {

        }

        public void BuildGraph()
        {
            Model = new PlotModel ("Bad Plot");
            Model.TitleFontSize = 12;
            Model.TitleFont = "Helvetica";
            Model.TitleFontWeight = FontWeights.Normal;
            Model.TitlePadding = 0;
            Model.Padding = new OxyPlot.OxyThickness (3, 0, 0, 12);
            Model.PlotAreaBackground = OxyColors.White;
            Model.PlotAreaBorderThickness = 0;
            Model.Background = OxyColors.Red;

            //once an axis is added application fails with null ref
            Model.Axes.Add (new LinearAxis (AxisPosition.Left) {
                TickStyle = TickStyle.Outside,
                AxislineStyle = LineStyle.Solid,
                MajorStep = 1, 
                Minimum = 0,
                Maximum = 10
            });
        }
    }</code></pre>
Nothing fancy, a red background with a y-axis...enough to show the error.

When I run this code I get a <code>System.NullReferenceException</code> in <code>
PlotElement.cs</code>

<pre><code>/// <summary>
        /// Gets the actual font.
        /// </summary>
        protected internal string ActualFont
        {
            get
            {
                return this.Font ?? this.PlotModel.DefaultFont;
            }
        }</code></pre>
If I change my code to the following the view displays as expected:

<pre><code>public class GraphViewGood : PlotView
    {
        PlotModel model;

        public GraphViewGood ()
        {

        }

        public void BuildGraph()
        {
            model = new PlotModel ("Good Plot");
            model.TitleFontSize = 12;
            model.TitleFont = "Helvetica";
            model.TitleFontWeight = FontWeights.Normal;
            model.TitlePadding = 0;
            model.Padding = new OxyPlot.OxyThickness (3, 0, 0, 12);
            model.PlotAreaBackground = OxyColors.White;
            model.PlotAreaBorderThickness = 0;
            model.Background = OxyColors.Red;

            model.Axes.Add (new LinearAxis (AxisPosition.Left) {
                TickStyle = TickStyle.Outside,
                AxislineStyle = LineStyle.Solid,
                MajorStep = 1, 
                Minimum = 0,
                Maximum = 10
            });
            Model = model;
        }
    }</code></pre>

**Comment by objorke** [comment]
I think this can also be reproduceed on other platforms!

**Comment by objorke** [comment]
Could not be reproduced on WPF

**Comment by tibel** [comment]
This is a old issue for a old OxyPlot version.
As described the `NullReferenceException` was in line `return this.Font ?? this.PlotModel.DefaultFont;`.

This was fixed by using `ElementCollection<T>` for axes in the PlotModel an setting the Parent to the PlotModel.

I think this issue can be closed.
