### ISSUE TITLE
Port functionality to .net Core and The new version System.Common.Drawing

### ISSUE THREAD

**Issue by curtstate** [oxyplot/oxyplot#1263]
*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description
Need a port to .NET core for various bits of functionality, including but not limited to Png export without winForms or WPF dependencies.

I have ported the pngExporter for my own .net core project at work and put it into a PR before I made this issue.

**Comment by objorke** [comment]
What should the name of this port be?

- OxyPlot.Drawing
- OxyPlot.Core.Drawing
- OxyPlot.SystemDrawing
- OxyPlot.System.Common.Drawing

**Comment by objorke** [comment]
Or can it be part of OxyPlot.Core, but only included if compiled for .NET Core 2.x? (multi-target project, conditional defines?)

**Comment by curtstate** [comment]
How about OxyPlot.Core.Drawing ?
