### ISSUE TITLE
AreaSeries incorrect display with LogarithmicAxis

### ISSUE THREAD

**Issue by wkoeter** [oxyplot/oxyplot#1266]
Bug

Create plotmodel with logarithmic axis on the vertical axis.
Create areaseries with constant min and max

```csharp
 public PlotModel Create()
{
      var model = new PlotModel();
      model.Axes.Add(new LogarithmicAxis() { Position = AxisPosition.Left ,Maximum = 10000});
      model.Series.Add(CreateAreaSeries());
      return model;
}


public Series CreateAreaSeries()
 {
      var result = new AreaSeries();
      for (int i = 0; i < 1000; i++)
      {
                result.Points.Add(new DataPoint(i, 10));
                result.Points2.Add(new DataPoint(i, -1)); // Points 2 Y
      }
      return result;
 }

```

Try 3 different cases for changing minimum:
points 2 y > 0 (i.e. 0.1) Shows as expected
![image](https://user-images.githubusercontent.com/17491881/50276591-983d0800-0442-11e9-8048-6847cd39f165.png)
points 2 y = 0 
![image](https://user-images.githubusercontent.com/17491881/50276533-7774b280-0442-11e9-9849-7a5bf2fd73b1.png)
points 2 y < 0 (i.e. -1)
![image](https://user-images.githubusercontent.com/17491881/50276536-78a5df80-0442-11e9-99cb-5f8c448774a0.png)

Platform:
.NET version: 4.5

### Expected behaviour

Expected an area between minimum(3 cases: -1, 0 and 0.1) and maximum(10)

### Actual behaviour

Only get an area between points above 0 (case 0.1) and maximum(10)
For other cases minimum appears to go to maximum of Y axis or infinite.

**Comment by objorke** [comment]
Negative values on a logarithmic axis?? `log(-1) = 1.36i`...
Shouldn't this be handled as invalid values?

**Comment by wkoeter** [comment]
Not really.
Please google images for "bode magnitude plot"

**Comment by VisualMelon** [comment]
If you want to present decibels, then you need to use a linear axis. The logarithmic axis projects data into a logarithmic screen-space, which makes no sense if the data are negative. (If your data are already in a log-space, then you want a linear axis).

**Comment by wkoeter** [comment]
Thank you for the feedback. I Will take this to the people in my team requesting these specific combinations of axis and content so they can figure out if that fits their need.

**Comment by zhaokuohaha** [comment]
@VisualMelon @objorke

**Comment by VisualMelon** [comment]
@zhaokuohaha assuming the `x` values are greater than zero, then you should be able to use a logarithmic axis as normal. Are you facing a particular problem?

I would caution that an area plot on a logarithmic axes may be misleading, as the meaning of an area is not shift invariant with respect to the original space.

**Comment by zhaokuohaha** [comment]
@VisualMelon My code is roughly as follows

```csharp
public PlotModel MyPlotModel { get; set; }
public LineSeries MyLine { get; set; }

// init method , call in constructor
MyLine  = new LineSeries();
MyPlotModel  = new PlotModel();
MyPlotModel .Series.Add(line );

MyPlotModel .Axes.Add(new LogarithmicAxis
{
    MajorGridlineStyle = LineStyle.Solid,
    MinorGridlineStyle = LineStyle.Dot,
    PositionAtZeroCrossing = true,
    Base = 10,
    Key = "logAxis",
});

// arr data: [{x: 1, y: 0.1}, {x:2, y:0.01}]
// points should like: (1, -1), (2, -2) .... 
line .Points.AddRange(arr.Select(t => new DataPoint(t.x, Math.Log10(t.y))));
```

and the xaml looks normal:
```xml
<oxy:PlotView Model="{Binding MyPlotModel }"/>
```

However the result like, the min value of `y` is zero, I can't find any way to solv this right know 😂 
![image](https://user-images.githubusercontent.com/16274628/105567584-f2b99880-5d6d-11eb-939e-41b23885a70b.png)

**Comment by VisualMelon** [comment]
> line .Points.AddRange(arr.Select(t => new DataPoint(t.x, Math.Log10(t.y))));

Is `line == MyLine`? The log axis performs the logarithm itself, so unless you want a log-axis of log-values, you probably don't only want one of the `Log10` and `LogarithmicAxis`. Non-positive values supplied to a log axis are -as I recall - not rendered, which is probably want you are seeing here.

**Comment by zhaokuohaha** [comment]
@VisualMelon 

> Is line == MyLine? 

yes

when I remove `Math.Log10()` from data.  the line shows follow. 
It render the origin value , but not result of logarithm operation.

![image](https://user-images.githubusercontent.com/16274628/105574762-b9028500-5da1-11eb-9e7f-a88c4473bd0f.png)

**Comment by VisualMelon** [comment]
Because these values are no greater than `1`, the `Log10` of the values will always be no greater than `0`. The `LogarithmicAxis` cannot plot zero or negative values, because the logarithm is not defined for such values.

It doesn't make sense to plot the `log.log` for values that are not greater than `e^1`, and the library is behaving as expected by rejecting unplottable values.

**Comment by zhaokuohaha** [comment]
that's the point confuse me 😂 

so how can I do if I wanna to plot a such line.  as y axis use LogarithmicAxis.   and y-value is result of logarithm ?

**Comment by VisualMelon** [comment]
You can't plot `log.log` for this range without fudging the data or entering the complex domain, where it is usual to plot the real and imaginary components separately as on an Argand diagram (which OyxPlot doesn't directly support: you'd have to compute the real and imaginary components and plot them as separate series on a pair of linear axes). The `log.log` space is weird: I don't think I've ever seen it outside of complexity analysis.

I'm afraid this is really a domain problem that you need to work out: does it make sense to take the `log.log` of your data? What does it represent? Are you sure that the graph you posted above is not what you already need?

**Comment by zhaokuohaha** [comment]
@VisualMelon  Thanks. Your reply very rational.  May be I should orgainze  my code and need again.
