### ISSUE TITLE
Pull Requests are not handled

### ISSUE THREAD

**Issue by twsI** [oxyplot/oxyplot#1268]
### Expected behaviour

PR's should be reviewed and get merged or declined.

### Actual behaviour

Nothing happens at all, no comment, nothing.

### Feature description

Review them so people won't get discouraged.

**Comment by objorke** [comment]
I fully agree on this, we probably need more team members to keep this project running. There are currently 8 members in the developers team that have done a great job in the past, but the activity has been reduced a lot. I think we need to call for more team members, and find a process to make sure we assign some trustworthy folks :-) 

https://github.com/orgs/oxyplot/teams/developers
https://github.com/oxyplot/oxyplot/graphs/contributors
https://github.com/oxyplot/oxyplot/graphs/code-frequency
https://github.com/oxyplot/oxyplot/graphs/traffic

I am sorry that I have not been allowed/able to follow more up the last year(s). Corporate regulations strongly limited collaboration with open source for a while and now my family takes most of my time.

**Comment by agarcialeon** [comment]
I'm going to add #1273 for reference.

**Comment by objorke** [comment]
All pull requests handled.
