### ISSUE TITLE
New team members

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1273]
We need to add more team members that can handle pull requests and keep the project running.
Who are interested and can show a good track record on github?

https://github.com/orgs/oxyplot/teams

**Comment by twsI** [comment]
I might be interested eventho I have never been in such a team and do not know how much time is required

**Comment by GeertvanHorrik** [comment]
Have you considered adding yourself to open collective? We would be happy to support you there (and this way, you could even pay other devs to do stuff).

**Comment by agarcialeon** [comment]
I could help with documentation and when I have more time also with code. Documentation seems the weakest point of the tool for new users and information is scattered across other sources.

**Comment by maintain53** [comment]
How can I contribute to the documentation

**Comment by VisualMelon** [comment]
@maintain53 
See https://github.com/oxyplot/docs and https://github.com/oxyplot/documentation-examples

**Comment by objorke** [comment]
I have updated https://github.com/oxyplot/oxyplot/wiki/Contributing
