### ISSUE TITLE
Oxyplot line chart does not load inside a grid under listview in iOS

### ISSUE THREAD

**Issue by devxus007** [oxyplot/oxyplot#1279]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1. Create a cross platform blank xamarin project in visual studio and add references to oxyplot to the shared and iOS project
2.Initialize the oxyplot in app delegate with :  OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer.Init();
3.Create a listview and on viewcelltapped event of the list populate a grid row with a plotview with a model(like a dropdown the grid should appear under the listview header)

Platform:
.NET version:4.5

### Expected behaviour

Grid under the listview should load the line graph related to the list item clicked

### Actual behaviour

On click of the listview the graph sometimes appears and vanishes form the grid immediately 
OR
Click on the first listview cell and let the grid slide down ...no grpah here. 
Now open the second listview item and now sometimes you cansee the graph associated with the first listview cell item in the second listview grid.
OR 
Behaviour is totally random ..difficult to narrow down but it works fine if I open another content page to load the graph on click of the viewcell tapped event.

I am guessing this is a bug and oxyplot is not able to figure out which plotview in the listview to load the graph...Also not sure why the associated grpahs are not shown and other neightbouring listview items grpahs are shown.

Below is the code that cna be pasted into the mainpage of the shared code after referneceing xamarin assemblies to the project ...shared and iOS and after initializing oxyplot in app.delegate.

`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:local="clr-namespace:TestGrpah"
              xmlns:oxy="clr-namespace:OxyPlot.Xamarin.Forms;assembly=OxyPlot.Xamarin.Forms"
             x:Class="TestGrpah.MainPage">

    <ContentPage.Content>

        <Grid VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <StackLayout VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" Orientation="Vertical"  BackgroundColor="#f8f8ff">
                <Grid Margin="0,5,0,0" Padding="0" HorizontalOptions="Start" VerticalOptions="Start" BackgroundColor="White">
                    <Grid.RowDefinitions>
                        <RowDefinition  Height="20"/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="8*"/>
                        <ColumnDefinition Width="50*"/>
                        <ColumnDefinition Width="10*"/>

                        <ColumnDefinition Width="10*"/>
                        <ColumnDefinition Width="2*"/>
                        <ColumnDefinition Width="18*"/>
                        <ColumnDefinition Width="2*"/>

                    </Grid.ColumnDefinitions>
                    <Image Grid.Column="2"  Source="" VerticalOptions="CenterAndExpand" WidthRequest="15" HeightRequest="15"  HorizontalOptions="End"/>
                    <Image Grid.Column="3"  Source="" VerticalOptions="CenterAndExpand" WidthRequest="15" HeightRequest="15"  HorizontalOptions="End"/>
                    <Label Grid.Column="5"  Text=""  VerticalOptions="CenterAndExpand" HorizontalOptions="Center"   TextColor="Teal"  />
                </Grid>
                <ListView x:Name="ControlRouterlistview"  ItemsSource="{Binding RouterCollection}" BackgroundColor="#ffffff"   IsPullToRefreshEnabled="True"  HasUnevenRows="True">
                    <ListView.ItemTemplate>
                        <DataTemplate>
                            <ViewCell Tapped="ViewCell_Tapped">
                                <StackLayout  HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Padding="0">
                                    <Grid Margin="0" Padding="0" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand">
                                        <Grid.RowDefinitions>
                                            <RowDefinition  Height="45"/>
                                        </Grid.RowDefinitions>

                                        <Label Grid.Column="1"   Text="{Binding Uri}"  VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="TailTruncation" FontSize="Medium" />
                                       
                                    </Grid>
                                    <Grid x:Name="ChildGrid" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" BackgroundColor="White"  IsVisible="{Binding isvisible}" Margin="0,0" Padding="5">
                                        <Grid.RowDefinitions>
                                            <RowDefinition Height="20*"/>
                                            <RowDefinition Height="Auto"/>
                                        </Grid.RowDefinitions>
                                        <Grid HorizontalOptions="CenterAndExpand"  VerticalOptions="FillAndExpand" Grid.Row="0">
                                            <Grid.RowDefinitions>
                                                <RowDefinition Height="Auto"/>
                                                <RowDefinition Height="Auto"/>
                                            </Grid.RowDefinitions>
                                            <Grid.ColumnDefinitions>
                                                <ColumnDefinition Width="Auto"/>
                                            <ColumnDefinition Width="25*"/>
                                            <ColumnDefinition Width="Auto"/>
                                            <ColumnDefinition Width="Auto"/>
                                            </Grid.ColumnDefinitions>

                                        <Label Grid.Row="0" Grid.Column="0" Text="Call"  VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        <Label Grid.Row="0" Grid.Column="1" Text="2"   VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        <Label Grid.Row="0" Grid.Column="2" Text="SL"  VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap" FontSize="Small" />
                                        <Label Grid.Row="0" Grid.Column="3" Text="100"  VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        <Label Grid.Row="1" Grid.Column="2" Text="waiting"  VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        <Label Grid.Row="1" Grid.Column="3" Text="2 min"   HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        <Label Grid.Row="1" Grid.Column="0" Text="total"  VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        <Label Grid.Row="1" Grid.Column="1" Text="23"    VerticalOptions="CenterAndExpand" HorizontalOptions="StartAndExpand" LineBreakMode="NoWrap"  FontSize="Small" />
                                        </Grid>
                                        
                                        <oxy:PlotView  x:Name="LinePlotModel"  VerticalOptions="Fill" IsVisible="True"  HorizontalOptions="FillAndExpand" HeightRequest="300" WidthRequest="300" Grid.Row="1"/>
                                        
                                    </Grid>
                                </StackLayout>
                            </ViewCell>
                        </DataTemplate>
                    </ListView.ItemTemplate>
                </ListView>
            </StackLayout>
           
   
        </Grid>
    </ContentPage.Content>

</ContentPage>`

mainpage.cs:

`using OxyPlot;
using OxyPlot.Axes;
using OxyPlot.Series;
using OxyPlot.Xamarin.Forms;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace TestGrpah
{
    public partial class MainPage : ContentPage
    {
        ObservableCollection<RouterCTSADetails> RouterCollection;
        private ListView RouterChartListView;
        public MainPage()
        {
            InitializeComponent();
            RouterChartListView = this.FindByName<ListView>("ControlRouterlistview");
            RouterCollection = new ObservableCollection<RouterCTSADetails>() ;

            RouterCTSADetails routername;
            routername = new RouterCTSADetails();
            routername.Uri = "Helpdesk";
            RouterCollection.Add(routername);
            routername = new RouterCTSADetails();
            routername.Uri = "Support";
            RouterCollection.Add(routername);
            routername = new RouterCTSADetails();
            routername.Uri = "Email";
            RouterCollection.Add(routername);
            routername = new RouterCTSADetails();
            routername.Uri = "Chat";
            RouterCollection.Add(routername);

            RouterChartListView.ItemsSource = RouterCollection;
        }
        private void ViewCell_Tapped(object sender, EventArgs e)
        {
            try
            {
                if (((ViewCell)sender).BindingContext == null)
                    return;
                var Details = ((ViewCell)sender).BindingContext as RouterCTSADetails;
                int index = RouterCollection.IndexOf(Details);
                if (Details.isvisible)
                {

                    Details.isvisible = false;
                    Details.Uri = Details.Uri + "Unclicked";
                    if (index != -1)
                    {
                        RouterCollection.Remove(Details);
                        RouterCollection.Insert(index, Details);
                    }
                }
                else
                {

                    if (!string.IsNullOrEmpty(Details.Uri))
                    {
                        PlotModel m;
                        PlotView v1;
                        List<string> getChartDataFinal;
                        List<string> getChartData = new List<string>(new string[] { "08:00", "09:00", "10:00", "11:00", "3", "6", "1", "8", "33", "62", "15", "86" });
                        List<string> getChartData2 = new List<string>(new string[] { "12:30", "13:30", "14:30", "15:30", "3", "6", "1", "8", "33", "62", "15", "86" });
                        List<string> getChartData3 = new List<string>(new string[] { "16:40", "17:40", "18:40", "19:40", "3", "6", "1", "8", "33", "62", "15", "86" });
                        List<string> getChartData4 = new List<string>(new string[] { "21:50", "22:50", "23:50", "24:00", "3", "6", "1", "8", "33", "62", "15", "86" });
                        GenerateLineChart g = new GenerateLineChart();

                        if (index == 0)
                            getChartDataFinal = getChartData;
                        else if(index==1)
                            getChartDataFinal = getChartData2;
                        else if (index == 2)
                            getChartDataFinal = getChartData3;
                        else if (index == 3)
                            getChartDataFinal = getChartData4;
                        else
                            getChartDataFinal = getChartData;

                        m = g.DrawLineChart(getChartDataFinal);
                        //  Details.MyPlotViewModel = pr.GetRouterHistoryForLineChart(new string[] { Details.Uri });
                        //  Details.MyPiePlotViewModel = pr.GetRouterResultForPieChart(new string[] { Details.Uri });

                        Details.isvisible = !Details.isvisible;
                        Details.Uri = Details.Uri + "clicked";
                        if (index != -1)
                        {
                            v1 = ((ViewCell)sender).FindByName<PlotView>("LinePlotModel");

                            v1.IsVisible = true;
                            v1.Model = m;
                            RouterCollection.Remove(Details);
                            RouterCollection.Insert(index, Details);
                            ((ViewCell)sender).BindingContext = Details;

                        }
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }
        }
    }

    public class RouterCTSADetails
    {

        public string Uri { get; set; }
        public bool isvisible { get; set; }

    }

    public class GenerateLineChart
    {
        LineSeries callLineSeries, serviceLineSeries;
        TimeSpan tspan;
        public PlotModel DrawLineChart(List<string> getChartData)
        {
            int i = 0;
            int l = 0;
            string[] time = null;
            string[] call = null;
            string[] service = null;
            string[] chartData;
            chartData = new List<string>(getChartData).ToArray();
            try
            {
                if (chartData != null && chartData.Length > 0)
                {
                    time = new string[chartData.Length / 3];
                    for (i = 0; i < chartData.Length / 3; i++)
                    {
                        time[i] = chartData[i];
                    }
                }
                if (i == (chartData.Length / 3))
                {
                    int j = chartData.Length / 3;
                    l = j + j;
                    int k = 0;
                    call = new string[chartData.Length / 3];
                    for (i = j; i <= l - 1; i++)
                    {
                        call[k] = chartData[i];
                        k++;
                    }
                }
                if (i > chartData.Length / 2)
                {
                    int j = chartData.Length / 2;
                    service = new string[chartData.Length / 3];
                    int k = 0;
                    for (i = l; i < chartData.Length; i++)
                    {
                        service[k] = chartData[i];
                        k++;
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Could not load coordinates for line chart: " + ex.Message);
            }
            return drawChart(time, call, service, getChartData);
        }
        public PlotModel drawChart(string[] time, string[] call, string[] service, List<string> lineChartData)
        {
            double[] dCalls = null;
            PlotModel model = new PlotModel { Title = "", TitleColor = OxyColors.Gray };

            model.Background = OxyColors.White;
            model.ResetAllAxes();
            model.LegendPosition = LegendPosition.TopCenter;
            model.LegendPlacement = LegendPlacement.Outside;
            model.LegendOrientation = LegendOrientation.Horizontal;
            model.PlotType = PlotType.XY;
            model.InvalidatePlot(true);
            try
            {
                callLineSeries = new LineSeries()
                {
                    Title = "Calls",
                    StrokeThickness = 3,
                    MarkerType = MarkerType.Circle,
                    MarkerSize = 3,
                    Color = OxyColors.SkyBlue
                };

                serviceLineSeries = new LineSeries()
                {
                    Title = "Service level",
                    StrokeThickness = 3,
                    Color = OxyColors.Orange,
                    MarkerType = MarkerType.Square,
                    MarkerSize = 3
                };

                TimeSpan ts;
                dCalls = new double[time.Length];
                List<TimeSpan> timeValues = new List<TimeSpan>();
                for (int i = 0; i < time.Length; i++)
                {
                    if (TimeSpan.TryParse(time[i], out ts))
                        timeValues.Add(ts);
                    callLineSeries.Points.Add(new DataPoint(TimeSpanAxis.ToDouble(ts), Double.Parse(call[i])));
                    dCalls[i] = double.Parse(call[i]);
                    serviceLineSeries.Points.Add(new DataPoint(TimeSpanAxis.ToDouble(ts), Double.Parse(service[i])));
                }
                double highestCalls = (dCalls.Max()) + 1;
                int Length()
                {
                    if (timeValues != null && timeValues.Count > 0)
                    {
                        if (timeValues.Count > 10 && timeValues.Count < 13)
                            return 20;
                        else if (timeValues.Count >= 13)
                            return 15;
                        else if (timeValues.Count < 10)
                            return 30;
                        else
                            return 30;
                    }
                    else
                        return 30;
                }
                model.PlotAreaBorderColor = OxyColors.Transparent;

                model.Axes.Add(new LinearAxis { Position = AxisPosition.Right, Minimum = 0, Maximum = 110, Title ="Service level", TitleColor = OxyColors.Orange, AxislineStyle = LineStyle.Solid, MinorTickSize = 0, MajorTickSize = 5, IsPanEnabled = false, IsZoomEnabled = false });
                model.Axes.Add(new LinearAxis { Position = AxisPosition.Left, Minimum = 0, Maximum = highestCalls, Title = "Calls", TitleColor = OxyColors.SkyBlue, AxislineStyle = LineStyle.Solid, Key = "CallsAxis", MinorTickSize = 0, MajorTickSize = 5, IsPanEnabled = false, IsZoomEnabled = false });
                model.Axes.Add(new TimeSpanAxis
                {
                    Position = AxisPosition.Bottom,
                    LabelFormatter = d => { return string.Format("{0:00}:{1:00}", TimeSpanAxis.ToTimeSpan(d).Hours, TimeSpanAxis.ToTimeSpan(d).Minutes); },
                    Angle = -90,
                    AxislineStyle = LineStyle.Solid,
                    MajorTickSize = 5,
                    MinorTickSize = 0,
                    Minimum = TimeSpanAxis.ToDouble(timeValues[0]),
                    Maximum = TimeSpanAxis.ToDouble(timeValues[timeValues.Count - 1]),
                    IntervalLength = Length(),
                    IsZoomEnabled = false,
                    IsPanEnabled = false
                });
                callLineSeries.YAxisKey = "CallsAxis";
                model.Series.Add(callLineSeries);
                model.Series.Add(serviceLineSeries);
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine("Could not create line chart: " + ex.Message);
            }
            return model;
        }

    }
}`

**Comment by objorke** [comment]
Please copy the issue to https://github.com/oxyplot/oxyplot-xamarin
