### ISSUE TITLE
Tracker that only clips to data points and is always shown

### ISSUE THREAD

**Issue by hunterzzzpro** [oxyplot/oxyplot#1293]
The tracker seems to attach itself to the line rather than only attaching to the data points. 
Is there a way to make it only attach to the data points?

Also, on a touch-screen, it doesn't allow you to see the tracker if you move your finger at all. If panning is disabled it should allow the tracker to move up and down with the finger.

Thanks, any assistance on these matters will be great.

**Comment by VisualMelon** [comment]
You can prevent the tracker snapping to non-points on the line by setting the `LineSeries.CanTrackerInterpolatePoints` to false.

I'm afraid I can't help with the other issue, but it might help others to investigate if you could elaborate on which platform you are using.

**Comment by hunterzzzpro** [comment]
That works perfect!

Thank you

FWI: I'm using OxyPlot for a WPF application

**Comment by objorke** [comment]
Please create another issue for the visibility of the tracker with touch!
