### ISSUE TITLE
Limit lines

### ISSUE THREAD

**Issue by DenZuck** [oxyplot/oxyplot#1296]
### Feature description

Are limit lines implemented in this library? I need to highlight a range (min/max) like in example.

<img width="464" alt="image" src="https://user-images.githubusercontent.com/7376037/57928303-97ed4f80-78b0-11e9-89de-b287e324af2e.png">

**Comment by Dunkhan** [comment]
Check out the Annotations specifically RectangleAnnotation and LineAnnotation
You can draw a bar anywhere with that.

**Comment by DenZuck** [comment]
That's exactly what I was looking for. RectangleAnnotation for the green area and LineAnnotation for the middle line.

Thanks.
