### ISSUE TITLE
Issue with binding LineSeries to dynamic objects

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#130]
**Imported from [http://oxyplot.codeplex.com/workitem/10181](http://oxyplot.codeplex.com/workitem/10181)**

**[Sepidar](http://www.codeplex.com/site/users/view/Sepidar)** 2014-04-19 13:32
When binding a LineSeries to an object that implements ICustomTypeDescriptor, LineSeries can not find dynamic properties set in DataFieldX and DataFieldY. It is because you are using GetType() of objects in ReflectionHelper class. To overcome this problem,
 you can correct that code like this:

<pre><code>    public static void FillList(List<DataPoint> target, IEnumerable itemsSource, string dataFieldX, string dataFieldY)
    {
        PropertyDescriptor px = null;
        PropertyDescriptor py = null;
        Type t = null;

        foreach (var o in itemsSource)
        {
            if (pix == null || o.GetType() != t)
            {
                t = o.GetType();
                var properties = TypeDescriptor.GetProperties(o);
                px = properties(dataFieldX);
                py = properties(dataFieldY);
                if (px == null)
                {
                    throw new InvalidOperationException(
                        string.Format("Could not find data field {0} on type {1}", dataFieldX, t));
                }

                if (py == null)
                {
                    throw new InvalidOperationException(
                        string.Format("Could not find data field {0} on type {1}", dataFieldY, t));
                }
            }

            double x = Axis.ToDouble(px.GetValue(o));
            double y = Axis.ToDouble(py.GetValue(o));

            var pp = new DataPoint(x, y);
            target.Add(pp);
        }
    }
</code></pre>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-04-25 23:16
I don't think <code>TypeDescriptor</code> is available in PCL. Are there other ways to reflect on a dynamic object?

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
