### ISSUE TITLE
Mac Package?

### ISSUE THREAD

**Issue by kyluke** [oxyplot/oxyplot#1304]
Are there any plans to include a Xamarin.Mac nuget again? There is an old one on nuget that hasn't seen an update in years.

**Comment by kyluke** [comment]
any update?

**Comment by objorke** [comment]
This belongs to https://github.com/oxyplot/oxyplot-xamarin/issues, please create an issue there, or comment on this one: https://github.com/oxyplot/oxyplot-xamarin/issues/84
