### ISSUE TITLE
isDataUpdated issue

### ISSUE THREAD

**Issue by sensokame** [oxyplot/oxyplot#1308]
https://github.com/oxyplot/oxyplot/blob/2c254dc8352f59b927e7f6600071fcfa5fe764e7/Source/OxyPlot/PlotModel/PlotModel.cs#L1050

Going through the code of PlotModel, I came across this attribute, it's private attribute used to check if the data is updated or not, but it is never assigned as false which makes this check redundant.
Also, if this attribute is ever set to false/true shouldn't this check be && and not || as it is useless to update data if it is already updated?

**Comment by VisualMelon** [comment]
This looks like a classic invalidation flag, and looks fine to me.

It will have the initial (default) value of `false` when the `PlotModel` is constructed; it then forces the model to update the data the first time it is used. If the data changes after first usage, then you need to tell it, but it updates the first time whether or not it is explicitly requested.

**Comment by sensokame** [comment]
got it 👍  😛
