### ISSUE TITLE
DateTimeAxis: not displaying first and last axis labels?

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#131]
**Imported from [http://oxyplot.codeplex.com/workitem/10186](http://oxyplot.codeplex.com/workitem/10186)**

**[krishnaramuu](http://www.codeplex.com/site/users/view/krishnaramuu)** 2014-04-27 13:41
Hi, 

I have generated a line series graph that has datetime axis, when I try to generate the graph for the dates that doesn't have hours(i.e., zero hours it means the starting of the day) for example: 01-April-2014 00:00:00 to 15-April-2014 00:00:00 it could able
 to plot it with the starting datetime axis label and ending datetime axis label. If I set the dates with hours say like: 01-April-2014 16:00:00 to 15-April-2014 16:00:00, starting datetime axis label and ending datetime axis label are not being shown in the
 graph. I have attached an image to this issue. Please suggest how this can be solved.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-04-28 08:18
If this is a bug, please include code that reproduces the error!

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
