### ISSUE TITLE
Unable to build ExampleBrowser

### ISSUE THREAD

**Issue by silviubogan** [oxyplot/oxyplot#1316]
### Steps to reproduce

1. Try to build `\Source\Examples\WPF\ExampleBrowser` directory's project using Visual Studio 2019 on Windows 10.
1.1. Clone the repo `origin/develop`
1.2. Run dotnet restore in this directory.
1.3. Double click ExampleBrowser.csproj in Explorer.
1.4. Command build.
2. Build fails with:
The tag 'PlotView' does not exist in XML namespace 'clr-namespace:OxyPlot.Wpf;assembly=OxyPlot.Wpf'. Line 119 Position 18. MainWindow.xaml	119	

Platform:
.NET version: I use .NET Framework v4.7.2 usually, but now I just wanted to start working on something.

### Expected behaviour

The project should build successfully and the examples program should start, as I understood from [here](http://docs.oxyplot.org/en/latest/introduction/faq.html#where-can-i-find-examples).

### Actual behaviour

![devenv_2019-07-03_12-04-06](https://user-images.githubusercontent.com/198924/60579006-ea180080-9d8a-11e9-8841-33771fec0f6a.png)

**Comment by Mrxx99** [comment]
This project builds and runs fine for me.
Have you tried opening the whole solution instead of only the project?
The solution is "OxyPlot.WPF.sln" in the folder Source.

**Comment by silviubogan** [comment]
Your solution works. Thank you!
