### ISSUE TITLE
NetStandard 2.0  of oxplot?

### ISSUE THREAD

**Issue by alan-araya** [oxyplot/oxyplot#1319]
### Is there any plans to move Oxplot to full build/compatible with .NetStandard 2.0? Since .Net 4.61 should end the "official support" on the end of 2019, I guess you guys are working to port the lib to netstandard soon.

There any ETA of it?

**Comment by VisualMelon** [comment]
`OxyPlot.Core` already works with .NET Standard; I'm not sure I understand your question?

**Comment by alan-araya** [comment]
We are testing the build/archive done, but whats concerns our team is the warning message thrown by VS:

Warning	NU1701	Package 'OxyPlot.Core 1.0.0' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by danpaul88** [comment]
The 2.x preview versions support netstandard1.0 - they are some way behind the latest code in this repo however. I'm unsure when/if an updated beta / non-beta NuGet package is planned anytime soon.

https://www.nuget.org/packages/OxyPlot.Core/2.0.0-unstable1035

**Comment by alan-araya** [comment]
Right...We tested the build of a .NetStandard 2.0 using the nuget 1.0 of OxyPlot and was OK. As we were porting a PCL to NetStandard code the functions used on the project still works fine.
The warning is not very likely but we will use the 1.0 until a new stable be released.

**Comment by VisualMelon** [comment]
Can this be closed?
