### ISSUE TITLE
MajorGridlineStyle is ignored and always drawn as Solid

### ISSUE THREAD

**Issue by SFSteve** [oxyplot/oxyplot#1325]
### Steps to reproduce

1. Create a plotview and add a bottom axis
2. Set the MajorGridlineStyle to anything other than solid or none
3. Run

Platform: Xamarin forms
.NET version: standard 2.0

### Expected behaviour

The grid lines between the values should be dotted

### Actual behaviour

The lines are solid
![image](https://user-images.githubusercontent.com/24298678/62139337-0d2dc580-b2e1-11e9-9285-19b23337e9a1.png)

**Comment by objorke** [comment]
Please recreate this in https://github.com/oxyplot/oxyplot-xamarin/, I guess this is a Xamarin Forms specific issue :-)
