### ISSUE TITLE
Improve automatic MinorStep when MajorStep is 2

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#133]
**Imported from [http://oxyplot.codeplex.com/workitem/10188](http://oxyplot.codeplex.com/workitem/10188)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-04-28 10:39
When MajorStep is 2, the automatic MinorStep should be 0.5, not 0.4. 

Divide by 4 not by 5 in this case.

**Comment by VisualMelon** [comment]
Can this be closed?

**Comment by Jonarw** [comment]
Yes, I would think so.
