### ISSUE TITLE
Make use of the project

### ISSUE THREAD

**Issue by twsI** [oxyplot/oxyplot#1342]
This repo got a project, which could be used to sort issues by importance in a backlog, which currently isn't a thing. This could help people to figure out, which issue to work on. Right now, with over 400 issues, I have no idea where to start, in case I wanted to help.

**Comment by objorke** [comment]
Which projects could we create?
We also have labels? I suggest to see "high-priority", "good first issue" etc.

**Comment by twsI** [comment]
I had a simple Development project in mind to sort them, but i guess using labels is a good start.
