### ISSUE TITLE
Encoding Support for PDF Export in Core Library

### ISSUE THREAD

**Issue by nzain** [oxyplot/oxyplot#1343]
The core `PortableDocument` currently only supports `FontEncoding.WinAnsi` which limits the set of available characters. Right now, `PdfWriter` internally converts all strings to UTF-8 when writing a file and non-ANSI characters will be garbage in the viewed PDF. For example, the german special characters 'äöüß' work, but an interesting symbol like '≤' (\u2264) does not. Unicode support would be desirable, but unfortunately the PDF specification does not easily allow that.

This issue is part of #85 and may be related to #955. This blocks #866.

My initial web search did not turn up "a good way". As far as I understand, multiple Adobe specific ways to encode text are possible and none of them seems to be directly related to UTF-8 or UTF-16. Unicode support seems to require an additional `/ToUnicode` table.

Interesting reads:

- https://www.gnostice.com/nl_article.asp?id=383&t=Font_and_Encoding_Standard_types_supported_in_PDF_for_the_representation_of_text_content
- https://github.com/angea/PDF101  (hand made PDFs with unicode encoding, even customized)

Eventually it is possible to reverse-engineer a valid unicode PDF file (link above) to find a simple way to support at least Arial Unicode characters.

**Comment by nzain** [comment]
For all work on this, I'll refer to the [PDF-1.3 Specification](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDFReference13.pdf) because `1.3` is the writte version by our writer. Disclaimer: This topic becomes much more complicated than I expected and all the following information may be wrong, because I didn't really understand the spec! Corrections or help are very welcome.

Section 3.2.3 (pg 27) details _string objects_, either a sequence of literal characters enclosed in parentheses `( )` or a sequence of hex values enclosed in angle brackets `< >`. The following two both represent that string `syntax`:

    (syntax)
    <73 79 6E 74 61 78>

Section 3.8.1 (pg 88) talks about unicode text strings:
> For text string encoded in Unicode, the first two bytes must be `254` followed by `255`, representing the Unicode byte order marker, `U+FEFF` [known as BOM].
> The remainder of the string consists of unicode character codes, according to the `UTF-16` encoding [...]

**Unfortunately, this is not enough...** (or I did some mistake). Resulting PDF was empty.

Section 5.5.1 (pg 294+) refers to simple Type 1 fonts and tells us that the _Font Dictionary_ can either use some predefined `/Encoding` (right now Win ANSI, unicode is *not* available here) or specify a `/ToUnicode` CMap object like here:

    12 0 obj
    <<
      /BaseFont         /BAAAAA+Helvetica
      /FirstChar        0
      /FontDescriptor   14 0 R
      /LastChar         99
      /Subtype          /TrueType
      /ToUnicode        15 0 R
      /Type             /Font
      etc...

Section 5.5.5 (pg 305) is about character encoding, but I could not find relevant unicode information.

Section 5.6 and 5.6.1 (pg 310+) explain _composite fonts_ and multi-byte encodings. Eventually, it is not possible to use a simple standard font (built-in helvetica) and unicode together?

Pg. 312:
> A _CMap_ (character map) file specifies the correspondence between character codes and the CID numbers used to identify characters. It is equivalent to the concept of an encoding in simple fonts. Whereas a simple font allows a maximum of 256 characters to be encoded and accessible at one time, a CMap can describe a mapping from multiple-byte codes to thousands of characters in a large CID-keyed font. For example, it can describe [...] Unicode, an international standard encoding that covers many languages.

Section 5.6.4 (pg. 319) is about CMaps. Looks complicated and mandatory for this journey. There are predefined CMaps that could be referenced, including several UCS variants. Not sure, if those predefined maps are of any use for us.

Section 5.9 (pg 342) describes `/ToUnicode` CMaps. The introduction sounds like this is optional and only required for PDF interpreters (e.g. copy text).

Finally, Appendix D "Character Sets and Encodings" only describes built-in encodings, *not* unicode.

**Comment by Jonarw** [comment]
Covered by #1514.
