### ISSUE TITLE
Add Color to HistogramItem

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1347]
If not set, use the color of the parent series.

**Comment by VisualMelon** [comment]
Unless someone wants to cut their teeth on this, I'll sort it out after #1345 is resolved. I figure `HistogramItem` should provide 2 constructors, one taking a color and one which just sets it to undefined (fallback to color of the series), so there shouldn't be any dependency between the two.

**Comment by Jonarw** [comment]
When you're already fiddling with `HistogramItem` and the Histogram API in general, here's another point that might be worth considering:
Personally sometimes I like to know how many items exactly fall into a given histogram bin. Therefore I think it would be great if `HistogramItem` could also store the actual number of items contained in the respective bin. This wouldn't have any consequence for rendering etc., it would just enable us to display this information in the Tracker to be able to display this information to the user on demand.

This would require the following changes:
- Add `Count` property to `HistogramItem` (maybe as optional constructor item)
- Adapt `HistogramSeries.GetNearestPoint(...)` to be able to display this in the Tracker
- (optional) Adapt the `HistogramHelpers`
- (optional) Change default format string to include the `Count`

What do you think?

**Comment by VisualMelon** [comment]
I think that is a good idea. I'll add it as part of #1345 since it will need to be tested in the helper methods.
