### ISSUE TITLE
Increase size of marker as user zooms in

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#135]
**Imported from [http://oxyplot.codeplex.com/workitem/10192](http://oxyplot.codeplex.com/workitem/10192)**

**[oriches](http://www.codeplex.com/site/users/view/oriches)** 2014-05-08 16:35
Is it possible to increase the size of a point marker as the user zooms into the control?

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-08 18:32
LineSeries or ScatterSeries? Note that this library is cross-platform so this feature would be valid for all platforms, not only WPF.

Do you want to define the size in data space? Or in some other way?

I think this should be implemented as a custom series unless this could be a frequently used feature in LineSeries/ScatterSeries.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-08 18:33
Removed WPF from the workitem title.

**[oriches](http://www.codeplex.com/site/users/view/oriches)** 2014-05-08 19:06
I was thinking of LineSeries, I wanted the ability to increase\decrease the marker size when the user zooms in\out, there would be a min & max zoom value (defined by the user).

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-08 19:39
I think this can be solved by using the axis changed event. Then it is not necessary to add a new feature.

**[oriches](http://www.codeplex.com/site/users/view/oriches)** 2014-05-08 21:02
That was my thinking after investigating the Axis class further, thanks for the info anyway.

**Comment by upics** [comment]
I can't find a solution to this request. How can i achieve this behaviour? (Increase size of marker as user zooms in and viceversa)
