### ISSUE TITLE
C# syntax highlighting in OxyPlot.WPF Example Browser

### ISSUE THREAD

**Issue by silviubogan** [oxyplot/oxyplot#1356]
In my opinion this would be even more important than improving the documentation. If not, I would be glad to start improving the documentation. I think solving this issue would help me work on the docs faster and would also help to make the project more attractive.

I think it is not complicated, maybe there is a NuGet package for C# syntax highlighting but I am not sure.

I can take this issue if there is agreement upon this.

#### Description

Colored C# syntax in OxyPlot.WPF Example Browser, when selecting a section in the left sidebar, selecting an example in the section, and in the bottom of the window then selecting the `Code` tab.

#### How it should work

I would like it to work automatically, and there to be an option to copy as plain text and, if possible, as rich-formatted text or something similar like HTML.
It could also be a feature manually enabled: a checkbox in the bottom of the Code page, or in the context menu of the TextBox.

#### How should it look

Currently it looks like this (it also shows the context menu):

![ExampleBrowser_2019-09-15_09-17-33](https://user-images.githubusercontent.com/198924/64917548-894d7100-d79a-11e9-9b2c-937ff6fdad42.png)

Thank you.

**Comment by objorke** [comment]
I agree syntax highlighting is nice, but I don't think we should do this. It will add another package dependency to the example browser that needs to be maintained, and it will be a lot of work to make this consistent on all platforms that has an implementation of the example browser.
