### ISSUE TITLE
.net core 3 support 

### ISSUE THREAD

**Issue by JP75012** [oxyplot/oxyplot#1359]
### Feature description

As .net framework will be stopped by the end of 2020, it is necessary to support.net core 3 since wpf can be executed on .net core 3

**Comment by VisualMelon** [comment]
See https://github.com/oxyplot/oxyplot/issues/1331

Note that .NET Framework will not disappear over night: it will continue to be supported for a while yet. But yes, we should get on with this now that .NET Core 3 is actually out.

**Comment by JP75012** [comment]
Yes of course . But new applications should be started on core 3 instead of framework to avoid a migration later.

**Comment by objorke** [comment]
Agree we need to add support for .NET Core 3.0. This is a duplicate of #1331.
