### ISSUE TITLE
Xamarin.Forms export charts to image

### ISSUE THREAD

**Issue by olivercortinas** [oxyplot/oxyplot#1372]
The export to IMAGE or PDF for Xamarin.Forms is not included yet correct?
I have a requirement for that, any idea when is going to be added or if it's going to be added in some moment?
Thanks.

**Comment by objorke** [comment]
OxyPlot.Core (.NET Standard 1.0) contains PDF export (with some limitations, see https://github.com/oxyplot/oxyplot/labels/pdf).
OxyPlot.Drawing.Core (.NET Standard 2.0) contains export to PNG images.
It is also suggested to add export to PNG with ImageSharp #1188

**Comment by objorke** [comment]
If a native implementation for Xamarin is needed, please add the issue for https://github.com/oxyplot/oxyplot-xamarin/issues
