### ISSUE TITLE
project URI should be updated

### ISSUE THREAD

**Issue by nzain** [oxyplot/oxyplot#1388]
The project URI on nuget packages (see [https://www.nuget.org/packages/OxyPlot.Wpf](https://www.nuget.org/packages/OxyPlot.Wpf)) points to some japanese (?) page with cats. It should be updated to [https://oxyplot.github.io](https://oxyplot.github.io)

**Comment by objorke** [comment]
This should already be done - v2.0 packages should be correct
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.Wpf/OxyPlot.Wpf.csproj#L10

**Comment by VisualMelon** [comment]
@objorke indeed, but the nuget website still points to `oxyplot.org`. Would a 2.0 pre-release be a good solution... :)

**Comment by swharden** [comment]
@objorke the URL is still wrong on the organization page https://github.com/oxyplot

![image](https://user-images.githubusercontent.com/4165489/82161509-57316900-986b-11ea-83ed-7c759900e69c.png)

although I did enjoy spending the last few minutes looking through Japanese cat pictures 😸

**Comment by VisualMelon** [comment]
@swharden thanks, should be fixed.
