### ISSUE TITLE
Make the PngExporters consistent

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1390]
The PngExporter for WPF, Winforms and Core.Drawing should be consistent.
I suggest ot use the WinForms exporter as a template:

Include
- a static method to write to a file ("convenience"/one-liner method)
- a method to write to a stream
- a method to write to a platform dependent bitmap 

Do not add additional methods (=confusing)
Do not use native brush as parameter (making your code less portable)
Use `double` for resolution parameter
The implementation should be in the export to stream instance method

**Comment by VisualMelon** [comment]
I mostly concur. The situation in `Core.Drawing` is a bit ridiculous; however, the native brushes do allow some additional flexibility (e.g. they support gradients/hatching, not that we'd want to encourage that).

Would it make sense to align `SvgExporter` and `PdfExporter` at the same time? Their static methods both target only streams at the moment.

**Comment by objorke** [comment]
I see the additional possibilities if allowing native brushes, but I would prefer to not create such methods. The main principle in this library is to keep everything as portable as possible.

For SVG and PDF I suggest to create a separate issue. In the OxyPlot library we cannot export to file.

**Comment by VisualMelon** [comment]
> I would prefer to not create such methods.

Suits me.

> In the OxyPlot library we cannot export to file.

Wow. I didn't even realise that wasn't a thing in NetStandard 1.1. In that case, I don't see any dire need to change touch them, but I'd of course be happy to discuss/implement any suggestions.
