### ISSUE TITLE
Dispose brushes in PNG exporters

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1392]
### Steps to reproduce

1. Export PNG to stream

Platform: Winforms, Core.Drawing

### Expected behaviour

Brushes should be disposed

### Actual behaviour

Brushes not disposed?

**Comment by objorke** [comment]
#1391

**Comment by objorke** [comment]
#822 Is this related?

**Comment by VisualMelon** [comment]
I don't think this is relevant, but I'll have a go at reproducing #822 to confirm.

**Comment by VisualMelon** [comment]
Nope, I can't reproduce #822 under various configurations (feels like I've tried and failed before). WPF brushes shouldn't need disposal (and there is no mechanism by which we can accelerate their demise), so I think this can be closed since #1391 is merged.
