### ISSUE TITLE
Change ScatterPoint to value type

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#140]
**Imported from [http://oxyplot.codeplex.com/workitem/10208](http://oxyplot.codeplex.com/workitem/10208)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-27 15:29
The ScatterPoint is currently a reference type (class) 

Can we improve performance by changing to a value type? 

(similar to what was done for LineSeries/DataPoint)

**Comment by objorke** [comment]
I would like to see this breaking change in v1.0

**Comment by tibel** [comment]
I think that `ScatterPoint` might be to big for a `struct`, as stated by [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/ms229017.aspx).

**Comment by objorke** [comment]
Agree, it seems to be no good reason for changing this. I was thinking consistency with DataPoints, but now I think these cases are different.
I created branch with an example.
