### ISSUE TITLE
Most portable exporters ignore `PlotModel.Background`, but SVG does not.

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1409]
The two portable PNG Exporters and the portable PDF exporter both ignore the `PlotModel` background property, but the portable SVG Exporter does not.

Since it doesn't seem to be the job of the `PlotModel` to render its own background, this should surely be the job of the exporter?

Each of these exporters (except SVG) has its own `Background` property. I would suggest that if this is left undefined, then it should use the `PlotModel` background property. I'll be happy to implement these changes if they are deemed desirable.

**Comment by objorke** [comment]
Agree all these exporters should handle the `Background` property consistently. Do we need to be able to set it in the exporters? Could we remove this property from the exporters?

**Comment by VisualMelon** [comment]
I can't think of an especially compelling reason to keep them; though, they don't seem to be doing much harm. I'd be happy to strip them out entirely (i.e. so everything is as SVG is now), which would - if nothing else - save me writing a lot of tests, and make it harder for them to become out-of-sync again. I'll try to remember to sort out a PR over the weekend if nobody beats me to it.
