### ISSUE TITLE
Can't install Oxyplot.XamarinIOS

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#141]
**Imported from [http://oxyplot.codeplex.com/workitem/10209](http://oxyplot.codeplex.com/workitem/10209)**

**[Death69](http://www.codeplex.com/site/users/view/Death69)** 2014-05-27 15:51
Hi, 

i tried to install the assembly but there comes an error message that the "packages.config" is already in the folder. I tried to delete the packages.config and do a re-install but the error appeared again.

I'm using the latest Xamarin.IOS in VS2012. 

Any suggestions?

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-28 00:03
I tried reproducing this on VS 2013, but here the OxyPlot.XamarinIOS NuGet package is downloaded and installed properly.

**[Death69](http://www.codeplex.com/site/users/view/Death69)** 2014-05-28 08:06
Then this must be a problem with VS 2012. I have VS 2012 with Update 4 Version: 11.0.61030.00

Do you wan't me to post my info of VS?

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-31 11:43
Is this happening when you create a new clean project and add the OxyPlot.XamarinIOS NuGet reference? Is anybody else having this problem with VS?

**[Death69](http://www.codeplex.com/site/users/view/Death69)** 2014-06-02 07:59
Yes, thats happening when i create a new Project and try to add the reference.

**Comment by tibel** [comment]
The package name has changed to `OxyPlot.Xamarin.iOS`. As this is an old issue I think it should be closed.
