### ISSUE TITLE
Heatmapseries and scatterseries with coloraxis in a plot

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#142]
**Imported from [http://oxyplot.codeplex.com/workitem/10212](http://oxyplot.codeplex.com/workitem/10212)**

**[CSharpdevs](http://www.codeplex.com/site/users/view/CSharpdevs)** 2014-05-30 14:19
It may need to be drawn together of two different chart types in the specific applications. The Oxyplot allows this type plots. For example, it needs to be marked the specific points on the heatmap, the following code is used. Two chart use same linercoloraxis
 in the example.

<pre><code>scatterSeries2.Points.Add(new OxyPlot.Series.ScatterPoint(xp, yp, 3, colorValue));</code></pre>
In the above code, the size of the points is defined a constant (3). the zp variable is used insted of (3), the points have different sizes depening on selected binsize.

<pre><code>var pm3 = new PlotModel();
            var lca4 = new OxyPlot.Axes.LinearColorAxis { Palette = OxyPalettes.Jet(100) };
            lca4.Position = OxyPlot.Axes.AxisPosition.Right;
            lca4.FontSize = 18;
            var la4 = new OxyPlot.Axes.LinearAxis();
            la4.Position = OxyPlot.Axes.AxisPosition.Bottom;
            la4.FontSize = 18;
            la4.Title = "X ";
            la4.Minimum = 0;
            la4.Maximum = (nx - 1) * dx;
            var lb4 = new OxyPlot.Axes.LinearAxis();
            lb4.Position = OxyPlot.Axes.AxisPosition.Left;
            lb4.FontSize = 18;
            lb4.Title = "Y ";
            lb4.Minimum = 0;
            lb4.Maximum = (ny - 1) * dy;
            pm3.Axes.Add(la4);
            pm3.Axes.Add(lca4);
            pm3.Axes.Add(lb4);
            var hm2 = new OxyPlot.Series.HeatMapSeries();
            hm2.X0 = 0; hm2.X1 = (nx - 1) * dx; hm2.Y0 = 0; hm2.Y1 = (ny - 1) * dy;
            hm2.Interpolate = true;
            hm2.Data = new double[datanumberx, datanumbery];
            for (int j = 0; j < datanumbery; j++)
            {
                double yc = (j) * dy;
                for (int i = 0; i < datanumberx; i++)
                {
                    double xc = (i) * dx;
                    hm2.Data[i, j] = anomaly[i, j];
                }
            }
            pm3.Series.Add(hm2);
            var scatterSeries2 = new ScatterSeries { MarkerType = MarkerType.Circle };
            scatterSeries2.BinSize = 10;
            scatterSeries2.MarkerType = MarkerType.Circle;
            scatterSeries2.MarkerStrokeThickness = 1;
            scatterSeries2.MarkerStroke = OxyColors.Black;
            verisay = dataGridView10.RowCount;
            for (int i = 1; i < verisay; i++)
            {
                double xp = Convert.ToDouble(dataGridView1[0, i].Value);
                double yp = Convert.ToDouble(dataGridView1[1, i].Value);
                double zp = -Convert.ToDouble(dataGridView1[2, i].Value);
                var sizem = Convert.ToInt32(zp);
                var colorValue = zp;
                scatterSeries2.Points.Add(new OxyPlot.Series.ScatterPoint(xp, yp, 3, colorValue));
            }
            pm3.Series.Add(scatterSeries2);
            plot3.Model = pm3;</code></pre>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-05-31 11:38
Is this an issue? Sorry, I don't understand the problem. Can you change the code so it can be included in the ExampleLibrary under OpenIssues.cs?

**[CSharpdevs](http://www.codeplex.com/site/users/view/CSharpdevs)** 2014-06-01 22:30
Where is the example library submit link.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-06-02 00:41
The code should be included in

~\Source\Examples\ExampleLibrary\Issues\OpenIssues.cs

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
