### ISSUE TITLE
Remove PlotModel Width and Height properties

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1424]
Are these properties needed?

Remove these properties (breaking change), or replace with
```cs
        public double Width => this.PlotArea.Width; 
```

**Comment by objorke** [comment]
I suggest to remove these properties.

**Comment by VisualMelon** [comment]
Do they not describe the plot bounds rather than the plot area?

**Comment by objorke** [comment]
I may have been to quick on this... 
It is related to #1425 - should it be to change into an `OxyRect`?

**Comment by objorke** [comment]
I suggest to cover this in #1425.

**Comment by VisualMelon** [comment]
I'd second that. A `PlotBounds` rectangle would be most welcome.
