### ISSUE TITLE
Change IPlotModel.Render

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#1425]
Change the signature of the `Render` method in `IPlotModel` to
```cs
        void Render(IRenderContext rc, OxyRect rect);
```

This should make it possible to add subplot functionality easily #55

**Comment by VisualMelon** [comment]
Regarding subplots, I found it useful to define 2 versions, one where the rect determined the plot bounds (which is what I assume the proposal is suggesting), and one which determines the plot area, though the later can be simulated by fixing the margins.

**Comment by objorke** [comment]
I see you have suggested this already in the subplot issue :-)
It would be great if we could achieve the second version (aligned "plot areas") without adding extra parameters to the `Render` method. Can we try this minor change first, and see how well that can work with subplots?

**Comment by VisualMelon** [comment]
Certainly!
