### ISSUE TITLE
OxyThickness Width and Height

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1429]
The definitions of `OxyThickness.Width` and `Height` look wrong. They are defined as `Right - Left` and `Top - Bottom`, which would make sense for a `Rect`, but I would expected `Right + Left` and `Top + Bottom` for thickness.

Is this just me misunderstanding the API?

The only code I can find which uses it is the equality checker in `OcyThickness` itself, which is OK, but should probably compare the `Right` and `Bottom` instead.

**Comment by Jonarw** [comment]
I think you are right.
I would go even farther and say `Width` and `Height` don't make much sense for `OxyThickness`. Given that these properties are only used for equality checking and can easily be replaced there we could completely remove these.
