### ISSUE TITLE
Lineseries Tracker background

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#143]
**Imported from [http://oxyplot.codeplex.com/workitem/10213](http://oxyplot.codeplex.com/workitem/10213)**

**[papy_mujo](http://www.codeplex.com/site/users/view/papy_mujo)** 2014-06-02 18:17
Hi CodePLex, 

Thanks for Oxyplot that is very usefull for me. 

I have an issue for you. 

I display graphes with Lineseries, ans I would like to customized the tracker popup, when the user put the mouse over the curve.

I have already update the displayed sentence with TrackerFormatString. 

Is that possible to modify the backgroud color?? 

Thanks a lot for your answer

**Comment by Fruchtzwerg94** [comment]
Styling is also possible quite simple, this means you do not need to define the whole template by your own:

```
<oxy:PlotView.Resources>
    <Style TargetType="oxy:TrackerControl">
        <Setter Property="Background" Value="Red"/>
    </Style>
</oxy:PlotView.Resources>
```

**Comment by CinzV** [comment]
I have the same problem with Maui, but on Android/iOS.

```
<oxy:PlotView.Resources>
    <Style TargetType="oxy:TrackerControl">
        <Setter Property="Background" Value="Red"/>
    </Style>
</oxy:PlotView.Resources>
```
not work for me. My code is:

```
 <oxy:PlotView x:Name="plotView"
               HeightRequest="400"
               BackgroundColor="#222222" >
     <oxy:PlotView.Resources>
         <Style TargetType="oxy:TrackerControl">
             <Setter Property="Background" Value="Red"/>
         </Style>
     </oxy:PlotView.Resources>
 </oxy:PlotView>
```

and if I try to set TrackerControl on the code behind, the compiler tells me that the method is deprecated.
Could you help me, please?
