### ISSUE TITLE
Setting `Series.Color` after  automatic coloring turns the series invisible.

### ISSUE THREAD

**Issue by dhanjit** [oxyplot/oxyplot#1434]
### Steps to reproduce

1. Create a LineSeries with `Color` not set.
2. Change the `Series.Color` value from the ui through a binding or internal code.
3. `InvalidatePlot(false)`
4. The series turns invisible. `IsVisible` remains true.

Platform:
.NET version: 4.7

### Expected behaviour

Ideally, the chose color should take effect for the lineseries.

### Actual behaviour

Series turns invisible.

**Comment by Jonarw** [comment]
Which platform? (WPF/Winforms etc.)
Could you provide a code sample, or even better, write an example that showcases this bug?
Thanks!

**Comment by dhanjit** [comment]
Here is a minimal example. Platform WPF.

```xml
<Grid>
<Grid.RowDefinitions>
    <RowDefinition Height="Auto"/>
    <RowDefinition Height="*"/>
</Grid.RowDefinitions>
<TextBox Grid.Column="0" Grid.Row="0" Text="{Binding Color, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged, ElementName=series}" TextChanged="TextBox__TextChanged"/>
<ScrollViewer Grid.Column="0" Grid.Row="1">
    <oxy:Plot Title="Demo" Name="plot">
        <oxy:Plot.Series>
            <oxy:LineSeries Name="series" ItemsSource="{Binding Points}"/>
        </oxy:Plot.Series>
    </oxy:Plot>
</ScrollViewer>
```

Then create the xaml.cs as:

```cs

public partial class MainWindow : MainWindow 
{
    public IList<OxyPlot.DataPoint> Points { get; set; }
    public MainWindow() {
        InitializeComponent();
        Points = new List<OxyPlot.DataPoint> { new OxyPlot.DataPoint(0,4), new OxyPlot.DataPoint(1,3), new OxyPlot.DataPoint(2,5) };
        this.DataContext = this;
    }

    private void TextBox__TextChanged( object sender, TextChangedEventArgs e) { plot.InvalidatePlot(false); }
}

```

**Comment by Jonarw** [comment]
Could the issue be that you try to assign a `string` to the `Color` property which is of type `OxyColor`? I think if you use a converter you should be fine.

**Comment by dhanjit** [comment]
I used a converter:

```cs

public class OxyColorConverter : IValueConverter {
    public object Convert(object value, Type targetType, object parameter, CultureInfo culture) 
    {
        if (value == null) return "";
        return ((System.Windows.Media.Color)value).ToString();
    }

    public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture) 
    {
        return System.Windows.Media.ColorConverter.ConvertFromString((string)value);
    }

}

```

I changed the binding to:

```xml

<TextBox Grid.Column="0" Grid.Row="0"
               Text="{Binding Color, Mode=TwoWay, ElementName=series, Converter={StaticResource conv}}" TextChanged="TextBox__TextChanged"/>

```

And added the conv as a resource.
Still the same issue.

When I put a breakpoint in the converter convert functions, was surprised to see conversion required to and from `Media.Color` instead of `OxyColor`. I don't know why that is the case.

**Comment by dhanjit** [comment]
Seems like it works if I pass `#FFFF0000` but not `#00FF0000` 🤔

**Comment by VisualMelon** [comment]
#00FF0000 has 00 in the alpha channel, so would be invisible.

**Comment by dhanjit** [comment]
What is the recommended way to convert from string/media.color to oxyplot color /converter

**Comment by VisualMelon** [comment]
What you have looks fine, and sounds like it is going what I would expect. `ColorConverter.FromString(string)` will turn `#FFFF0000` into Red, and `#00FF0000` into Fully Transparent (Red). Have you tried some other values such as `"Blue"`, `#FF00000` (omit alpha), etc.?

**Comment by dhanjit** [comment]
Thanks. I just created the color using RGB ignoring A and it worked.
