### ISSUE TITLE
why 2.0 not find property of Smooth

### ISSUE THREAD

**Issue by batsword** [oxyplot/oxyplot#1436]
I was use oxyplot2.0 for wpf,can't find smooth.
how to smooth lines with oxyplot 2.0?

**Comment by batsword** [comment]
i got it

**Comment by mzy666888** [comment]
> I was use oxyplot2.0 for wpf,can't find smooth.
> how to smooth lines with oxyplot 2.0?

Where can find smooth?

**Comment by batsword** [comment]
@mzy666888  InterpolationAlgorithm = InterpolationAlgorithms.CanonicalSpline, 
初始化LineSeries的时候 添加
