### ISSUE TITLE
Marker disappears at edges

### ISSUE THREAD

**Issue by davidollmann** [oxyplot/oxyplot#1443]
Hello, 
I found the following weird behaviour and it may is a bug.

### Environment
- .Net Core 3.0 WPF
- OxyPlot.Core 2.0.0
- OxyPlot.Wpf 2.0.0

### How to reproduce
1. Add the following line to your XAML
```CSharp
<oxy:PlotView x:Name="OxyPlotView" Width="250" Height="250" Margin="0,30,0,0" />
```
2. Add this method [https://pastebin.com/NDZsXsuL](https://pastebin.com/NDZsXsuL) that corresponding window/page .cs file
3. Call `OxyPlotTesting();` at the constructor

Run the program. Then it should look similar to this
![image](https://user-images.githubusercontent.com/19890733/70488093-e174e480-1af7-11ea-91d7-cb8336065cf1.png)

As you can see the points that lay directly on the edges are cut off.

### The next step
If I now add a title to my model like so `OxyPlotView.Model = new PlotModel() { Title = "TestPlot" };` the behaviour is different.
![image](https://user-images.githubusercontent.com/19890733/70488500-306f4980-1af9-11ea-9611-c7856d999b71.png)

### The step after
Now I remove the `Position = AxisPosition.Bottom` line on my axis. And now I see all marker by the cost of one axis.
![image](https://user-images.githubusercontent.com/19890733/70488638-a2e02980-1af9-11ea-8700-bf09e5adfda3.png)

### Expected behaviour 
I expect the result of "The set after" but at the configuration of the raw pastebin code. I could cheat and set the properties `AbsoluteMinimum` and `AbsoluteMaximum` to something like +/-1.000000001. But I need that exact +/- 1.

Now the question to the developers. Is that behaviour like you would expect it or would you agree to my assumption?

**Comment by VisualMelon** [comment]
The last example is because by removing `Position = AxisPosition.Bottom` you end up with two Y-axes and, and the X is the default axis (which often create confusion, and are being removed at some point). The default axis then doesn't have the min and max, and computes them automatically with a margin.

The other two must be due to rounding errors... I'll probably take a look later on. Generally I'd advise against fitting axes exactly to the plot bounds, because it means plot elements bleed into the axes (as occurs here), so I'd sooner go with +/- 1.1 or something. (What I'd like, is a way to add padding to explicit minimums and maximums...)

**Comment by Jonarw** [comment]
Without having looked at the code, this looks like a typical floating-point comparison issue.

**Comment by aNoxez** [comment]
Found another behaviour. If I add axis to all edges (left, right, top and bottom) like in the pastebin code, then all markers are shown correctly.

Is there any way to add a margin to the outer of the absolute min/max values (without showing the gridlines)? 
In my case, markers are draggable and users can define their own series (add points, drag them, ...). But it could be quite confusing if I show them more of the grid than they can really use.

**Comment by VisualMelon** [comment]
@aNoxez sorry, only just noticed your question. You may be able to achieve what you suggest by setting the axis `StartPosition` and `EndPosition` properties, zeroing the min/max padding, and setting `CropGridlines` to true). There is a "Gridlines Cropping" example in the example library that shows this effect.
