### ISSUE TITLE
"There are no components in OxyPlot.Wpf.dll that can be placed on the toolbox" error

### ISSUE THREAD

**Issue by username30** [oxyplot/oxyplot#1446]
Hello,
I've found a bug.

### Steps to reproduce
1. Open documentation, Getting started section, WPF (XAML) chapter
2. Follow steps in "Create the view" part regarding how to add Plot control at Toolbox
3. Browse OxyPlot.Wpf.dll in solution folder and add it to Toolbox

Platform: Windows 10, Visual Studio 16.4.1
.NET version: Core 3.0
OxyPlot version: OxyPlot.Wpf 2.0.0

### Expected behaviour
Plot control added at Toolbox so it could be used in design view.

### Actual behaviour
Following error message appears:

![devenv_5MCWrAP1aB](https://user-images.githubusercontent.com/24947452/70704464-185b1e00-1ce3-11ea-8bc7-884e8be2029f.png)

I tried different versions of this dll from neighbour subfolders in "packages" folder - none helped.

**Comment by VisualMelon** [comment]
Reproduced with .NET Core and .NET Framework.

**Comment by HavenDV** [comment]
I think you need to add a file like this:
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/blob/master/MaterialDesignThemes.Wpf/VisualStudioToolsManifest.xml
In fact, I want to eventually add full support for the WPF designer. Now, even with a simple example, it shows something like
<img width="762" alt="image" src="https://user-images.githubusercontent.com/3002068/184595334-3ca73b72-c804-4e73-bfa4-ead626938261.png">

**Comment by VisualMelon** [comment]
Exception looks an awful lot like #1904 ; maybe the WPF provider needs some work as well

**Comment by HavenDV** [comment]
I already tried to remove the annotations, but according to StackTrace, this is not the problem.
In fact, this is one of the reasons why I started adding nullable annotations. Now there are a lot of places in the code where NRE can occur.
Model based on which the screenshot was taken:
<img width="695" alt="image" src="https://user-images.githubusercontent.com/3002068/184595927-339824e7-8785-4e73-8dff-94f5c617b986.png">

**Comment by VisualMelon** [comment]
Sorry, probably should have expanded on that a bit. Yeah, I doubt it's annotations: that's a bit of a red-herring in the other issue: the issue there is that changes where being made to the plot between update and rendering; may be that the WPF provision is performing a render pass without ensuring an update in this instance.
