### ISSUE TITLE
oxyplot use gdi or d2d?

### ISSUE THREAD

**Issue by batsword** [oxyplot/oxyplot#1448]
oxyplot use gdi or d2d? 
not enough performance in wpf ，about 1 million points, 
Very slow

**Comment by VisualMelon** [comment]
The `OxyPlot.WindowsForms` and `OxyPlot.Common.Drawing` packages use the GDI+.

The `OxyPlot.SharpdDx.WPF` package provides a WPF embdeed D2D based renderer.

If you are showing 1 million points on one page, however, your best bet is pruning. Some series provide some such functinality already (e.g. Scatter Series provides binning).

**Comment by batsword** [comment]
@VisualMelon  Is the performance of D2D better than GDI +?

**Comment by batsword** [comment]
@VisualMelon 
Oxyplot 1.0.0 uses D2D, but the example seems to have bugs.
Is there a version available about oxyplot shartdx

**Comment by objorke** [comment]
Please use the template and formulate issues as bugs or feature requests.
You should test each implementation for your use case, I do not think we can make a general performance comparison (it may not depend on just the number of points).
