### ISSUE TITLE
Again support .NET 4.0 for WinForms and WPF

### ISSUE THREAD

**Issue by maettu-this** [oxyplot/oxyplot#1452]
### Again support .NET 4.0 for WinForms and WPF

As discussed by email, I believe really good libraries should not be limited to the latest bells and whistles, as not all applications can keep up with Microsoft release cycles and support deadlines. .NET 4.0 is the last version of .NET supported on WinXP, and a tool e.g. used on an autonomous machine in a production environment may be tied to the OS version used on that machine. So I ask for maintaining support for .NET 4.0 for WinForms and WPF, even knowing that Microsoft officially ended support for .NET 4.0. (Note that if the Microsoft dates were strictly followed, .NET 3.5 SP1 would still have to be supported.  .NET 3.5 SP1 is officially supported until 2023/2028.)

**Comment by objorke** [comment]
We should consider if we can reintroduce support for net40. I think it should be done, if it does not complicate our build.

**Comment by maettu-this** [comment]
Note that former `OxyPlot_NET40.csproj` had unnecessary references to...

- System.Xaml
- WindowsBase
- PresentationCore
- PresentationFramework

Consider removing those references when merging te project from version 1.0.0.
