### ISSUE TITLE
How to print array to oxyplot?

### ISSUE THREAD

**Issue by rasimcekic** [oxyplot/oxyplot#1456]
Hello everyone,

After using Windows Form Application, I switched to WPF for more speed and creative designs. I was using zedGraph for real time graph in Windows Form Application. I was able to print the array that receive every 200 ms directly to the graph/chart without any "for loops".

Question : After passing WPF, I realized that zedgraph's is not a wpf library, but I don't want to do it using "user control". Can I directly print the array in oxyplot graph without loop. 
Note: Since I always take array from the outside, I don't want to waste time entering a loop and pressing the chart.

**Comment by Jonarw** [comment]
The issue section is meant for issues with the code of the oxyplot library itself, not for questions regarding its usage. Thanks for understanding!
