### ISSUE TITLE
Confusion among PlotModel.Background and PlotView.BackColor (WinForms)

### ISSUE THREAD

**Issue by maettu-this** [oxyplot/oxyplot#1463]
### Feature description

I find it confusing that PlotModel.Background is the same as PlotView.BackColor, for two reasons:
- Same thing with two different means (who "wins" if both are given?).
- Same thing with two different terms ("back" -vs- "background").

Either, a clearer terminology can be found (probably not that easy among all UI technologies), or, better description/documentation.

**Comment by VisualMelon** [comment]
#1444 may be relevant

**Comment by objorke** [comment]
When `PlotModel.Background` is set, it should override the current background color of the control (which depends on framework/platform). I think this is easy to implement everywhere. 

Removing `PlotModel.Background` is of course possible, but this requires the background color to be defined when exporting to bmp, svg etc.

**Comment by VisualMelon** [comment]
The behaviour described above is the current behaviour for the `System.Windows.Forms` PlotView.
 - `PlotModel.Background` is used where appropriate
 - `PlotModel.BackColor` is inherited from `Control` and handled completely separately

The way I see it, the current behaviour and API is fine: it's perfectly reasonable to specify a background on the model, and `Background` is fairly consistent with the rest of the library. The default value of `PlotModel.Background` is `Undefined` which is rendered fully transparent.

Perhaps the documentation could be improved, but we probably shouldn't shadow `Control.Backcolor`. The [documentation for `PlotModel.Background`](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/PlotModel/PlotModel.cs#L223-L228) says "If the background color is set to `OxyColors.Undefined`, the default color of the plot view will be used.`, which could probably do with losing the "default", and being clearer on the situation with exporters which no longer provide an alternative `Background` as of #1444.
