### ISSUE TITLE
Add an example showing how to hide an already shown legend

### ISSUE THREAD

**Issue by maettu-this** [oxyplot/oxyplot#1470]
### Improvement description

Extend the LegendExamples with one that first shows but then hides the legend.
Why? It took me a while to find the `IsLegendVisible` property.

**Comment by garydev10** [comment]
@maettu-this May I work on this issue? 
Should I update `LegendHidden` example? Or add a new `Example`?
I would like to add `RectangleAnnotation` that toggles `IsLegendVisible` on mouse click.

**Comment by VisualMelon** [comment]
This is a `LegendHidden` example in `LegendExamples` already; another using a plot-controller to Show/Hide the legend would be OK.
