### ISSUE TITLE
Change order of TargetFrameworks in OxyPlot.Wpf.csproj

### ISSUE THREAD

**Issue by HermanEldering** [oxyplot/oxyplot#1483]
Currently when referencing the OxyPlot.Wpf project directly from a .NET Framework project Visual Studio displays a warning "The project 'OxyPlot.Wpf' cannot be referenced. The referenced project is targeted to a different framework family (.NETCoreApp)".

It is possible to [prevent this warning](https://developercommunity.visualstudio.com/content/problem/710554/build-warning-when-referencing-multitarget-project.html) by changing the order of the target frameworks.

I've tested it and by changing [the line in the project file](https://github.com/objorke/oxyplot/blob/4daca0ae13667c5a97ad5dcec425f33a9ff7fd49/Source/OxyPlot.Wpf/OxyPlot.Wpf.csproj#L3) from

    <TargetFrameworks>netcoreapp3.0;net45;net40</TargetFrameworks>

to

    <TargetFrameworks>net45;net40;netcoreapp3.0</TargetFrameworks>

the warning disappears.

This might apply to more project files but the core project (OxyPlot.csproj) is not affected.

**Comment by VisualMelon** [comment]
Is a similar warning displayed for .NET Core applications if the order is the other way around?

**Comment by HermanEldering** [comment]
I've created a .NET Core console app in my solution and referenced my OxyPlot and OxyPlot.Wpf projects (with the changed order) and it didn't show a warning.
