### ISSUE TITLE
How to use from source instead of nuget wpf.net 4.8

### ISSUE THREAD

**Issue by professordave** [oxyplot/oxyplot#1485]
Sorry for the question.  Not sure where else to post this.

Have a working project using nuget, area series, line series, etc. works great!

There seems to be a bunch of changes post 2.0 release relating to bar charts and enabling many charts to be transposable which I would like to start developing with.

If I compile oxyplot dlls, drag and drop them to my wpf project and then reference them in my project it complains of missing xaml definitions for <plot> line series and other xaml tokens.

Is there a simple how to of how to take the output of a compile of the oxyplot libraries and use them?

It seems actual binary releases of oxyplot are few, one in 2016 and one just happened in 2019.

Thanks in advance!

### Steps to reproduce

1.
2.
3.

Platform:
.NET version:

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Can you also include a screen shot?

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by Jonarw** [comment]
The current unstable version from [MyGet](https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Core) (2.1.0-unstable.1378 at the time of writing) should give you all the latest changes. Refer to [readme.md](https://github.com/oxyplot/oxyplot) for instructions how to use this. Be aware that for some reason  currently an older package version is declared as the 'Latest' version, but you should be able to manually select 2.1.0-unstable.1378.

**Comment by professordave** [comment]
Thanks!

**Comment by princeoffoods** [comment]
Hi, 
MyGet still thinks the November 2019 version it the latest version.
Would be nice if this could be changed to point to the newest build.

Newest in my get: 2.1.0-unstable0006
Actual current version: 2.1.0-unstable.1388
