### ISSUE TITLE
nugget package warning in .net core 3.1 WPF project

### ISSUE THREAD

**Issue by quicoli** [oxyplot/oxyplot#1487]
Hi :)

I'm upgrating my projects to .net core 3.1. One of them uses oxyplot. 
I getting this warning:

![image](https://user-images.githubusercontent.com/8388239/75699679-c229c580-5ca8-11ea-8c11-fb9a250ddb8e.png)

any suggestion?

Thanks for your time and help

**Comment by Jonarw** [comment]
I suggest you upgrade to OxyPlot 2.0.0 stable or 2.1.0 unstable. You can find them on [myget](https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Core).

**Comment by quicoli** [comment]
Thanks! That worked for me :)
