### ISSUE TITLE
'Legends' could not be found in the namespace OxyPlot

### ISSUE THREAD

**Issue by abrasat** [oxyplot/oxyplot#1490]
I am writing a WPF NetCore 3.1 demo application using OxyPlot. I installed the OxyPlot.Core and OxyPlot.Wpf packages from nuget. Unfortunately the PlotModel from these packages does not contain the Legends property. Are the nuget packages not actualized? The WpfExamples from the OxyPlot repository here are using the Legends property.

**Comment by Jonarw** [comment]
> The latest pre-release packages are pushed by AppVeyor CI to myget.org. To install these packages, set the myget.org package source https://www.myget.org/F/oxyplot and remember the "-pre" flag.

(From readme.md)

Hope this helped :). Closing this.

**Comment by abrasat** [comment]
Thanks for your reply. I added the myget.org package source to Visual Studio 2019 and installed the OxyPlot.Core and OxyPlot.Wpf packages with the version "2.1.0-unstable0006" (dated 19.10.2019). I tried with both NetCore 3.0 and NetCore 3.1 WPF application settings, but unfortunately the "Legends" still cannot be found. According the OxyPlot code on github, the legends were added on 24.11.2019, which is newer than the last prelease on myget.org.
Can you please check this?
