### ISSUE TITLE
How can i hide Series on Oxyplot chart

### ISSUE THREAD

**Issue by Vincent95227** [oxyplot/oxyplot#1493]
Hi guys, 

I have a problem with oxyplot.

Actually i have create a WPF page with the chart on the right side and a treeview on the left  side (use a legend).

on This page i have a thread that is used to read the new values to add to the series and this thread check the treeview. When it check those items, if an item is checked so the serie must be visible and is it's unchecked the serie must be hidden.

today I have test to hide a serie : 
-  by changing the color in real time : doesn't work
- to change the linestyle and markertype to none value : doesn't work

Do you have a solution to do this ? 

Thank you in advance;

ps: I'm french, sorry for my bad english, i'm doing my best

**Comment by lobra07** [comment]
use the lineseries  IsVisible=false  proprety

**Comment by Vincent95227** [comment]
> use the lineseries IsVisible=false proprety

I have tried but it doesn't work too 

Code extract :
 series[idxSerie].IsVisible = false;
 plotModel1.InvalidatePlot(true);

**Comment by lobra07** [comment]
first set to is visible to false then try clearing the seriess  points and re update them .. and then invalidateplot .

**Comment by Vincent95227** [comment]
Thank you, i retry the " Isvisible " and it's work, i have made a mistake inside my program.

I have another question, 
in this chart i have mutiple series. some of this series are historic series so they are static, and i have real time series. 
My question is Can I link te Xaxis to follow the advancement of the real-time serie ?

**Comment by lobra07** [comment]
what i understand that your saing you have data that is shorter then the other series and is it posible to show on the same plot or not ?

then answer is yes but it would look like ther is a cut in the graph  .. 
![AC Voltage](https://user-images.githubusercontent.com/57301661/77182156-5c796e00-6add-11ea-8c8e-f454ac8ba56d.png)


as in the graph you can see the green is longer then the yellow and red

**Comment by Vincent95227** [comment]
so,
if we take your chart like an example: 
the red is the real time serie and the green is the historic
the red is shorter than  the green.

i want the maximum value  of the Xaxis is the last incomming value of the red.

When the last incomming data is comming to the red the maximum of the xAxis evolve and discover the green serie

Do you see what i mean ?

**Comment by lobra07** [comment]
you need to put your data in list and evrytime the new data come you will shift the list data and re draw it on the axeis and you have to define 
`            LinearAxis axissx = new LinearAxis { Title=settings_window.x_axes_name, Position = AxisPosition.Bottom, maximum= whateveryouwant, AbsoluteMaximum = whateveryouwant  };
   PlotModel.Axes.Add(axissx);

`

**Comment by Vincent95227** [comment]
@lobra07 thanks a lot for your help, all it's working.
