### ISSUE TITLE
Text visible of LineAnnotation

### ISSUE THREAD

**Issue by goliat26** [oxyplot/oxyplot#1495]
I have little problem with LineAnnotation.

Im need add LineAnnotation with text but this text visibility is dependent on height of this line.
Can i fix height of this line? Now the height is dependent of chart Y axis and when i resize window, the line is resizing too (and text is hiding and showing).
![obraz](https://user-images.githubusercontent.com/43955340/77235799-3aedb480-6bb9-11ea-82e2-1865fdf56ea2.png)
In this screen, line is visible but text is not.
![obraz](https://user-images.githubusercontent.com/43955340/77235808-5658bf80-6bb9-11ea-88f5-5601a08f7a6d.png)
Resize window (height of it) and text is visible.
How can i fix it and make that text will be ever visible?

**Comment by objorke** [comment]
Can you provide code that reproduces the issue?

**Comment by goliat26** [comment]
Of course.
In this example you can see, that when you resize window, text will show up.
[ChartTests.zip](https://github.com/oxyplot/oxyplot/files/4388614/ChartTests.zip)

**Comment by VisualMelon** [comment]
Setting the annotation `TextMargin` to zero will avoid this clipping.

**Comment by goliat26** [comment]
Thanks for reply.
And what with my second question?

Can i fixed line height but dependent on pixels, no on Y axis scale?

**Comment by VisualMelon** [comment]
To do that, you would probably need to write a custom annotation, something like this maybe:

        private class FlagAnnotation : Annotation
        {
            public DataPoint Location { get; set; }
            public double Size { get; set; }
            public ScreenVector[] Geometry { get; set; }
            public OxyColor Fill { get; set; }
            public OxyColor Stroke { get; set; }
            public double StrokeThickness { get; set; }
            public string Text { get; set; }
            public ScreenVector TextOffset { get; set; }
            public HorizontalAlignment HorizontalTextAlignent { get; set; }
            public VerticalAlignment VerticalTextAlignent { get; set; }

            public FlagAnnotation(DataPoint location)
            {
                this.Location = location;
                
                this.Size = 20;
                this.Geometry = new ScreenVector[] { new ScreenVector(0, 0), new ScreenVector(0, -1), new ScreenVector(0.5, -0.8), new ScreenVector(0, -0.6) };
                this.TextOffset = new ScreenVector(-0.1, -1);
                this.HorizontalTextAlignent = HorizontalAlignment.Right;
                this.VerticalTextAlignent = VerticalAlignment.Top;
                this.Fill = OxyColors.Undefined;
                this.Stroke = OxyColors.Black;
                this.StrokeThickness = 2;
                this.Text = null;
            }

            public override void Render(IRenderContext rc)
            {
                rc.SetClip(this.GetClippingRect());
                var offset = this.XAxis.Transform(this.Location.X, this.Location.Y, this.YAxis);
                var actualPoints = new ScreenPoint[Geometry.Length];
                for (int i = 0; i < actualPoints.Length; i++)
                    actualPoints[i] = offset + Geometry[i] * this.Size;
                rc.DrawPolygon(actualPoints, Fill, Stroke, this.StrokeThickness, this.EdgeRenderingMode);
                rc.DrawText(offset + this.TextOffset * this.Size, this.Text, this.TextColor, this.ActualFont, this.ActualFontSize, this.ActualFontWeight, 0, this.HorizontalTextAlignent, this.VerticalTextAlignent, null);
                rc.ResetClip();
            }
        }

This specifies the location in data-space, but the geometry in screen-space.

Usage:

            var flagAnnotation = new FlagAnnotation(new DataPoint(50, 50))
            {
                Text = "A flag",
                TextColor = OxyColors.Blue,
                Stroke = OxyColors.Blue,
                Fill = OxyColors.Yellow,
            };
            plot.Annotations.Add(flagAnnotation);

![image](https://user-images.githubusercontent.com/5646475/81494030-40a07600-929d-11ea-8140-064a9756d8da.png)

**Comment by VisualMelon** [comment]
Closing: `PointAnnotation` will cover most use-cases, and I think we already provide good extensibility for this sort of thing.

**Comment by sohrab4748** [comment]
Thanks, it is so good!
