### ISSUE TITLE
cannot open in VS2017

### ISSUE THREAD

**Issue by smetis** [oxyplot/oxyplot#1497]
Hi,
I try to open the WPF project in VS2017 but failed with error "Project file is incomplete. Expected imports are missing".

I see the target dotnet core version is 3.0 which is not supported by VS2017. Is the latest code still compatible with VS2017 or I have to upgrade to 2019?

**Comment by Jonarw** [comment]
You probably gave the answer yourself - I assume VS2017 does not support netcore3.0 (though I do not know for sure).
What's holding you back from upgrading to VS2019?

**Comment by smetis** [comment]
we are customizing this for internal company use, upgrade to vs2019 means extra cost for all developers to upgrade to new version. We dont need VS2019 features really.

the reason of this question was because i saw the commit log that says the code support VS2017, that got me puzzled if there is something wrong in my 2017 setup, in case someone out there have proven working oxyplot code (latest) running on VS2017.

**Comment by objorke** [comment]
The code should be compatible with VS 2017, but you may need to create new project and solution files.

**Comment by objorke** [comment]
We cannot support old versions of Visual Studio. The minimum requirement should be the latest version of Visual Studio CE.
