### ISSUE TITLE
WinForms: Exception when using toolbox to add Plot control

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#15]
**Imported from [http://oxyplot.codeplex.com/workitem/9952](http://oxyplot.codeplex.com/workitem/9952)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2012-04-03 10:02
Adding a Plot control from the WinForms toolbox should work without throwing exception on the PlotModel.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
