### ISSUE TITLE
Do not allow setting other properties in Wpf.PlotView when the Model property is set

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#150]
**Imported from [http://oxyplot.codeplex.com/workitem/10222](http://oxyplot.codeplex.com/workitem/10222)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-06-16 09:58
When using the Model property, it should not be possible to change properties or the annotation/axis/series collections of the PlotView.

See also #108 

<a href="https://oxyplot.codeplex.com/discussions/548744" rel="nofollow">https://oxyplot.codeplex.com/discussions/548744</a>

**Comment by tibel** [comment]
This was fixed with #239.
