### ISSUE TITLE
Add renderer based on SkiaSharp

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1509]
### Why would this be awesome?

- Performance: 
  - SkiaSharp offers GPU-accelerated rendering on [many platforms](https://github.com/mono/SkiaSharp/wiki/Views-Support-Matrix) (sadly not WPF at the moment, though this may [change](https://github.com/mono/SkiaSharp/issues/745#issuecomment-581581567))
  - Even the CPU-based Skia renderer seems to be faster on WPF than `CanvasRenderContext`

- Portability
  - SkiaSharp itself targets `netstandard1.3`
  - The same `SkiaRenderContext` could be used on all platforms where a SkiaSharp `View` [is available](https://github.com/mono/SkiaSharp/wiki/Views-Support-Matrix)
  - This would make the implementation of OxyPlot controls on new platforms easier, as you wouldn't have to implement the `IRenderContext` for each platform individually
  - All SkiaSharp-based platforms would produce similar rendering output, because they would be based on the same `IRenderContext` implementation

- Export functionality
  - SkiaSharp supports PNG and PDF export (including Unicode) without any further dependencies - so this would be a nice way of getting 'proper' portable PDF export

### Current State
I have a somewhat crude albeit working version of oxyplot with SkiaSharp in this branch: https://github.com/Jonarw/oxyplot/tree/skia

This still needs some more work and testing, but allows for viewing the examples as well as PDF and PNG export.

The central question for me is:
Would be want to have this in the main repository? Or should this be a separate repository like OxyPlot.Avalonia and OxyPlot.SharpDX?

**Comment by VisualMelon** [comment]
> SkiaSharp supports PNG and PDF export (including Unicode) without any further dependencies - so this would be a nice way of getting 'proper' portable PDF export

Has CJK support as well, which is grand (#955).

**Comment by Jonarw** [comment]
I worked some more on the SkiaSharp-based renderer and would say it is now pretty much finished (branch linked above is NOT up to date).

This includes:

- `SkiaRenderContext` 
  - this is fully DPI-aware (similar approach to the WPF `CanvasRenderContext`)
  - is used as basis for all SkiaSharp-based exporters
  - can be used as basis for SkiaSharp-based `PlotView`s (I am working on one for WPF, but this can be treated as a separate issue)
- `PngExporter`
- `JpegExporter`
- `PdfExporter` - with support for Unicode and CJK
- `SvgExporter` - based on `OxyPlot.SvgExporter`, uses SkiaSharp only for text measuring
- `SkiaSvgExporter` - SVG export fully done by SkiaSharp. Works very well for me, despite being declared incomplete

I will make a PR so we can talk about code. Personally I think it would be worth it to have this in the main repository, especially for the PDF export, but if someone (@objorke?) disagrees, I would also be happy to have this in a separate repository.
