### ISSUE TITLE
Title of plot exceeding plotarea

### ISSUE THREAD

**Issue by UndisputedBasement33** [oxyplot/oxyplot#1510]
If the title of the plot is longer than the plot-width the title exceeds the plotarea and covers other content (WPF).
![1](https://user-images.githubusercontent.com/34984201/79636763-575e1c00-817a-11ea-97bc-801c65ec25db.png)

**Comment by Jonarw** [comment]
Can't reproduce this on latest `develop` version.
Which version are you on?
Could you share some code reproducing the issue?

**Comment by UndisputedBasement33** [comment]
Thanks for coming back on this issue. I'm using Oxyplot v2.0.0

Here is sample code that produces this output:
![2](https://user-images.githubusercontent.com/34984201/79680921-575f2a00-8215-11ea-8d09-beebc5be4196.png)
  
ViewModel:
```
using OxyPlot;

namespace WpfApp1 {
    public class ShellViewModel : Caliburn.Micro.PropertyChangedBase, IShell 
    {

        private PlotModel Plot00 { get; set; }
        public PlotModel[] PlotModels { get; set; } = new PlotModel[2];
        public ShellViewModel()
        {
            Plot00 = new PlotModel { Title = "This is a very long sample title, that exceeds the window limits" };
            PlotModels[0] = Plot00;
        }
    }
}
```

View:
```
<Window x:Class="WpfApp1.ShellView"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:oxy="clr-namespace:OxyPlot.Wpf;assembly=OxyPlot.Wpf">

    <Grid Background="White">
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <DockPanel Background="Purple" Grid.Column="0"/>
        <oxy:PlotView  x:Name="Plot00" Model="{Binding PlotModels[0]}" Grid.Row="0" Grid.Column="1" Margin="0,0,2.5,2.5"/>
        <DockPanel Background="Purple" Grid.Column="2"/>
    </Grid>

</Window>
```

@Jonarw What is the behaviour in your case? Is it wrapping or just cutting?

**Comment by Jonarw** [comment]
In my case it was cutting, but this was probably just related to z-order. I can see in the code that no explicit clipping is applied to the title text.
https://github.com/oxyplot/oxyplot/blob/b1778c6afe36338707f7219f97ff5981415717bc/Source/OxyPlot/PlotModel/PlotModel.Rendering.cs#L445

**Comment by UndisputedBasement33** [comment]
Yes you can see in my 2nd example that the z-order has an effect. Because it's not cutting on the left side, but cutting on the right side.

Is there currently a way to wrap the title? I mean I could certainly change the fontsize in order to fit the title or make the title shorter, but in my case the user can increase the window size and this generates more space for the plot and then the current title fits well.

**Comment by UndisputedBasement33** [comment]
Hi,
I added the title clipping to the source code. I went through the contribution guideline, created a new branch, comit the code, added examples etc. But it looks like I'm not allowed to push my branch. Could you tell me what I'm doing wrong? Thank you

**Comment by Jonarw** [comment]
Thanks for taking the time and fixing this!

First you would have to create your own fork (click the 'Fork' button on the top right of the GitHub page).
Then you can push your branch to your own fork and create a Pull Request (GitHub will automatically suggest this to you after pushing your branch).
