### ISSUE TITLE
Label Control for Contour Series not working

### ISSUE THREAD

**Issue by UndisputedBasement33** [oxyplot/oxyplot#1511]
If I create a contour series like described in the Oxyplot documentation and I want to manipulate the labels with LabelSpacing and LabelSteps there is no effect.

Sample code (using Oxyplot v2.0.0 in WPF):
```
var cs = new ContourSeries
{
        Color = OxyColors.Black,
        LabelBackground = OxyColors.White,
        ColumnCoordinates = yy,
        RowCoordinates = xx,
        LabelSpacing = 10,
        LabelStep = 2,
        Data = peaksData
};
```

My target was to show the label only on every 2nd contour, and I wanted to move the label a bit, so that when you use transparent background for the label, that it doesn't get strikethrough by the contour. But LabelSpacing and LabelSteps seem to not have any effect.

**Comment by Jonarw** [comment]
This would be why:
https://github.com/oxyplot/oxyplot/blob/b1778c6afe36338707f7219f97ff5981415717bc/Source/OxyPlot/Series/ContourSeries.cs#L398
