### ISSUE TITLE
Add WPF PlotView based on SkiaSharp

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1515]
I already started working on this and have a basic working implementation. Stuff I still need to figure out (suggestions are welcome):

- Find a way to share code between `OxyPlot.WPF` and `OxyPlot.SkiaSharp.WPF`
  - Stuff like Tracker etc. would be duplicated otherwise
  - Introduce `OxyPlot.WPF.Shared` project?
- Find a way to have an example browser for `OxyPlot.SkiaSharp.WPF`
  - Integrate into WPF `ExampleBrowser` and offer a way to switch between Canvas and SkiaSharp renderer?
  - This would have the nice side effect to have a direct visual comparison between both renderers

**Comment by CodingBlob** [comment]
Can this new renderer be the default? I tried the SkiaSharp renderer today with a custom plot view implementation and the performance is very good.
