### ISSUE TITLE
Keeping LineSeries colors after invalidating plot

### ISSUE THREAD

**Issue by abrasat** [oxyplot/oxyplot#1517]
Is there any setting that configures the PlotModel to assign the same colors to the line series after calling InvalidatePlot() to refresh plot?
I have for each LineSeries in ModelPlot a checkbox that allows to set at runtime the IsVisible property for the corresponding LineSeries object. After setting the property the InvalidatePlot() method is called to refresh the plot. The problem is that the LineSeries get after the refresh new colors, it seems that the colors are "recycled" randomly. Would be possible to keep the same colors after refreshing the plot?

**Comment by Jonarw** [comment]
Did you try setting the color explicitly via the `LineSeries.Color`?

**Comment by abrasat** [comment]
No. But then I would need some algorithm to automatically generate unique colors.

**Comment by Jonarw** [comment]
OxyPlot uses a Default Palette of colors that are used in order when you don't specify the Color on your Series:
https://github.com/oxyplot/oxyplot/blob/4a4d2643a0238ea587ebfd8f91b4eec77825606b/Source/OxyPlot/PlotModel/PlotModel.cs#L126

**Comment by abrasat** [comment]
Thanks for the link. What happens if there the PlotModel has more than 11 (number of colors in the default colors list) line series, do the default colors repeat?

**Comment by VisualMelon** [comment]
When it 'runs out' of colors, the colors will cycle through the `DefaultColors` again, but will also cycle through the dash styles (the relevant code is in [PlotModel.cs](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/PlotModel/PlotModel.cs#L639-L655
)). This behaviour can be seen in the various Legend Examples in the Example Library, e.g. [Greyscale colors](https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Examples/LegendExamples.cs#L183-L197):

![image](https://user-images.githubusercontent.com/5646475/80458925-80746e80-8929-11ea-8609-2e06e5a2b234.png)

**Comment by abrasat** [comment]
Yes, I see now the combination between LineSeries.Color and LineSeries.LineStyle. Thanks.
