### ISSUE TITLE
Remove unneeded exporters

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1518]
With the new SkiaSharp-based Exporters available, we may want to rethink which of the other Exporters we really need to keep in the main repository.
I have tried to create an overview here to help us with the decision.

### PDF

| Exporter | Unicode-Support | Targets |
| --- | --- | --- |
| `OxyPlot.PdfExporter` | X | `netstandard1.0;net45;net40` |
| `OxyPlot.Pdf.PdfExporter` | O | `net452` |
| `OxyPlot.SkiaSharp.PdfExporter` | ✓ | `netstandard1.3;net45` |

I think the `OxyPlot.Pdf.PdfExporter` would be an obvious candidate to be removed. The PdfSharp project seems to be inactive, there is not even support for netstandard.

`OxyPlot.PdfExporter` might be worth keeping, because it is the only option for people on .NET 4.0. On the other hand, we might consider moving this to a separate package in an external repository like `oxyplot-legacyexporters`? If someone were to go ahead and fix Unicode-Support, we could take this back in.

### PNG
Exporter | DPI-Aware | Targets |
| --- | --- | --- |
`OxyPlot.Wpf.PngExporter` | ✓ | `net45;net40;netcoreapp3.1`
`OxyPlot.WindowsForms.PngExporter` | X | `net45;net40;netcoreapp3.1`
`OxyPlot.ImageSharp.PngExporter` | X | `netstandard2.0`*
`OxyPlot.Core.Drawing.PngExporter` | X | `netstandard2.0`
`OxyPlot.SkiaSharp.PngExporter` | ✓ | `netstandard1.3;net45`

*could easily be changed to `netstandard1.3` I think

I think we should keep the View-specific exporters for WPF and WindowsForms, because they allow PNG-Export for Windows Desktop applications without any additional dependency. Also they are the only option for people on .NET 4.0.

`OxyPlot.Core.Drawing.PngExporter` is kind of obsolete as far as I can tell. The SkiaSharp or ImageSharp exporters should be full replacements for this I guess.

Regarding ImageSharp: Compared to SkiaSharp it has the advantages that it is a fully-managed implementation and has a smaller deploy size. According to my quick check, this should easily be adapted to target netstandard1.3, so I think this might also be worth keeping.

### SVG
Exporter | Issues | Targets 
| --- | --- | --- |
`OxyPlot.SvgExporter` | only limited text measuring | `netstandard1.0;net45;net40`
`OxyPlot.Wpf.SvgExporter` | text alignment issues | `net45;net40;netcoreapp3.1`
`OxyPlot.WindowsForms.SvgExporter` | text alignment issues | `net45;net40;netcoreapp3.1`
`OxyPlot.SkiaSharp.SvgExporter` | text alignment issues | `netstandard1.3;net45`
`OxyPlot.SkiaSharp.SkiaSvgExporter` | - | `netstandard1.3;net45`

All the SVG exporters based on `OxyPlot.SvgExporter` share the same problem with wonky vertical text alignment. However compared to SkiaSharp they have the clear advantage of requiring no additional dependency. Also they are the only option for people on .NET 4.0. I don't really have a strong opinion on these.

The `OxyPlot.SkiaSharp.SkiaSvgExporter` seems to work really well as far as I saw until now. 

Suggestions and other inputs are welcome! Did I miss something?

**Comment by VisualMelon** [comment]
I'd want to keep `OxyPlot.Pdf` in the main package, but that's just because I'm lazy and I've had to update twenty odd package if it moved ;) So long as it stays (being it lightweight an managed only)

Would it be possible for `OxyPlot.Core.Drawing.PngExporter` to share its `GraphicsRenderContext` with `OxyPlot.WindowsForms`? (If I have a bit of time I'll give it a try). Otherwise, the exporters require little maintenance owing to heavy code reuse with other essential components.

What is the different with text alignment in SkiaSvg vs the others? Is it obvious from a couple of examples? I through together a workaround for them a while back (which was in part due to inconsistent rendered behaviour), but if it is able to pull off something better, I'd be happy to take a look into patching up the existing ones.

**Comment by objorke** [comment]
I suggest to remove the obsolete code after next major release (v4?). Could it just be marked `[Obsolete]` and included in the library for one more release? 

Can we also remove the 3 pdf issues in the next milestones (v3) now?

It´s great to hear that the text alignment is working in the skia svg exporter! I had to look at the code to see the difference between the two SVG exporters. Could the `SvgExporter` be removed and the `SkiaSvgExporter` be renamed to simply `SvgExporter`? It would be great to get rid of the `TextMeasurer` property completely :-)

**Comment by VisualMelon** [comment]
Having reviewed it, it would be possible to share code between `System.Core.Drawing` and `System.Windows.Forms`, but needs some preprocessor conditionals if it's going to be a full solution.

Owing to the lack of shared code, `System.Core.Drawing` has fallen behind `System.Windows.Forms` significantly, and it lacks tests. If no decision is taken to remove it, I'll be happy to update it (pretty much a C&P job).

**Comment by Jonarw** [comment]
> What is the different with text alignment in SkiaSvg vs the others? Is it obvious from a couple of examples?

It is obvious from the output of the `OxyPlot.SkiaSharp.Tests`.
Output with `OxyPlot.SkiaSharp.SvgExporter`:
![image](https://user-images.githubusercontent.com/18097859/80494689-3e6a1d80-8967-11ea-9f94-b2d494da29d4.png)

Output with `OxyPlot.SkiaSharp.SkiaSvgExporter`:
![image](https://user-images.githubusercontent.com/18097859/80494747-4fb32a00-8967-11ea-90fd-f1d20ad51abc.png)

> I suggest to remove the obsolete code after next major release (v4?). Could it just be marked [Obsolete] and included in the library for one more release?

Sounds reasonable to me!

> Can we also remove the 3 pdf issues in the next milestones (v3) now?

Yes I would say we can close these issues, the SkiaSharp-based exporter should cover those use-cases.

> Could the `SvgExporter` be removed and the `SkiaSvgExporter` be renamed to simply `SvgExporter`?

Yes, this would be a good idea I think. Initially I was not sure how good the result with the `SkiaSvgExporter` would be so I thought I'd include both. But seeing that the `SkiaSvgExporter` actually works really well, this might be more confusing than anything else.

> Having reviewed it, it would be possible to share code between System.Core.Drawing and System.Windows.Forms, but needs some preprocessor conditionals if it's going to be a full solution.

I think a few conditionals would be better than having the whole thing duplicated as we have it now.
On the other hand, do we really need `OxyPlot.Core.Drawing`? Does it have an advantage compared to `OxyPlot.ImageSharp`?

**Comment by VisualMelon** [comment]
> Does it have an advantage compared to OxyPlot.ImageSharp?

The only advantage I can think of would be compatibility with the `WindowsForms` renderer. They may have very different font support, and this might be a concern for someone porting e.g. an ASP.NET application to run on linux.

I'll have another go at merging the code-bases, and we don't think it is too abhorrent we can consider keeping it, otherwise I'd suggest updating it to match winforms for 2.0 support before maybe removing in 3.0.

**Comment by Jonarw** [comment]
So to sum it up (we can track these points in separate issues):

- `OxyPlot.Pdf.PdfExporter`: Mark obsolete for v3, remove in v4
- `OxyPlot.PdfExporter`: I'm still not sure what to make of this one. I kind of fear that people being unaware of other options might use this Exporter because of its high visibility as part of the main package and might be disappointed in the output. We could keep it as is, but mark it as obsolete indefinitely with the suggestion to consider using the SkiaSharp-based PDF exporter? Or move it to a separate package? Or none of those?
- `OxyPlot.Core.Drawing.PngExporter`: Merge with `WindowsForms` renderer, if unsuccessful mark obsolute for v3, remove in v4
- `OxyPlot.ImageSharp.PngExporter`: Change to target `netstandard1.3`
- `OxyPlot.SvgExporter` (and derived ones): Improve vertical text alignment, maybe compare with how SkiaSharp does it?
- `OxyPlot.SkiaSharp.SvgExporter`: remove and replace by `OxyPlot.SkiaSharp.SkiaSvgExporter`

Any disagreements? What should we do with `OxyPlot.PdfExporter`?

**Comment by VisualMelon** [comment]
Perhaps I'm just irationally attached to it, but I'd vote to keep `OxyPlot.PdfExporter`: it's lightweight, low maintenance, and managed only. I see what you mean about visibility: adding some documentation to explain that it's deficient for Unicode would be a good idea.

**Comment by objorke** [comment]
For `OxyPlot.Pdf.PdfExporter` I suggest to mark it obsolete, and stop publishing the OxyPlot.Pdf package after v3.

For `OxyPlot.PdfExporter` I suggest to mark it obsolete and remove it in v4 (move the code to a legacy repository which is not published in a package).

Agree with the plans for the png and svg exporters!

**Comment by Jonarw** [comment]
I have create some external issues to track the proposed actions, so I think we can close this one.
