### ISSUE TITLE
Plot in WPF window does not show up when called from different WPF window.

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#152]
**Imported from [http://oxyplot.codeplex.com/workitem/10224](http://oxyplot.codeplex.com/workitem/10224)**

**[akmm94](http://www.codeplex.com/site/users/view/akmm94)** 2014-06-20 04:42
Hi All, 

When I am calling a new window to show up Oxy plot it just does not show up at all. If I open the window by itself it shows the plot. But if I call from another window it just does not show up. What can be the reason? Any help would be appreciated.

I am using VS 2012 and latest Oxy Plot.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
