### ISSUE TITLE
XYAxisSeries.EnsureAxes is not called for all series

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#153]
**Imported from [http://oxyplot.codeplex.com/workitem/10226](http://oxyplot.codeplex.com/workitem/10226)**

**[henrikp](http://www.codeplex.com/site/users/view/henrikp)** 2014-07-02 07:55
XYAxisSeries.EnsureAxes is not called for all series. Therefore one gets an exception in XYAxisSeris.VerifyAxes which is called when the series is rendered. For us that happens when the user selects to view a group of plots which have already been rendered
 once. 

The problem seems connected to the fact that PlotModel.InvalidatePlot() will do nothing if the PlotView is null.

Our workaround is to always call 

((IPlotModel)PlotModel).Update(false); 

before 

PlotModel.InvalidatePlot(true); 

but this seems unnatural.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-07-02 12:42
I agree, this should not be the responsibility of the client application.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
