### ISSUE TITLE
Change OxyPlot.ImageSharp to target netstandard1.3

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1530]
See discussion in #1518.
ImageSharp itself targets netstandard1.3, so it should be possible.

Optional:

- Implement `DrawImage(...)`
- DPI-Awareness

**Comment by VisualMelon** [comment]
While we are at it, should we rename the `PngRenderContext` to `ImageRenderContext`, and add overloads for the various formats supported by ImageSharp? (e.g. png, jpg, gif). Additional exporters could be added for the corresponding formats, or we could find some other way of specifying the format (e.g. an enum, filename expection).

**Comment by Jonarw** [comment]
Propably separate exporters for each export formats would be preferable, as there might be some additional settings relevant for each format (e.g. compression factor for JPEG).
