### ISSUE TITLE
IsTransposed property in example browser is too generous

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1544]
# Steps to reproduce

1. Open your example browser of choice with 'transpose' support OR look at the example library texts for any of the exporters
2. Look at any of the rendering examples (i.e. things without axes)
3. Set the 'Transpose' checkbox

Platform: Any
.NET version: Any

### Expected behaviour

Plots without axes should not be transposable: the `IsTransposable` property should detect and reject these cases, and consequently the `Transpose` checkbox should be disabled.

![image](https://user-images.githubusercontent.com/5646475/81263356-6e848100-9037-11ea-840d-2d4537e297f1.png)

### Actual behaviour

We are allowed to transpose the plot, and it just complains about a lack of axes.

![image](https://user-images.githubusercontent.com/5646475/81263065-e56d4a00-9036-11ea-9df3-6dad0e1e80fe.png)

# Resolution

What should be the considered transposable? Is it sufficient to change the condition to always require axes, given that without axes you can't transpose any axes?

            return (model.Axes.Count > 0 || model.Series.Count > 0 || model.Annotations.Count > 0)
                && model.Axes.All(a => a.Position != AxisPosition.None)
                && model.Series.All(s =>
                   {
                       var type = s.GetType();
                       return s is XYAxisSeries
                              && type.GetTypeInfo().Assembly == typeof(PlotModel).GetTypeInfo().Assembly
                              && !NonTransposableSeriesTypes.Contains(type);
                   });

To

            return (model.Axes.Count > 0 && (model.Series.Count > 0 || model.Annotations.Count > 0))
                && /* snip */

PR to follow if nothing jumps out at me.

**Comment by Jonarw** [comment]
If I remember right the issue here were automatically-generated axes:
It is possible for a plot to have `model.Axes.Count == 0`, but still being sensibly transposable, because default x and y axes will be generated.

But you are right, this method could be improved.

**Comment by VisualMelon** [comment]
Good point.

Given #992, I'll make a new issue for adding axes where necessary to all the examples, then hopefully this will be a self-solving problem.

**Comment by VisualMelon** [comment]
Having another play with this, simply removing the check for annotations should suffice: no axes are generated if there are no series, but it doesn't care about annotations. The data-space annotation examples (those that are transpoable) all specify axes or series because they have to in order to show something.

    return (model.Axes.Count > 0 || model.Series.Count > 0)
        && /*snip*/

Given #992 might not go through, we perhaps don't want #1547, and hopefully this a sufficient solution for the time being.
