### ISSUE TITLE
Unify support for non-CRLF (i.e. just LF) line endings

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1545]
### Feature description

Presently line splitting is done by splitting on `\r\n`, either with [regex](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Svg/SvgRenderContext.cs#L162), [string.Split](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Rendering/RenderContext/RenderingExtensions.cs#L565), or is left to some other library (e.g. in the case of WPF and WinForms/GDI+).

The later two examples support `\n` line endies out-of-the-box, so I suggest replacing all other instances of splitting strings with the following regex based method:

    var lines = Regex.Split(text, "\r?\n");

This should probably be stuffed into an method somewhere to foster consistency.

**Comment by Jonarw** [comment]
This is normally used by `IRenderContext` implementations, right? Or are there other uses?

So maybe a static method `RenderContextBase.SplitLines(string text)` would be a good place for this?

**Comment by VisualMelon** [comment]
Just `RenderContexts`.

My concern with `RenderContextBase` is that the Skia render will need it (correct me if I'm wrong), and if it's a member of `RenderContextBase` then it would need to be public which would feel weird (maybe that's just me).

Would it be silly to just add it to `StringHelper` as an extension method?

**Comment by VisualMelon** [comment]
Managed to miss `PortableDocumentFont` as a dependant. I don't think it should be public in `RenderContextBase`, so I'll put it in `StringHelper` for the moment.
