### ISSUE TITLE
Plotarea is calculated wrong in HeatMap

### ISSUE THREAD

**Issue by UndisputedBasement33** [oxyplot/oxyplot#1574]
I'm using the latest commit (699e9ddb) of Oxyplot from Github. There is an undesired behavior with the heatmap series, which can be explained with the examples.
This is the 2x3 interpolated example:
![with color axis](https://user-images.githubusercontent.com/34984201/82644038-f7431580-9c10-11ea-839f-7ef84b15df4b.png)

If I change it now to not display the ColorAxis it looks like this:
![no color axis](https://user-images.githubusercontent.com/34984201/82644131-1a6dc500-9c11-11ea-8cbb-b6c7ab4b4bf5.png)

It still leaves the space on the right side for the ColorAxis and additionally it creates an extra margin between the title and the chart. It also looks like there is more margin on the left side.

**Comment by VisualMelon** [comment]
I can't reproduce this; how exactly did you hide the axis? Removing it completely causes exceptions, and setting `IsAxisVisible=false` behaves as I would expect:

![image](https://user-images.githubusercontent.com/5646475/82645460-cf50b380-9c0a-11ea-8df0-33fbf5ce66c1.png)

**Comment by UndisputedBasement33** [comment]
I just changed this line:
`model.Axes.Add(new LinearColorAxis { Position = AxisPosition.Right, Palette = OxyPalettes.Jet(500), HighColor = OxyColors.Gray, LowColor = OxyColors.Black });`
to this:
`model.Axes.Add(new LinearColorAxis { Palette = OxyPalettes.Jet(500), HighColor = OxyColors.Gray, LowColor = OxyColors.Black });`

**Comment by VisualMelon** [comment]
Thanks, reproduced it now.

**Comment by UndisputedBasement33** [comment]
Like you wrote. If I add `IsAxisVisible=false` it behaves as desired.

**Comment by VisualMelon** [comment]
`LinearColorAxis` seems to be one of a few axes that is designed to work with `AxisPosition.None`, but the behaviour that is appropriate for e.g. `AngleAxis` is not appropriate for it. It's not immediately obvious to me how this should be resolved.

**Comment by Jonarw** [comment]
Two ideas, not completely happy with either:
- Add `AxisPosition.All`, which would apply for polar axes
- Make `IsAxisVisible` return false when `AxisPosition==AxisPosition.None`

**Comment by VisualMelon** [comment]
To add another:

 - The color axis could override the `Measure` and return zero for everything when it is set to `None`

I've not been able to convince myself of any of these solutions, but I don't think making `IsAxisVisible` non-passive is a good idea.

**Comment by VisualMelon** [comment]
@Jonarw any others thoughts on this? I'll put together a PR will my suggestion soon unless someone can talk me around, because it's the 'lowest friction' change.

**Comment by Jonarw** [comment]
Yes, I agree that your proposal is probably the 'cleanest' one.
