### ISSUE TITLE
Full Plotarea Magnitude Axis with negative minimum rendering is dodgy

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1586]
When a `MagnitudeAxisFullPlotArea` has a negative minimum, the magnitude grid lines escape the plot area. The more of the axis is 'below zero', the more noticeable the aberrations.

![image](https://user-images.githubusercontent.com/5646475/83360959-1104fb00-a37d-11ea-9a5c-496391fbb239.png)

Note that by default the magnitude axis has a non-zero `MinimumPadding`, which means that most examples have a negative minimum, but it is not large enough relative to the maximum to be noticeable if it is occurring.

This is similar to #1364.

Obviously this behaviour is not ideal, but does it make sense to allow the minimum to go negative? #44 is somewhat bare, but I wonder if this needs discussion.

**Comment by Jonarw** [comment]
> Obviously this behaviour is not ideal, but does it make sense to allow the minimum to go negative?

Absolutely! Take a look at the 'Directivity Pattern' on this website for example:
https://www.visaton.de/en/products/bass-midranges/al-130-8-ohm

I wonder if we could significantly simplify the `MagnitudeAxisFullPlotAreaRenderer` by relying on clipping. We could just draw full circles for every tick and clip them by the axis bounds.

**Comment by VisualMelon** [comment]
@Jonarw thanks for the reference.

I suspect the fix for this should be fairly simple (probably just some mug like me not realising the minimum can go negative or something), but if it becomes any more painful I wouldn't complain about leaning on clipping. Clipping would certainly make life easier and tidier if we were to combine the two magnitude axes as per #1401.
