### ISSUE TITLE
Remove support for IRenderContext implementations without native clipping?

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1593]
Since #1565, all 'official' `IRenderContext` implementations support native clipping (if I didn't miss any). We could think about removing the support for `IRenderContext` implementations without native clipping. 

This would implicate the following changes:

- Change return type of `bool IRenderContext.SetClip(...)` to `void` (or maybe even go one step further and do something like `PushClip(...)` and `PopClip()`)
- Remove the corresponding code paths in `RenderingExtensions`
- Possibly `CohenSutherlandClipping` and `SutherlandHodgmanClipping` could be completely removed?

This would have some advantages:

- We could remove some fairly complex code which is currently unused
- The rendering of some plot elements could be significantly simplified if there was a `IRenderContext.SetClip()` which is guaranteed to succeed (e.g. in the `MagnitudeAxisFullPlotArea`)
- This would open up some opportunities for future enhancements regarding clipping. It would be nice for example (in terms of performance and file size of SVG and PDF files) if clipping was not set and reset for every single series that is rendered, but only once for every group of series with the same axes.

There are two disadvantages I can think of:

- The barrier of entry is slightly higher for new `IRenderContext` implementations
- This would be a breaking change of `IRenderContext.SetClip(...)`

What are your thoughts? Is it worth it?

**Comment by VisualMelon** [comment]
My understanding is that only the 'built in' PDF renderer _doesn't_ support clipping, and that is being retired? Nothing except the `*Clipped` methods seem to look at the return value of `SetClip`, so for our stuff there shouldn't be any trouble patching it up.

Adding a push/pop stack could be a real boon (though I can't immediately think where we would use it), and it would be doable without modifying any of the existing renderers (though we want this behaviour to be overridable). If you wanted to put a draft PR together, I'd be happy to take a look.

**Comment by Jonarw** [comment]
> My understanding is that only the 'built in' PDF renderer doesn't support clipping, and that is being retired?

You are correct actually, while the `OxyPlot.PdfRenderContext` pretends to support `SetClip(...)` and `ResetClip()`, it actually does a no-op. But this shouldn't concern us too much here.

I actually have been working on this over the last couple of days and will probably put together a PR soon.
