### ISSUE TITLE
Legend does not display with multiple plots in tab

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#160]
**Imported from [http://oxyplot.codeplex.com/workitem/10234](http://oxyplot.codeplex.com/workitem/10234)**

**[Sheex](http://www.codeplex.com/site/users/view/Sheex)** 2014-07-21 20:40
I have a setup generating a series of plots in a Winforms TabControl (3 per page, 4 tabs for a total of 12 plots). When only one plot is present in the tab, the legend displays fine in that plot; once multiple plots are present, however, the legend vanishes
 in each. This occurs even when PlotModel.IsLegendVisible is explicitly set to true.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
