### ISSUE TITLE
.NET 4.0 support - how to deal with lack of read-only collection interfaces?

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1600]
As it became apparent in #1572, we may want to develop some kind of strategy how we deal with the support for .NET 4.0. As this was re-added only recently in #1452, we'll probably want to support this for a while (at least until the next major release I guess).

The specific problem that came up in the above PR was the lack of read-only collection interfaces in .NET 4.0 (specifically `IReadOnlyList<T>` and `IReadOnlyCollection<T>`).
There already are [some](https://github.com/oxyplot/oxyplot/blob/113cee0696bd37d4b6be207536d069992de67d72/Source/OxyPlot/Axes/Axis.cs#L718) [instances](https://github.com/oxyplot/oxyplot/blob/113cee0696bd37d4b6be207536d069992de67d72/Source/OxyPlot/Rendering/RenderContext/IRenderContext.cs#L58) where we use `IList<T>` where `IReadOnlyList<T>` would arguably be a better choice. In #1572 however this workaround is not possible due to the lack of covariance when using `IList<T>`.

There are several possibilities of dealing with this:

### 1. Add separate members for Count and Indexer to interfaces, like I've done in this [draft](https://github.com/oxyplot/oxyplot/pull/1572/files/3a08870f13ca39b4482a089e3aafed61196d773b#diff-191cb1ecc2002af11ce735d27a8195c8).

    public interface IExample<T>
    {
        IEnumerable<T> Items { get; }
        int ItemsCount { get; }
        T this[int index];
    }

Pro: 
- Very simple
- Works without restriction on all frameworks

Con:
- Clunky interface
- Breaking change for implementation whenever we drop .NET 4.0 support
- Breaking change for consumers whenever we drop .NET 4.0 support

### 2. Add a wrapper class for `IList<T>` that can be used like IReadOnlyList<T>, as proposed by VisualMelon in this [gist](https://gist.github.com/VisualMelon/d8baadc9f28f8d5f1bf60bf9eaf8c318).

    public interface IExample<T>
    {
        ReadOnlyList<T> Items { get; }
    }

Pro: 
- Works without restriction on all frameworks

Con:
- Breaking change for consumers whenever we drop .NET 4.0 support

### 3. a) Reference this [package](https://github.com/mausch/ReadOnlyCollections)
_(unfortunately the assemblies of this package are not signed, so we can't use it)_
### 3. b) Define `IReadOnlyList<T>` and `IReadOnlyCollection<T>` ourselves

    public interface IExample<T>
    {
        IReadOnlyList<T> Items { get; }
    }

This would be conditionally compiled for .NET 4.0 and would 'live' in `System.Collections.Generic`, like [this](https://github.com/mausch/ReadOnlyCollections/blob/master/ReadOnlyCollectionsInterfaces/Interfaces.cs).
We would also have to add a conditionally-compiled wrapper class on .NET 4.0.

Pro:
- We could use `IReadOnlyList<T>` and `IReadOnlyCollection<T>` exactly as we are used to
- No breaking changes whenever we drop .NET 4.0 support

Con:
- Potential confusion
- .NET 4.0 users who already use the same workaround may run into ambiguity issues

**Comment by Jonarw** [comment]
Option 1) is obviously the least preferred from my side.

Option 2) and 3) would both be viable. 
Personally I am slightly leaning towards 3), just because I think it is preferable to cause minor problems to .NET 4.0 users (who will be a minority anyway) rather than to everyone else.

**Comment by VisualMelon** [comment]
I think I agree 3 would be better. The only advantage of 2 would be the reduced effort in implementation at our end: for 3 we will need to refit every assignment, which could be a static `AsReadOnly` method or conditional compilation blocks. The former would probably be preferable as it will be easier to document that it is a kludge and people won't be afraid to remove it in the future. Something like

    public static IReadOnlyList<T> AsReadOnlyList(this IList<T> list)
    {
    #if NET40
        return ReadOnlyList<T>(list);
    #else
        return list;
    #endif
    }

One other consideration, is that the `IList<T>` usage under 4.0 won't be specific to OxyPlot, so there may be consumers who have their own APIs which expect an `IList<T>`. It may be worth considering exposing `IList<T>` to 4.0 consumer, but we probably need to decide which APIs we would be refitting to work out whether that would just be asking for trouble. The trouble would be limited to 4.0, and it would mean that existing 4.0 applications would not experience code breaking changes, but would mean the 4.0 API isn't as tight as it could be.

**Comment by Jonarw** [comment]
>  for 3 we will need to refit every assignment, which could be a static `AsReadOnly` method or conditional compilation blocks. 

Yes, I would have added an extension very similar to the one proposed by you to deal with this. When we remove .NET 4.0 support, we can just delete the extension and remove it in all places where errors pop up.

> One other consideration, is that the `IList<T>` usage under 4.0 won't be specific to OxyPlot, so there may be consumers who have their own APIs which expect an `IList<T>`

Good point. How about we also implement `IList<T>` on our wrapper class, so .NET 4.0 users can cast the `IReadOnlyList<T>` to `IList<T>` if they need to do so.

I will put together a proposal later, so we can see how ugly this gets.
