### ISSUE TITLE
OxyPlot SkiaSharp Nuget Errors

### ISSUE THREAD

**Issue by sushi19921992** [oxyplot/oxyplot#1603]
Hi guys,

Trying to restore nuget packages for oxyplot doesn't seem to work with the new oxyplot skiasharp pre-release.

`Unable to find version '2.1.0-unstable.1419' of package 'OxyPlot.Core'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'OxyPlot.Core.2.1.0-unstable.1419' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Package 'OxyPlot.Core.2.1.0-unstable.1419' is not found on source 'https://api.nuget.org/v3/index.json'.
    Unable to find version '2.1.0-unstable.1419' of package 'OxyPlot.SkiaSharp'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'OxyPlot.SkiaSharp.2.1.0-unstable.1419' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Package 'OxyPlot.SkiaSharp.2.1.0-unstable.1419' is not found on source 'https://api.nuget.org/v3/index.json'.
    Unable to find version '2.1.0-unstable.1419' of package 'OxyPlot.SkiaSharp.Wpf'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'OxyPlot.SkiaSharp.Wpf.2.1.0-unstable.1419' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Package 'OxyPlot.SkiaSharp.Wpf.2.1.0-unstable.1419' is not found on source 'https://api.nuget.org/v3/index.json'.
    Unable to find version '2.1.0-unstable.1419' of package 'OxyPlot.Wpf.Shared'.
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'OxyPlot.Wpf.Shared.2.1.0-unstable.1419' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
      https://api.nuget.org/v3/index.json: Package 'OxyPlot.Wpf.Shared.2.1.0-unstable.1419' is not found on source 'https://api.nuget.org/v3/index.json'.`

Not sure how to fix this?

**Comment by VisualMelon** [comment]
I can't see the pre-release feed in there: can you check/paste your `nuget.config`, the package reference, and (if you are using VS) the configured package sources?

The AppVeyor CI builds can be accessed from https://www.myget.org/F/oxyplot/api/v3/index.json (you need to specify the version exactly, because the naming went weird at some point so by default it pulls down a rather old build).

**Comment by sushi19921992** [comment]
Yeah I think it's the fact that pre release wasn't checked for nuget. I was gonna say, apparently we have to use official releases from OxyPlot and not pre-releases. Do we have any idea when we'll get a "stable" release version of OxyPlot.SkaiSharp.Wpf

**Comment by VisualMelon** [comment]
I'm afraid I couldn't say when the next release would be.

**Comment by VisualMelon** [comment]
Can this be closed, or are there other observed difficulties using the pre-releases?

**Comment by sushi1992** [comment]
No you can close it :) the problems are nuget related with it failing to restore prerelease packages and that's not your problem but probably nugets problem.
