### ISSUE TITLE
myget.org feed points to wrong version

### ISSUE THREAD

**Issue by princeoffoods** [oxyplot/oxyplot#1606]
### Steps to reproduce
Try to update from oxyplot myget feed in Visual Studio 

### Expected behaviour
Update to newest version (currently v2.1.0-unstable.1422)

### Actual behaviour
Update to old version is suggested (v2.1.0-unstable006)
![oxyplot](https://user-images.githubusercontent.com/2674926/84507649-759b5080-acc1-11ea-8d09-09300788193a.jpg)

**Comment by VisualMelon** [comment]
As best I can tell, this is due to the naming changing at some point. I agree it's weird, but in a way, it's good that people are forced to pick a specific pre-release version, because there will be breaking changes.

**Comment by Jonarw** [comment]
I agree is is fairly unintuitive. Most people probably want one of the following:
- A stable API -> they use v2.0
- The latest features -> they use the latest preview

So it does not really make sense for anyone to use v2.1.0-unstable0006 at the moment, though that is the most-downloaded v2.1.0 version on myget. So I think it would be good to fix this, e.g. by un-listing the first couple of v2.1.0-unstable versions.

This would need to be done by someone with access to the myget account. @objorke would you have time to take a look at this?

**Comment by VisualMelon** [comment]
> by un-listing the first couple of v2.1.0-unstable versions.

Good idea

**Comment by rstm-sf** [comment]
Yes, it was good to remove them
![image](https://user-images.githubusercontent.com/2669927/94897190-8eb25200-04a8-11eb-85d8-25551daff6ae.png)

**Comment by VisualMelon** [comment]
Pinging @objorke again

**Comment by objorke** [comment]
Sorry, I didn't notice this issue. I have unlisted all the 2.1.0-unstable000X packages now, I think. Let me know if some are still listed. @VisualMelon and @Jonarw, can I give you access to the myget feed? I think I need your myget usernames to assign privileges. https://www.myget.org/feed/Security/oxyplot

**Comment by objorke** [comment]
See also #1681, I think it would be easier if everything is on github.

**Comment by objorke** [comment]
See also the overview on https://github.com/oxyplot/oxyplot/wiki/NuGet-package-versions
I just added the SkiaSharp and ImageSharp packages

**Comment by VisualMelon** [comment]
Thanks @objorke they all seem to be gone (closing).
