### ISSUE TITLE
Heatmap does not work properly with DateTimeAxis

### ISSUE THREAD

**Issue by mennowo** [oxyplot/oxyplot#1611]
Hello,

in order to display a heatmap with a DateTimeAxis, I add a LinearAxis also as a kind of "shadow axis". Then I do this:

```
plotSeriesModel.Updated += (sender, e) =>
{
  heatMapSeries.YAxis.IsAxisVisible = false;
};
```
This works, but has a side effect: the value in the tracker is now a double and seems to have as its value "(time of slice - start time) / size of time slice)". It is not possible to format this correctly. Since [the TrackerChanged cannot be used to alter the text in the UI](https://oxyplot.readthedocs.io/en/master/views/tracker.html), this seems impossible to solve. Is this correct?

Would it not be possible to allow changing the tracker text manually _before_ the tracker text is set in the UI? This way it would be possible to transform the double into a DateTime object and display the correct value.

Greets, Menno

**Comment by VisualMelon** [comment]
Heatmap with DateTimeAxis seems to work for me with 2.0  (though I may be missing something).

![image](https://user-images.githubusercontent.com/5646475/85282569-de35ba80-b483-11ea-977a-4ee068727d36.png)

Could you show your example code? Note that you need to use `DateTimeAxis.ToDouble` and `ToDateTime` to translate values used by series.

**Comment by VisualMelon** [comment]
Regarding trackers, that doesn't seem to be possible. It would need to be a per-series format delegate or something, which I'm sure has been discussed before, but I can't find the issue...

**Comment by VisualMelon** [comment]
What does look like a bug, is that the `LabelFormatter` for an axis is not used by the tracker (e.g. there is no reason you couldn't set the `LabelFormatter` of the shadow axis to something like `shadowAxis.LabelFormatter = dt => "" + DateTimeAxis.ToDateTime(dt);`, and it would seem reasonable that this should affect the tracker also).

**Comment by mennowo** [comment]
Thanks for your reply. I actually had the same thought, that being able to use the LabelFormatter for the tracker would solve the issue. And it would indeed seem intuitive if the LabelFormatter would affect the tracker. Maybe only if the TrackerFormatString has not been set?

You note that this should work better in 2.0 lead to some further investigation. And to the resolution! Thanks.

The problem was that I had set minimum and maximum on the DateTimeAxis, but had set Y0 and Y1 to different values on the HeatMapSeries. Therefore the heatmap appeared empty. Now it works fine. Here is some sample code for reference. It has a DateTimeSeries on the left, and a categoryAxis on the bottom. It uses a class from [this thread](https://github.com/oxyplot/oxyplot/issues/497).

```
// this code presupposed a list 'allItems' and an object 'myData'
// also it uses a couple of [extension methods on DateTime](https://stackoverflow.com/questions/1393696/rounding-datetime-objects)
var plotSeriesModel = new ViewResolvingPlotModel();
var heatMapSeries = new HeatMapSeries
{
    X0 = 0,
    X1 = allItems.Count(x => x.Show) - 1,
    Y0 = Axis.ToDouble(myData.Start.AddMinutes(myData.Interval)),
    Y1 = Axis.ToDouble(myData.End.Ceiling(TimeSpan.FromMinutes(myData.Interval))),
    TrackerFormatString = "Item: {2}\nTime: {4}\nValue: {6:0.#}",
    Interpolate = false,
    Data = myData.Data
};
plotSeriesModel.Series.Add(heatMapSeries);
var XAxis = new CategoryAxis()
{
    Position = AxisPosition.Bottom,
    Title = "Item",
    ItemsSource = allItems.Where(x => x.Show).Select(x => x.Name),
    MaximumPadding = 0.3,
    MinimumPadding = 0.3,
    AbsoluteMinimum = -1,
    AbsoluteMaximum = allItems.Count(x => x.Show)
};
plotSeriesModel.Axes.Add(XAxis);
var YAxis = new DateTimeAxis()
{
    Minimum = Axis.ToDouble(myData.Start.AddMinutes(myData.Interval)),
    Maximum = Axis.ToDouble(myData.End.Ceiling(TimeSpan.FromMinutes(myData.Interval))),
    Title = "Time",
    StringFormat = "HH:mm",
    Position = AxisPosition.Left
};
plotSeriesModel.Axes.Add(YAxis);
var linearColorAxis = new LinearColorAxis();
linearColorAxis.Palette = OxyPalette.Interpolate(100, OxyColors.ForestGreen, OxyColors.Yellow, OxyColors.Crimson);
linearColorAxis.HighColor = OxyColors.Crimson;
linearColorAxis.LowColor = OxyColors.ForestGreen;
linearColorAxis.Position = AxisPosition.Right;
linearColorAxis.Minimum = 0;
linearColorAxis.Maximum = (int) newData.Max2D();
plotSeriesModel.Axes.Add(linearColorAxis);
```
