### ISSUE TITLE
Oxyplot "develop" release on myget.org?

### ISSUE THREAD

**Issue by abrasat** [oxyplot/oxyplot#1615]
Is the release based on the actual code from the "develop" oxyplot branch available on myget.org?
I dont find any new version there.

**Comment by VisualMelon** [comment]
This is where the AppVeyor CI pushes it's builds: https://www.myget.org/feed/oxyplot/package/nuget/OxyPlot.Core

Note that it automatically selects an old version, because version naming has changed at some point. The current version latest is 2.1.0-unstable.1424

**Comment by abrasat** [comment]
Ok, thanks. What URL exactly has to be added as additional package source in Visual Studio, in view to be able to update the Oxyplot packages from there?

**Comment by VisualMelon** [comment]
It says on that page: https://www.myget.org/F/oxyplot/api/v3/index.json

Yes, that feed will give you access to everything in main repository and a handful of other things.

**Comment by VisualMelon** [comment]
Closing this as I think it's address: feel free to reopen if you have further questions.
