### ISSUE TITLE
DateTimeAxis not displaying correct date

### ISSUE THREAD

**Issue by stijnvankampen** [oxyplot/oxyplot#1617]
### Steps to reproduce

1. Make DateTimeAxis
2. Add datapoints with datetime.now and datetime + 10 seconds
3. Run application

Platform: WPF
.NET version: 4.8
OxyPlot version: 2.0.0

### Expected behaviour

X-axis should display current time.

### Actual behaviour

X-axis now displays some 1900-xx-xx time, but also display correct time. This is visible in the screenshot.

![4mQlwmq4DX](https://user-images.githubusercontent.com/8737434/86006305-0f7b3100-ba16-11ea-8f9e-c622616e5311.png)

**Comment by VisualMelon** [comment]
Can you provide your example code? This looks like there are two axes on the X-axis.

**Comment by stijnvankampen** [comment]
Ok, I think I made a mistake. I set the y-axis to datetime as well, which resulted in this behaviour. Now I have the y-axis set to linearaxis and this works perfect.

**Comment by VisualMelon** [comment]
That sounds like you didn't set the YAxis `Position = AxisPosition.Left`, and the Y-Axis in the picture is the default vertical axis.

**Comment by stijnvankampen** [comment]
That makes sense, thanks for your help.
