### ISSUE TITLE
Size of vertical legend box is too small in width for content

### ISSUE THREAD

**Issue by axunonb** [oxyplot/oxyplot#1618]
### Steps to reproduce

New console app (netcore3.1) with OxyPlot.ExampleLibrary 2.0.0 referenced as a nuget package.

```Csharp
var exporter = new SvgExporter();
using (var s = File.Create(@"Path-so-result.svg"))
{
    var model = LineSeriesExamples.TwoLineSeries();

    model.LegendBackground = OxyColor.FromAColor(220, OxyColors.White);
    model.LegendBorder = OxyColors.Black;
    model.LegendBorderThickness = 1.0; 
    model.LegendPlacement = LegendPlacement.Outside;
    model.LegendPosition = LegendPosition.BottomLeft;
    model.LegendOrientation = LegendOrientation.Vertical;
    model.LegendLineSpacing = 10;
    // model.LegendMaxWidth = 1000;   // irrelevant
    model.LegendFontSize = 14;
    exporter.Export(model, s);
}
```
Platform:
.NET version: Net Core 3.1

### Expected behaviour

The legend should be rendered within the width of the legend box

### Actual behaviour

The legend exceeds the width of the vertical legend box.
It looks like ```GetLegendSize(IRenderContext rc, OxySize availableLegendArea)``` of class ```Legend.Rendering``` does not calculate the string width correctly. The issue shows up no matter which ```LegendFontSize``` is set.

This issue also exists in the current development branch (commit https://github.com/oxyplot/oxyplot/commit/807974d0330f478b568d249af7632ec63a1f6a55), when using ```model.Legends.Add(new Legend(...)``` with same parameters as above.

![OxyPlotLegend](https://user-images.githubusercontent.com/10255664/86179710-15af0180-bb2b-11ea-980a-1440796e04fd.jpg)

**Comment by VisualMelon** [comment]
This is a deficiency with the built in text renderer for the SVG exporter, which doesn't produce accurate text measurements. The issue can largely be mitigated by using an alternative text measurer:
 - If you are on windows, `OxyPlot.WindowsForms.SvgExporter` uses GDI+ text measuring which generally produces much better results.
 - If you can use the a development branch, then the new cross-platform Skia offering includes an Svg exporter.

**Comment by axunonb** [comment]
```SkiaSharp.SvgExporter``` works just fine, thank you. Really appreciate this great library. Unfortunately I cannot go for GDI+ because of platform independency. Looks like I'll have to include a project reference in my target project for now, which is not so nice. Do you have plans for a next pre-release version?

**Comment by VisualMelon** [comment]
I'm afraid I can't comment on proper releases, but you can get the CI builds from myget (see https://github.com/oxyplot/oxyplot/issues/1615 for a couple of notes)

**Comment by axunonb** [comment]
Okay, I'll have a look.
Just oversaw that with ```SkiaSharp.SvgExporter``` model ```Background``` color is not rendered (remains white). I'll have to investigate whether is my fault. We can close this issue, thanks again.

**Comment by VisualMelon** [comment]
That's an omission in the Skia Svg exporter. I'll sort out a PR.
