### ISSUE TITLE
RectangleBarSeries rendered on top layer

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#162]
**Imported from [http://oxyplot.codeplex.com/workitem/10236](http://oxyplot.codeplex.com/workitem/10236)**

**[CyberLoupGarou](http://www.codeplex.com/site/users/view/CyberLoupGarou)** 2014-07-30 10:27
Hello 

I'm using the RectangleBarSeries as a trick to display columns on a DateTimeAxis. It works fairly well but it seems these series are drawn on top of every other series. So if you mix LineSeries and RectangleBarSeries, the rectangles appear to be on top and
 prevent any tracker event on the LineSeries. 

As it works fine with AreaSeries instead of RectangleBarSeries, I guess this shouldn't be too big of a problem. I don't know if there's a way to specify a layer for series, like there is for annotations...

**[CyberLoupGarou](http://www.codeplex.com/site/users/view/CyberLoupGarou)** 2014-07-30 13:56
Forgot to say that I'm using the WPF version.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-08-06 11:01
Can you provide code that shows the error? I tried the following code and cannot reproduce:

<div style="color:Black; background-color:White">
<pre>
        [Example(<span style="color:#A31515">"#10236: RectangleBarSeries rendered on top layer"</span>)]
        <span style="color:Blue">public</span> <span style="color:Blue">static</span> PlotModel RectangleBarSeriesRenderedOnTopLayer()
        {
            <span style="color:Blue">var</span> plotModel1 = <span style="color:Blue">new</span> PlotModel
            {
                Title = <span style="color:#A31515">"Issue 10236"</span>,
            };
            <span style="color:Blue">var</span> lineSeries1 = <span style="color:Blue">new</span> LineSeries();
            lineSeries1.Points.Add(<span style="color:Blue">new</span> DataPoint(0, 1));
            lineSeries1.Points.Add(<span style="color:Blue">new</span> DataPoint(1, 0));
            plotModel1.Series.Add(lineSeries1);
            <span style="color:Blue">var</span> rectangleBarSeries1 = <span style="color:Blue">new</span> RectangleBarSeries();
            rectangleBarSeries1.Items.Add(<span style="color:Blue">new</span> RectangleBarItem(0.25, 0.25, 0.75, 0.75));
            plotModel1.Series.Add(rectangleBarSeries1);
            <span style="color:Blue">var</span> lineSeries2 = <span style="color:Blue">new</span> LineSeries();
            lineSeries2.Points.Add(<span style="color:Blue">new</span> DataPoint(0, 0));
            lineSeries2.Points.Add(<span style="color:Blue">new</span> DataPoint(1, 1));
            plotModel1.Series.Add(lineSeries2);
            <span style="color:Blue">return</span> plotModel1;
        }
</pre>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-08-07 10:49
I added the example to ExampleLibrary -> Issues

**[CyberLoupGarou](http://www.codeplex.com/site/users/view/CyberLoupGarou)** 2014-08-07 11:34
I tweaked my code a bit, making sure I add the RectangleBarSeries first so they are "under" the other series. And I think they are correctly rendered.

But the tracker (that I've set to appear on mouseover) seems confused about the series to show. It is true it's over two different series. As I type this, I think I have the idea why it always show the RectangleBarSeries. It always "enters" the RectangleBarSeries
 first, and doesn't leave it before going over the LineSeries. That might explain why it always choose to show the series "behind". I might be stretching things a bit with what I'm trying to do ;)

I'll test it with the default tracker behaviour (the click) to see if the problem remains.

Do you think I should post in the discussions the way I "trick" to display columns series on a LinearAxis? I've also managed to do bubble series. Your library is really something well done.

**[CyberLoupGarou](http://www.codeplex.com/site/users/view/CyberLoupGarou)** 2014-08-08 08:16
Ok, it is indeed the tracker event and not the rendering that causes the problem. Sorry to have wrongly identified the problem.

Once I set the tracker to behave as usual, if I click on the line when it is not over the rectangle, the tracker is able to follow the LineSeries over RectangleBarSeries.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
