### ISSUE TITLE
TileMapAnnotation requires custom user agent on openstreet map.

### ISSUE THREAD

**Issue by Kareltje1980** [oxyplot/oxyplot#1642]
### Steps to reproduce

1. Open Oxyplot.WindowsForms Example browser
2. Exceptions are thrown when loading the data 429

### Expected behaviour

Should show the map

### Actual behaviour
no Map

### Solution
Add a UserAgent to the request and limit the threads to max 2.

They updated their usage policy
https://operations.osmfoundation.org/policies/tiles/

**Comment by objorke** [comment]
See also #1400
