### ISSUE TITLE
Zoom In/Out By Scrollwheel Uses Incorrect Scale Factors

### ISSUE THREAD

**Issue by jupistar** [oxyplot/oxyplot#1648]
### Steps to reproduce

1. Generate any 2D plot (say a line plot)
2. Place cursor near the center of the x-axis and scrollwheel forward
3. Without moving cursor, scrollwheel backward

Platform:
.NET version
Windows Forms

The amount of zoom in and out should be equal.

But it's not.

The problem appears to be in Started(OxyMouseEventArgs) in ZoomStepManipulator. The Step property is being used as an additive value, but zooming is multiplicative. So, if Step = 0.12, then the scale is being set to 1.12 and if Step = -0.12, then the scale is set to 0.88. But 1.12 and 0.88 are not reciprocals of each other. Currently, the scale variable is being set like this:

            var scale = this.Step;
            if (this.FineControl)
                scale *= 3;

            scale = 1 + scale;

Thus if step is negative, it creates a <1 multiplicative zoom. A correct equation would be to set the scale variable like:

            var scale = this.Step;
            if (this.FineControl)
                scale *= 3;

            if (scale > 0)
                scale = 1 + scale;
            else
                scale = 1.0 / (1 - scale);

But that code feels weird (subtracting a negative value). Still, this resolves the issue of inconsistent zooming. But my understanding of OxyPlot code is superficial. This may not be the correct place to address the issue. Of course, if this is acceptable, the follow lines of code can be removed:

            // make sure the zoom factor is not negative
            if (scale < 0.1)
            {
                scale = 0.1;
            }

**Comment by jupistar** [comment]
Thanks. I know it's can be easy to fix bugs in isolation while completely ignoring the larger context, which is why I placed it here for someone who knows the project thoroughly to review. Thanks!

**Comment by VisualMelon** [comment]
@jupistar to clarify, if you want to open a PR for this change, please do! (Otherwise I'll try to get around to it over the weekend). My concern is that making a larger change (i.e. making the delta multiplicative, rather than additive) may have unforeseeable repercussions, so I'd be hesitant to do any more than you already suggest.

**Comment by jupistar** [comment]
I will try. I've never done this sort of thing on a project I didn't create. So, if I screw it up... :)

**Comment by VisualMelon** [comment]
@jupistar If you want to submit this is a PR, feel free to go ahead and I'll be happy to help you with the process. Otherwise, aaea469 is as your suggestion, and I'll submit that for review soon.

**Comment by jupistar** [comment]
That is okay with me. I'm very sorry that I didn't follow through on this, because I wanted to understand the process. However, I just have had 0 time this last month to do anything.

**Comment by VisualMelon** [comment]
That's alright. If you want any guidance with the other PR, just go for it; we'll be happy to guide you through the process.

**Comment by jupistar** [comment]
Okay, I'll target 2 weeks from now to do that... it's on my whiteboard!

**Comment by VisualMelon** [comment]
@jupistar that said, it would be worth making an Issue for it first, to make sure it's something we will be happy to include; or if it's a solution to an existing issue then it's worth outlining the proposed solution (in the same issue) to get immediate feedback and let other people know it's being worked on.

**Comment by jupistar** [comment]
Okay, it's a "new feature". I'll do that now.
