### ISSUE TITLE
Axis.ScreenMin and Axis.ScreenMax are weird

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1652]
Horizontal and Vertical axes do not provide useful values for `ScreenMin` and `ScreenMax`. They suffice for finding the start and end of the axis in the dimension in which they exist, but do not provide any information about the other dimensions. The odd piece of code is: https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/Axis.cs#L1372-L1373

            this.ScreenMin = new ScreenPoint(a0, a1);
            this.ScreenMax = new ScreenPoint(a1, a0);

Existing code ignores this weirdness because it all explicitly checks whether the axis is horizontal or vertical before querying the min/max values.

Note that the bounds the in the other dimensions are not known when these bounds are set: they are only known after rendering, when the margins from other tiers are known. As such, there is no obvious solution, but it would make sense to me to update the ScreenMin and ScreenMax after rendering. This will help with simplifying axis hit-testing (which is performed inside `PlotModel` at the moment). The information that is 'missing' from the screen min and max is ultimately recorded in `PositionTierMinShift` and `PositionTierMaxShift`, relative to the plot bounds. Even these are `internal`, so stuff like #1651 is impossible to do reliably.

The issue of when these things should be updated is related to #1621.

**Comment by Jonarw** [comment]
Fully agree that this is 'weird' to say the least.

Maybe this could be rectified as part of a potential larger refactoring of the Axes code as in #1640?
