### ISSUE TITLE
Mouse events do not work as expected

### ISSUE THREAD

**Issue by mcmatze** [oxyplot/oxyplot#166]
I have some plots in WPF and i'm using a PlotView. Now i want to add a new functionality: I want to show up a context menu when the user is right clicking (without mouse moving).

I've tried following events and the result:

plotView.Clicked does not exists.
plotView.MouseDown only works when you double click on the plot.
plotView.MouseUp does not show up.
plotView.MouseMove does not show up.

plotView.Model.Clicked does not exists.
plotView.Model.MouseDown works as expected.
plotView.Model.MouseMove does not provide a mouse status (right button clicked, left button, etc.)
plotView.Model.MouseUp does not provide mouse status too.

I think that there are some issues about this.

**Comment by tibel** [comment]
With #446 the PlotController does not intercept the events any more.
When there is no handler or the handler does not set `Handled=true` you get the event on the `PlotView` as expected.
