### ISSUE TITLE
SkiaSharp Stable Release

### ISSUE THREAD

**Issue by sushi19921992** [oxyplot/oxyplot#1664]
hey @VisualMelon @objorke @Jonarw , just wondering if there is an update in terms of when (or if) SkiaSharp will ever have a stable release rather than an unstable. Just curious in terms of if this is on your roadmap or not. Thanks!

**Comment by sushi19921992** [comment]
@VisualMelon that sounds promising. Definitely will be keen to use 2.1 when it is properly released and maybe I can report any bugs if I come across them. I'll keep an eye out for the next month or so, as this'll be the time we would need a proper release of Skia (at least, in a month or so it would be super convenient to have a proper release of the Skia/performance improvement stuff).

I'll keep a watch :) thanks

**Comment by VisualMelon** [comment]
2.1.0 has just been released; sorry for the delay.
