### ISSUE TITLE
c# winfrom ：How am I supposed to specify default axes under multiple axes

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1666]

**Comment by VisualMelon** [comment]
You can't change the default axes; they are based on the order in which they exist in the `Axes` collection.

If you have multiple axes, you should be specify the `AxisKey` on each series to ensure they are meaningful.

<hr />

It probably wouldn't be hard to allow the user to change the default axis by specifying a default key, but I don't think that's a good idea.

**Comment by SynapseIkaros** [comment]
> 您无法更改默认轴；它们基于它们在`Axes`集合中存在的顺序。
> 
> 如果有多个轴，则应`AxisKey`在每个系列上指定，以确保它们有意义。
> 
> 允许用户通过指定默认键来更改默认轴可能并不困难，但我认为这不是一个好主意。

How do I change numeric values of the second axis by using right mouse button and scroll wheel in intermediate interface

**Comment by VisualMelon** [comment]
@SynapseIkaros please open separate issues for separate concerns. For short questions, feel free to ping me on [gitter](https://gitter.im/oxyplot/oxyplot). Also, we don't have an API reference (we probably should...) but you can search the documentation in a limited capacity on [fuget](https://www.fuget.org/packages/OxyPlot.Core/2.0.0/lib/netstandard1.0/OxyPlot.dll/OxyPlot.Axes/Axis).

> How do I change numeric values of the second axis by using right mouse button and scroll wheel in intermediate interface

I'm afraid I don't understand what you mean.

**Comment by SynapseIkaros** [comment]
> @SynapseIkaros请针对不同的关注点提出单独的问题。简短的问题，请随时向我[询问](https://gitter.im/oxyplot/oxyplot)。另外，我们没有API参考（可能应该...），但是您可以在[fuget](https://www.fuget.org/packages/OxyPlot.Core/2.0.0/lib/netstandard1.0/OxyPlot.dll/OxyPlot.Axes/Axis)上以有限的容量搜索文档。
> 
> > 如何在中间界面中使用鼠标右键和滚轮更改第二轴的数值
> 
> 恐怕我不明白你的意思。

Wheel zoom, default is axis 1, but I have multiple shafts, how can I scroll can enlarge axis 2, and do not need special use mouse to select him

**Comment by VisualMelon** [comment]
Ah, sorry, I mis understood your original post. You'll need to mess with the `PlotController`, see #59 (or reorder your axes).
