### ISSUE TITLE
Add netstandard2.0 target?

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1668]
I recently studied this page for an unrelated project:
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/cross-platform-targeting

Especially this point I think is relevant for us:

> DO include a netstandard2.0 target if you require a netstandard1.x target.
> All platforms supporting .NET Standard 2.0 will use the netstandard2.0 target and benefit from having a smaller package graph while older platforms will still work and fall back to using the netstandard1.x target.

That is something that I actually did notice in the past, but never thought about it too much: when referencing OxyPlot from .NET Core a lot of Microsoft packages are added in the process. 
I guess it would be nice to avoid this, so I would propose to add the `netstandard2.0` target to the core library (and to all other libraries targeting any `netstandard1.x`, e.g. `OxyPlot.SkiaSharp`).

---

By the way, I think this other point should already be covered by our `net45` target:
> CONSIDER adding a target for net461 when you're offering a netstandard2.0 target.
> Using .NET Standard 2.0 from .NET Framework has some issues that were addressed in .NET Framework 4.7.2. You can improve the experience for developers that are still on .NET Framework 4.6.1 - 4.7.1 by offering them a binary that is built for .NET Framework 4.6.1.

**Comment by VisualMelon** [comment]
+1 by sheer coincidence I was reading the same thing today while trying to work out how to set the UserAgent in netstandard1.0.
