### ISSUE TITLE
c# winfrom: Whether transparent background can be set?

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1670]
Code comes from git

**Comment by SynapseIkaros** [comment]
@VisualMelon

**Comment by VisualMelon** [comment]
I'm not sure what you mean. You can set the `PlotModel` background to a transparent color. There are some weird things in WinForms with respect to opacity, so you'll just have to try and see what happens.

**Comment by KoalaBear84** [comment]
@SynapseIkaros Did you got it to work?

Here I get "Property value is not valid.", "Control does not support transparent background colors." when trying to set "Transparent" as the BackColor.

I integrated a (very) little OxyPlot graph inside a DeskBand. The deskband itself is transparent, also the labels and the PictureBox, but can't get the OxyPlot to be transparent.

**Comment by KoalaBear84** [comment]
Hmm.. It's a very hard issue. I have every possible property to Transparent. But the one I really want isn't possible, `Background`.

```c#
LineSeries.Background = OxyColors.Transparent;
PlotModelTemperature.PlotAreaBackground = OxyColors.Transparent;
PlotModelTemperature.PlotAreaBorderColor = OxyColors.Transparent;
```

Also tried exporting to PNG (because PNG supports transparency) and assign to a PictureBox. But the WindowsForms one doesn't have a `Background` property which the WPF one does :(

```c#
PngExporter pngExporter = new PngExporter
{
    Height = PlotTemperature.Height,
    Width = PlotTemperature.Width,
    Resolution = PlotTemperature.DeviceDpi
};

Bitmap bitmap = pngExporter.ExportToBitmap(PlotModelTemperature);
PictureTemperature.Image = bitmap;
```

Also tried this:

```c#
using (MemoryStream memoryStream = new MemoryStream())
{
	Bitmap bitmap = new Bitmap(1, 1);
	bitmap.MakeTransparent();
	PlotTemperature.BackgroundImage = bitmap;
}
```

Unfortunately nothing works.

Yes, I even tried switching to WPF, didn't come at the point to test the transparency. Because I couldn't get all the mouse events to work, and had some layout issues.

**Comment by KoalaBear84** [comment]
Hmm. I did manage to make it work, but only when you don't need ANY interactive things of course.

This will take a `PlotModel` object, generates a bitmap of it, and uses that as the `Image` on a `PictureBox` component.

```c#
PngExporter pngExporter = new PngExporter
{
	Height = PictureBoxHistory.Height,
	Width = PictureBoxHistory.Width,
	Resolution = PictureBoxHistory.DeviceDpi
};

Bitmap bitmap = pngExporter.ExportToBitmap(PlotModelTemperature);

PictureBoxHistory.Image = bitmap;
```

**Comment by VisualMelon** [comment]
Looks like this is impossible without calling `SetStyle(ControlStyles.SupportsTransparentBackColor, true)` on the PlotView, which I'd overlooked. I'm not sure if there is a particular reason we don't support this on `PlotView`, but there may be some weird issues with interaction, and the child-background rendering behaviour isn't implemented (though I'm not sure what it should be). You should be able to call this with reflection as a fudge, but we probably need to address this in the library: generally it's a bad idea putting a plot on a crazy background, but to support simple use-cases it is probably a good idea.

Transparent controls are non-trivial in winforms: the 'background' is rendered by the parent element, so if you need a control to be rendered on-top of another control, it must be a child of that control and have a transparent background: it's easy to pick up a form back-ground colour, but beyond that care must be taken.

**Comment by KoalaBear84** [comment]
I did have `SetStyle(ControlStyles.SupportsTransparentBackColor, true)` in the load event, but can only call it without parameters, or direct it to another control.

But if OxyPlot could call this, it might work without all the exporting :)

**Comment by VisualMelon** [comment]
You can always extend `PlotView`:

        public class PlotView2 : PlotView
        {
            public PlotView2()
            {
                this.SetStyle(ControlStyles.SupportsTransparentBackColor, true);
            }
        }

        public Form1()
        {
            var view1 = new PictureBox() { Dock = DockStyle.Fill, ImageLocation = "https://upload.wikimedia.org/wikipedia/commons/0/0a/Black_Swan_2_-_Pitt_Town_Lagoon.jpg", SizeMode = PictureBoxSizeMode.Zoom };
            Controls.Add(view1);

            var view2 = new PlotView2() { Location = new Point(0,0), Width = 300, Height = 300 };
            view1.Controls.Add(view2);
            view2.BackColor = Color.Transparent;

            var plot2 = new PlotModel() { Title = "Foreground", Background = OxyColors.Transparent, PlotAreaBackground = OxyColor.FromArgb(128, 255, 255, 255) };
            plot2.Series.Add(new FunctionSeries(Math.Sin, -10, 10, 0.1));
            view2.Model = plot2;
            plot2.InvalidatePlot(true);
            view2.BringToFront();

            InitializeComponent();
        }

Like I said, it's not properly supported, but if you just need a static background to show through, it should hopefully suffice.

**Comment by KoalaBear84** [comment]
Thanks! I decided to use this route, didn't thought about deriving 😇 And, yes, it now works as I wanted ❤

I've made a simple 'reproduce' project for anyone. It looks like you NEED to create it programmatically. Else it doesn't work.

[WindowsFormsAppOxyPlotTransparent.zip](https://github.com/oxyplot/oxyplot/files/5747503/WindowsFormsAppOxyPlotTransparent.zip)

Preview:
![image](https://user-images.githubusercontent.com/5886900/103218633-d61b7380-491b-11eb-9ee2-18fafc3f62c5.png)

**Comment by SynapseIkaros** [comment]
> 谢谢！我决定使用这条路线，没有想到 而且，是的，它现在可以按我的意愿工作 
> 
> 我为任何人创建了一个简单的“重现”项目。看起来您需要以编程方式创建它。否则它不起作用。
> 
> [WindowsFormsAppOxyPlotTransparent.zip](https://github.com/oxyplot/oxyplot/files/5747503/WindowsFormsAppOxyPlotTransparent.zip)
> 
> 预习：
> ![图片](https://user-images.githubusercontent.com/5886900/103218633-d61b7380-491b-11eb-9ee2-18fafc3f62c5.png)

In WinForm, all transparent backgrounds point to their parents, even the MainForm itself
