### ISSUE TITLE
Dashed lines are solid when exporting via SkiaSharp.SvgExporter

### ISSUE THREAD

**Issue by SBSQ** [oxyplot/oxyplot#1674]
Hello,
I have noticed that the SkiaSharp.SvgExporter does not support dashed lines.

### Environment
.Net Framework 4.6.2
Latest pre-release version OxyPlot.SkiaSharp 2.1.0

### Steps To Reproduce
1. Create a plot with any line that has style set to LineStyle.Dash
Example:

        protected override void SetupPlotModel()
        {
            PlotModel = new PlotModel()
            {
                Title = "Dashed Line Chart",
            };

            PlotModel.Axes.Add(new LinearAxis
            {
                Key = "X",
                Position = AxisPosition.Bottom,
                Title = "X Axis",
            });

            PlotModel.Axes.Add(new LinearAxis
            {
                Key = "Y",
                Position = AxisPosition.Left,
                Title = "Y Axis",
            });
        }

        protected override void Plot()
        {
            var line = new LineSeries()
            {
                LineStyle = LineStyle.Dash,
                Color = ColourBlack,
                StrokeThickness = 3,
            };

            line.Points.Add(new DataPoint(1, 1));
            line.Points.Add(new DataPoint(10, 10));

            PlotModel.Series.Add(line);
        }

### Expected behaviour
This is taken from the SkiaSharp.PDFExporter. The dashed line appears as expected.
![image](https://user-images.githubusercontent.com/10110129/94760916-ed14fd00-03e2-11eb-99da-471c02e12b93.png)

### Actual behaviour
The dashed line is solid in the SVGExporter.
![image](https://user-images.githubusercontent.com/10110129/94760862-cc4ca780-03e2-11eb-9ddb-6bc88422c71b.png)

**Comment by VisualMelon** [comment]
Reproduced: the Rendering capabilities clipping example is an existing example. Seems to be specific to SVG (other Skia exporters work fine). There seems to be nothing about a dashed line in the output at all.

**Comment by Jonarw** [comment]
Well Skia's (and therefore also SkiaSharp's) SVG export is considered incomplete - I guess this is one of the things which is just not implemented on their side. So I don't think we can really do anything about it. A potential fix could not even be done in SkiaSharp, but would have to go into the original Skia library if I'm not mistaken.

I did try if the newest version of SkiaSharp (which also uses a much newer version of Skia) would fix the problem, but with no success.

**Comment by Doeharrrck** [comment]
I have just updated SkiaSharp to version **2.88.3** in my personal branch after also coming across this issue. Seems that this issue is fixed/implemented in that version. With version 2.**80**.3 it was still **not** working.

**Comment by VisualMelon** [comment]
@Doeharrrck thanks for this information!
