### ISSUE TITLE
OxyPlot.SkiaSharp.WPF main UI starts to slow down

### ISSUE THREAD

**Issue by karuzzo** [oxyplot/oxyplot#1675]
Hi, my name is Vlad. I am writing to you because I got a issue with OxyPlot.SkiaSharp.WPF 2.1.0-unstable. When I start drawing candles, the interface of the program itself starts to slow down. Please help with advice on how to solve this problem. 

Here is a link to a 1minute video with the described problem. 
https://drive.google.com/file/d/1LL9O8z0_aB45_gjXx8Le9KMI6CpSQIAS/view?usp=sharing

**Comment by VisualMelon** [comment]
We are unable to access the video. Can you provide a small example that reproduces the problem?

**Comment by karuzzo** [comment]
its my mistake, im so sorry
