### ISSUE TITLE
How to change position for the YAxis of series

### ISSUE THREAD

**Issue by bdrachinsky** [oxyplot/oxyplot#1680]
Hi @objorke , I'm trying to change YAxis of certain series but I found the only way is changing Y of points but I would like to apply Y offset for the whole series line because there could be thousand of thousands point

![image](https://user-images.githubusercontent.com/13419649/95054524-ae40b900-06fa-11eb-8c09-2d3f37b2e23a.png)

I marked here channel box and series above. Thanks for your time!

**Comment by bdrachinsky** [comment]
Total height of Channel boxes is 860
Plot area has 850 height
I'm trying to synchronizing series to their channel box

Any ideas how could I move series except changing Yvalue of points

**Comment by objorke** [comment]
I think you can create multiple Y axes and use the `StartPosition`/`EndPosition` properties to achieve this. 
See https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/Axis.cs#L555
