### ISSUE TITLE
Offset Ticks on axis so that they do not start at zero

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1684]
My code is a bit messy, so I provide some fragment data to give an example.
plotModel1.Axes.Add(new LinearAxis
            {
                AxisDistance = 2,
                Key = "Y0",
                Maximum = 100,
                AbsoluteMinimum = -25,
                //IsZoomEnabled = false,
                //IsPanEnabled = false,
                Minimum = -25,
                MajorStep =(100-(-25))/3.00,
                MinorStep = 100 / 5 / 5,
                AxislineThickness = 2,
                MinorGridlineThickness = 1,
                Position = AxisPosition.Left,        
                MajorGridlineStyle = LineStyle.Solid,   
                MinorGridlineStyle = LineStyle.Solid,      
                AxislineStyle = LineStyle.Solid,      
                TickStyle = TickStyle.Outside,     
                MinorTickSize = 0,         
                MajorGridlineColor = OxyColors.Red,  
            });
I want to divide the axis into three segments, so the total / 3.
But the axis still starts at 0
@VisualMelon

**Comment by SynapseIkaros** [comment]
I want to keep the minimum and maximum values,

**Comment by VisualMelon** [comment]
I do not believe it is possible to offset the tick values from zero. If you need that level of control, consider making your own axis class and overriding `GetTickValues` to return particular values of interest. Linking #1640 for back-reference.
