### ISSUE TITLE
When I translated the axis and reassigned the maximum / minimum value of the axis, it didn't change.

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1686]
Initialization Exampl

        private void TrendsSeries_Load(object sender, EventArgs e)
        {

            DateTime d = DateTime.Now.AddSeconds(-60);
            var start = new TimeSpan(d.Hour, d.Minute, d.Second);
            var end = new TimeSpan(DateTime.Now.Hour, DateTime.Now.Minute, DateTime.Now.Second);
            double increment = 1;

            var r = new Random(7);
            var data = new Collection<TimeValue>();
            var current = start;
            while (current <= end)
            {
                data.Add(new TimeValue { Time = current, Value = r.NextDouble() });
                current = current.Add(new TimeSpan(0, 0, (int)increment));
            }

            var plotModel1 = new PlotModel { Title = "TimeSpan axis" };
            var timeSpanAxis1 = new TimeSpanAxis
            {
                Key = "X0",
                Position = AxisPosition.Bottom,
                StringFormat = "hh:mm:ss",
                Minimum = TimeSpanAxis.ToDouble(start),
                Maximum = TimeSpanAxis.ToDouble(end),
                MajorStep = 15,
                MinorStep = 1,
                MajorGridlineStyle = LineStyle.Solid,
                //MinimumMajorStep=1,
                //MinimumMinorStep
                MinorGridlineStyle = LineStyle.Solid,
                MinorTickSize = 5,
            };
            plotModel1.Axes.Add(timeSpanAxis1);
            var linearAxis1 = new LinearAxis { Position = AxisPosition.Left };
            plotModel1.Axes.Add(linearAxis1);
            var lineSeries1 = new LineSeries
            {
                Color = OxyColor.FromArgb(255, 78, 154, 6),
                StrokeThickness = 1,
                DataFieldX = "Time",
                DataFieldY = "Value",
                ItemsSource = data
            };
            plotModel1.Series.Add(lineSeries1);
            plotView1.Model = plotModel1;

        }

**Comment by SynapseIkaros** [comment]
The right mouse button translates the axis.
Reassign maximum / minimum valu

                var r = new Random();
                var model = plotView1.Model;
                LineSeries line = model.Series[0] as LineSeries;
                var data = new Collection<TimeValue>();
                data = (Collection<TimeValue>)line.ItemsSource;

                DateTime d = DateTime.Now.AddSeconds(-60);
                var start = new TimeSpan(d.Hour, d.Minute, d.Second);
                var end = new TimeSpan(DateTime.Now.Hour, DateTime.Now.Minute, DateTime.Now.Second);
                model.GetAxis("X0").Minimum = TimeSpanAxis.ToDouble(start);
                model.GetAxis("X0").Maximum = TimeSpanAxis.ToDouble(end);

                data.Add(new TimeValue { Time = data[data.Count - 1].Time.Add(new TimeSpan(0, 0, 1)), Value = r.NextDouble() });
                (model.Series[0] as LineSeries).ItemsSource = data;
                plotView1.Model = null;
                plotView1.Model = model;
                plotView1.Refresh();

**Comment by SynapseIkaros** [comment]
The axis did not change, but remained the way it was after I translated.

**Comment by SynapseIkaros** [comment]
.NET version: 4.7.2
The code comes from GitHub.

**Comment by VisualMelon** [comment]
If you replace 

            plotView1.Model = null;
            plotView1.Model = model;
            plotView1.Refresh();

with

    model.InvalidatePlot(true);

do you get the same behaviour? It's not clear which platform you are using, but invoking `Refresh` on the `PlotView` won't update the model, only render it, which I don't think covers computing the `ActualMinimum` and `ActualMaximum` on the axes.

**Comment by SynapseIkaros** [comment]
c# winform

**Comment by SynapseIkaros** [comment]
> 如果您更换
> 
> ```
>         plotView1.Model = null;
>         plotView1.Model = model;
>         plotView1.Refresh();
> ```
> 
> 与
> 
> ```
> model.InvalidatePlot(true);
> ```
> 
> 你会得到相同的行为吗？目前尚不清楚您使用的是哪个平台，但是`Refresh`在on上调用`PlotView`不会更新模型，而只会渲染模型，我认为这并不涉及计算`ActualMinimum`and`ActualMaximum`轴。
Model.InvalidatePlot (true).
Updated the model correctly.
After I moved the drawing interface with the right mouse button
The model will not be updated.

**Comment by SynapseIkaros** [comment]
The function I need is.
Update the lines every second.
Axis does not move, line moves to the left, axis update time value.
Track the latest points in real time

**Comment by VisualMelon** [comment]
Yeah, changing model should have been calling that anyway in WinForms. It's working fine for me. Note that if you click and pan with the right mouse button that the default controller will then change the `ViewMinimum` `ViewMaximum` which override `Minimum` and `Maximum`. The best way to deal with this would be to unregister the handler in the controller if you don't want it. Otherwise, if you just want to change the view min/max, you can use the `Axis.Zoom(double, double)` overload, passing in the new view min/max. If you need to use `Minimum` and `Maximum` for some reason, you could reset the axis before setting them, which clears the `ViewMinimum` and `ViewMaximum`.

**Comment by SynapseIkaros** [comment]
Thank you. This is a good solution to my problem.

**Comment by SynapseIkaros** [comment]
@VisualMelon
