### ISSUE TITLE
SkiaRenderContext ignores LineJoin=Miter for small angles

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1690]
### Expected behaviour

The specified `LineJoin` should be applied. 

### Actual behaviour

When `LineJoin` is set to `Miter`, the SkiaSharp renderer falls back to `Bevel` for small angles. This can be seen in the LineJoin example added in #1687.
![image](https://user-images.githubusercontent.com/18097859/95679411-f2d4c480-0bd2-11eb-801d-8648663b694b.png)

### Cause

The `SkPaint.StrokeMiter` property limits how large the Miter can get in relation to `StrokeThickness`. It defaults to 4 and therefore small angles default to a Bevel.
I propose to raise this value to be consistent with other renderers. I'm not sure if it makes more sense to set this to `PositiveInfinity` or rather use some sufficiently large number that still somewhat limits the miter. In theory the Miter can get infinitely large at pathologically small angles...

**Comment by VisualMelon** [comment]
I don't have strong feelings on the matter, but something non-infinite would be sensible I think. In [WinForms](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.pen.miterlimit?view=dotnet-plat-ext-3.1) and [WPF](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.pen.miterlimit?view=netcore-3.1) the default l/w ratio seems to be 10, so maybe it would make sense to try to be consistent with them.

**Comment by Jonarw** [comment]
Default value of 10 sounds good to be consistent with Winforms&WPF!
I think I'll make it configurable on `SkiaRenderContext` for now, if we ever decide we want this on `PlotView`/`Exporter` level we should do this for all of them.
