### ISSUE TITLE
How to correctly define the maximum / minimum value(DateTimeAxis)

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1694]
c# winfrom  code for git
I want to change the display seconds of the scale
I can get the effect I want in this example. -Example("Just Volume (combined), fixed axis")
But I don't know how to reproduce it when I use LineSeries now.

**Comment by VisualMelon** [comment]
I'm afraid I don't understand the question. Could you provide some more details, and maybe a mock up? From the title, it sounds like my comments over in https://github.com/oxyplot/oxyplot/issues/1686#issuecomment-706916684 might suffice.

**Comment by SynapseIkaros** [comment]
> 恐怕我不明白这个问题。您能否提供更多详细信息，也许还提供一个模型？从标题看来，我在[＃1686中的评论（评论）](https://github.com/oxyplot/oxyplot/issues/1686#issuecomment-706916684)可能就足够了。
 private static Example CreateVolumeSeries(
            string title, 
            VolumeStyle style, 
            int n = 10000,
            bool natural = false)
        {
            var pm = new PlotModel { Title = title };

            var series = new VolumeSeries
            {
                PositiveColor = OxyColors.DarkGreen,
                NegativeColor = OxyColors.Red,
                PositiveHollow = false,
                NegativeHollow = false,
                VolumeStyle = style,
                Title = "VolumeSeries",
            };

            // create bars
            foreach (var bar in OhlcvItemGenerator.MRProcess(n))
            {
                series.Append(bar);
            }

            // create visible window
            var Istart = n - 200;
            var Iend = n - 120;
            var Xmin = series.Items[Istart].X;
            var Xmax = series.Items[Iend].X;         
            // setup axes
            var timeAxis = new DateTimeAxis
            {
                Position = AxisPosition.Bottom,
                Minimum = Xmin,
                Maximum = Xmax
            };

            var volAxis = new LinearAxis
            {
                Position = AxisPosition.Left,
                StartPosition = 0.0,
                EndPosition = 1.0,
                Minimum = natural ? double.NaN : 0,
                Maximum = natural ? double.NaN : 10000
            };

            switch (style)
            {
                case VolumeStyle.Combined:
                case VolumeStyle.Stacked:
                    pm.Axes.Add(timeAxis);
                    pm.Axes.Add(volAxis);
                    break;

                case VolumeStyle.PositiveNegative:
                    volAxis.Minimum = natural ? double.NaN : -10000;
                    pm.Axes.Add(timeAxis);
                    pm.Axes.Add(volAxis);
                    break;
            }

            pm.Series.Add(series);

            var controller = new PlotController();
            controller.UnbindAll();
            controller.BindMouseDown(OxyMouseButton.Left, PlotCommands.PanAt);
            return new Example(pm, controller);
        }

**Comment by SynapseIkaros** [comment]
This is an example. -Example("Just Volume (combined), fixed axis")

**Comment by SynapseIkaros** [comment]
const string keyAxisY_Humidity = "axisY_Humidity";

            var plotModel = new PlotModel()
            {
                Title = "Multi vertical axes with lineSeries",
            };

            Legend l = new Legend
            {
                LegendBackground = OxyColors.White
            };
            plotModel.Legends.Add(l);

            var axisX_Time = new DateTimeAxis()
            {
                Key = "X0",
                Title = "Time",
                StringFormat = "hh:mm:ss",
                Position = AxisPosition.Bottom,
                MajorGridlineStyle = LineStyle.Solid,
                FontSize = 13,
            };
            plotModel.Axes.Add(axisX_Time);

            LineSeries lineSeriesHumidity = null;
            LinearAxis axisY_Humidity = null;
            axisY_Humidity = new LinearAxis()
            {
                Title = "Humidity",
                Position = AxisPosition.Left,
                MajorGridlineStyle = LineStyle.None,
                PositionTier = 3,
                Key = keyAxisY_Humidity,
                IsAxisVisible = true,
            };

            lineSeriesHumidity = new LineSeries()
            {
                Title = "Humidity",
                Color = OxyColors.LightSkyBlue,
                MarkerSize = 3,
                MarkerFill = OxyColors.DeepSkyBlue,
                YAxisKey = keyAxisY_Humidity,
                IsVisible = true,
            };

            plotModel.Axes.Add(axisY_Humidity);
            plotModel.Series.Add(lineSeriesHumidity);
            lineSeriesHumidity.Points.Clear();

            var timeSpan = TimeSpan.FromSeconds(1);
            var time = DateTime.Now;
            int countPoints = 60;
            for (int i = 1; i <= countPoints; i++)
            {
                double humidity = 50 + 2.0 * Math.Sin(2.0 * i);

                lineSeriesHumidity.Points.Add(DateTimeAxis.CreateDataPoint(time, humidity));

                time += timeSpan;
            }

            axisY_Humidity.Minimum = 47;
            axisY_Humidity.Maximum = 60;

            plotView1.Model = plotModel;
            plotView1.Model.InvalidatePlot(true);

This is LineSeries.
I want to control the value of the scale.

**Comment by SynapseIkaros** [comment]
-Example("Just Volume (combined), fixed axis")
From the example, I think it's using coordinates to assign values.
But I don't know how to get the right coordinates.

**Comment by SynapseIkaros** [comment]
Examples come from : oxyplot-develop\Source\Examples\ExampleLibrary\Series\FinancialSeries\VolumeSeriesExamples.cs

**Comment by SynapseIkaros** [comment]
![image](https://user-images.githubusercontent.com/53081122/95805210-6e4f8680-0d37-11eb-9d6f-f6f22c17a6ad.png)

**Comment by SynapseIkaros** [comment]
![QQ图片20201013093542](https://user-images.githubusercontent.com/53081122/95805289-a5be3300-0d37-11eb-8cbb-91f38be3ba22.png)

**Comment by SynapseIkaros** [comment]
This is made of TimeSpanAxis.

**Comment by SynapseIkaros** [comment]
I don't know how DateTimeAxis can do it.

**Comment by VisualMelon** [comment]
As with `TimeSpanAxis`, you need to translate the date/time values, in this case with `DateTimeAxis.ToDouble(DateTime)`. In that example, the X values are computed in https://github.com/oxyplot/oxyplot/blob/94db37a0f609e4df794feee9c431cc1848e52e6a/Source/Examples/ExampleLibrary/Series/FinancialSeries/OhlcvItemGenerator.cs#L72

**Comment by SynapseIkaros** [comment]
> 与一样`TimeSpanAxis`，您需要转换日期/时间值，在这种情况下，请使用`DateTimeAxis.ToDouble(DateTime)`。在该示例中，X值计算为
> 
> https://github.com/oxyplot/oxyplot/blob/94db37a0f609e4df794feee9c431cc1848e52e6a/Source/Examples/ExampleLibrary/Series/FinancialSeries/OhlcvItemGenerator.cs#L72

I'm sorry. I got the problem wrong.

**Comment by SynapseIkaros** [comment]
What I want to modify is MajorStep property.

**Comment by SynapseIkaros** [comment]
var axisX_Time = new DateTimeAxis()
            {
                Key = "X0",
                StringFormat = "yyyy-MM-dd\r\nhh:mm:ss",
                Position = AxisPosition.Bottom,
                MajorGridlineStyle = LineStyle.Solid,
                FontSize = 13,
                Minimum = DateTimeAxis.ToDouble(DateTime.Now),
                Maximum = DateTimeAxis.ToDouble(DateTime.Now.AddSeconds(60)),
                MajorStep = 1,
            };
            plotModel.Axes.Add(axisX_Time);

**Comment by SynapseIkaros** [comment]
![image](https://user-images.githubusercontent.com/53081122/95831845-24cd5e80-0d6c-11eb-98d9-8a13cab62f0e.png)

**Comment by SynapseIkaros** [comment]
MajorStep = 1
Time is gone.

**Comment by VisualMelon** [comment]
You'll have to specify the `IntervalType`. The `MajorStep` is then multiples of the interval, though some interval types override it (e.g. `Weeks` is equivalent to `Days` with a major step of `7`).

**Comment by SynapseIkaros** [comment]
-Example("Just Volume (combined), fixed axis")
In this example, I can control MajorStep very well.
I just need to change the maximum / minimum value
So I thought it was the maximum / minimum worthy of the problem.

**Comment by VisualMelon** [comment]
The default interval type does not mix well with non unity `MajorStep`, because it doesn't consider the `MajorStep` when it determines an appropriate interval: if need to control the `MajorStep`, you will have to specify the `IntervalType` also. Once you specify the `IntervalType`, the min/max no longer influence the actual major step.

**Comment by SynapseIkaros** [comment]
var axisX_Time = new DateTimeAxis()
            {
                Key="X0",
                Position = AxisPosition.Bottom,
                Minimum = DateTimeAxis.ToDouble(DateTime.Now),
                Maximum = DateTimeAxis.ToDouble(DateTime.Now.AddMinutes(1)),
                IntervalType = DateTimeIntervalType.Minutes,
                MajorGridlineStyle = LineStyle.Solid,
                StringFormat = "HH:mm:ss",
                MajorStep = 1.0 / 24 / 2/30/4, // 1/24 = 1 hour, 1/24/2 = 30 minutes
                IsZoomEnabled = true,
                MaximumPadding = 0,
                MinimumPadding = 0,
                TickStyle = OxyPlot.Axes.TickStyle.None

            };
            plotModel.Axes.Add(axisX_Time);

IntervalType does not affect MajorStep.
He always calculates it on a day-by-day basis.

**Comment by SynapseIkaros** [comment]
@VisualMelon

**Comment by VisualMelon** [comment]
Sorry, my mistake, `MajorStep` is measured in days (I've got that wrong before, I think...).

**Comment by SynapseIkaros** [comment]
> 抱歉，我的错误`MajorStep`是用几天来衡量的（我认为之前我做错了...）。
> 
> 是的，您绝对正确：`IntervalType`除了格式化外，其他都没关系。

Thanks for your help

I've solved this problem
