### ISSUE TITLE
Dynamic binding of series in WPF

### ISSUE THREAD

**Issue by ottisj** [oxyplot/oxyplot#1701]
### Series dynamic binding

Hi there, I have the following task in my application:
I read somehow data from an excel file and parse it to a XYManager class, where the most important collection is:
 `public ObservableCollection<DataPoint> XYPoints`
of course DataPoint is OxyPlot data point.
Now in my model I have a collection of several XYManagers, each representing a collection of XY points, and public property PlotModel, bound in my XAML like follows:

` <oxyplot:PlotView x:Name="opGraph" Model="{Binding Model}"/>`

Everything works fine when I am using the following iteration to "fill the model with data":

```
_model.Series.Clear();
            foreach (XYManager item in _data)
            {
                OxyPlot.Series.LineSeries sr = new OxyPlot.Series.LineSeries();
                sr.Points.AddRange(item.XYPoints);

                _model.Series.Add(sr);
            }
```

But I would like to make direct binding between my XYManager (s) collections and OxyPlot Series, because I have the data listed in table and I want if user changes data in table the change is seen in Plot immediatelly.
So is it possible to make binding like:
```
Binding b = new Binding("XYSerie");
                b.Source = _data[0];
                _model.SetBinding(b);
```

Thanks in Advance 
Jan

**Comment by Jonarw** [comment]
No, there is no direct support for Bindings in oxyplot.
I guess one of the reasons is that the library is meant to be portable, whereas every platform has its own methods of binding.

**Comment by ottisj** [comment]
Thanks, so will do it myself. Jan
