### ISSUE TITLE
If the line is too dense, it will blur.

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1704]
![image](https://user-images.githubusercontent.com/53081122/96697557-a3567b80-13be-11eb-8d2c-6f81ca3c4ce9.png)

**Comment by SynapseIkaros** [comment]
c# winform
Is this normal? Or am I missing some settings?

**Comment by VisualMelon** [comment]
Sorry, I'm not sure which blurring it is to which you are referring: the fuzzyness in the gap between two nearly-parallel lines is just an artefact of the anti-aliasing, and is completely normal. You can disable antialising by specifying the `EdgeRenderingMode` in 2.1.
