### ISSUE TITLE
The collection has been modified; the enumeration operation may not be performed

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1705]
c#　
winform  
.net 4.7.2 
The code comes from git

**Comment by SynapseIkaros** [comment]
private async void button2_Click(object sender, EventArgs e)
        {
             t = Task.Run(() =>
               {
                while (true)
                {
                    if (token.IsCancellationRequested)
                    {
                        return "";
                    }
                    Thread.Sleep(200);
                    var end = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, DateTime.Now.Hour, 
                    DateTime.Now.Minute, DateTime.Now.Second,DateTime.Now.Millisecond);
                    var start = DateTime.Now.AddSeconds(-60);
                    var r = new Random();
                    var model = plotView1.Model;
                    if (!(model.GetAxisOrDefault("X0", null) != null))
                        return "";
                    DateTimeAxis xAxis = model.GetAxis("X0") as DateTimeAxis;
                    xAxis.Zoom(DateTimeAxis.ToDouble(start), DateTimeAxis.ToDouble(end));

                    LineSeries line = model.Series[0] as LineSeries;
                    line.Points.Add(DateTimeAxis.CreateDataPoint(end, r.Next(0, 100)));
                    plotView1.Model = null;
                    plotView1.Model = model;
                }
            }, token);
            await t;
        }

**Comment by SynapseIkaros** [comment]
In the process of drawing lines.
If I move my mouse online quickly.
There will be a mistake.

**Comment by SynapseIkaros** [comment]
System.InvalidOperationException
  HResult=0x80131509
  Message=集合已修改；可能无法执行枚举操作。
  Source=mscorlib
  StackTrace:
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   在 System.Collections.Generic.List`1.Enumerator.MoveNext()
   在 System.Linq.Enumerable.<SkipIterator>d__31`1.MoveNext()
   在 OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(IEnumerable`1 points, Int32 startIdx, ScreenPoint point)
   在 OxyPlot.Series.XYAxisSeries.GetNearestPointInternal(IEnumerable`1 points, ScreenPoint point)
   在 OxyPlot.Series.DataPointSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate)
   在 OxyPlot.Series.LineSeries.GetNearestPoint(ScreenPoint point, Boolean interpolate)
   在 OxyPlot.TrackerManipulator.GetNearestHit(Series series, ScreenPoint point, Boolean snap, Boolean pointsOnly)
   在 OxyPlot.TrackerManipulator.Delta(OxyMouseEventArgs e)
   在 OxyPlot.ControllerBase.HandleMouseMove(IView view, OxyMouseEventArgs args)
   在 OxyPlot.WindowsForms.PlotView.OnMouseMove(MouseEventArgs e)
   在 System.Windows.Forms.Control.WmMouseMove(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   在 System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   在 System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   在 System.Windows.Forms.Application.Run(Form mainForm)
   在 OxPlotDemo.Program.Main() 在 C:\Users\Diego\source\repos\OxPlotDemo\OxPlotDemo\Program.cs 中: 第 19 行

**Comment by Jonarw** [comment]
https://github.com/oxyplot/oxyplot/issues/1482
