### ISSUE TITLE
c# winform BarSeries

### ISSUE THREAD

**Issue by SynapseIkaros** [oxyplot/oxyplot#1710]
var categoryAxis = new CategoryAxis
            {
                AxislineStyle = LineStyle.Solid,
                TickStyle = TickStyle.None,
                Key = "y",
                IsAxisVisible=true,
                GapWidth = 1,
            };
            categoryAxis.Labels.AddRange(new[] { "" });
            pm.Axes.Add(categoryAxis);
            pm.Axes.Add(
                new LinearAxis
                {
                    Position = AxisPosition.Left,
                    Minimum = 0,
                    Maximum = 6000,
                    MajorStep = 1000,
                    MinorStep = 1000,
                    AxislineStyle = LineStyle.Solid,
                    MajorGridlineStyle = LineStyle.None,
                    TickStyle = TickStyle.Outside,
                    StringFormat = "#,0",
                    IsAxisVisible=true,
                    Key = "x"
                    
                });

            for (int i = 0; i < 10; i++)
            {
                var bs = new BarSeries { Title = "bar " + i, XAxisKey = "x", YAxisKey = "y", IsStacked = false, StrokeColor = 
                OxyColors.Black, StrokeThickness = 1 };
                bs.Items.Add(new BarItem { Value = rd.Next(0, 6000) });
                pm.Series.Add(bs);
            }

Why is categoryaxis the y-axis?

**Comment by SynapseIkaros** [comment]
The location of categoryaxis is at the bottom

**Comment by VisualMelon** [comment]
Sorry, I don't understand the question: can you clarify which version you are using and show exactly what is happening that you don't expect.
