### ISSUE TITLE
GitHub Actions Failing

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1713]
The github action is crashing at the moment. It's to do with this recent change: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

The [msbuild setup script](https://github.com/warrenbuckley/Setup-MSBuild) is apparently out of date and we should use [the offical version instead now](https://github.com/microsoft/setup-msbuild). I don't know if just swapping this out will solve the problem; I would guess not.

I can't look deeply into this now; it's not a big issue, but it's annoying not having that layer of checks working.

**Comment by rstm-sf** [comment]
We can look at [this example](https://github.com/reactiveui/ReactiveUI.Validation/blob/98656a238652dc354b52e1b3852b8b6b2f3c6765/.github/workflows/ci-build.yml#L40-L45)
