### ISSUE TITLE
LineSeries line thickness

### ISSUE THREAD

**Issue by Dimigergo** [oxyplot/oxyplot#1722]
Is it possible to add LineThicknessProperty to LineSeries like the BrokenLineThicknessProperty?

I use the OxyPlot.WPF 2.0.0.

Thanks in advance!

**Comment by VisualMelon** [comment]
I think you are looking for `StrokeThickness`.

**Comment by Dimigergo** [comment]
2.0.0 OxyPlot.WPF.LineSeries doesn't have StrokeThickness property. :(

Only these:
![oxyplot](https://user-images.githubusercontent.com/11498949/100336301-49a52a80-2fd6-11eb-8cb2-c76fcc79c57a.png)

**Comment by VisualMelon** [comment]
Line 147 in your screenshot ;)

**Comment by Dimigergo** [comment]
Ohh, how stupid I'm... :D Very sorry for this. I can't see it in DependencyProperty list.
Sorry for this!
