### ISSUE TITLE
BarSeries incorrect label alignment

### ISSUE THREAD

**Issue by papka-Leo** [oxyplot/oxyplot#1726]
### Steps to reproduce

1. Use OxyPlot.SkiaSharp.WPF or OxyPlot.WPF version 2.1.0-Preview
2. Create BarSeries with LabelPlacement = LabelPlacement.Base, LabelFormatString = "{0:f4}", BaseValue = -100, Value axis from -100 to 100.
3. Negative values labels will not display at all, zero values labels will display partially. It's seems to be the same behavior as if BaseValue not set when negative values labels are aligned at the left side from axis zero.

This is regression - all works fine with OxyPlot.WPF version 2.0.0

Platform: Windows
.NET version: .net core 3.1 or .net 5.0

### Expected behaviour

User can see all labels

### Actual behaviour

User can't see negative values, zero values are half-placed

P.S. Sorry for my English, I've attached sample solution. First project demonstates incorrect behavior. Second projects shows right version.
[HistogramNegativeNumbersTest.zip](https://github.com/oxyplot/oxyplot/files/5688649/HistogramNegativeNumbersTest.zip)

**Comment by VisualMelon** [comment]
Reproduced. Picture of incorrect behaviour:

![image](https://user-images.githubusercontent.com/5646475/102082184-6b414700-3e09-11eb-94ab-6bdfb5e25119.png)

**Comment by VisualMelon** [comment]
Issues seems to be

https://github.com/oxyplot/oxyplot/blob/40d32aed58af0edc0a039a0d1ac7cddefb34d553/Source/OxyPlot/Series/BarSeries/BarSeries.cs#L313

Should probably be `var sign = Math.Sign(item.Value - baseValue);`

I'll add an example with labels and a non-zero base value.
