### ISSUE TITLE
Invisible series are visible in the legend in version 2.1.0-Preview1

### ISSUE THREAD

**Issue by rstm-sf** [oxyplot/oxyplot#1730]
Hello!

### Invisible series are visible in the legend in version 2.1.0-Preview1

1. Open [`LegendExamples.LegendRightTopInside()`](https://github.com/oxyplot/oxyplot/blob/61ffa99e16bb6f320326d117a0fd6e86bea71634/Source/Examples/ExampleLibrary/Examples/LegendExamples.cs#L20)
2. Add `model.Series[0].IsVisible = false;` row after [`model.Legends.Add(l);`](https://github.com/oxyplot/oxyplot/blob/61ffa99e16bb6f320326d117a0fd6e86bea71634/Source/Examples/ExampleLibrary/Examples/LegendExamples.cs#L31)
3. Run ExampleLibrary in the any host, f.e. wpf

![image](https://user-images.githubusercontent.com/2669927/102898291-594f4c00-447a-11eb-8ab8-532eeb6c555d.png)

Platform: Windows
.NET version:  Any?

**Comment by VisualMelon** [comment]
Is this https://github.com/oxyplot/oxyplot/pull/1624 ?

**Comment by VisualMelon** [comment]
Ah, no, I see what you mean now. I thought this was the original behaviour (though I don't recall anyone changing it), but I could be mistaken. This makes sense to me, now that visibility is controllable by legends: there is still the `RenderInLegend` property that forces matters, but if it is a breaking change, we should probably revert it.

**Comment by rstm-sf** [comment]
> there is still the `RenderInLegend` property that forces matters

Thanks, I didn't know about it. It's work



> but if it is a breaking change

It looks like it. Legend changing was intuitive, but _Visible_ was taken by surprise




> we should discuss it and consider reverting it

Sorry, but I'm badly familiar with this library to be completely sure that this change is not for this release. Before this version it became invisible in the legend and I didn't think about some additional property

**Comment by Jonarw** [comment]
Yes this is a breaking change coming from 2.0. I think the change itself is fine and makes sense, maybe we should consider mentioning it more explicitly in the changelog.

Nevertheless I think there should be a way of disabling this behavior. In some plots you may not want the user to be able to hide graphs via the legend. In my fork I use at work I hacked this in, but I guess it would be good to support this officially.

**Comment by VisualMelon** [comment]
@Jonarw making it optional sounds good to me, especially if you use it successfully. I agree it should be clearly described in the change log. If I've understood it correctly, #1723 is the same problem.

**Comment by VisualMelon** [comment]
Would it suffice to add a new property to `LegendBase` called `ShowHiddenSeries` or similar which controls this behaviour? Would we agree that the default should be `true`?
