### ISSUE TITLE
Should we enable GitHub Discussions for the oxyplot repo?

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1734]
About this new GitHub feature: https://docs.github.com/en/free-pro-team@latest/discussions/quickstart

This could help keep the Issues section clean from questions regarding the usage of the library and would give an 'official' platform to ask such questions. As far as I understand it should be possible to convert both ways between Issues and Discussions. So I guess we could potentially move all issues tagged `Question` over to Discussions.

Personally I don't really see a downside to this. What's your opinion? Especially @objorke and @VisualMelon, but other opinions are of course also welcome!

**Comment by VisualMelon** [comment]
I can see a couple of possible downsides (though I may be missing the point), but I'm not opposed to trying it. Couple of thoughts:
 - It's new, which means nobody will be able to find it (obviously that will change with time)
 - May make it harder to find/reference other discussion (will discussions have the same indexing? i.e. if an issue is moved, can we still reference it easily, and will old references keep working? (and vice-versa))
 - More avenues of communication means more things to watch/neglect, but if this has good github integration then that shouldn't be too big an issue

As a relevant point, there are a few other places where people ask questions at the moment.
 - There is a reasonable amount of through-put on our [gitter](https://gitter.im/oxyplot/oxyplot): it's mostly people asking questions about how to do things, and I'll open an Issue if they reveal a problem.
 - There is also a user-echo forum, which is pretty much abandoned, but people still post there occasionally (it has some dead links that we should probably deal with) (see #1274)
 - There are significantly more questions on [SO](https://stackoverflow.com/questions/tagged/oxyplot) than I expected.

Apart from github issues, the gitter is the only one I watch at the moment.

**Comment by objorke** [comment]
I like this! It would be great to have a natural GitHub place for discussions and have all the `Question` issues moved over.
My only concern is that there should not be more communication channels than necessary to monitor. So if the discussions feature is added, I suggest the gitter and userecho channels are sealed/shut down!

**Comment by Jonarw** [comment]
> May make it harder to find/reference other discussion (will discussions have the same indexing? i.e. if an issue is moved, can we still reference it easily, and will old references keep working? (and vice-versa))

As far as I know, issues and discussions share their indices, just as issues and PRs already do.
Links and references to issues won't break when they are converted to discussions, there are automatic redirections.

> More avenues of communication means more things to watch/neglect, but if this has good github integration then that shouldn't be too big an issue

I agree. As suggested by objorke, we might consider retiring some of the other channels once we see that the Discussions work for us.

**Comment by VisualMelon** [comment]
Closing, as discussions have been enabled.
