### ISSUE TITLE
LineAnnotation text clipping on reversed axes

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#1741]
### Steps to reproduce

1. View example `LineAnnotation` in an example browser, and reverse the axes.
2. The 'First' annotation is clipped

![image](https://user-images.githubusercontent.com/5646475/107202446-1f1e1780-69f2-11eb-86e4-7d1e30ba5f07.png)

The text should be positioned within the plot bounds, as occurs on a non-reversed axes, but is not. This appears to be mitigated by uncommenting this line:

https://github.com/oxyplot/oxyplot/blob/61ffa99e16bb6f320326d117a0fd6e86bea71634/Source/OxyPlot/Annotations/TextualAnnotation.cs#L77

The line was introduced (as a comment) in https://github.com/oxyplot/oxyplot/pull/1435/files#diff-9b25104c8bfedc3c97747a9d1e89366896b9f1ed1e70fd1f2101691da6eb3a8eR77

@Jonarw do you recall if there was a particular reason this was disabled? There are other problems with annotations on line plots (e.g. the text doesn't clamp to the Y axes, which would be nice), so we should probably review them all at some point.

**Comment by Jonarw** [comment]
I remember debating (with myself) whether `TextualAnnotation`s should change their text direction when transposing the plot. I seem to have decided against it, which makes more sense in opinion, but could be debatable of course.

But disabling this particular line of course also means that the annotation does not 'notice' when axes are reversed (which the `Orientate` function would take care of), which I apparently didn't think about. I'm not quite sure how to best address this at the moment...

**Comment by VisualMelon** [comment]
Looking at this now, I agree completely with you that the direction shouldn't change. This probably needs better support in the rendering routines themselves.

**Comment by VisualMelon** [comment]
Had a go at fixing this in https://github.com/VisualMelon/oxyplot/tree/Issue1741

It seems to address the text positioning problem when the text 'should' be visible, but it sometimes presents the text for vertical/horizontal when it should not be visible (when axes reversed). If you reverse the axes, and drag the plot off to the right, then when the 'Horizontal' annotation leaves the plot it disappears briefly, before reappearing, 'snapped' to the end of the plot. I'm not sure what is causing this at the moment, but it also occurs on a non-reversed axis if you set the `Minimum` rather than `Maximum`. I'm not sure yet if this is a new bug or an old one (possibly pre-transposable annotations), will take another look soon.

**Comment by VisualMelon** [comment]
Looks like it is an old bug; should be mitigated by #1764
