### ISSUE TITLE
UWP exhibits stepping when drawing curved lines.  How to fix?

### ISSUE THREAD

**Issue by Noemata** [oxyplot/oxyplot#1754]
UWP oxyplot line rendering exhibits stepping when drawing a curved line.  I can't tell if the start of the line is a bit off, or the end, or both.  Any ideas on how this could be corrected or what the root cause might be?

Screenshot is below:

![image](https://user-images.githubusercontent.com/6632315/112239797-8ba94a80-8c1d-11eb-9363-1c1bbc9544e9.png)

**Comment by Noemata** [comment]
Another more obvious example of the problem:

![image](https://user-images.githubusercontent.com/6632315/112240907-9f55b080-8c1f-11eb-8e77-63a5f752d842.png)

**Comment by Noemata** [comment]
Zoomed in view of above:

![image](https://user-images.githubusercontent.com/6632315/112241358-797cdb80-8c20-11eb-9897-6d092d232f52.png)

**Comment by Noemata** [comment]
Never mind ...

![image](https://user-images.githubusercontent.com/6632315/112858561-fd4f2180-907f-11eb-9b72-38b38e3220fd.png)

**Comment by VisualMelon** [comment]
Did you resolve your problem?

**Comment by Noemata** [comment]
@VisualMelon , thank you for asking.  Yes, I did resolve the issue.  The real issue was the current disconnect between the previous UWP sources and the current WPF parts.

**Comment by VisualMelon** [comment]
My apologies for not getting back to you sooner. I'll close this for the time being, but feel free to re-open it if there is a deficiency in the library or documentation.
