### ISSUE TITLE
LineSeries tracker tooltip not showing when InterpolationAlgorithm=CanonicalSpline

### ISSUE THREAD

**Issue by iniceice88** [oxyplot/oxyplot#1756]
### Steps to reproduce

1.Create a LineSeries
```csharp
public static PlotModel CreateLineSeriesModel()
{
	var plot = new PlotModel();

	plot.Axes.Add(new LinearAxis { Position = AxisPosition.Left });
	plot.Axes.Add(new LinearAxis { Position = AxisPosition.Bottom });

	var ls = new LineSeries();
	ls.InterpolationAlgorithm = InterpolationAlgorithms.CanonicalSpline;
	for (int i = 1; i <= 30; i++)
	{
		ls.Points.Add(new DataPoint(i, 0.01));
	}
	ls.Points.Add(new DataPoint(31, 1));
	ls.Points.Add(new DataPoint(32, 10));
	ls.Points.Add(new DataPoint(33, 100));
	ls.Points.Add(new DataPoint(34, 1000));
	plot.Series.Add(ls);

	return plot;
}
```
2.Left click on point 1 ~ point 31

Platform:
.NET version:4.8

### Expected behaviour

Track tooltip should showing

### Actual behaviour

Tooltip not showing

### More Information

LineSeries.SmoothedPoints:

`
(32,10);(32.06,11.86);(32.12,11.93);(32.18,10.65);(32.24,8.46);(32.29,5.81);(32.35,3.14);(32.41,0.9);(32.47,-0.47);(32.53,-0.52);(32.59,1.2);(32.65,5.12);(32.71,11.7);(32.76,21.38);(32.82,34.61);(32.88,51.82);(32.94,73.47);(33,100);(33.01,102.8);(33.01,105.69);(33.02,108.65);(33.02,111.68);(33.03,114.79);(33.03,117.98);(33.04,121.23);(33.05,124.56);(33.05,127.96);(33.06,131.44);(33.06,134.98);(33.07,138.59);(33.08,142.27);(33.08,146.01);(33.09,149.83);(33.09,153.7);(33.1,157.64);(33.11,161.65);(33.11,165.72);(33.12,169.84);(33.12,174.03);(33.13,178.28);(33.14,182.59);(33.14,186.96);(33.15,191.38);(33.15,195.86);(33.16,200.4);(33.17,204.99);(33.17,209.63);(33.18,214.33);(33.19,219.08);(33.19,223.88);(33.2,228.72);(33.2,233.62);(33.21,238.57);(33.22,243.56);(33.22,248.6);(33.23,253.69);(33.24,258.82);(33.24,263.99);(33.25,269.21);(33.26,274.47);(33.26,279.77);(33.27,285.11);(33.28,290.49);(33.28,295.91);(33.29,301.36);(33.29,306.85);(33.3,312.38);(33.31,317.95);(33.31,323.54);(33.32,329.17);(33.33,334.83);(33.33,340.53);(33.34,346.25);(33.35,352);(33.35,357.78);(33.36,363.59);(33.37,369.43);(33.37,375.29);(33.38,381.18);(33.39,387.09);(33.39,393.02);(33.4,398.98);(33.41,404.96);(33.41,410.95);(33.42,416.97);(33.42,423.01);(33.43,429.06);(33.44,435.13);(33.44,441.22);(33.45,447.32);(33.46,453.44);(33.46,459.57);(33.47,465.71);(33.48,471.87);(33.48,478.03);(33.49,484.21);(33.5,490.39);(33.5,496.58);(33.51,502.78);(33.51,508.98);(33.52,515.19);(33.53,521.41);(33.53,527.63);(33.54,533.85);(33.55,540.07);(33.55,546.29);(33.56,552.51);(33.57,558.74);(33.57,564.96);(33.58,571.17);(33.58,577.39);(33.59,583.6);(33.6,589.8);(33.6,596);(33.61,602.19);(33.62,608.37);(33.62,614.54);(33.63,620.71);(33.63,626.86);(33.64,633);(33.65,639.13);(33.65,645.24);(33.66,651.34);(33.66,657.43);(33.67,663.5);(33.68,669.55);(33.68,675.58);(33.69,681.6);(33.69,687.59);(33.7,693.57);(33.7,699.52);(33.71,705.45);(33.72,711.36);(33.72,717.24);(33.73,723.1);(33.73,728.93);(33.74,734.74);(33.74,740.52);(33.75,746.26);(33.76,751.98);(33.76,757.67);(33.77,763.33);(33.77,768.95);(33.78,774.55);(33.78,780.1);(33.79,785.63);(33.79,791.11);(33.8,796.56);(33.8,801.98);(33.81,807.35);(33.81,812.69);(33.82,817.98);(33.82,823.23);(33.83,828.44);(33.83,833.61);(33.84,838.74);(33.84,843.82);(33.85,848.85);(33.85,853.84);(33.86,858.78);(33.86,863.67);(33.87,868.51);(33.87,873.3);(33.88,878.04);(33.88,882.73);(33.89,887.37);(33.89,891.95);(33.89,896.48);(33.9,900.95);(33.9,905.37);(33.91,909.72);(33.91,914.02);(33.92,918.27);(33.92,922.45);(33.92,926.57);(33.93,930.63);(33.93,934.62);(33.94,938.55);(33.94,942.42);(33.94,946.22);(33.95,949.96);(33.95,953.63);(33.96,957.23);(33.96,960.76);(33.96,964.23);(33.97,967.62);(33.97,970.94);(33.97,974.18);(33.98,977.36);(33.98,980.46);(33.98,983.48);(33.99,986.43);(33.99,989.3);(33.99,992.1);(33.99,994.81);(34,997.45);(34,1000)
`

**Comment by VisualMelon** [comment]
Thanks for reporting this, and sorry about the slow response.

This seems to be caused by a high tolerance filtering excessively many points. The `tolerance` on this example is computed as a little over `5`; the data-points that are missing are those which are closely packed.

Unfortunately, the `ToleranceDivisor` in `LineSeries` is hard-coded. A workaround might be to override `ResetSmoothedPoints`, but fixing this will require someone who understands the splines implementation (The code is annotated with references.)

This example may demonstrates another deficiency in the rendering, in that the spline appears only to be computed on visible values (i.e. the visible window), which doesn't really make sense.

I may be wrong, but I think that this issue is essentially a manifestation of the fundamental problem that you can't meaningfully perform automatic 'smoothing' in data-space: apart from being misleading, a nice line depends on knowing the rendering transform (log/lin/whatever), that is, you can't generate a sensible tolerance unless you know the rendered scale. It may be that a different mechanism can be used for filtering, but I think it can never be scale-invariant.

**Comment by iniceice88** [comment]
Thanks for your reply!
As a workaround,I override `ResetSmoothedPoints` and simply insert `ActualPoints`  to `SmoothedPoints`:
```c#
public class MyLineSeries : LineSeries
{
    protected override void ResetSmoothedPoints()
    {
        base.ResetSmoothedPoints();
        EnsureSmoothedPointsContainsActualPoints();
    }

    private void EnsureSmoothedPointsContainsActualPoints()
    {
        if (this.InterpolationAlgorithm == null || ActualPoints.Count == 0)
            return;

        int smoothedPointsIndex = 0;
        foreach (var ap in ActualPoints)
        {
            bool allSmaller = false;
            for (int i = smoothedPointsIndex; i < SmoothedPoints.Count; i++)
            {
                var diff = SmoothedPoints[i].X - ap.X;
                if (diff < 0)
                    continue;

                // Equals
                if (diff < double.Epsilon)
                {
                    smoothedPointsIndex = i + 1;
                    break;
                }
                allSmaller = true;
                SmoothedPoints.Insert(i, new DataPoint(ap.X, ap.Y));
                smoothedPointsIndex = i + 1;
                break;
            }
            if (allSmaller)
                SmoothedPoints.Add(new DataPoint(ap.X, ap.Y));
        }
    }
}
```

**Comment by VisualMelon** [comment]
That's a nice general workaround, thanks for posting it.
