### ISSUE TITLE
Adding Line series  in a Candlestick series using Windows Form

### ISSUE THREAD

**Issue by 32x0lf** [oxyplot/oxyplot#1757]
Hi,  I have posted in SO about my problem in adding a line series to a candlestick series. [Add Line Series + Candlestick](https://stackoverflow.com/questions/66856961/how-to-add-lineseries-candlesticks-using-oxyplot) . Whenever I add a line series it will divide the chart just like the image in SO.

**Comment by VisualMelon** [comment]
It looks like your data-points for the line series are not properly converted dates. I guess

    lineseries.Points.Add(new DataPoint(close, close));

should be something like this

    lineseries.Points.Add(new DataPoint(DateTimeAxis.ToDouble(x.QTime), close));

**Comment by 32x0lf** [comment]
Thanks VisualMelon it works now.
