### ISSUE TITLE
Legend should not change color when the series is selected

### ISSUE THREAD

**Issue by Gimly** [oxyplot/oxyplot#176]
For now, the legend changes color when the series is selected, even when just one element of the series is selected.

I think this behavior is relatively strange and disrupts the users. There should at least be an option to remove the behavior.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
