### ISSUE TITLE
Linear axis gridline thickness minimum = default

### ISSUE THREAD

**Issue by keltie** [oxyplot/oxyplot#1761]
Hi, in trying to produce some fine rendered gridlines for a linear axis, it seemed like the minimum gridline thickness being rendered is limited to 1.0. When trying to render a thickness less than 0.5, the gridlines are not rendered at all.

The contrast with a series StrokeThickness is quite clear as it will render finer than the default.

Is it possible that the 0.5 threshold is a rounding thing? ( i.e. > 0.5 = 1.0, < 0.5 = 0.0)

### Steps to reproduce
1. Attempting to render gridlines finer than a thickness of 1.0
MinorGridlineStyle = OxyPlot.LineStyle.Solid, 
MinorGridlineThickness = 0.5,

1. Attempting to render gridlines finer than a thickness of 0.5
MinorGridlineStyle = OxyPlot.LineStyle.Solid, 
MinorGridlineThickness = 0.3,

Nuget package: 2.1.0-Preview1
Platform: Windows Wpf
.NET version: 4.8

### Expected behaviour
1. Gridline rendering to be finer than 1.0
2. Gridline rendering to be finer than 0.5

### Actual behaviour
1. Gridline rendering still equals default of 1.0
2. Gridline rendering not present

**Comment by VisualMelon** [comment]
The default value for the `EdgeRenderingMode` for axes in 2.1 is `PreferSharpness`, which rounds lines to integer canvas values (makes vertical/horizontal lines tidy). For `Series` it is `PreferGeometricAccuracy`, which allows `WPF` to perform the automatic anti-aliasing to produce transparent transparent lines for all geometry (including vertical lines of arbitrary width).

**Comment by keltie** [comment]
Ah... Thanks so much. Not an issue at all, I just didn't read deeply enough! :)
