### ISSUE TITLE
Opacity has no effect on image annotations

### ISSUE THREAD

**Issue by daze507** [oxyplot/oxyplot#1766]
Platform: Windows (windows form)
.NET version: 4.7.2
Oxyplot version: 2.0.0

### Expected behaviour

Setting the opacity property should change the opacity of the ImageAnnotation objects added to a PlotModel.

### Actual behaviour

The opacity is always 1 no matter the what value is set to the Opacity property.
I tried to change it in the ImageAnnotationExamples class of the ExampleLibrary and the same behaviour occurs.

**Comment by VisualMelon** [comment]
The `ColorMatrix` is transforming the 1 column, not the alpha column. PR to follow...
