### ISSUE TITLE
Getting 'OxyPlot.Metro.xr.xml' and 'Generic.xbf' does not exist on compilation, v2014.1.438

### ISSUE THREAD

**Issue by jackp555** [oxyplot/oxyplot#178]
When compiling Windows Store app with v2014.1.438 of OxyPlot.Metro, I get:

1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\AppxPackage\Microsoft.AppXPackage.Targets(1490,9): error APPX0702: Payload file '<SOLUTION_PATH>\packages\OxyPlot.Metro.2014.1.438\lib\NetCore45\OxyPlot.Metro\OxyPlot.Metro\OxyPlot.Metro.xr.xml' does not exist.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\AppxPackage\Microsoft.AppXPackage.Targets(1490,9): error APPX0702: Payload file '<SOLUTION_PATH>\packages\OxyPlot.Metro.2014.1.438\lib\NetCore45\OxyPlot.Metro\OxyPlot.Metro\Themes\Generic.xbf' does not exist.

Looks like "\OxyPlot.Metro\" folder name in the path is incorrectly duplicated

**Comment by selaromdotnet** [comment]
any chance anyone remembers what the fix was? I'm having a similar issue where the folder name is being added and therefore not finding the files to include... If anyone can point me in the direction on how this was fixed I'd really appreciate it!
