### ISSUE TITLE
Display problem when two vertical axis on the same position

### ISSUE THREAD

**Issue by csainc** [oxyplot/oxyplot#180]
Hello,

It is possible to define two vertical axis on the left position or on the right position of the plotview, the two axis are correctly displayed but not the associated titles.
There is only one title displayed, and it is not the correct one.

Best regards

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
