### ISSUE TITLE
Remove target frameworks v4 and v4.5

### ISSUE THREAD

**Issue by BobLd** [oxyplot/oxyplot#1835]
### Feature description
Remove target frameworks v4 and v4.5 so that the project can be build in Visual Studio 2022. From https://docs.microsoft.com/en-gb/dotnet/framework/install/guide-for-developers:
> Starting with Visual Studio 2022, Visual Studio no longer includes .NET Framework components for .NET Framework 4.0 - 4.5.1 because these versions are no longer supported. Visual Studio 2022 and later versions can't build apps that target .NET Framework 4.0 through .NET Framework 4.5.1. To continue building these apps, you can use Visual Studio 2019 or an earlier version.

**Comment by VisualMelon** [comment]
Thanks for reporting this. Do we know what actually happens if you don't have .NET 4.0 installed? I'd have thought it would error for those targets, but should otherwise compile fine (I don't have a machine without .NET 4 so can't test myself at present).

**Comment by BobLd** [comment]
As far as I see, in VS 2022, even with .NET 4.0 and  .NET 4.5 installed, it won't compiled.

I tried to (re)install .NET 4 to make sure I had it, but this is what I get (so I assume it's installed on my machine):
![image](https://user-images.githubusercontent.com/38405645/147384797-5ef1f2e5-f82b-48a9-8412-b468d112f846.png)

**Comment by VisualMelon** [comment]
It'll be the SDK rather than the runtime; I don't know enough about how the toolchains work.

We could address this by making the target conditional (we don't want separate projects) or by dropping them altogether.

**Comment by BobLd** [comment]
I cannot compile the solution at all... and you're right, sorry for that about sdk/runtime. But I think it is now relatively tricky to find the sdk...
![image](https://user-images.githubusercontent.com/38405645/147385186-c44d2400-a0d3-42fe-940c-d8adebb9a747.png)

**Comment by VisualMelon** [comment]
Haha, don't worry about it.

Given the whole sln packs up we'd better do something about that. If we can find a suitable MSBUILD property to work out whether the frameworks are supported or not then a conditional in the projects would be nice; otherwise, it may be time to finally drop .NET 4.

**Comment by BobLd** [comment]
haha I think it's the right time 😄

**Comment by VisualMelon** [comment]
Can we get away with dropping 4.0 and bumping 4.5.1 to 4.5.2 (supported until April I think) for the time being so that VS is happy, and defer any further decisions until a later date?

**Comment by BobLd** [comment]
That sounds good to me. And if it's not too cumbersome, we could also add a reference to net6.0 😄
