### ISSUE TITLE
PointAnnotation doesn't show the Text

### ISSUE THREAD

**Issue by aforoughi1** [oxyplot/oxyplot#1845]
### Steps to reproduce

1. The PointAnnotation works under 2.0 but I it doesn't work under 2.1
For example,

 public void Annotation(MarkerType shape, OxyColor color, double size, string text, DataPoint position)
        {
            var annotation = new PointAnnotation
            {
                Shape = shape,
                Text = text,
                TextColor = color,
                TextHorizontalAlignment = HorizontalAlignment.Center,
                TextVerticalAlignment = VerticalAlignment.Middle,
                TextMargin = 0,
                TextPosition = position,
                FontWeight = FontWeights.Bold,
                Fill = OxyColors.Transparent,
                Stroke = SetTransparency(200, color),
                StrokeThickness = 2,
                Size = size,
                X = position.X,
                Y = position.Y
            };
                
            Model.Annotations.Add(annotation);
        }
2. To Test it , call
   Annotation(MarkerType.Circle, OxyColors.RoyalBlue, 8, "D", new DataPoint(60, 60));

Platform:
.Net 6.0 and WinUI

### Expected behaviour
I expected to see a Circle Marker with Letter D inside. However, I only see a  Circle with No Text. 

If I export it  as below , the pdf is correct

 public static void ExportToPDF(this PlotModel model, Stream stream, float w = 1050, float h = 350)
        {
            OxyPlot.SkiaSharp.PdfExporter pdfExporter =  new OxyPlot.SkiaSharp.PdfExporter { Width = w, Height = h };
            stream.SetLength(0);
            pdfExporter.Export(model, stream);
            stream.Flush();
            stream.Close();
        }

[TSCO.L.PDF](https://github.com/oxyplot/oxyplot/files/8025082/TSCO.L.PDF)
![Screenshot 2022-02-08 151819](https://user-images.githubusercontent.com/48822519/153017411-8485c420-cc2b-4ee8-9525-bffcca7c8f29.png)

**Comment by VisualMelon** [comment]
Which WinUI provision are you using? I didn't think anyone had got around to a 2.1 port, and 2.1 isn't binary compatible with 2.0.

**Comment by aforoughi1** [comment]
I am using https://github.com/HavenDV/H.OxyPlot/
It works very well with minor issues, have ported my UWP app to WinUI.

**Comment by VisualMelon** [comment]
I suspect this may be in an issue with the WinUI provision: as you note, the labels do appear in the rendered PDF through Skia which suggests the core library is be behaving as expected, and I can repro in our winforms provision. It may be best to report over at https://github.com/HavenDV/H.OxyPlot/

We've had issue in the past with incorrect text clipping in various places. Are you able to test whether it occurs with a longer/multi-line piece of text?

**Comment by aforoughi1** [comment]
Thanks for investigating this. I will add an issue under HavenDV. As a workaround, I have used the ImageAnnotation.

The OxyPolt library is great and works for me, however, .Net 6 is required for my other libraries so I will stick to HD till the WinUI release. 

Do you have a time line for WinUI release?

**Comment by VisualMelon** [comment]
No timeline I'm afraid, indeed, I don't think there is any plan for it at all; I'm not committing anything like as much time as I have been to OxyPlot, and I'm not familiar with WinUI so it's not something I'll be looking at.

HavenDV's shared codebase idea is interesting; things like UWP are difficult for some people to test, so it makes it much harder to contribute, which is why they tend to fall behind the core library.

**Comment by VisualMelon** [comment]
See https://github.com/HavenDV/H.OxyPlot/issues/1
