### ISSUE TITLE
TwoColorAreaSeries is not displayed correctly

### ISSUE THREAD

**Issue by aforoughi1** [oxyplot/oxyplot#1848]
Steps to reproduce

 public PlotModel Model { get; private set; } = new PlotModel
        {
            Title = "Hello WinUI 3",
            Axes =
            {
                new LinearAxis { Position = AxisPosition.Bottom },
                new LinearAxis { Position = AxisPosition.Left },
            },
            Series =
            {
                new TwoColorAreaSeries
                {
                    Color = OxyColors.Tomato,
                    Color2 = OxyColors.LightBlue,
                    MarkerFill = OxyColors.Transparent,
                    MarkerFill2 = OxyColors.Transparent,
                    StrokeThickness = 2,
                    MarkerType = MarkerType.Circle,
                    MarkerSize = 3,
                    Points =
                    {
                        new DataPoint(0, 229.96),
                        new DataPoint(15, 248.14),
                        new DataPoint(16, 248.86),
                        new DataPoint(27, 225.35),
                        new DataPoint(22, 216.84),
                        new DataPoint(5, 217.61),
                        new DataPoint(3, 218.82)
                    },
                    Points2 =
                    {
                        new DataPoint(0, 232.5),
                        new DataPoint(8, 242.69),
                        new DataPoint(15, 249.6),
                        new DataPoint(16, 250.19),
                        new DataPoint(27, 227.2),
                        new DataPoint(24, 221.86),
                        new DataPoint(23, 220.83),
                        new DataPoint(4, 220.54),
                        new DataPoint(2, 224.90)
                    },
                }
            }
        };

Platform:
The feature works under 2.0 but I it doesn't work under 2.1

Expected behaviour
![Expected](https://user-images.githubusercontent.com/48822519/153560677-605c30d5-8617-4f51-9a15-b58f65b61bc0.png)

Actual behavior
![Actual](https://user-images.githubusercontent.com/48822519/153560725-02a44348-0a0b-4dab-a95f-a593e8d20eaa.png)

**Comment by VisualMelon** [comment]
I can't repro this with the WPF provision.

May be one to ask over at https://github.com/HavenDV/H.OxyPlot

There were some changes to clipping in 2.1 (mostly removing loads of stuff), and indeed this looks like a mis-placed clipping rectangle to me; that said, the clipping should be the same for both polys as they share the same axes and I don't see anything odd in the H.OxyPlot sources.

<hr />

All that said, area series isn't really designed for non-monotonic data. This shouldn't be difficult to implement as a custom series; linking @https://github.com/oxyplot/oxyplot/issues/1751 as a potential use-case (distinct requirement perhaps being the ability to track the outline); in this case a 'closed' area series would be a simpler solution.

**Comment by HavenDV** [comment]
I don't follow every issue here. Please bring my attention to @HavenDV if you think this is related to my fork.
In this case, the issue is really only on the UWP/WinUI side, I'm still solving it.
You do not need to report it separately, I will write about readiness here

**Comment by HavenDV** [comment]
And I did not find anything similar to this bug in
https://github.com/microsoft/WindowsAppSDK
https://github.com/microsoft/microsoft-ui-xaml
I will try to recreate this bug outside of OxyPlot and create an issue in the WinUI repo.

**Comment by HavenDV** [comment]
While I was building a repro for a WinUI problem, I tried to implement DrawPolygons via a PolyLineSegment. This worked and fixed this issue. The fix will be available on NuGet in 20 minutes.

**Comment by HavenDV** [comment]
I created two issues in the WindowsAppSDK based on research into this issue:
https://github.com/microsoft/WindowsAppSDK/issues/2096
https://github.com/microsoft/WindowsAppSDK/issues/2097

**Comment by VisualMelon** [comment]
@HavenDV thanks for confirming this is WinUI specific; I don't think we can transfer the issue between organisations, so I'll leave this open for the moment; happy to close whenever you're happy for it to be closed.

**Comment by HavenDV** [comment]
Since I applied the workaround with `PolyLineSegment`, for now, I just need confirmation from @aforoughi1 that everything is working. After that, you can close the issue

**Comment by aforoughi1** [comment]
Confirmed.

**Comment by HavenDV** [comment]
Unfortunately, workaround has been found to cause problems that cannot be worked around. I will cancel the fix, for a complete solution to the problem, I will have to wait for a response from Microsoft: https://github.com/microsoft/microsoft-ui-xaml/issues/6716
