### ISSUE TITLE
Hit test exception with async scatterplotting

### ISSUE THREAD

**Issue by bradmartin333** [oxyplot/oxyplot#1851]
### Steps to reproduce

1. Async timer addition of points to a scatter series
2. Furiously click and bring up tracker
3. Coincide clicks with addition of points

Platform:
.NET version:

### Expected behaviour

The click / hit test should be either ignored or handled with a try/catch

### Actual behaviour

Exception regarding the elements in the scatter series changing during the hit test

### Alternate

PlotModel/View has a property to disable hit test to prevent such a behavior or an overridable function

### What I am doing

I disable the PlotView before adding a point and enable after adding the point. Open to finding bugs in my own code.

**Comment by VisualMelon** [comment]
You should lock the `PlotModel.SyncRoot` when updating series: this is a problem for update and rendering also, not just hit-testing. This ensures that operations which need access to the data are serialised and should prevent any such issues.

Note that you can disable hit-testing by overriding `PlotModel.HandleMouseDown`; it's not nice, but it might help your scenario if it is a performance concern.

**Comment by bradmartin333** [comment]
> You should lock the `PlotModel.SyncRoot` when updating series: this is a problem for update and rendering also, not just hit-testing. This ensures that operations which need access to the data are serialised and should prevent any such issues.

Okay, I will try this out:

 `lock (PlotModel.SyncRoot)
  {
      // add points
  }`

> Note that you can disable hit-testing by overriding `PlotModel.HandleMouseDown`; it's not nice, but it might help your scenario if it is a performance concern.

This was my first attempt, but I wasn't able to get a working override.

**Comment by bradmartin333** [comment]
Amazing - thank you so much for your help!

The locker worked perfectly even with using the tracker.
Knowing how to utilize the PlotController is a great tool as well, so thanks again!

Case closed
