### ISSUE TITLE
Legends are overlapping each other

### ISSUE THREAD

**Issue by minusium** [oxyplot/oxyplot#1859]
Platform: Windows
.NET version: 6.0

![image](https://user-images.githubusercontent.com/21140798/155838350-c9752f12-3fbb-4b36-a593-cebe87446e4e.png)

This is my code:
```cs
        private Dictionary<int, long[]> _data = new();
        private List<string> _columns = new();
...
            var plotModel = new PlotModel();
            plotModel.Axes.Add(new LinearAxis
            {
                Key = "size",
                Position = AxisPosition.Bottom,
                Title = "Size",
                MajorGridlineStyle = LineStyle.Dash,
            });
            plotModel.Axes.Add(new LinearAxis
            {
                Key = "time",
                Position = AxisPosition.Left,
                Title = "Time",
                Unit = "Ticks",
                MajorGridlineStyle = LineStyle.Dash,
            });

            for (int i = 0; i < _columns.Count; i++)
            {
                plotModel.Legends.Add(new Legend
                {
                    Key = _columns[i],
                    LegendTitle = _columns[i],
                    LegendPosition = LegendPosition.TopCenter,
                    LegendPlacement = LegendPlacement.Outside,
                    LegendOrientation = LegendOrientation.Horizontal,
                });

                var series = new LineSeries
                {
                    Title = _columns[i],
                    LegendKey = _columns[i],
                    XAxisKey = "size",
                    YAxisKey = "time",
                    ItemsSource = _data.Select(row => new DataPoint(row.Key, row.Value[i])).ToArray(),
                };
                plotModel.Series.Add(series);
            }

            var exporter = new SvgExporter { Width = 1920, Height = 1080, };
            exporter.ExportToFile(plotModel, fileName);
```

**Comment by minusium** [comment]
Result should be like this. It's not rendering legends by default and document is under construction so I don't know what should I do.

![image](https://user-images.githubusercontent.com/21140798/155838678-45573d07-98e1-4e2b-89c3-1f02e04595dc.png)

**Comment by VisualMelon** [comment]
Yes, you need to use a single `Legend`, which can display multiple series.

The closest example we have to your first image is here: https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Examples/LegendExamples.cs#L52-L68

![image](https://user-images.githubusercontent.com/5646475/155838880-08fdbb91-f73b-495a-9148-740314214fa3.png)

You'd just need to change the position to `BottomCenter`.

**Comment by minusium** [comment]
Thanks, I thought I have to create a legend for each data series. this fixed my problem:
![image](https://user-images.githubusercontent.com/21140798/155838927-f1e6cad5-9e26-4a6e-97a8-e5da67569b2f.png)

Btw I have another problem with svg exporter and I don't know if it's me or library, should I create another issue?
![image](https://user-images.githubusercontent.com/21140798/155838946-2a1c9201-d35a-4b57-819e-45621f5a2eb7.png)

**Comment by VisualMelon** [comment]
Yes, please open another issue: be sure to provide details on which SvgExporter (there have been a number through the years) and which version you are using.

That said, check that you are truncating the output file before you export to it (i.e. either delete it explicitly, or make sure when you open it that you are opening in a way that truncates it (e.g. `FileMode.Create`): this issue commonly occurs when you output to a file that has previously been written, so it's probably just that.

**Comment by minusium** [comment]
> this issue commonly occurs when you output to a file that has previously been written, so it's probably just that.

That was the case! Thanks.
