### ISSUE TITLE
ColumnSeries label angle (data overlapped)

### ISSUE THREAD

**Issue by Dimigergo** [oxyplot/oxyplot#1870]
As you can see the image the column bar label is shown, but overlapped with each other.

![columnseries](https://user-images.githubusercontent.com/11498949/159490238-e354e39b-37f9-490a-a59c-b4a4d69e6b8d.png)

The following code is used:
```
new ColumnSeries
{
    Title = serieName,
    StrokeThickness = 1,
    XAxisKey = categoryName,
    FillColor = this.PlotModel.DefaultColors[colorIndex],
    Tag = serieName,
    LabelPlacement = LabelPlacement.Outside,
    LabelFormatString = "{0}"
};
```

Is it possible to rotate these labels, or is it possible to make a fix for me?
I use Oxyplot.Windows (UAP10) 1.0.0 with ColumnSeries and OxyPlot WPF 2.1 with BarSeries (switched X Y axis, because ColumnSerie is removed)

Thanks in advance!

**Comment by Dimigergo** [comment]
Ping.

**Comment by VisualMelon** [comment]
I don't think rotated labels on `BarSeries` is supported, but it's certainly something that could be done relatively simply. I'm really busy these days, so I'm afraid I won't have time to work on this.

**Comment by blogcraft** [comment]
Why I can't find ColumnSeries in 2.1.2?

**Comment by VisualMelon** [comment]
It was removed at some point. Use a `BarSeries` and set the `XAxisKey` and `YAxisKey` accordingly to determine the orientation of the plot.

**Comment by blogcraft** [comment]
> It was removed at some point. Use a `BarSeries` and set the `XAxisKey` and `YAxisKey` accordingly to determine the orientation of the plot.

Thanks a lot! 😊 It would be nice to update the docs to avoid confusion.

**Comment by VisualMelon** [comment]
Yes... I really must do that at some point

**Comment by Aschelde** [comment]
I am trying to use the BarSeries for a vertical bar chart and set the XAxisKey and YAxisKey accordingly, but I run into the error: 'BarSeries requires a CategoryAxis on the Y Axis'. Any help would be appreciated!

**Comment by VisualMelon** [comment]
@Aschelde `BarSeries` - as the error says - demands a `CategoryAxis` on the YAxis: it won't work with e.g. `LinearAxis` for both axes. If you are using a `CategoryAxis` and still facing issues, please could you provide a reproducing example/snippet in new Issue.

**Comment by alexkivikoski** [comment]
We are looking for a solution on the overlapping labels too (on BarSeries). Any suggestions?

**Comment by bytesolo** [comment]
This question took up an entire afternoon of my time. Since ColumnSeries has been removed, a complete BarSeries alternative should be provided, with clear "YAxisKey=" y1 "and" XAxisKey="x1" information in the documentation or exceptions. I hope developers can take this issue seriously. Although there is only one line of code, it is enough to kill many programmers'  a beautiful afternoon.
