### ISSUE TITLE
maui support

### ISSUE THREAD

**Issue by softminer** [oxyplot/oxyplot#1888]
### Feature description
Hello,will oxyplot support maui from microsoft?

**Comment by VisualMelon** [comment]
Sorry this Issue was neglected: no plan at present.

Closing, as the same request is discussed in #1958

**Comment by janusw** [comment]
FYI, I have published a first version of OxyPlot.Maui.Skia on nuget.org:
https://www.nuget.org/packages/OxyPlot.Maui.Skia

Would be great if people could try it and give some feedback (please open an issue at https://github.com/oxyplot/oxyplot-maui if something does not work).

For now it only supports .NET 7, but I plan to do some updates and include .NET 8 support soon.
