### ISSUE TITLE
0 < double.Epsilon checks return false

### ISSUE THREAD

**Issue by pantosh** [oxyplot/oxyplot#1924]
Several expressions in OxyPlot make a zero value check using the idiom: `value < double.Epsilon`.
For example the range check in CalculateActualInterval in Axis.cs

The problem is that `0 < double.Epsilon` is not a safe comparison in .NET. It may evaluate to false, if double.Epsilon is expressed as 0 by the compiler.
The consequence in Axis.CalculateActualInterval is that it gets stuck in an infinite while(true) loop later in the method.

```
            // This is the actual code. It does not throw if range == 0
            if (Math.Abs(range) < double.Epsilon)
            {
                throw new ArgumentException("Range cannot be zero.", "range");
            }

            // This does not throw either
            if (range < double.Epsilon && range > -double.Epsilon)
            {
                throw new ArgumentException("Range cannot be zero.", "range");
            }

               // This throws!!!
            if (range == 0)
            {
                throw new ArgumentException("Range cannot be zero.", "range");
            }
```

The issue is observed with Visual Studio Pro 2022 17.2.6 using an x64 build, target .NET 4.8.

Setting ActualMaximum to ActualMinimum and forcing a CalculateActualInterval will reproduce the issue.
ActualMaximum / ActualMinimum needs to be set indirectly, not quite sure how. Perhaps Zoom(0) will do the trick.

Suggestion:
Change all `value < double.Epsilon` to simply `value == 0` or at least `value <= double.Epsilon`

The `value < double.Epsilon` idiom occurs several places in the codebase.

### Steps to reproduce

1. Setting ActualMaximum to ActualMinimum and forcing a CalculateActualInterval will reproduce the issue.
ActualMaximum / ActualMinimum needs to be set indirectly, not quite sure how. Perhaps Zoom(0) will do the trick.

Platform:
.NET version: 4.8

### Expected behaviour

Exception thrown for range == 0

### Actual behaviour

Oxyplot gets stuck in infinite loop.

**Comment by VisualMelon** [comment]
> if double.Epsilon is expressed as 0 by the compiler.

This is a new one for me! Can you throw us some documentation on this possibility?

In any case, checking against zero directly would seem sensible.

**Comment by VisualMelon** [comment]
Looks like it's an issue on ARM at least: https://docs.microsoft.com/en-us/dotnet/api/system.double.epsilon?view=net-6.0#platform-notes

**Comment by pantosh** [comment]
The issue occurred on a standard Windows 10 Intel Core i7 in an x64 specific build.
The double.Epsilon constant is presumably rounded to 0 somewhere in the compile pipeline. This does contradict The MS documentation: https://docs.microsoft.com/en-us/dotnet/api/system.double.epsilon?view=net-6.0 which clearly states:

"
The value of the Epsilon property reflects the smallest positive Double value that is significant in numeric operations or comparisons when the value of the Double instance is zero. For example, the following code shows that zero and Epsilon are considered to be unequal values....
"

However, they also write:

"
If you create a custom algorithm that determines whether two floating-point numbers can be considered equal, we do not recommend that you base your algorithm on the value of the Epsilon constant to establish the acceptable absolute margin of difference for the two values to be considered equal.
"

Anyway. The observation is clear: `range < double.Epsilon` can evaluate to false for range == 0.
The solution is trivial. Either simply use `range == 0` or `range <= double.Epsilon`.

Should I make a Pull Request for this?

**Comment by VisualMelon** [comment]
That does sound like a bug rather, but I agree it's odd anyway, and clearly an issue on ARM in any case.

Most literal fix would be `x < double.Epsilon || x == 0`, which will hopefully be equivalent to `x <= 0`, so I'd say go with that (though instances like `if (Math.Abs(u2) < double.Epsilon)` can just be `== 0`). A PR would be most welcome.

This also suggests that the fix for the crazy rendering of HistogramSeries in #1886 will need revising.

**Comment by pantosh** [comment]
Interestingly I found this comment in Quaternion:
```
            // Check if axis vector is undefined (close to zero in length)
            // double.Epsilon cannot be used. It turns out that the results are
            // not deterministic for different CPU architectures.
```
so, this was actually a known issue in the codebase.

**Comment by pantosh** [comment]
I have seen double.Epsilon being mis-interpreted in several other projects as well.
It is commonly misunderstood as "something epsilon larger than the floating point truncation error" and then used to compare if a value that has been through some operations is equal to some value that should be equal in a mathematical sense.

However, this is not the correct use of double.Epsilon. It is merely the bit pattern that represents the smallest possible floating point value of a given bit size. Frankly, I can't think of many if any practical usages of double.Epsilon, since you cannot trust if the CPU-architecture will truncate it to zero. 

```
            var zero = 0.0;
            var epsilon = double.Epsilon;
            var oneZero = 1.0 / zero;
            var oneEpsilon = 1.0 / epsilon;
            var smallerThanEpsilon1 = 0.0 < double.Epsilon;
            var smallerThanEpsilon2 = zero < double.Epsilon;
            var smallerThanEpsilon3 = Math.Abs(zero) < double.Epsilon;
            TestContext.WriteLine(oneZero);
            TestContext.WriteLine(oneEpsilon);
            TestContext.WriteLine(smallerThanEpsilon1);
            TestContext.WriteLine(smallerThanEpsilon2);
            TestContext.WriteLine(smallerThanEpsilon3);
```
In an "Any" architecture this produces:
```
∞
∞
True
True
True
```

If I change the architecture to x64:
```
∞
∞
True
False
False
```

**Comment by pantosh** [comment]
My suggestion is to get rid of all double.Epsilon usages in the code. I did do that initially, but then I ren into this in HistogramSeries.cs:
```
                if (this.YAxis.IsLogarithmic())
                {
                    this.MinY = Math.Max(this.ActualItems.Min(r => r.Height), double.Epsilon);
                    this.MaxY = Math.Max(this.ActualItems.Max(r => r.Height), double.Epsilon);
                }
```

It looks a bit like double.Epsilon is used as some kind of non-zero marker. I don't know the intent of this, but I worry that replacing Epsilon with 0 will break something on some platforms.

**Comment by VisualMelon** [comment]
I thought those days were behind us (IEEE-754 saturation and all that) but clearly not.

Re mis-use, it doesn't help that epsilon is traditionally defined differently in e.g. C++.

Re. histogram, yep: that will break, and that needs to be reviewed, but I'm happy to look at that separately since it's not going to be a systematic change (feel free to ignore it for any PR)

**Comment by VisualMelon** [comment]
Is this some nonsense to do with unnormalized float support having particularly bad performance on some architectures? I'm struggling to work out why this should be a problem on any .NET supported architecture (not contesting that it is; just a bit disturbed by your discovery).

<hr />

Yeah, sounds like there are no guarantees there: https://stackoverflow.com/questions/22915543/how-are-denormalized-floats-handled-in-c ; looks like it's just not feasible to ensure either way, so we get the worst of both worlds.

**Comment by pantosh** [comment]
Regarding PR it says that:
- [ ] I have included examples or tests
- [ ] I have updated the change log
- [ ] I am listed in the CONTRIBUTORS file

I have neither. Tests are difficult to make for an architecture quirk like this and the checks are rather deep down in the oxyplot rendering tree, so I wouldn't know how to set up a simple unit test.

I am also not aware on how to update the change log and I am not in the contributors file.

**Comment by VisualMelon** [comment]
Don't worry about examples for this; I'm happy if you're able to check this fixes the issue for you (i.e. existing examples suffice).

You can see examples for the change log and contrib files in this PR: https://github.com/oxyplot/oxyplot/pull/1883/files

And don't worry about squashing either; we can do that.

**Comment by pantosh** [comment]
Unrelated, but while investigating this I found a strinky performance bug too.
DataPointSeries.GetItems ignores cached item source points.
This means, that if an item source is used then every mouse movement will result in a complete re-generation of all points in the data source. This can be quite expensive.
The fix is simple. It is just a removal of an itemssource check.

Should I make an issue and PR for this too?

**Comment by VisualMelon** [comment]
Yes, feel free to open a new issue for anything like that.
