### ISSUE TITLE
SkiaSharp: LineDashStyle.DotPause crashes the renderer

### ISSUE THREAD

**Issue by zotrb** [oxyplot/oxyplot#1929]
### Steps to reproduce

1. Set LineDashStyle.DotPause on a series
2. Render the chart

Platform:
.NET version: 6.0 windows

### Expected behaviour
The series should render

### Actual behaviour
Oxyplot reports "The intervals must have an even number of entries (Parameter 'intervals')"
at SkiaSharp.SKPathEffect.CreateDash(Single[] intervals, Single phase)
![image](https://user-images.githubusercontent.com/75790147/187410099-c46158d6-35f1-4340-8ca2-b96b5ec87592.png)

**Comment by VisualMelon** [comment]
I don't think `DotPause` is part of the core library; `Dot` works OK for me (and all default line styles have an even number of intervals)

Are you using a custom build of the library?

**Comment by zotrb** [comment]
Ah, my apologies. I didn't spot that this has been overridden in a custom library in our project :-)
 
The dash pattern has an odd number of entries. Looks like it works (or at least, renders without throwing an exception) in the WPF renderer (2.1) but not in the SkiaSharp renderer. I don't know if that would be considered a bug though.

I can resolve it on my side by removing the unsupported dashes.

**Comment by VisualMelon** [comment]
I think since this isn't really an extension point in the library that it can't be considered a bug at present; however, it could be made extensible as a new feature and it would be important to document/detect this in that case.

I think we can assume the Skia behaviour is by-design given the exception.

**Comment by zotrb** [comment]
Sure. No worries.
Thanks for the quick response :-)
