### ISSUE TITLE
Remove Weekends from DateTime Axis

### ISSUE THREAD

**Issue by a-hart** [oxyplot/oxyplot#193]
When plotting daily stock data for series. It would be nice if the datetime axis would filter out weekends, so the candlestick series is continuous instead of having spaces between each week.

This causes problems when adding any linear series to the chartPlot as well.(e.g. moving averages)
![datetimeaxis](https://cloud.githubusercontent.com/assets/3454671/4366434/dc1e1d74-42be-11e4-96ab-ed2b903f8304.png)
![datetimeaxis2](https://cloud.githubusercontent.com/assets/3454671/4366435/dc1f9302-42be-11e4-8c09-e0fcd245fc1d.png)

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
