### ISSUE TITLE
Oxyplot doesn't build on fresh VS2022 install (net452 targeting pack can no longer be installed by VS installer)

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#1938]
I just stumbled across this problem while trying to build oxyplot for the first time on a fresh Windows install.
You can apparently no longer select the .NET 4.5.2 targeting pack in the VS installer (see screenshot below). Therefore it is not possible to build oxyplot without going through extra hoops (download the SDK from [here](https://dotnet.microsoft.com/en-us/download/visual-studio-sdks)).

![image](https://user-images.githubusercontent.com/18097859/191055053-50bc506c-0c4d-44b6-b7c7-3c5b752a8313.png)

I think we should consider upgrading all projects to at least .NET 4.6.2.

**Comment by VisualMelon** [comment]
Agreed. After #1937 goes through, let's bump everything to 4.6.2, add net6 everywhere, and then remove net core 3.1 in December when it's EOL.
