### ISSUE TITLE
LineSeries: Data sources in different ranges (for example, 0-10, 0-100) are displayed in the same range

### ISSUE THREAD

**Issue by ChineseK** [oxyplot/oxyplot#1939]
At present, it is realized by zooming in or data source, but you want to click the left mouse button to display the original data
picture 1 Data not magnified
![1](https://user-images.githubusercontent.com/25895423/191178781-e6fb4e79-eab2-4c15-9935-a3632465a9bb.png)
picture 2 Data  magnified
![2](https://user-images.githubusercontent.com/25895423/191178850-4f263df4-6fdd-491d-bde4-b494be23536c.png)

**Comment by VisualMelon** [comment]
Sorry, I'm not sure what you mean: can you elaborate further?

Are you saying that you'd expect the series in the top picture to both fill the extents of the plots (i.e. scaled regardless of the axis), but to be able to track the actual value with the mouse (i.e. display the true value, not the scaled value)?

Perhaps https://github.com/oxyplot/oxyplot/issues/1450 is related

**Comment by ChineseK** [comment]
thank you ,I try to learn more

**Comment by ChineseK** [comment]
> 抱歉，我不确定您的意思：您能进一步详细说明吗？
> 
> 您是说您希望上图中的系列既能填充绘图的范围（即无论轴如何都缩放），但能够用鼠标跟踪实际值（即显示真实值，不是缩放值）？
> 
> 或许#1450相关

Your understanding is correct, but I haven't filtered the relevant information. I'm a beginner. Can you give me more suggestions
