### ISSUE TITLE
Add support for Dot Net MAUI

### ISSUE THREAD

**Issue by akshayjain692** [oxyplot/oxyplot#1958]
Please add support for MAUI

**Comment by VisualMelon** [comment]
There has been work recently to revive the Xamarin provision; perhaps this could be built from that.

I personally will not likely work on this, as I have no use at the moment for MAUI and no experience with Xamarin.

**Comment by janusw** [comment]
> There has been work recently to revive the Xamarin provision; perhaps this could be built from that.

Yes, I'd certainly like to move OxyPlot.Xamarin.Forms towards MAUI at some point. This issue should be raised in the oxyplot-xamarin project.

> I personally will not likely work on this, as I have no use at the moment for MAUI and no experience with Xamarin.

I hope to work on it sometime next year (if I find the time for it). I won't give any promises, though ;)

**Comment by Hackmodford** [comment]
[This is a really good start](https://github.com/iniceice88/OxyPlot.Maui.Skia). Maybe this could be made official?

**Comment by janusw** [comment]
> [This is a really good start](https://github.com/iniceice88/OxyPlot.Maui.Skia). Maybe this could be made official?

Haven't tried it yet, but yes, looks like a good starting point. 👍 

@objorke @VisualMelon  Could we move https://github.com/iniceice88/OxyPlot.Maui.Skia into the oxyplot organization?

@iniceice88 Would this be ok with you?

**Comment by objorke** [comment]
I suggest a new oxyplot-maui repo if build/release cycle is different from the other supported platforms

**Comment by janusw** [comment]
> I suggest a new oxyplot-maui repo if build/release cycle is different from the other supported platforms

Yes, I think it should stay in a separate repo, and I'd hope that @iniceice88 would continue to act as a maintainer. I could probably help a bit with that, and we could at some point publish an 'official' nupkg to nuget.org.

The oxyplot maintainers seem to agree. So, @iniceice88, if you agree with this plan as well, you could initiate the transfer of the repo by going to the general settings of your repo, scroll all the way down to the "danger zone", select "Transfer ownership" and then "Specify an organization or username", enter "oxyplot" (for the oxyplot organization) and confirm the transfer.

Then @objorke or @VisualMelon could invite you, @iniceice88, to become a member of the organization, and give the two of us the necessary permissions for maintaining the repo, and we continue from there. 😃

**Comment by janusw** [comment]
> > [This is a really good start](https://github.com/iniceice88/OxyPlot.Maui.Skia). Maybe this could be made official?
> 
> Haven't tried it yet, but yes, looks like a good starting point. 👍

Just tried it now: The library and the sample build cleanly, and the sample app (with example browser) runs well on MacOS. Haven't tried other platforms.

Some to-do items that I can see:
* Add GitHub Actions integration with automatic builds (and nupkg generation).
* Publish a first experimental nupkg.
* Update to .NET 7 (and 8!).
* Update the SkiaSharp version.
* etc ...

I can help with some of these, but I'd suggest to move the repo into the oxyplot org first.

**Comment by janusw** [comment]
> > Haven't tried it yet, but yes, looks like a good starting point. 👍
> 
> Just tried it now: The library and the sample build cleanly, and the sample app (with example browser) runs well on MacOS. Haven't tried other platforms.

FYI: I also verified that the sample app works nicely on Android. I could not get it to run on iOS 17 (but I assume that will be solved by moving to .NET 7). So, overall this looks like pretty solid work to me 👍

**Comment by Hackmodford** [comment]
FYI I’m currently using a fork of the project in an iPad app that is running on iOS 17.

**Comment by janusw** [comment]
> FYI I’m currently using a fork of the project in an iPad app that is running on iOS 17.

Good to know. I'm pretty sure this will only work with .NET 7, though, and your fork doesn't seem to have .NET 7 support, so I assume you're using some other fork.

Out of the six forks of the project, three(!) seem to have added .NET 7 support (independent of each other), and none of them even cared to open a PR and upstream the change. That is exactly one of the reasons why I suggested to move the project into the oxyplot organization: To have a sinlge well-maintained repository with a consistent development process instead of dead-forking the project. I really hope @iniceice88 will agree with my proposal.

**Comment by Hackmodford** [comment]
> > FYI I’m currently using a fork of the project in an iPad app that is running on iOS 17.
> 
> Good to know. I'm pretty sure this will only work with .NET 7, though, and your fork doesn't seem to have .NET 7 support, so I assume you're using some other fork.
> 
> Out of the six forks of the project, three(!) seem to have added .NET 7 support (independent of each other), and none of them even cared to open a PR and upstream the change. That is exactly one of the reasons why I suggested to move the project into the oxyplot organization: To have a sinlge well-maintained repository with a consistent development process instead of dead-forking the project. I really hope @iniceice88 will agree with my proposal.

You're right. I drag/dropped the project into my solution and then modified the csproj file to support .net 8.

**Comment by iniceice88** [comment]
> @objorke @VisualMelon Could we move https://github.com/iniceice88/OxyPlot.Maui.Skia into the oxyplot organization?
> 
> @iniceice88 Would this be ok with you?

It is okay with me to move the OxyPlot.Maui.Skia repository into the OxyPlot organization.
However, unfortunately, I don't have enough  time to maintain it. I hope someone can take over for me.

This repository was simply migrated from [OxyPlot.Xamarin.Skia](https://github.com/iniceice88/OxyPlot.Xamarin.Forms.Skia) and implemented using the third-party library SkiaSharp. As an official implementation of MAUI, I believe that using the [Microsoft.Maui.Graphics](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/) is a better approach.

To-dos:
- iOS,macOS not tested
- macOS pan/zoom support [issues#4](https://github.com/iniceice88/OxyPlot.Maui.Skia/issues/4)

**Comment by janusw** [comment]
> > @objorke @VisualMelon Could we move https://github.com/iniceice88/OxyPlot.Maui.Skia into the oxyplot organization?
> > @iniceice88 Would this be ok with you?
> 
> It is okay with me to move the OxyPlot.Maui.Skia repository into the OxyPlot organization.

Very good, thanks for the reply, @iniceice88.

> However, unfortunately, I don't have enough time to maintain it. I hope someone can take over for me.

That is one more reason for moving it indeed :)

I can certainly help, at least with the initial CI setup, publishing a nupkg and some fixes. I'm not sure if I have the time for full maintainership in the long run. In any case, if the project is under the umbrella of the oxyplot org, it will be easier to share maintainership and get other people into the boat.


> This repository was simply migrated from [OxyPlot.Xamarin.Skia](https://github.com/iniceice88/OxyPlot.Xamarin.Forms.Skia) and implemented using the third-party library SkiaSharp. As an official implementation of MAUI, I believe that using the [Microsoft.Maui.Graphics](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/graphics/) is a better approach.

Possibly. OTOH, Skia(Sharp) is a pretty popular and well-maintained project, and for my taste it might be ok to stick with it.

Anyway, for the start, everybody will be happy with anything that works I guess. 😆 

> To-dos:
> 
>     * iOS,macOS not tested

As written above, I skimmed over the sample app on MacOS and it mostly looked alright. There might be some problems lurking in the details, though (needs to be checked).

iOS (v17) will require .NET 7 (or 8) support. That is one of the first things we should add (shouldn't be hard).

**Comment by janusw** [comment]
> The oxyplot maintainers seem to agree. So, @iniceice88, if you agree with this plan as well, you could initiate the transfer of the repo by going to the general settings of your repo, scroll all the way down to the "danger zone", select "Transfer ownership" and then "Specify an organization or username", enter "oxyplot" (for the oxyplot organization) and confirm the transfer.

@iniceice88 Could you please follow these steps? I think an oxyplot maintainer (@objorke or @VisualMelon) needs to approve the transfer after you have requested it.

**Comment by iniceice88** [comment]
@janusw  I encountered the following error message:

**You don’t have the permission to create public repositories on oxyplot**

**Comment by janusw** [comment]
> @janusw I encountered the following error message:
> 
> **You don’t have the permission to create public repositories on oxyplot**

Ah, so probably an oxyplot admin first needs to give you permissions to create a repo in the org. I cannot do that, and I also cannot create repos there myself. @objorke @VisualMelon Could you help here?

**Comment by iniceice88** [comment]
@objorke @VisualMelon Maybe you can create a new repository from my souce code, and after that, I will archive my repository.

**Comment by VisualMelon** [comment]
I've created https://github.com/oxyplot/oxyplot-maui and pushed a copy of your repo; @janusw I can't properly test or audit the Maui code: are you happy to 'own' this work in that regard?

**Comment by VisualMelon** [comment]
@iniceice88 thanks for contributing this work.
We can consider re-naming with regards to skia/not skia; until a 'native' implementation exists I think calling it oxyplot-maui is OK.

**Comment by janusw** [comment]
> I've created https://github.com/oxyplot/oxyplot-maui and pushed a copy of your repo;

Great, thanks. In contrast to moving the repo, the copy created this way does not include the issues/PRs from the original repo, but of course we can just duplicate the open issues in the new repo.


> @janusw I can't properly test or audit the Maui code: are you happy to 'own' this work in that regard?

Yes, I'll test some more and will add a couple of improvements (see my to-do list above).

**Comment by janusw** [comment]
Since we have a Maui repo in the oxplot org now, I'll close this issue. All further problems regarding the MAUI port should be discussed in the new repo.

@iniceice88 @VisualMelon Thanks for your support here.

@iniceice88 Maybe you can add a deprecation notice to the ReadMe of your repo (with a link to https://github.com/oxyplot/oxyplot-maui)? Thanks.

**Comment by janusw** [comment]
> > I've created https://github.com/oxyplot/oxyplot-maui and pushed a copy of your repo;
> > @janusw I can't properly test or audit the Maui code: are you happy to 'own' this work in that regard?
> 
> Yes, I'll test some more and will add a couple of improvements (see my to-do list above).

@VisualMelon Could you please give me (and @iniceice88) write permissions for the new repo (so that we can commit changes and merge PRs)?

**Comment by VisualMelon** [comment]
@janusw I've made you a maintainer on the repo.

@iniceice88 I won't give you write permission for the time being because you're not an existing member and don't have a history with the oxyplot organisation as a whole, as it were: obviously we'll be happy to merge PRs and keen to get your input on issues. Invited you as a 'triage' collaborator in the meantime.

If @objorke is happy with adding you to the organisation etc. then I'm happy, and can sort out the permissions accordingly

**Comment by VisualMelon** [comment]
@janusw we can try moving the repo if there's a way to do that which doesn't require weird permissions

**Comment by janusw** [comment]
> @janusw we can try moving the repo if there's a way to do that which doesn't require weird permissions

Nevermind. We have a repo now (even it hasn't brought along all assets from the old one), and I think that's good enough. Thanks again for your support!

**Comment by iniceice88** [comment]
> @iniceice88 Maybe you can add a deprecation notice to the ReadMe of your repo (with a link to https://github.com/oxyplot/oxyplot-maui)? Thanks.

@janusw I have archived my repo, and the README now points to the official repo.

**Comment by janusw** [comment]
FYI, I have published a first version of OxyPlot.Maui.Skia on nuget.org:
https://www.nuget.org/packages/OxyPlot.Maui.Skia

Would be great if people could try it and give some feedback (please open an issue at https://github.com/oxyplot/oxyplot-maui if something does not work).

For now it only supports .NET 7, but I plan to do some updates and include .NET 8 support soon.
