### ISSUE TITLE
Extra tick on CategoryAxis

### ISSUE THREAD

**Issue by goremykin** [oxyplot/oxyplot#1971]
### Steps to reproduce

1. Create a plot with CategoryAxis as X and LinearAxis as Y. Specify the MajorStep for the CategoryAxis
2. Check ticks on the CategoryAxis 

Platform: Windows
.NET version: 6

### Expected behaviour
As I have 24 items and step = 4, I don't expect the "empty" tick in the end

### Actual behaviour
There is an extra tick
![image](https://user-images.githubusercontent.com/25577658/210061511-a4d02c78-be5c-473c-8e94-9b4758036020.png)

You can find plot model here (it has a lot of additional settings, but the bug is reproducible without them):
https://github.com/goremykin/oxyplot-example/blob/main/WinFormsApp1/Form1.cs

Also you can just clone and run this app:
https://github.com/goremykin/oxyplot-example

Minor: additionally I would like to draw your attention to the margin at the left side of the plot. There is no margin at the right side and at the bottom, but there is small margin at the left side.

**Comment by VisualMelon** [comment]
Reproduced weird tick with 2.1.2, 2.1.0, and 2.0.0

Picture with 2.0.0 has the same empty tick but no margin on the left.
![image](https://user-images.githubusercontent.com/5646475/210064903-527231fd-bc2b-466b-a43c-f397e9a5647d.png)

The margin should be there (it is expected): it is included to ensure that a tick label on the very edge of the plot is rendered correctly. It is there on the right as well, but it is smaller than the margin for the right-hand axis, so is not apparent.

You can remove the margin manually by overriding the left-hand plot margin in your `PlotView`:

    PlotMargins = new OxyThickness(0, double.NaN, double.NaN, double.NaN)

The current behaviour may not be desirable for `CategoryAxis` specifically.

**Comment by goremykin** [comment]
@VisualMelon, Yep, I already tried to specify PlotMargins like you wrote, but depending on the plot width it can cut the label at the left side :(
In any case this margin is not a big problem
![image](https://user-images.githubusercontent.com/25577658/210066201-03225579-48e4-42e0-8d0e-7a38969745d9.png)

**Comment by VisualMelon** [comment]
Created branch with example where it goes wrong and candidate fix: https://github.com/VisualMelon/oxyplot/tree/Issue1971

Problematic code is https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/CategoryAxis.cs#L114-L118

Looks like we just need to change the `+ 1` to `+ MajorStep` but will need to test that properly etc. though I don't have time to do that right now.

`GetTicks` is an overridable method, so you should be able to patch this locally as it will probably be while before another release. Let me know if you want any help with this.

**Comment by goremykin** [comment]
@VisualMelon, You are my lifesaver, now it looks nice
![image](https://user-images.githubusercontent.com/25577658/210070129-5bbbc33e-06da-440c-b06b-9573379ddb9b.png)

**Comment by VisualMelon** [comment]
If you are overriding `GetTickValues` already, then you conditionally remove the last tick. You can remove ticks that are outside the data-range by conditioning against the `DataMinimum` and `DataMaximum`, something like:

    majorTickValues = majorTickValues.Where(x => x >= this.DataMinimum && x < this.DataMaximum).ToList();
