### ISSUE TITLE
Disappear Background in PngExporter

### ISSUE THREAD

**Issue by MoritaMasaki** [oxyplot/oxyplot#1978]
### Steps to reproduce

1. Get OxyPlot.Wpf(2.1.2) from Nuget  
2. Write "OxyPlot.Wpf.PngExporter.Background"

Platform:
.NET version: .NET 6.0

### Expected behaviour

Get or Set the Background property

### Actual behaviour

No define the Background property.
Previous version has the Background.

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by VisualMelon** [comment]
Use the `PlotModel.Background` property instead: the properties on the exporters were removed because they were redundant and weren't entirely consistent between all the exporters.

**Comment by VisualMelon** [comment]
Closing; feel free to re-open if the above doesn't address your concern.
