### ISSUE TITLE
How to get the the screen point of certain point on the oxyplot axis

### ISSUE THREAD

**Issue by micheldauros** [oxyplot/oxyplot#1986]
Hello, I want to get the screen point of certain point (like the origin) on the oxyplot axis in order to draw some graphs(on a seperated canvas) ouside of the plotarea. Anyone can help?
Platform:
.NET version:
WPF
Oxyplot.wpf Version 2.1.2

**Comment by VisualMelon** [comment]
Take a look at the `OverlayExample` from the WPF Examples: https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/WPF/WpfExamples/Examples/OverlayDemo/MainWindow.xaml.cs#L59-L60

This shows up to maintain a WPF element in alignment with a pair of axes. The specific method to get a `ScreenPoint` from a `DataPoint` is the `Transform` method, which exists on `Axis`.

**Comment by micheldauros** [comment]
@VisualMelon Thanks for your reply, though I found it is always (0,0) in the initializing phase of the plotview. I finally get the correct coordinates in Loaded event.

**Comment by VisualMelon** [comment]
Closing as hopefully solved: feel free to reopen is you still have problems with it.
