### ISSUE TITLE
Upgrade Oxyplot from 2.0.0 to 2.1.2 in a WPF-Application

### ISSUE THREAD

**Issue by GeFiBDG** [oxyplot/oxyplot#1989]
Hello, 
until today we used OxyPlot.WPF version 2.0.0. 
Now we wanted to upgrade to the new version 2.1.2.  However, we get a lot of error messages in our xaml files in which oxyplot elements are used. What do we have to do to solve this problem?

**Comment by VisualMelon** [comment]
The XAML provision is no longer part of the core library: https://github.com/oxyplot/oxyplot-contrib

2.1.2 is mostly bug fixes; see release notes for 2.1.0 for compatibility notes: https://github.com/oxyplot/oxyplot/releases/tag/v2.1.0

**Comment by VisualMelon** [comment]
Closing as hopefully solved: feel free to reopen if you still have problems or further questions.
