### ISSUE TITLE
How can I show the tracker on mouse over

### ISSUE THREAD

**Issue by BenLampson** [oxyplot/oxyplot#1996]
I want to set the line data to display behavior.
Currently, we need to left-click the line to show the value.
But I want to show the value when the mouse over how to change this behavior.
There has not any example to show this feature.

**Comment by VisualMelon** [comment]
See https://github.com/oxyplot/oxyplot/blob/develop/Source/Examples/ExampleLibrary/Examples/PlotControllerExamples.cs#L32-L47 for an example

Depends on a controller command implement at https://github.com/oxyplot/oxyplot/blob/25e040ef62db36e8a1f28efdcd922cf9ab5438e7/Source/OxyPlot/PlotController/PlotCommands.cs#L41 if you want to see how it works/how to adapt it further

**Comment by BenLampson** [comment]
Thanks for your reply, it works fine.
