### ISSUE TITLE
Support sub/superscript on angled text

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#2]
**Imported from [http://oxyplot.codeplex.com/workitem/7717](http://oxyplot.codeplex.com/workitem/7717)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2010-12-05 13:25
sub/superscript is currently only working on horizontal text

**Comment by VisualMelon** [comment]
Closing as the `Rendering capabilities > DrawMathText - Rotation` example shows this feature working
