### ISSUE TITLE
[Feature-WANT]Supported FontFamilyCache for using embedded font

### ISSUE THREAD

**Issue by emako** [oxyplot/oxyplot#2021]
I want to use the embedded font for OxyPlot.Wpf, but the code `ff = new FontFamily(familyName);` provided in class CanvasRenderContext can only use `public FontFamily(string familyName)` instead of `public FontFamily(Uri baseUri, string familyName)`.

So the new feature wana to be provided and
Here is some code about my solution:

```c#
// FontFamilyCache.cs
public static class FontFamilyCache
{
    public static void AddFontFamilyCache(string familyName, FontFamily fontFamily)
    {
        CanvasRenderContext.AddFontFamilyCache(familyName, fontFamily);
    }
}
```

```c#
// CanvasRenderContext.cs
// Make fontFamilyCache static and add method named AddFontFamilyCache
        public static void AddFontFamilyCache(string familyName, FontFamily fontFamily)
        {
            if (!fontFamilyCache.TryGetValue(familyName, out _))
            {
                fontFamilyCache.Add(familyName, fontFamily);
            }
        }
```

**Comment by VisualMelon** [comment]
This seems a reasonable idea to me, but I'm not sure where we'd include it. Linking #1556 because there may be API considerations (probably not, as this will need to be per platform)
