### ISSUE TITLE
Update published nuget packages to support net 7 framework builds

### ISSUE THREAD

**Issue by Sundow** [oxyplot/oxyplot#2044]
### Feature description

The latest currently published stable nuget packages version is 2.1.2 released for net framework 4 and for net core 3.1 while the source code is already buildable for net 7. Would be nice to update the packages.

(I need to update a very old app which uses OxyPlot to net 7 and I would prefer to use nuget packages to building and storing dependency assemblies).

**Comment by VisualMelon** [comment]
2.1.2 does target .NET 7, I believe (now I'm not so sure... (indeed, it does not)), and earlier non-framework versions should be targetable from .NET 7 also.

How exactly are you targeting the nuget package, and what error/problem do you get?

**Comment by Sundow** [comment]
Here is what it targets:
![image](https://github.com/oxyplot/oxyplot/assets/5367824/63a1b730-9f9e-4de2-9cbf-d790f4ed1470)

I reference a package like:

`<PackageReference Include="OxyPlot.Wpf" Version="2.1.2" />`

In my net7.0-windows project and while it builds no asset is copied to the build directory. Worked ok when the application targeted net472, other packages referenced the same way are ok. Obviously something with build target.

**Comment by VisualMelon** [comment]
This 'just works' for me (net7.0-windows, WPF application): I've never used cake: is it in your screenshot by chance, or are you using it and so maybe it needs configuring rather than/in addition to the csproj?

**Comment by Sundow** [comment]
> This 'just works' for me (net7.0-windows, WPF application): I've never used cake: is it in your screenshot by chance, or are you using it and so maybe it needs configuring rather than/in addition to the csproj?

No, I reference the stuff in a classical way, cake is there just occasionally. But supported frameworks are there. And still, not "just works" for me. Not a big deal, I can compile assemblies from code but would be just a bit more convenient having nugets.

**Comment by VisualMelon** [comment]
Unless there is a roll-forward policy that is changing the behaviour for you, I'd suspect that changing the package wouldn't change anything; this feels like a build process issue. When I have internet that works properly again, I'll push a package to my test feed and put the details here so you can try that, and if that makes a difference then we can go from there.

**Comment by VisualMelon** [comment]
@Sundow should be a 2.1.2-net7 at https://www.myget.org/F/melonoxyplottesting (see https://www.myget.org/feed/melonoxyplottesting/package/nuget/OxyPlot.Wpf) ; it says it is out of date because it has a beta/preview suffix.

**Comment by Sundow** [comment]
> @Sundow should be a 2.1.2-net7 at https://www.myget.org/F/melonoxyplottesting (see https://www.myget.org/feed/melonoxyplottesting/package/nuget/OxyPlot.Wpf) ; it says it is out of date because it has a beta/preview suffix.

I tried with this nuget source and it works. But you actually were right, it works even with nuget 2.1.2 from the official nuget. It was my mistake, I forgot to put 
`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`
to my project when converting it to net 7 from net 472.
And after this + explicit loading of OxyPlot.Wpf assembly (mentioning it in xaml is not enough to load it in net 7 version) it works for me.
Sorry for bothering. I guess this request can now be closed.

(By saying so it can still be useful to mention net 7 as the supported framework :-) )

**Comment by VisualMelon** [comment]
@Sundow thanks for the update: glad you got it working
