### ISSUE TITLE
Data out of plotarea when use Oxyplot.PdfExporter

### ISSUE THREAD

**Issue by acuiko** [oxyplot/oxyplot#2045]
I have a chart with strongly limited axes. My data can be different and sometime some points of series can be out of PlotArea limited by axes min/max values. In such cases, I believe the data should not be displayed. When I use OxyPlot+PdfSharp (`OxyPlot.Pdf.PdfExporter`) for exporting it works as expected but when I try the same with `OxyPlot.PdfExporter` the series escape plot area which is not what am I expecting.
I know that both methods are obsolete and I should use `OxyPlot.SkiaSharp.PdfExporter` instead (which works well in this case). However, please advise whether it is possible to somehow achieve the goal using the OxyPlot.PdfExporter method.

### Steps to reproduce

1. My model:

```
var model = new PlotModel();

var linearAxis1 = new LinearAxis
{
    Position = AxisPosition.Bottom,
    Minimum = 0,
    Maximum = 20,
};
model.Axes.Add(linearAxis1);
var linearAxis2 = new LinearAxis
{
    Position = AxisPosition.Left,
    Minimum = 0,
    Maximum = 20,
};
model.Axes.Add(linearAxis2);
```

2. My data:
```
LineSeries h60 = new LineSeries();
h60.Points.Add(new DataPoint(5, 60));
h60.Points.Add(new DataPoint(15, -20));
model.Series.Add(h60);
```

3. Pdf exporting:
using (var stream = File.Create("test.pdf"))
```
{
        OxyPlot.Pdf.PdfExporter.Export(model, stream, 300, 300);
}
```

Platform: x64.
.NET version: 4.6.2:

### Expected behaviour

Series should fit within plot area and not cross the axes. Output generated with `OxyPlot.Pdf.PdfExporter.Export(model, stream, 300, 300)`  (the same I get with `OxyPlot.SkiaSharp.PdfExporter.Export(model, stream, 300, 300)`):
![image](https://github.com/oxyplot/oxyplot/assets/11881641/82d48a78-ffc0-4eb0-bb00-063974df8fff)

### Actual behavior
Series crosses plot area. Output generated with `OxyPlot.PdfExporter.Export(model, stream, 300, 300)` :
![image](https://github.com/oxyplot/oxyplot/assets/11881641/3004d06f-e98c-4e95-998a-2b909374074c)

Is there a way to get correct chart using `OxyPlot.PdfExporter`?

**Comment by VisualMelon** [comment]
No, I'm afraid not; if you need PDF output we would suggest using the `OxyPlot.SkiaSharp` provision, which includes a `PdfExporter`

**Comment by acuiko** [comment]
> No, I'm afraid not; if you need PDF output we would suggest using the `OxyPlot.SkiaSharp` provision, which includes a `PdfExporter`

What stops me from using `OxyPlot.SkiaSharp` is the fact that it needs a few dozen other dll's (SkiaSharp with many many dependencies) which is not great when deploying.

**Comment by VisualMelon** [comment]
I believe an older version of the simple PDF exporter used to implement clipping manually, but it was removed because it had issues.
