### ISSUE TITLE
Axis padding and black line on Y-axis

### ISSUE THREAD

**Issue by Nit29** [oxyplot/oxyplot#208]
Hi-

Is there any way to control the margins around the plot? Currently, the plot points gets cut off on the right, top and bottom of the plot.

Also, when the Y-axis ranges from really low value, say(0) to a high value like (20000), there is black thick line on the Y-axis near the X-axis intersection.

Please refer the attached image for the points cut off without margin and the black line on the Y-axis.
![plotmarginissue](https://cloud.githubusercontent.com/assets/8783476/4466173/1d4c2434-48e2-11e4-8f4f-507d01015c0a.png)

**Comment by mabermoske** [comment]
Regarding the points being cutoff, was the solution to not set the Minimum/Maximum values? Then did the padding work correctly? @Nit29
