### ISSUE TITLE
Mouse Events Being Handled Prevents my Event Handler from Firing

### ISSUE THREAD

**Issue by Camuvingian** [oxyplot/oxyplot#212]
I have the following XAML code for my OxyPlot area

	<Grid>
		<OxyPlot:PlotView 
			Model="{Binding Model}"
			Margin="10,0,10,0"
			Caliburn:Message.Attach="[Event MouseUp] = [Action MouseUp($this, $eventArgs)]"/>
	</Grid>

But my handler in my ViewModel is not firing. Using Snoop I can see the the Plot Area is gobbling up the event marking it as `Handled` preventing my handler from firing. Am I missing something obvious here and is there anyway to handle the `MouseMove`, `MouseDown` and `MouseUp` events?

**Comment by tibel** [comment]
With #446 the PlotController does not intercept the events any more.
When there is no handler or the handler does not set `Handled=true` you get the event on the `PlotView` as expected.
