### ISSUE TITLE
DiscontinuousAreaSeries and AreaSeriesItem

### ISSUE THREAD

**Issue by bsguedes** [oxyplot/oxyplot#215]
When plotting an AreaSeries, it would be nice to display gracefully a discontinuity in an AreaSeries.

Today, we have the points that bound the area series connected when a discontinuity appears, filling the area between the upper and the lower bound. It would be nice to have something like this:

![image](https://cloud.githubusercontent.com/assets/7770756/4591679/6fc32772-5070-11e4-8563-27a7620d092c.png)

In order to have this working, we have to make sure that the points in the upper and lower bound are synched, i.e. the gaps are aligned related to the X axis. objo gave the nice suggestion of having a collection of AreaSeriesItem, where each element would contains both points (here I assume that a NaN value in one of the two values is not accepted). The discontinuity would be created by adding an AreaSeriesItem.Undefined to the collection at a given x value.

**Comment by federicocoppola** [comment]
I have a solution without breaking the compatibility, how can I submit it?
![2015-04-10_141445](https://cloud.githubusercontent.com/assets/5793119/7087463/2384b7b2-df8c-11e4-814f-5f22d37b8c7f.png)

**Comment by objorke** [comment]
I think your solution looks good! All contributions must be submitted as pull requests. See
https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md

**Comment by objorke** [comment]
I have rebased and will create a PR for you.

**Comment by objorke** [comment]
I like the idea of `AreaSeriesItem` too!
