### ISSUE TITLE
Tooltips no longer working in version 2014.1.319.1

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#219]
We are using a custom tooltip on the plot title. We accomplish this by using a custom Annotation and using src.SetToolTip on the IRenderContext.

When updating from 2014.1.277.1 => 2014.1.319.1 (or any new release), this seems to be broken.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.

**Comment by GeertvanHorrik** [comment]
Thanks. It's still on my todo list, but time and priorities are hard. Will re-open when I start on this.

**Comment by objorke** [comment]
We could also add a `TitleTooltip` property on the `PlotModel`. Should be very easy to implement...

@GeertvanHorrik I don't like the implementation in `PlotTitleTooltipAnnotation` - does it triy to set the tooltip of all following "plot elements" (axes/annotations/series)? I think the current implementation where the tool tip is set for each plot element and cleared at the end is correct!

**Comment by GeertvanHorrik** [comment]
Sorry for my late reply. This is just to let you know it's still on my list, just need to find some time.

**Comment by objorke** [comment]
No problem, we have not marked this as high priority or part of the v2015.1 milestone.

**Comment by GeertvanHorrik** [comment]
Going to try and fix this today. First updating to the latest oxyplot, then will check if the issue still exists.

**Comment by GeertvanHorrik** [comment]
@objorke what I need is actually just the title to have a tooltip on a plot. Let me check if I can implement with what's currently available inside oxyplot.

**Comment by GeertvanHorrik** [comment]
Using the ToolTip property on the Plot control seems to work. Then I can use a converter to set the right tooltip (not sure why I didn't use it before, probably wasn't available a long time ago when we started using OxyPlot).

The only disadvantage is that the location of the ToolTip sometimes is a bit off (but that's "ok" for me).

**Comment by GeertvanHorrik** [comment]
The popup is positioned directly at the location you enter the control. So in a list of plots, when I move from 1 to another, the tooltip is there where I get into the control:

![image](https://cloud.githubusercontent.com/assets/1246444/8335504/5d88b15a-1a9e-11e5-9531-015206551c64.png)

**Comment by GeertvanHorrik** [comment]
Created PR #508 as you can see, this issue can stay closed.

**Comment by objorke** [comment]
I still like the idea of having a `TitleTooltip` on the `PlotModel` :-)

**Comment by GeertvanHorrik** [comment]
I can implement that partially. No problem to implement it (it's just an additional mapping from model => view). But... this needs to be implemented on all platforms?

**Comment by GeertvanHorrik** [comment]
You are talking about TitleTooltip. Does that mean the tooltip should only be available on the title itself?

**Comment by objorke** [comment]
Yes, that is how I understood the first feature request! :-)

**Comment by GeertvanHorrik** [comment]
Ok, I am happy to introduce any of it. Just let me know which way to go. To me it doesn't matter, but I will fix the wrong tooltip positioning anyway.

**Comment by GeertvanHorrik** [comment]
The issue with the tooltips is that the "SetBetweenShowDelay" is not being respected somehow. It immediately fires a new tooltip when you move from 1 element in the list to another. Even with a custom popup placement callback, the popup is shown too fast.

**Comment by GeertvanHorrik** [comment]
![oxyplot_tooltips](https://cloud.githubusercontent.com/assets/1246444/8374456/c8e5ca16-1bf5-11e5-9f59-d84fd6225f9b.gif)

**Comment by objorke** [comment]
@GeertvanHorrik I think it should be possible to add a `PlotModel.TitleTooltip` property, then set the tooltip on the render context just before drawing the title, and clear the current tooltip afterwards. Please include an example in the example library. You could also add a dependency property to the WPF `Plot` control!

**Comment by objorke** [comment]
Is the `SetBetweenShowDelay` needed if adding the tooltip to the titles only?

**Comment by GeertvanHorrik** [comment]
So to summarize:

1) Add a separate example
2) Add PlotModel.TitleTooltip
3) Add Plot.TitleTooltip DP
4) Render it on the context

Will work on that, will leave the other tooltip stuff as is for now.

**Comment by GeertvanHorrik** [comment]
See PR, let's keep this issue closed so we can focus on the actual logic / content there.
