### ISSUE TITLE
Exception in Visual Studio 2013. FileNotFoundException on Designer.

### ISSUE THREAD

**Issue by petinho** [oxyplot/oxyplot#221]
Hi.

I've started a project this week and in Visual Studio designer doesn't work after adding References through NuGet.

"FileNotFoundException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified."

I've seen it's a common problem, I tried all updates proposed on other issues/threads, but it's not working. Execute works, but designer not.
I'm on a VS2013 Express Update 3 Environment.

Thanks in advance.

**Comment by kevkon3** [comment]
I just wanted to report that I had the same problem. I am using VS 2013 Ultimate Version 12.0.30501.00 Update 2 and .NET 4.5.50938.

I installed Silverlight SDK 5.0 and now it works just fine.

**Comment by cdjc** [comment]
Weird. I also had the same problem with VS 2013 Professional 12.0.40629.00 Update 5 (.NET 4.5.51659). Installed Silverlight SDK 5.0 and it works fine for me now as well.
