### ISSUE TITLE
Too many significant figures (decimal places) in LinearAxis.

### ISSUE THREAD

**Issue by oloopy** [oxyplot/oxyplot#227]
Platform: 
* .NET Framework 4.5
* OxyPlot 2014.1.546
* WPF

I am drawing LinearSeries with LinearAxis, but in some cases it is found that the Y LinearAxis would display a number with too many significant figures while All the data points I have are all with only 2 decimal places. Please see the screenshot below.

![2014-10-26_10-37-34](https://cloud.githubusercontent.com/assets/1088621/4781708/b2ca1774-5cb9-11e4-8179-09211e51f719.png)

Even if I let OxyPlot automatically assign a LinearAxis to the plot, this incorrectness still shows.

Then I looked into the source code and found IntervalLength might help. The screenshot below shows the LinearAxis with IntervalLength set to 20. At this time, the Axis performs correctly (IntervalLength 30 - 60 would not help). 

![2014-10-26_10-38-45](https://cloud.githubusercontent.com/assets/1088621/4781721/4d2d81fc-5cba-11e4-9258-177f2d58605d.png)

I know manually set the IntervalLength would not solve the problem completely. So... Any other solutions recommended?

Thanks in advance :)

**Comment by objorke** [comment]
@Mitch-Connor @oloopy I think this was solved by #289. Can we close this issue?

**Comment by oloopy** [comment]
@objorke @Mitch-Connor Thanks for your help! I have upgraded my routine to version 2015.1.658-alpha and it works great.
