### ISSUE TITLE
OxyColor and Color

### ISSUE THREAD

**Issue by nihau** [oxyplot/oxyplot#228]
Okay, few days ago found that properties like axislinecolor, foreground, background became OxyColor type. Solved this by implementing extension ToColor\FromColor, but can you guys just overload operator '='?

**Comment by objorke** [comment]
@nihau which properties are you referring to? OxyPlot.Wpf.Axes.Axis.AxisLineColor looks correct.
Can this issue be closed?

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
