### ISSUE TITLE
Reorganize NuGet packages

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#242]
Reorganize/clean up the NuGet packages to make it easier to understand which package to use.

List of current NuGet packages: http://www.nuget.org/packages?q=oxyplot

Packages built by AppVeyor:

- OxyPlot.Core - PCL, NET35, NET40, NET45 libraries
- OxyPlot.Wpf (NET4 WPF+XPS)
- OxyPlot.Windows (Windows store/WinRT and Windows mobile apps) NEW!
- OxyPlot.WP8 (Windows Phone 8 Silverlight)
- OxyPlot.Silverlight (SL5)
- OxyPlot.WindowsForms (NET4)
- OxyPlot.GtkSharp (NET4)
- OxyPlot.Xwt (NET4, based on Xwt)
- OxyPlot.Pdf (NET4, adds dependency to PdfSharp)
- OxyPlot.OpenXML (NET 4, adds dependency to OpenXML)

Packages built on machines with a Xamarin subscription

- OxyPlot.Xamarin.Android
- OxyPlot.Xamarin.iOS
- OxyPlot.Xamarin.Mac (must be built on a Mac...)
- OxyPlot.Xamarin.Forms (must be built on a Windows machine for the Windows app renderer...)

Remove / mark obsolete
- OxyPlot
- OxyPlot.Mobile
- OxyPlot.WindowsUniversal

**Comment by tibel** [comment]
Also issue #242 describes these build issues.

**Comment by objorke** [comment]
There is currently 19 packages, I think this can still be improved. 
I think #274 is about CI of the Xamarin packages

**Comment by tibel** [comment]
A year ago I thought similar: Many packages are confusing. But changed my mind when seeing CoreFX the first time. They have much more packages than OxyPlot might ever have.

Thus said:
OxyPlot supports many UI (or rendering) technologies and there is more to come (e.g. DirectX, Eto?).
NuGet has the concept of platforms, but this is not enough as there might be multiple UI stacks on the platform.

For .NET 4.0 OxyPlot supports:
- WPF
- WinForms
- GTK#
- Xwt

As an OxyPlot user I will (probably) NOT use multiple UI stacks in one application. When I create a WPF app, all I need is OxyPlot.Wpf. I don't want some WinForms assembly references in my project.

OxyPlot.Xamarin.Forms on the other hand has to support one UI stack per platform. So all the Xamarin.Forms can be in one single nuget package. Which references the specific UI platform packages (e.g. OxyPlot.WP8 or OxyPlot.Xamarin.iOS)

What I suggest:
- remove `OxyPlot` package (as it combines WinForms and WPF in one package)
- remove `OxyPlot.Mobile`package (distinguish between desktop and mobile does not work any more with UniversalApps)
- keep package per UI technology

**Comment by objorke** [comment]
@tibel thanks for clearing up, I think you have some very good points. A large number of packages may be ok when they are all following a very clear pattern.

@mattleibow what do you think? is it ok to remove OxyPlot.Mobile?

Should "OxyPlot for Windows Universal apps" be renamed to "OxyPlot for Windows apps" now?

And when Xamarin Forms includes support for Windows apps (as demonstrated recently), I guess we could add a reference to the "OxyPlot for Windows apps" package from the "OxyPlot for Xamarin.Forms" package

**Comment by mattleibow** [comment]
@objorke, I agree with you. Removing the mobile package seems like a good idea. Mobile is now getting blurry... Each platform/UI (iOS/Android/WinWPF/WinRT) can have their own package and this could be the pattern.

Renaming the WinU package to Win seems a good idea - especially with the coming of Windows 10. The Xamarin.Forms package will just have conditional dependencies and then the actual forms assemblies.

**Comment by objorke** [comment]
I changed the issue description. Does it look ok? Is "OxyPlot.Win" a good name?

**Comment by mattleibow** [comment]
@tibel @objorke ... I think OxyPlot.Windows is better. (I was just avoiding typing) Not much longer and is the "correct" name.

**Comment by tibel** [comment]
@objorke OxyPlot.Windows should not include WP8. WP8 aka "Windows Phone 8 Silverlight" should stay separate.

**Comment by objorke** [comment]
@mattleibow @tibel thanks, I have updated the issue description according to your comments!
