### ISSUE TITLE
OxyPlot-2014.1.571-alpha nuget packages still refers to PCL target framework in NET40 case.

### ISSUE THREAD

**Issue by PatriceMarin** [oxyplot/oxyplot#254]
After the merge #251, nuget packages should not refer to PCL assemblies anymore.
But, OxyPlot.dll has the following target framework:

[assembly: TargetFramework(".NETPortable,Version=v4.0,Profile=Profile328", FrameworkDisplayName = ".NET Portable Subset")]

Investigation in progress...

**Comment by objorke** [comment]
Can this be closed?

**Comment by PatriceMarin** [comment]
Yes :)
