### ISSUE TITLE
Way to force plot update

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#270]
I have lots of plots and I have the zoom synchronized (if I zoom 1, all others make the same move). Now this works in 99 % of the cases, except when I need to reset an axis (then the change is not notified by OxyPlot). No matter what I do, it never updates. I think this is because the isPlotInvalidated in PlotBase is never set to a different value thus calling update makes no sense.

Would you be interested in making an (extension?) method to allow full invalidation of a plot?

btw: using WPF 4.0

**Comment by harika-strand** [comment]
can u please send us the solution of how to update the plot view of oxyplot .
In the updated version it;s not showing any functionality for Update Method .
Please help me out to solve the issue
