### ISSUE TITLE
Add more information to the AxisChangedEventArgs

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#275]
I want to synchronize the axis of multiple plots, but only by the moved delta. I think it should be easy to put the delta in there as well. I will first test it locally, then create a PR if it works.

**Comment by objorke** [comment]
what happened to this? I see #276 was accepted and merged, and guess this can be closed. Right?

**Comment by GeertvanHorrik** [comment]
Yes, it can be closed.
