### ISSUE TITLE
InvalidOperationException: XAxis not defined

### ISSUE THREAD

**Issue by fgroes** [oxyplot/oxyplot#277]
My application consists of main tabs. When i switch tabs, which means that the plot is not displayed and then I switch back I get the said error message. The plots are ment to update every 100 ms therefore i opted for not creating a new plotmodel for new data.

The dispatcher stuff was an attempt to avoid threading problems, as was suggested in some other solutions, it did not work though. I am grateful for any ideas. If you need further information please ask.

```c#
    public partial class ControlSignalPlot : UserControl
    {
        #region Properties

        public bool IsPlotEnabled
        {
            set { plotView.IsEnabled = value; }
        }

        public double[] Data
        {
            set
            {
                double[] data = value;
                if (data == null) return;
                m_PlotHandler.AddPoints(data);
            }
        }

        #endregion

        #region Fields

        private PlotHandler m_PlotHandler;

        #endregion

        #region Constructors

        public ControlSignalPlot()
        {
            InitializeComponent();

            Action a = () =>
                {
                    m_PlotHandler = new PlotHandler(Application.Current.Dispatcher);
                    plotView.DataContext = m_PlotHandler.PlotModel;
                };
            Dispatcher.Invoke(a);           
        }

        #endregion

        #region Methods

        #endregion
    }


    public class PlotHandler
    {
        public PlotModel PlotModel
        {
            get { return m_PlotModel; }
        }

        private PlotModel m_PlotModel;
        private LinearAxis m_HorizontalAxis;
        private Dispatcher m_CurrentDispatcher;

        public PlotHandler(Dispatcher dispatcher)
        {
            CreatePlotModel();
            m_CurrentDispatcher = dispatcher;
            //m_CurrentDispatcher = Dispatcher.CurrentDispatcher;
        }

        private void CreatePlotModel()
        {
            m_PlotModel = new PlotModel();
            m_PlotModel.PlotAreaBackground = OxyColor.FromArgb(255, 0, 0, 0);
            m_HorizontalAxis = new LinearAxis();
            m_HorizontalAxis.Position = AxisPosition.Bottom;
            m_HorizontalAxis.Minimum = 0;
            m_HorizontalAxis.Maximum = 1000;
            m_PlotModel.Axes.Add(m_HorizontalAxis);
            LinearAxis verticalAxis = new LinearAxis();
            verticalAxis.Position = AxisPosition.Left;
            verticalAxis.Minimum = 0;
            verticalAxis.Maximum = 10;
            m_PlotModel.Axes.Add(verticalAxis);
            LineSeries lineSeries = CreateLineSeries();
            m_PlotModel.Series.Add(lineSeries);
        }

        private LineSeries CreateLineSeries()
        {
            LineSeries lineSeries = new LineSeries();
            lineSeries.Color = OxyColor.FromArgb(255, 0, 255, 0);
            return lineSeries;
        }

        public void AddPoints(double[] data)
        {           
            try
            {
                Action a = () =>
                {
                    m_HorizontalAxis.Maximum = data.Length;
                    LineSeries lineSeries = CreateLineSeries();
                    for (int i = 0; i < data.Length; i++)
                    {
                        lineSeries.Points.Add(new DataPoint(i, data[i]));
                    }
                    m_PlotModel.Series.Clear();
                    m_PlotModel.Series.Add(lineSeries);
                    m_PlotModel.InvalidatePlot(true);
                };
                m_CurrentDispatcher.BeginInvoke(a);
            }
            catch
            {
                throw new NotImplementedException();
            }
        }
    }
```

Stack trace:
> bei OxyPlot.Series.XYAxisSeries.VerifyAxes() in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot\Series\XYAxisSeries.cs:Zeile 671.
   bei OxyPlot.Series.LineSeries.Render(IRenderContext rc, PlotModel model) in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot\Series\LineSeries.cs:Zeile 363.
   bei OxyPlot.PlotModel.RenderSeries(IRenderContext rc) in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot\PlotModel\PlotModel.Rendering.cs:Zeile 385.
   bei OxyPlot.PlotModel.RenderOverride(IRenderContext rc, Double width, Double height) in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot\PlotModel\PlotModel.Rendering.cs:Zeile 117.
   bei OxyPlot.PlotModel.OxyPlot.IPlotModel.Render(IRenderContext rc, Double width, Double height) in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot\PlotModel\PlotModel.Rendering.cs:Zeile 54.
   bei OxyPlot.Wpf.PlotView.UpdateVisuals() in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot.Wpf\PlotView.cs:Zeile 1107.
   bei OxyPlot.Wpf.PlotView.ArrangeOverride(Size arrangeBounds) in c:\TeamCity\buildAgent\work\3b9fcf1ba397d0ed\Source\OxyPlot.Wpf\PlotView.cs:Zeile 564.
   bei System.Windows.FrameworkElement.ArrangeCore(Rect finalRect)
   bei System.Windows.UIElement.Arrange(Rect finalRect)
   bei System.Windows.ContextLayoutManager.UpdateLayout()
   bei System.Windows.Controls.TabItem.OnPreviewGotKeyboardFocus(KeyboardFocusChangedEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.KeyboardDevice.TryChangeFocus(DependencyObject newFocus, IKeyboardInputProvider keyboardInputProvider, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   bei System.Windows.Input.KeyboardDevice.Focus(DependencyObject focus, Boolean askOld, Boolean askNew, Boolean forceToNullIfFailed)
   bei System.Windows.Input.KeyboardDevice.Focus(IInputElement element)
   bei System.Windows.UIElement.Focus()
   bei System.Windows.Controls.TabItem.SetFocus()
   bei System.Windows.Controls.TabItem.OnMouseLeftButtonDown(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run()
   bei EOSTATEMeltpool.App.Main() in D:\Projekte\EOS\Online\EOSTATEMeltpool\EOSTATEMeltpool\obj\x86\Debug\App.g.cs:Zeile 0.
   bei System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   bei Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
