### ISSUE TITLE
Extension methods placeholders

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#280]
I have a lot of extension methods that might be of use. They are not really valid for the models but can be of great use.

What if there would by an *Extensions* folder in the core project with the following classes:

* PlotModelExtensions
* AxisExtensions

These are the most important for now I think. This would make it easier for pull requests as well. I am not familiar with the *whole* solution, only with WPF so adding new files is challenge.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
