### ISSUE TITLE
LinearAxis.AxislineColor Property is not set

### ISSUE THREAD

**Issue by david-laundav** [oxyplot/oxyplot#282]
Using Xamarin.Forms in a PCL, consider the following case:

var xAxis = new LinearAxis();
xAxis.AxislineColor = OxyColor.FromRgb(214, 34, 89);

When setting the AxislineColor property, the color of the axis is not updated.
The same issue occurs when simply using OxyColors instead of defining the color yourself using OxyColor.FromRgb();

**Comment by drunkendaddy** [comment]
Looks like plot area border color is drawn over the axis line.

So, I set 

PlotModel.PlotAreaBorderColor = OxyColors.Transparent;

and then

xAxis .AxislineStyle = LineStyle.Solid;
xAxis .AxislineColor = OxyColors.White;

Its working now.
