### ISSUE TITLE
PlotView not exposing Invalidate

### ISSUE THREAD

**Issue by david-laundav** [oxyplot/oxyplot#288]
As mentioned in [this issue on Stackoverflow](http://stackoverflow.com/questions/27426584/fill-color-of-a-single-point-in-a-scatterseries), when I create a `ScatterSeries` and listen to the `TouchStarted` event to highlight the selected item, it is not updated immediately in the `PlotView`. I have to drag the canvas before the `SelectionColor` is applied.

First, in my ViewModel, I do like so:
```C#
var model = new PlotModel()
{  
SelectionColor = OxyColors.Red,
// ...
};

var scatterSeries = new ScatterSeries()
{
    SelectionMode = SelectionMode.Single,
    // ...
};

var scatterPoints = new List<ScatterPoint>
{
    new ScatterPoint(0, 4),
    // ...
};
```

Thereafter, I listen to the TouchStarted event of the ScatterSeries:
```
scatterSeries.TouchStarted += (sender, e) =>
{
    var xCoordinate = e.Position.X;
    var yCoordinate = e.Position.Y;

    var screenPoint = new ScreenPoint(xCoordinate, yCoordinate);

    var point = lineSeries.GetNearestPoint(screenPoint, false);
    var index = (int)point.Index;
    scatterSeries.SelectItem(index);

    // I expect it to refresh and update the PlotModel here:
    model.InvalidatePlot(true); 

    e.Handled = true;
};
```
In my ViewModel I have also created a PlotModel Property which my PlotView (in my View) is bound to (i.e. PlotView.ModelProperty). 

As mentioned, this seems to work fine, except for that the `PlotModel` is not updated immediately with the `SelectionColor` - I have to drag the canvas before it updates.

I think this may have something to do with the fact, that my PlotView is not invalidated after data has been updated. 

[As Cheesebaron mentions](http://stackoverflow.com/a/27427305/2399772), I am unable to Invalidate the PlotView since it is not exposed in Xamarin.Forms.

Is this something you could possibly include, or do you have any other solution?

**Comment by objorke** [comment]
is this solved now?

**Comment by david-laundav** [comment]
Tested on Android which works. Should be tested on iOS as well, as soon as #348 is fixed.

**Comment by objorke** [comment]
I think this is a duplicate of #338

**Comment by david-laundav** [comment]
It is a duplicate of #338 indeed. Closing.
