### ISSUE TITLE
Xamarin.Forms 1.3 pre-3 doesn't seem to be compatible

### ISSUE THREAD

**Issue by vicentor** [oxyplot/oxyplot#293]
See: http://forums.xamarin.com/discussion/29635/oxyplot-charts-in-xamarin-forms?new=1
All examples suggest to use:

`return new Content ...`

When the new `Xamarin.Forms` uses (has a property directly on the Page):

`Content = new StackLayout ...`

The link I provided shows the newer way to manage pages, I'm mentionning it in case it has something to do with the issue.

**Comment by objorke** [comment]
The packages have been updated, can this issue be closed? @vicentor

**Comment by vicentor** [comment]
I'll check it out as soon as I can.

**Comment by tibel** [comment]
Minimum supported Xamarin.Forms version is 1.3.3.6323.
Please verify with latest OxyPlot version. Thanks.

According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
