### ISSUE TITLE
Create Xamarin Component with NuGet dependency

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#298]
Don't build and include the OxyPlot libraries in the component, but add dependencies to NuGet. See http://lastexitcode.com/blog/2014/10/26/XamarinComponentsAndNuGet/

The OxyPlot Xamarin Component is located in
https://github.com/oxyplot/xamarin-component

**Comment by mattleibow** [comment]
This has been done and a PR is there.

https://components.xamarin.com/view/oxyplot

**Comment by objorke** [comment]
Well done!!
