### ISSUE TITLE
The plot labels placed strangely for some specific axis angles

### ISSUE THREAD

**Issue by archeg** [oxyplot/oxyplot#301]
![image](https://cloud.githubusercontent.com/assets/700094/5565322/1915cb12-8efc-11e4-87a7-e78772ed8709.png)

Please notice that bottom and top axis labels overlaps with the axis itself. https://github.com/oxyplot/oxyplot/pull/300 has an example of the screen. I actually began wondering is it an issue at all? I would expect the bottom labels to be put lower than axis line and top labels to be put higher.

If it is an issue:
I found that `HorizontalAndVerticalAxisRenderer.GetRotatedAlignments()` calculates the stuff a bit wrong. I do not fully understand why this method exists, and why is it so complex - so I have doubts I understand it.

If I remove this method at all, and set `va = VerticalAlignment.Middle`, and `ha` according to the next rule (method `RenderMajorItems`):
* For `AxisPosition.Left`: if -90 < axis.Angle < 90, Right, else Left
* For `AxisPosition.Right`: if -90 < axis.Angle < 90, Left else Right
* For `AxisPosition.Top`: if axis.Angle > 0, Right, else Left
* For `AxisPosition.Bottom`: if axis.Angle > 0, Left else Right

The result is next:
![image](https://cloud.githubusercontent.com/assets/700094/5565339/560732f8-8efd-11e4-8837-7c9f765fef7c.png)

Red squares are the origins.

Could this be considered as a fix? Any chance `GetRotatedAlignments()` does more than I think it is?

**Comment by objorke** [comment]
@archeg: Isn't this fixed by #303?

**Comment by archeg** [comment]
Yes. It is fixed now
