### ISSUE TITLE
PlotView gives an error with Xamarin Unified API

### ISSUE THREAD

**Issue by nodoid** [oxyplot/oxyplot#306]
When building against the new Unified API, PlotView gives an error that Monotouch.UIKit.UIView is defined in an assembly not referenced - it looks like the version on nuget (2014.1.546) was built against the old API rather than the unified.

**Comment by XiaoHippo** [comment]
As a starter, you might want to try updating all references to "{6BC8ED88-2882-458C-8E55-DFD12B67127B}" to "{FEACFBD2-3405-455C-9665-78FE426C6842}" (https://github.com/oxyplot/oxyplot/search?utf8=%E2%9C%93&q=%7B6BC8ED88-2882-458C-8E55-DFD12B67127B%7D).

See http://developer.xamarin.com/guides/cross-platform/macios/updating_ios_apps/

**Comment by objorke** [comment]
Note the package has been renamed to "OxyPlot.Xamarin.iOS"
https://www.nuget.org/packages/OxyPlot.Xamarin.iOS

Is this still a problem?

**Comment by tibel** [comment]
I think this issue should be closed. As there were many changes since `2014.1´ in iOS support.
