### ISSUE TITLE
DateTimeAxis.ToDouble conversion

### ISSUE THREAD

**Issue by matmenier** [oxyplot/oxyplot#308]
Hi!

I'm having some trouble making a plot view with a DateTime axis. When I'm trying to convert the DateTime values with the DateTimeAxis.ToDouble method, I get an error message:
The file c:\projects\oxyplot\Source\OxyPlot\Axes\DateTimeAxis.cs' doesn't exist.

Does someone have an idea to fix it?

**Comment by objorke** [comment]
Can you show the DateTime value that cannot be converted? 
And can you include the stack trace?

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
