### ISSUE TITLE
UI Thread Blocking on develop branch

### ISSUE THREAD

**Issue by PranishDutt** [oxyplot/oxyplot#309]
Using the master branch of oxyplot, the UI thread isn't blocked when calling `InvalidatePlot(...)` repeatedly, but using the develop branch with the exact same code base blocks the UI thread when calling `InvalidatePlot(...)`.

I'd assume something new which was recently added to the develop branch is causing the UI to block.

**Comment by tibel** [comment]
What platform (WPF, SL, Store, ...) you are using?

**Comment by PranishDutt** [comment]
WPF.

I'm not doing anything special with it aside plotting points and annotations on inside an on-going task. Using the master branch works without the UI blocking, but using the same code with the develop branch causes the UI to block.

**Comment by tibel** [comment]
I can reproduce the issue with the "Realtime Demo" and and created a pull request to fix it.

**Comment by PranishDutt** [comment]
I can confirm that the changes in the pull request fixes the issue.
