### ISSUE TITLE
Easy Way to Produce Step-Change Line Series

### ISSUE THREAD

**Issue by Camuvingian** [oxyplot/oxyplot#312]
I would like to be able to plot my line series without any interpolation what-so-ever. I would like the line series to plot a horizontal line between each point in the series and at the actual point then draw vertically upwards/downwards depending on the level. Like this illustration with betting odds:

![1x2_home](https://cloud.githubusercontent.com/assets/4823601/5602195/718e06a0-9335-11e4-800a-33504be0b5b3.png)

Is there an easy way of doing this with the library or will I have to "fool" OxyPlot in to doing this?

**Comment by objorke** [comment]
Did you try the `StairStepSeries`?

**Comment by Camuvingian** [comment]
No, didn't even know it existed! I will take a look, for now I am just adding additional points to my line series, all pretty straight forward. Thanks for your time.

**Comment by objorke** [comment]
Let us know if this issue can be closed. Note that we need a clear description for bugs and new features. For questions, please use the forum or the chat room :-)

**Comment by Camuvingian** [comment]
Yeah, this is exactly what I needed. Most appreciated. I will use the forum/chatroom in future.

**Comment by objorke** [comment]
for the chat room: see the gitter link on the README page or the "chat room" link on the oxyplot.org page
