### ISSUE TITLE
how click legend label display or hide line ?

### ISSUE THREAD

**Issue by hcxlc** [oxyplot/oxyplot#314]
how click legend label display or hide line ?

**Comment by objorke** [comment]
Do you want to click on a legend to display or hide a series? 
I don't think events on the legends are supported, I added #315 to cover this.

Note: For questions, please use the forum or the chat room! :-) I want to keep the issues section for bugs and improvements only.

**Comment by hcxlc** [comment]
yes, thank you!
Please refer to http://www.highcharts.com/demo/line-basic
When the series too much, can show hidden series

**Comment by objorke** [comment]
I have added the link to #315
