### ISSUE TITLE
Build errors in Xwt examples

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#317]
1. The `Info.plist` file is missing, cannot build the ExampleBrowser.Mac project
2. The XwtDemo project is missing references to OxyPlot and OxyPlot.Xwt

**Comment by objorke** [comment]
@sevoku do you have this file? or should we create a new one?

**Comment by sevoku** [comment]
Oh, yes! It should be somewhere, but I can't boot my Mac VM right now...

It should be something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleIdentifier</key>
	<string>com.oxyplot.xwt.ExampleBrowser</string>
	<key>CFBundleName</key>
	<string>ExampleBrowser</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.6</string>
	<key>NSPrincipalClass</key>
	<string>NSApplication</string>
</dict>
</plist>
```

**Comment by objorke** [comment]
Great! How do you run OSX on a VM? Hacked version like in [this](http://lifehacker.com/5938332/how-to-run-mac-os-x-on-any-windows-pc-using-virtualbox)?

**Comment by sevoku** [comment]
Not exactly, but it works almost always the same way. You need a special loader to install the original dmg or a prepared virtual disc.
