### ISSUE TITLE
OxyPlot.Wpf.LinearAxis.ActualMaximum/ActualMinimum

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#33]
**Imported from [http://oxyplot.codeplex.com/workitem/9993](http://oxyplot.codeplex.com/workitem/9993)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2012-08-24 09:12
Add read-only dependency propertie for ActualMaximum/ActualMinimum on OxyPlot.Wpf.LinearAxis

ref. <a href="http://oxyplot.codeplex.com/discussions/392464" rel="nofollow">http://oxyplot.codeplex.com/discussions/392464</a>

**Comment by tibel** [comment]
This is the original request for #424. Will close this as duplicated as the discussion is on the new one.
