### ISSUE TITLE
StringFormat for TimeSpanAxis not recognizing f, ff, fff, etc 

### ISSUE THREAD

**Issue by lycannon** [oxyplot/oxyplot#330]
The TimeSpanAxis does not recognize the f, ff, fff, etc format string.

IE: mm:ss:ff displays 01:04:ff instead of numbers for ff.

**Comment by tibel** [comment]
If this is not enough we would have to do something similar to:
http://referencesource.microsoft.com/#mscorlib/system/globalization/timespanformat.cs

**Comment by pltaylor** [comment]
@tibel Is there a recommended way to test what the axis displays for a label?  I have looked around for an existing test and haven't stumbled on one that tests what is printed to the labels and don't see one.

**Comment by objorke** [comment]
I tried to add a test... This seems to work?
