### ISSUE TITLE
TrackerFormatString in ColumnSeries  with binding don't work

### ISSUE THREAD

**Issue by JavierJJJ** [oxyplot/oxyplot#333]
When Use a ColumnsSeries with a binding ValueField don't work the TrackerFormatString, show an empty tooltip.
I test from Version 2014.1.546 to 2015.1.690, previous versión 2014.1.491 work well

In example browser can view on example ColumnSeries - Binding to ItemsSource and Binding to ItemsSource(Reflection)

**Comment by objorke** [comment]
@JavierJJJ can this be closed?

**Comment by JavierJJJ** [comment]
Can be closed, now operate correct
