### ISSUE TITLE
iOS multitouch pan/zoom is glitchy and slow

### ISSUE THREAD

**Issue by TheAlmightyBob** [oxyplot/oxyplot#336]
1. The current touch handling logic can mix up fingers during a zoom gesture, leading to some unexpected jumpy behavior. For example, it will switch back and forth between single-touch and multitouch modes.
2. The KeepFixedAspectRatio mode is a bit unstable if trying to only zoom along one axis.
3. The second finger (i.e., starting a zoom gesture) creates an unnecessary second TouchManipulator, which, among other possible side-effects, means that the graph is being invalidated twice as often as it needs to be.

**Comment by objorke** [comment]
Can this be closed?

**Comment by TheAlmightyBob** [comment]
Yep! I only created it to accompany the pull request. :)
