### ISSUE TITLE
PlotModel.Invalidate is not hooked up on iOS/Android (including Forms)

### ISSUE THREAD

**Issue by TheAlmightyBob** [oxyplot/oxyplot#338]
The other platforms have OnModelChanged logic that gets executed when the model is set on the PlotView (in particular, AttachPlotView), but this is missing from iOS/Android. Thus, calling Invalidate on the model has no effect. This can be observed in some of the examples that take advantage of this (e.g. Touch).

(this is intended to replace issue #288, which just describes one symptom of this issue)

**Comment by objorke** [comment]
can this be closed now?

**Comment by TheAlmightyBob** [comment]
It might be wise for somebody else to verify the fix on Android first, since I don't have a license for that.

**Comment by tibel** [comment]
Please verify with latest OxyPlot version. Thanks.

According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
