### ISSUE TITLE
Add "tap" support for touch-enabled platforms

### ISSUE THREAD

**Issue by TheAlmightyBob** [oxyplot/oxyplot#340]
[this time, I do not have a corresponding pull request ready to go. sorry.]

The current TouchStarted/TouchDelta/TouchCompleted pattern is a good start that works for pan/zoom and some other scenarios. However, it's difficult for an app to enable pan/zoom *and* try to handle those events to detect simple taps (e.g. to select lines/annotations). I believe the platforms each already have support for capturing taps separately, so this should mainly be a matter of piping that through the core library.
- Update: Those events actually could not be used to detect taps on Windows, and can no longer be used to detect taps on iOS. They really mean "pan/zoom manipulation started," not touch in general.

~~The current situation is particularly complicated on iOS (where I've spent the most time). Even after my recent fixes, the event sequence can be a little.... *unexpected*... to app developers. In handling the scenario of the user changing fingers mid-gesture, the logic may "restart" the touch handling.~~

~~For example:
Put one finger down
Put a second finger down
Lift the first finger~~

~~Results in:
TouchStarted (first finger)
TouchCompleted(first finger)
TouchStarted (second finger)~~

~~Possibly that is an issue in itself and could use work, but the point in this context is that it makes it that much more difficult for an app developer to try to detect a tap.~~

~~In the iOS scenario, this may benefit from refactoring the current logic into a custom gesture recognizer (to then be used in conjunction with a TapGestureRecognizer).~~

[above issues were resolved in #359. Pan/Zoom currently uses an iOS gesture recognizer and no longer generates extra Started/Completed events]

P.S. It might also be nice to have the ability to forward touches to the mouse events, particularly for Windows, but maybe there's a reason that hasn't been done before...

**Comment by objorke** [comment]
Good ideas here! The original idea was to implement support for the 'low level' tap events (the current exposed api) in a similar way on all the touch-capable platforms, then hopefully create a more developer friendly gesture recognition system on top of it. I think such a system could be done in portable code!

It would be great if someone could look into this - do some refactoring of the current code or come up with some better ideas!

**Comment by TheAlmightyBob** [comment]
If that's the goal, then it seems like the current API would need to be even lower-level... e.g., information about specific touches instead of just pan/scale properties. Which may mean abandoning some of the platform-specific helpers (such as the Windows manipulation events).

I certainly understand the value of doing as much as possible in PCL, and I do think it's possible, but it seems like a lot of refactoring and extra work vs. wrapping the existing platform-specific gesture support.

I guess what I'm trying to get at is: Do you think my suggestion of just exposing the existing platform tap events though separate OxyPlot tap events would actually be counterproductive to the long-term plan for OxyPlot touch support?

P.S. Seems like Win8/WPF should also be tagged.

**Comment by objorke** [comment]
How many gesture events should be added? Only tap? Double-tap? Long press?
I agree we can implement this in platform-specific code if it is too much work to handle this in portable code. But this means it must be implemented for at least 4 different platforms (iOS, Android, Windows Universal, WPF).

**Comment by TheAlmightyBob** [comment]
What would you attach the portable gesture recognizers to? PlotModel? PlotView? Individual lines/axes/etc? The pan/zoom behavior is handled by ControllerBase/TouchManipulator, but presumably the whole idea for other gesture recognizers like Tap would be that the client app would create/attach them with its own custom event handlers, with ControllerBase/etc knowing nothing about them.... ?

I could imagine moving the iOS PanZoomGestureRecognizer into PCL, sticking that in-between PlotView and PlotController (or TouchManipulator?), and modifying the other platforms to provide similar low-level information to iOS (individual touchpoints, up/down/move/etc, rather than the current use of Windows manipulation events) to use it.... but that still doesn't get you to Tap.
(assuming that gesture recognizers are expected to be at the same level so that clients can add/remove/customize them and have them interact with each other the way they do on iOS)

(it *would* allow the other platforms to have KeepAspectRatioWhenPinching, and possibly reduce platform-specific bugs/inconsistencies with pan/zoom...)


(side-note, I was surprised to realize that there also doesn't appear to be a Click for the mouse-inclined...? not sure if that should be considered in relation to this...)

**Comment by objorke** [comment]
These are difficult questions :) I may need think more about this...
The idea behind the current design is to use gesture recognizers or subscribe to touch/mouse/key events on the platform side, then pass the relevant events to a portable `PlotController`. The default controller implementation passes the events to the elements of the plot (series, axes etc). It is also possible to create your own implementation of the "plot controller".

If you want to implement portable gesture recognizers, can this be done in a new `GestureRecognizerPlotController`? I understand it is a good pattern to use, but maybe it should not be mixed with the current event model?

I agree that consistency across the platforms is very important.

Yes, I think there has already been a request for a click-event. I have added #368

**Comment by TheAlmightyBob** [comment]
I was just trying to understand what the current state of thinking was wrt. your previous mention of "a more developer friendly gesture recognition system on top." (or did I misunderstand the goal of that?)

If you want to keep the current event model and not mix it with a gesture model, then things circle back to the original idea of "why not add a tap to the event model?"

Or it could just be Click, and both mouse and touch would fire it. Or follow the Windows route of calling it Tap for both mouse and touch. :)

**Comment by objorke** [comment]
Sorry, I don't have a clear picture of what should be done here at the moment - help on this issue is greatly appreciated!

My current understanding and standpoint on this topic is:
- Add tap (#340) and click (#368) events to controllers and models
- Use gesture recognizers instead of events in the `PlotView` implementations: Yes, if it simplifies or improves usability. (#359)
- Add support for portable gesture recognizers in OxyPlot: Will this add extra value? We should create a new issue about this. I guess the design needs to be discussed (find commonalities in iOS/AndroiD/WinPhone/WPF gesture recognizers, how to implement it...)

Gesture recognizer links: [iOS](https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/GestureRecognizer_basics/GestureRecognizer_basics.html) [win](https://msdn.microsoft.com/library/windows/apps/br241937) [android](http://developer.android.com/training/gestures/detector.html)

**Comment by Gaisuru** [comment]
Has there been any movement on this? You working on it @TheAlmightyBob ?

**Comment by TheAlmightyBob** [comment]
I am not. No movement that I know of.
I believe it can be worked around on iOS and Windows... not sure about Android, but I'm not set up to work on Android. Don't get me wrong, I still think this would be a valuable addition. It just stumbled a bit on the question of how best to address it cross-platform.

(now that Xamarin.Forms has finally done a bit more with their idea of cross-platform gesture recognizers, I wonder if there is any insight to be gained from their approach...)

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/25
since this is more than 50% related to Xamarin projects...
