### ISSUE TITLE
Layout problem of PlotView in windows phone 8.1

### ISSUE THREAD

**Issue by jiongyang** [oxyplot/oxyplot#346]
The PlotView will not show up when inside a StackPanel. Can be fixed by override the MeasureOverride method in PlotView class:
```csharp
        /// <summary>
        /// Provides the behavior for the Measure pass of layout. Classes can override this method to define their own Arrange pass behavior.
        /// </summary>
        /// <param name="availableSize"></param>
        /// <returns></returns>
        protected override Size MeasureOverride(Size availableSize)
        {

            if (double.IsInfinity(availableSize.Width))
            {
                availableSize.Width = availableSize.Height;
            }

            if (double.IsInfinity(availableSize.Height))
            {
                availableSize.Height = availableSize.Width;
            }

            if (double.IsInfinity(availableSize.Width))
            {
                return base.MeasureOverride(availableSize);
            }
            else
            {
                return availableSize;
            }

        }
```

**Comment by tibel** [comment]
The plot has no minimum or preferred size.
Setting MinWidth and MinHeight should help.

**Comment by objorke** [comment]
Can we close this issue?

**Comment by objorke** [comment]
Thanks, @tibel
@jiongyang, can we close this issue?

**Comment by jiongyang** [comment]
Thanks very much for your reply, @tibel @objorke. I think this is kind of a design issue. The main problem is that when the PlotView is put inside the StackPanel, the available size passed to its MeasureOverride method is infinity and it currently returns zero as the desired size, even when I set the alignment to stretch. Is this the excepted behavior? I am just worrying if we hardcode the size of the plot, it will not be able to automatically adjust its size based on the container?

**Comment by jiongyang** [comment]
Btw, @tibel @objorke, if you put the PlotView in a Grid which will pass a finite availableSize to the MeasureOverride, the PlotView will properly stretch its content to fill the entire grid without specifying the width or minwidth.

**Comment by objorke** [comment]
I think the current implementation is correct. The default values of `MinWidth` and `MinHeight` should be `0` for the `PlotView` control. If you want the control to fill all the available area, you should not use a `StackPanel`. This behaviour is consistent on all the XAML platforms, and also consistent with other XAML controls, I think.
