### ISSUE TITLE
Default constructor not found for type OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer

### ISSUE THREAD

**Issue by david-laundav** [oxyplot/oxyplot#348]
Having installed OxyPlot from the NuGet Package Manager like below:

`Install-Package OxyPlot.Xamarin.Forms -Version 2015.1.689-alpha -Pre`

An error occurs on iOS stating that:
`Default constructor not found for type OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer`

This issue is not present on Android. Have not tested on WP8.

Information:
Xamarin.Forms: 1.3.1.6296

**Comment by objorke** [comment]
There is no constructor now:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.Xamarin.Forms.Platform.iOS/PlotViewRenderer.cs
should we add one?

**Comment by david-laundav** [comment]
I think we will need to, as otherwise, the PlotViewRenderer crashes on iOS. I am although not sure doing so is the proper way to fix the issue. What would you recon, @objorke?

**Comment by david-laundav** [comment]
Needs to be added to NuGet

**Comment by objorke** [comment]
the Xamarin build must be done manually -  no CI for the Xamarin projects yet: #274 
will start a new build tonight!

**Comment by ReneWiersma** [comment]
What's the status of this? I'm running into this exact same issue right now.

**Comment by david-laundav** [comment]
@ReneWiersma If you build the source yourself, it will work. I don't think it's in the NuGet currently, as @objorke mentioned in the previous post. 

@objorke Do you know when OxyPlot.Xamarin.Forms will be continuously integrated?

**Comment by objorke** [comment]
This should be included in the latest pre-release package
https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2015.1.721-alpha
but I have not had time to verify myself yet.

CI of the Xamarin projects is covered by #274. Currently I have to get my Mac build host online, start the Windows build machine and trig the build manually. It would be great if it was possible to set up CI somewhere! Help wanted :-)

**Comment by david-laundav** [comment]
@objorke Awesome. I'll check it tonight. Isn't the release notes maintained anymore? I don't see that #348 should be included in 721-alpha. It'd be awesome if it was possible to see the changes so people wouldn't have to ask these questions.

Not sure about setting up CI. I have although just quickly looked up a few different services:
http://docs.solanolabs.com/introduction/
http://docs.travis-ci.com/user/getting-started/

**Comment by objorke** [comment]
@david-laundav The release notes should be updated in the PR, but it is possible that it was forgotten in #350.

I am not aware of any CI services that offer Xamarin builds yet. Currently, appveyor is used for the Windows builds. I don't think solanolabs and travis offer C#/Xamarin builds. Please use #274 for more links and ideas to solve that issue :-)

**Comment by david-laundav** [comment]
@objorke Ah, I see. I might have forgotten when I did the PR. Apologises. Should I make a new PR for changing the release notes, or could I have you quickly update them? The latter would be greatly appreciated. 

@objorke @ReneWiersma I just tested 2015.1.721-alpha, where this issue no longer exists. I will for that reason close this issue now.

**Comment by objorke** [comment]
@david-laundav I have updated the change log!

**Comment by david-laundav** [comment]
Awesome, thanks!
