### ISSUE TITLE
OxyPlot.Core PCL Profile 259 

### ISSUE THREAD

**Issue by ze-pequeno** [oxyplot/oxyplot#351]
When I install OxyPlot.Core on PCL projet that target Profile 259, I have the flollowing error : 

```
Install-Package : Could not install package 'OxyPlot.Core 2014.1.546'. You are trying to install this package into a project that targets 
'portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For 
more information, contact the package author.
```

Actually my project target Profile158, but I planned to switch to Profile 259 to use the latest MvvmCross version. Is there a way to make it work ?

**Comment by david-laundav** [comment]
This is probably an issue with your targets in your PCL. Try double-clicking on your Properties in your PCL, and remove "Windows Phone 8.1" from your targets. Use "Windows Phone Silverlight 8" (or 8.1) instead.

I have experienced this issue myself a bunch of times, and reproduced it just now.

**Comment by ze-pequeno** [comment]
When I remove "Windows Phone 8.1" from targets, profile switch to 78 ... "OxyPlot.Core" successfully installed, but I wan't to target Profile259. Profile 259 is Profile 78 + Windows Phone 8.1

**Comment by david-laundav** [comment]
Yeah, but you cannot, as of currently, target Windows Phone 8.1, which is why you get the error. I am using 78 myself which works fine, which you will probably have to do for now.

**Comment by ze-pequeno** [comment]
Yes I understand. It's possible to plan a fix for this ?

**Comment by david-laundav** [comment]
@objorke, do you what the roadmap is on supporting Windows Phone 8.1? Is that something we will do?

**Comment by objorke** [comment]
I don't like the idea of removing support for Windows Phone 8.1 - isn't that the future for Windows Phone development?

**Comment by david-laundav** [comment]
I don't think the idea was to remove support for Windows Phone 8.1, but rather include it. Right now, when you target "Windows Phone 8.1" instead of "Windows Phone Silverlight 8" (or 8.1) in your Core.PCL, NuGet will throw an error as seen in the original post.

**Comment by objorke** [comment]
Sorry, I misunderstood. Including support for Windows Phone 8.1 should of course be there. Please create a PR if it is not correct!

**Comment by david-laundav** [comment]
@objorke Could you add labels to this issue? Specifically "you-take-it", "help-wanted", "WindowsPhone" & "NuGet"?

**Comment by objorke** [comment]
We are currently on profile 328:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/OxyPlot.csproj

which should support for almost everything:
![image](https://cloud.githubusercontent.com/assets/439716/5922938/d6254bbe-a64f-11e4-9b5c-278652ed83b1.png)

What should be changed?

**Comment by ze-pequeno** [comment]
Maybe the OxyPlot.Core.nuspec to provide Profile259 assemblies ?

**Comment by objorke** [comment]
The targets defined in the .nuspec are "portable-net4+sl4+wp71+win8+wpa81"
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/OxyPlot.Core.nuspec

**Comment by ze-pequeno** [comment]
So I don't understand why install failed. Any idea ? Do you need more informations ?

**Comment by objorke** [comment]
Portable class library profiles: http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY/preview

**Comment by objorke** [comment]
should the nuspec target be changed to `portable-net4+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1` for profile 328?

**Comment by objorke** [comment]
I'll give it a try - also adding `+Xamarin.iOS10`

**Comment by ze-pequeno** [comment]
Actually OxyPlot works on my project that target Profile 158 : 
```xml
<package id="OxyPlot.Core" version="2014.1.546" targetFramework="portable-net45+sl50+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10" />```

**Comment by ze-pequeno** [comment]
I compared the different targets. 

Profile 158 : `portable-net45+sl5+netcore45+wp8+MonoAndroid1+MonoTouch1`
Profile 259 : `portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1` 
Profile 328 : `portable-net4+sl5+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1` 

The difference between 158 et 259 is that sl5 disappeared from 158 in favor of wpa81 on 259.

Maybe the nuspec should add specific target `portable-net4+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1`, based on 328 without sl5, to work on profile 259. What do you think of it ?

**Comment by ze-pequeno** [comment]
Sorry, but I just see that installation on profile 259 work with 2015.1.708-alpha release. 

I think it is due to the following change https://github.com/oxyplot/oxyplot/issues/161 that provides support for WP8.1

So I just have one more question, when the next stable release is planned for OxyPlot.Core and OxyPlot.Xamarin.Android ?

**Comment by objorke** [comment]
Great! Can we close this issue?

The stable release will happen when all issues in
https://github.com/oxyplot/oxyplot/milestones/v2015.1
are closed and testing has been done on all platforms!
Please contribute so we can get there!

**Comment by ze-pequeno** [comment]
Yes we can close this issue. 

Thank's, I will try to contribute
