### ISSUE TITLE
Change NuGet packages to use PCL bait and switch trick

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#358]
See http://log.paulbetts.org/the-bait-and-switch-pcl-trick/
How should the projects be set up? Should this only be applied to the Xamarin.Forms packages?

**Comment by mattleibow** [comment]
Based on th structure of the Xamarin.Forms NuGet, this will happen automatically. This cannot be done with the "normal" platform specific NuGets as the interfaces are a bit different.

**Comment by tibel** [comment]
OK, so bait-and-switch is only for the `OxyPlot.Xamarin.Forms` nuget package.
Still open is how to build the Xamarin.Forms package (see #274) with the right dependency versions.
