### ISSUE TITLE
Clean up NuGet Package Mess

### ISSUE THREAD

**Issue by JohannesRudolph** [oxyplot/oxyplot#374]
As much as I like flexible deployment options, I observe a troubling trend with an uncontrolled proliferation of packages in open source projects. OxyPlot unfortunately is no exception. 

Say I want to use OxyPlot with a Xamarin iOS and Android Project, plus a common library. All packages are pre-release it seems (which is fine), but there's too many and I couldn't at a quick glance find a documentation that pointed me to the "right" packages to use. Here's what I see: 

* OxyPlot.Xamarin.Android, 2015.1.721 depends on OxyPlot.Core same version
* OxyPlot.Xamarin.iOS, 2015.1.721 depends on OxyPlot.Core same version

So it seems there's individual packages for Silverlight, Forms, WPF etc. that you want users to use, which is all fine in my opinion. But then there's also "collection" packages like:

* OxyPlot, 2015.1.753, depends on nothing and says it's for all Windows/SL platforms but not Xamarin
* OxyPlot.Mobile, 2015.1.744, depends on core, same version

So.... I hope you get the point by now, it's not a great user experience. Either approach (individual packages or collection packages) seems fine to me, as you should be able to ship a collection package that contains libraries for every platform. Updating OxyPlot solution-wide should be easier in that case. 

In any case, I feel there should be only one way to do it. Happy to be convinced that both approaches have their merits, but then we need clear user guidance and all nuget packages should have same "freshness" = up to date versions all the time.

**Comment by objorke** [comment]
I totally agree on this, but I have not found a way to solve this yet. The windows based packages are built by AppVeyor, but we don't yet have CI for the mobil/Xamarin packages (#274).

**Comment by objorke** [comment]
I think #274 covers this issue, or should we find some other solution?

**Comment by JohannesRudolph** [comment]
It's not exactly about the freshness of the packages (i.e. I think it's not
relevant how they are built and pushed to nuget), but rather that there's
either a collection package to choose or individual packages. I can see the
collection package has advantages, so we could theoretically pull the
individual platform packages from NuGet? Either way I'm fine with it, as
long as one consistent approach is chosen.

**Comment by objorke** [comment]
See also #242. Would it be OK to have only 1 or 2 packages containing all the targets?

**Comment by JohannesRudolph** [comment]
1 or 2 packages -> great :+1: 

#242 looks like it captures what I was trying to say.
