### ISSUE TITLE
Unable to install OxyPlot.Mobile in Xamarin.Forms PCL

### ISSUE THREAD

**Issue by david-laundav** [oxyplot/oxyplot#375]
Since the new (738+), I am unable to install OxyPlot.Xamarin.Forms in my PCL as it depends on OxyPlot.Mobile which can't be installed in a PCL due to the following error:

Install-Package : Could not install package 'OxyPlot.Mobile 2015.1.744-alpha'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any ideas?

I am using Profile78 for my PCL.

**Comment by objorke** [comment]
Is this already fixed? @mattleibow 24b2138de0c18394b7989231f3d569f9989199cc (build 753)

**Comment by david-laundav** [comment]
@objorke If it is fixed in 753-alpha, do you know when it will be available?

Thanks.

**Comment by david-laundav** [comment]
I just built 753-alpha myself with 24b2138 myself, and it works correctly. I can reference the .dlls in the PCL as well as in the iOS project.

**Comment by objorke** [comment]
@mattleibow will you set up CI?

**Comment by rmarinho** [comment]
same issue here. i will wait for a new nuget build.

**Comment by objorke** [comment]
I received this message from Sonal B - I guess this is the same issue:

Hi ,

I tried the latest version of Oxyplot.Xamarin.Forms but its failed to install into portable project with below error message, where as it gets properly installed for all platform specific projects like Android,IOS and windows but fails for protable project.

```
PM> Install-Package OxyPlot.Xamarin.Forms -Pre Attempting to resolve dependency 'OxyPlot.Core (= 2015.1.744-alpha)'. 
Attempting to resolve dependency 'OxyPlot.Mobile (= 2015.1.744-alpha)'. Attempting to resolve dependency 'Xamarin.Forms'. 'OxyPlot.Xamarin.Forms 2015.1.744-alpha' already installed. 
Adding 'OxyPlot.Mobile 2015.1.744-alpha' to OxyDemo. 
Install-Package : Could not install package 'OxyPlot.Mobile 2015.1.744-alpha'. 
You are trying to install this package into a project that targets 'portable-net45+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. 
For more information, contact the package author. At line:1 char:1 + Install-Package OxyPlot.Xamarin.Forms -Pre + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

I have latest version of Nuget 2.8.50926.663 installed for Visual studio 2013 Am I missing anything ? Your help will be appreciated.

**Comment by david-laundav** [comment]
@objorke Yeah, installing OxyPlot to a PCL won't work prior to 753-alpha as I tested earlier due to the OxyPlot.Mobile dependecy. So, unfortunately, it is as expected, that Sonal B receives an error when trying to install 744-alpha. He/she will have to wait for when 753-alpha is released on NuGet.

**Comment by mattleibow** [comment]
@david-laundav , @objorke , @rmarinho , sorry about the delay. We are busy setting up CI on our side and somehow I missed the notifications from GitHub :(

**Comment by tibel** [comment]
Seems that this issue is resolved and can be closed?
