### ISSUE TITLE
aligning plots on separate panes (w/ shared axis)

### ISSUE THREAD

**Issue by tr8dr** [oxyplot/oxyplot#376]
I wanted to understand the best way to align a series of PlotViews where an X or Y axis may be shared.  Is the best approach to:

1. getting the sizing right:
    * create additional PlotViews with same dimension along axis to be aligned with
    * fix the size of __PlotModel.PlotMargins__ on all of the views so that differences in values on the axis do not cause misalignment?
2. getting the axes min/max synchronized
    * assume cannot reuse the same axis object on different panes due to PlotView specific state?   Hence must adjust Minimum and Maximum via events
     
Given the (potential) need to fix the margin sizes, is there a public property / method to interrogate an axis to determine its desired dimensions for some range?   And if so, does this need to be done post rendering (i.e. on an event after initial render)?

**Comment by objorke** [comment]
Please use the forum for questions, or change the formulation to a bug or feature request :-)

**Comment by dodikk** [comment]
@objorke , I believe this could be a feature request for supporting something like this :

![screen shot 2018-01-15 at 11 18 53 am](https://user-images.githubusercontent.com/396451/35056927-025a19de-fbbc-11e7-8d54-f6a2f4ec4d99.png)

1. We have two chart views
2. With the synchronized horizontal axes (top axis is invisible for this particular example)

So far I have not found any specific rules for creating a "feature request" issue. 
```
Suggesting new features
Please use the discussion forums or add it directly in the issue tracker in the same way as bug reports.
```

P.S. @tr8dr , have you managed to implement the "synchronized axis" thing ?

**Comment by dodikk** [comment]
Without this feature the only approach I see is

```
Hey, OxyPlot user! Go Emulate it yourself.
```

Some approaches :

### Approach 1
1. Use `Axis.LabelFormatter` to have same length of `Y` labels
2. The grids should match ==> profit

### Approach 2
1. Use a single `PlotView`
2. Normalize "blue" series to the scale of "green" series and add `blue.max()`
3. Add some `Axis.LabelFormatter` "magic" for values above `blue.max()` (actually, normalize the label value back to "blue" scale)
4. Profit : no changes to the library ==> some pain implementing this logic to make labels look "beautiful"

P.S. Sorry for "necro posting" or violating some repo rules I'm not aware of.

**Comment by dodikk** [comment]
> Please use the forum for questions,

Like this, I guess.
http://discussion.oxyplot.org/forums/1-general/topics/455-oxyplot-synchronized-axiss-for-two-chart/

**Comment by dodikk** [comment]
A forum discussion by @tr8dr . Unfortunately, it has not been answered.

http://discussion.oxyplot.org/forums/1-general/topics/687-aligning-plots-on-separate-panes-w-shared-axis/
