### ISSUE TITLE
ThreeColorLineSeries

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#378]
- Low and high limits
- Color and line style above the high limit
- Color and line style below the low limit
- The inherited Color and line style is used elsewhere

**Comment by objorke** [comment]
Thanks to Luka B for the following code:
https://gist.github.com/objorke/250d27c64cbe4f50ef15

Can someone create a PR?

**Comment by Camuvingian** [comment]
This is just what I have come here to search for, great stuff! Look forward to this being in the next release. For now I will add to my own project... Thanks very much.
