### ISSUE TITLE
StyleCop violation due to copyright year in file headers

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#380]
- customize the stylecop rule to allow different year in the copyright notice?
- change copyright to 2010-2015, update all files when necessary?
- remove year from copyright?

**Comment by tr8dr** [comment]
@objorke Don't really know what is appropriate re: yr.  If was in the US, apparently suggests (http://copyright.gov/circs/circ61.pdf):

> Year of Completion · Give the year of completion and the exact date of first publication, if any, for the 
> particular version of the computer program for which registration is sought.

Suggesting that in the US, 1st year of publication of the source (the year of authorship) may be important.  For my own code I tend to put a copyright date corresponding to the creation date of the file.

Am more concerned with code and functionality than copyright really ;)  I just noted that style-cop was locked to 2014.  So the wrong person to ask.
