### ISSUE TITLE
fixes for CandleStickAndVolumeSeries + VolumeSeries

### ISSUE THREAD

**Issue by tr8dr** [oxyplot/oxyplot#389]
1. missing UpdateMaxMin() for default axis sizing
    * I added UpdateMaxMin() and some behavior around this to allow the use of these series without explicitly setting Minimum and Maximum on the axes.
2. CandleStickAndVolume series would throw an exception if created with a Y axis without the "Bars" key (normally used to distinguish the volume and bars axis)
    * now will find a default axis if Axis.Key = "Bars" is not available

I have implemented tests for the above.

**Comment by objorke** [comment]
two different bugs -> should be two issues! :-)
