### ISSUE TITLE
Failed Implementation of Custom/Absolute StairStep Series

### ISSUE THREAD

**Issue by Camuvingian** [oxyplot/oxyplot#395]
I am attempting to create a new plot type in OxyPlot. I essentally need a StairStepSeries, but with any negative values replaces by their `Math.Abs` value and when this occurs, the line style to reflect this has happened (by using color and or `LineStyle`). So, to highlight what I want 

![plotexample](https://cloud.githubusercontent.com/assets/4823601/6351456/b68a386a-bc33-11e4-9ecb-c0dfd175c34e.png)

To do this, I have created the two classes (I have pasted actual code used below). This is conceptually easy when you know the tools you are working with, which I don't. My problem is directly related to my improper use of `rectangle.DrawClippedLineSegments()`. I can get a standard `StairStepSeries` plotting (copying the internal code) but when I attempt to use the `rectangle.DrawClippedLineSegments()` intuatively I realise I have not got a clue what this method does or how it is supposed to be used, but can't find any documentation. What is `rectangle.DrawClippedLineSegments()` doing and how should this method be used?

Any help anyone can provide (esp. changes or ammendments to my non-working class), it would be most appreciated. Thanks for your time.

---

_Code:_

    namespace OxyPlot.Series
    {
        using System;
        using System.Collections.Generic;
        using OxyPlot.Series;

        /// <summary>
        /// Are we reversing positive of negative values?
        /// </summary>
        public enum ThresholdType { ReflectAbove, ReflectBelow };

        /// <summary>
        /// Class that renders absolute positive and absolute negative values 
        /// but changes the line style according to those values that changed sign. 
        /// The value at which the absolute vaue is taken can be manually set.
        /// </summary>
        public class AbsoluteStairStepSeries : StairStepSeries
        {
            /// <summary>
            /// The default color used when a value is reversed accross the threshold.
            /// </summary>
            private OxyColor defaultColorThreshold;

            #region Initialization.
            /// <summary>
            /// Default ctor.
            /// </summary>
            public AbsoluteStairStepSeries()
            {
                this.Threshold = 0.0;
                this.ThresholdType = OxyPlot.Series.ThresholdType.ReflectAbove;
                this.ColorThreshold = this.ActualColor;
                this.LineStyleThreshold = OxyPlot.LineStyle.LongDash;
            }
            #endregion // Initialization.

            /// <summary>
            /// Sets the default values.
            /// </summary>
            /// <param name="model">The model.</param>
            protected override void SetDefaultValues(PlotModel model)
            {
                base.SetDefaultValues(model);
                if (this.ColorThreshold.IsAutomatic())
                    this.defaultColorThreshold = model.GetDefaultColor();
                if (this.LineStyleThreshold == LineStyle.Automatic)
                    this.LineStyleThreshold = model.GetDefaultLineStyle();
            }

            /// <summary>
            /// Renders the LineSeries on the specified rendering context.
            /// </summary>
            /// <param name="rc">The rendering context.</param>
            /// <param name="model">The owner plot model.</param>
            public override void Render(IRenderContext rc, PlotModel model)
            {
                if (this.ActualPoints.Count == 0)
                    return;

                // Set defaults.
                this.VerifyAxes();
                OxyRect clippingRect = this.GetClippingRect();
                double[] dashArray = this.ActualDashArray;
                double[] verticalLineDashArray = this.VerticalLineStyle.GetDashArray();
                LineStyle lineStyle = this.ActualLineStyle;
                double verticalStrokeThickness = double.IsNaN(this.VerticalStrokeThickness) ?
                    this.StrokeThickness : this.VerticalStrokeThickness;
                OxyColor actualColor = this.GetSelectableColor(this.ActualColor);

                // Perform thresholding on clipping rectangle. 
                //double threshold = this.YAxis.Transform(this.Threshold);
                //switch (ThresholdType)
                //{
                //  // reflect any values below the threshold above the threshold. 
                //  case ThresholdType.ReflectAbove:
                //      //if (clippingRect.Bottom < threshold)
                //          clippingRect.Bottom = threshold;
                //      break;
                //  case ThresholdType.ReflectBelow:
                //      break;
                //  default:
                //      break;
                //}

                // Perform the render action.
                Action<IList<ScreenPoint>, IList<ScreenPoint>> renderPoints = (lpts, mpts) =>
                {
                    // Clip the line segments with the clipping rectangle.
                    if (this.StrokeThickness > 0 && lineStyle != LineStyle.None)
                    {
                        if (!verticalStrokeThickness.Equals(this.StrokeThickness) || 
                             this.VerticalLineStyle != lineStyle)
                        {
                            // TODO: change to array
                            List<ScreenPoint> hlptsOk = new List<ScreenPoint>();
                            List<ScreenPoint> vlptsOk = new List<ScreenPoint>();
                            List<ScreenPoint> hlptsFlip = new List<ScreenPoint>();
                            List<ScreenPoint> vlptsFlip = new List<ScreenPoint>();
                            double threshold = this.YAxis.Transform(this.Threshold);
                            for (int i = 0; i + 2 < lpts.Count; i += 2)
                            {
                                switch (ThresholdType)
                                {
                                    case ThresholdType.ReflectAbove:
                                        clippingRect.Bottom = threshold;
                                        if (lpts[i].Y < threshold)
                                            hlptsFlip.Add(new ScreenPoint(lpts[i].X, threshold - lpts[i].Y));
                                        else
                                            hlptsOk.Add(lpts[i]);

                                        if (lpts[i + 1].Y < threshold)
                                        {
                                            ScreenPoint tmp = new ScreenPoint(
                                                lpts[i + 1].X, threshold - lpts[i + 1].Y);
                                            hlptsFlip.Add(tmp);
                                            vlptsFlip.Add(tmp);
                                        }
                                        else
                                        {
                                            hlptsOk.Add(lpts[i + 1]);
                                            vlptsOk.Add(lpts[i + 1]);
                                        }

                                        if (lpts[i + 2].Y < threshold)
                                            vlptsFlip.Add(new ScreenPoint(lpts[i + 2].X, threshold - lpts[i + 2].Y));
                                        else
                                            vlptsOk.Add(lpts[i + 2]);
                                        break;
                                    case ThresholdType.ReflectBelow:
                                        break;
                                    default:
                                        break;
                                }
                            }

                            //for (int i = 0; i + 2 < lpts.Count; i += 2)
                            //{
                            //  hlpts.Add(lpts[i]);
                            //  hlpts.Add(lpts[i + 1]);
                            //  vlpts.Add(lpts[i + 1]);
                            //  vlpts.Add(lpts[i + 2]);
                            //}

                            rc.DrawClippedLineSegments(
                                 clippingRect,
                                 hlptsOk, 
                                 actualColor,
                                 this.StrokeThickness,
                                 dashArray,
                                 this.LineJoin,
                                 false);
                            rc.DrawClippedLineSegments(
                                 clippingRect,
                                 hlptsFlip,
                                 OxyColor.FromRgb(255, 0, 0),
                                 this.StrokeThickness,
                                 dashArray,
                                 this.LineJoin,
                                 false);
                            rc.DrawClippedLineSegments(
                                 clippingRect,
                                 vlptsOk,
                                 actualColor,
                                 verticalStrokeThickness,
                                 verticalLineDashArray,
                                 this.LineJoin,
                                 false);
                            rc.DrawClippedLineSegments(
                                 clippingRect,
                                 vlptsFlip,
                                 OxyColor.FromRgb(255, 0, 0),
                                 verticalStrokeThickness,
                                 verticalLineDashArray,
                                 this.LineJoin,
                                 false);
                        }
                        else
                        {
                            rc.DrawClippedLine(
                                 clippingRect,
                                 lpts,
                                 0,
                                 actualColor,
                                 this.StrokeThickness,
                                 dashArray,
                                 this.LineJoin,
                                 false);
                        }
                    }

                    if (this.MarkerType != MarkerType.None)
                    {
                        rc.DrawMarkers(
                             clippingRect,
                             mpts,
                             this.MarkerType,
                             this.MarkerOutline,
                             new[] { this.MarkerSize },
                             this.MarkerFill,
                             this.MarkerStroke,
                             this.MarkerStrokeThickness);
                    }
                };

                // Transform all points to screen coordinates
                // Render the line when invalid points occur.
                var linePoints = new List<ScreenPoint>();
                var markerPoints = new List<ScreenPoint>();
                double previousY = double.NaN;
                foreach (var point in this.ActualPoints)
                {
                    if (!this.IsValidPoint(point))
                    {
                        renderPoints(linePoints, markerPoints);
                        linePoints.Clear();
                        markerPoints.Clear();
                        previousY = double.NaN;
                        continue;
                    }

                    var transformedPoint = this.Transform(point);
                    if (!double.IsNaN(previousY))
                    {
                        // Horizontal line from the previous point to the current x-coordinate
                        linePoints.Add(new ScreenPoint(transformedPoint.X, previousY));
                    }

                    linePoints.Add(transformedPoint);
                    markerPoints.Add(transformedPoint);
                    previousY = transformedPoint.Y;
                }

                renderPoints(linePoints, markerPoints);
                if (this.LabelFormatString != null)
                {
                    // Render point labels (not optimized for performance).
                    this.RenderPointLabels(rc, clippingRect);
                }
            }

            #region Properties.
            /// <summary>
            /// The value, positive or negative at which any values are reversed 
            /// accross the threshold.
            /// </summary>
            public double Threshold { get; set; }

            /// <summary>
            /// Hold the thresholding type.
            /// </summary>
            public ThresholdType    ThresholdType { get; set; }

            /// <summary>
            /// Gets or sets the color for the part of the 
            /// line that is above/below the threshold.
            /// </summary>
            public OxyColor ColorThreshold { get; set; }

            /// <summary>
            /// Gets the actual threshold color.
            /// </summary>
            /// <value>The actual color.</value>
            public OxyColor ActualColorThreshold
            {
                get { return this.ColorThreshold.GetActualColor(this.defaultColorThreshold); }
            }

            /// <summary>
            /// Gets or sets the line style for the part of the 
            /// line that is above/below the threshold.
            /// </summary>
            /// <value>The line style.</value>
            public LineStyle LineStyleThreshold { get; set; }

            /// <summary>
            /// Gets the actual line style for the part of the 
            /// line that is above/below the threshold.
            /// </summary>
            /// <value>The line style.</value>
            public LineStyle ActualLineStyleThreshold
            {
                get
                {
                    return this.LineStyleThreshold != LineStyle.Automatic ?
                        this.LineStyleThreshold : LineStyle.Solid;
                }
            }
            #endregion // Properties.
        }
    }
    
and the WPF class

    namespace OxyPlot.Wpf
    {
        using System.Windows;
        using System.Windows.Media;
        using OxyPlot.Series;

        /// <summary>
        /// The WPF wrapper for OxyPlot.AbsoluteStairStepSeries.
        /// </summary>
        public class AbsoluteStairStepSeries : StairStepSeries
        {
            /// <summary>
            /// Default ctor.
            /// </summary>
            public AbsoluteStairStepSeries()
            {
                this.InternalSeries = new OxyPlot.Series.AbsoluteStairStepSeries();
            }

            /// <summary>
            /// Creates the internal series.
            /// </summary>
            /// <returns>
            /// The internal series.
            /// </returns>
            public override OxyPlot.Series.Series CreateModel()
            {
                this.SynchronizeProperties(this.InternalSeries);
                return this.InternalSeries;
            }

            /// <summary>
            /// Synchronizes the properties.
            /// </summary>
            /// <param name="series">The series.</param>
            protected override void SynchronizeProperties(OxyPlot.Series.Series series)
            {
                base.SynchronizeProperties(series);
                var s = series as OxyPlot.Series.AbsoluteStairStepSeries;
                s.Threshold = this.Threshold;
                s.ColorThreshold = this.ColorThreshold.ToOxyColor();
            }

            /// <summary>
            /// Identifies the <see cref="Threshold"/> dependency property.
            /// </summary>
            public static readonly DependencyProperty ThresholdProperty = DependencyProperty.Register(
                "Threshold", typeof(double), typeof(AbsoluteStairStepSeries), 
                    new UIPropertyMetadata(0.0, AppearanceChanged));
            
            /// <summary>
            /// Identifies the <see cref="ThresholdType"/> dependency property.
            /// </summary>
            public static readonly DependencyProperty ThresholdTypeProperty = DependencyProperty.Register(
                "ThresholdType", typeof(ThresholdType), typeof(AbsoluteStairStepSeries), 
                    new UIPropertyMetadata(ThresholdType.ReflectAbove, AppearanceChanged));

            /// <summary>
            /// Identifies the <see cref="ColorThreshold"/> dependency property.
            /// </summary>
            public static readonly DependencyProperty ColorThresholdProperty = DependencyProperty.Register(
                "ColorThreshold", typeof(Color), typeof(AbsoluteStairStepSeries), 
                    new UIPropertyMetadata(Colors.Red, AppearanceChanged));

            /// <summary>
            /// Identifies the <see cref="LineStyleThreshold"/> dependency property.
            /// </summary>
            public static readonly DependencyProperty LineStyleThresholdProperty = DependencyProperty.Register(
                "LineStyleThreshold", typeof(LineStyle), typeof(AbsoluteStairStepSeries), 
                    new UIPropertyMetadata(LineStyle.LongDash, AppearanceChanged));

            /// <summary>
            /// Get or set the threshold value.
            /// </summary>
            public double Threshold
            {
                get { return (double)GetValue(ThresholdProperty); }
                set { SetValue(ThresholdProperty, value); }
            }

            /// <summary>
            /// Get or set the threshold type to be used.
            /// </summary>
            public ThresholdType ThresholdType
            {
                get { return (ThresholdType)GetValue(ThresholdTypeProperty); }
                set { SetValue(ThresholdTypeProperty, value); }
            }

            /// <summary>
            /// Get or set the threshold color.
            /// </summary>
            public Color ColorThreshold
            {
                get { return (Color)GetValue(ColorThresholdProperty); }
                set { SetValue(ColorThresholdProperty, value); }
            }

            /// <summary>
            /// Get or set the threshold line style.
            /// </summary>
            public LineStyle LineStyleThreshold
            {
                get { return (LineStyle)GetValue(LineStyleThresholdProperty); }
                set { SetValue(LineStyleThresholdProperty, value); }
            }
        }
    }

**Comment by objorke** [comment]
Is this a question? Please use the forum for long questions or gitter.im for short questions :-)

**Comment by Camuvingian** [comment]
Hi @objorke, I do apologize. I did not mean to clutter the Issues page. I had no idea it would post the entire code so explicitly. This is a question about usage of internal methods. I will have a look for the forum pages now. Sorry for any inconvenience.

**Comment by objorke** [comment]
@Camuvingian no problem! You see I am just trying to keep the issue list clean :)

**Comment by objorke** [comment]
we can try to answer the questions in the forum!

**Comment by Camuvingian** [comment]
@objorke I can't seem to ask the question in the forum. When I click "Post", it just says "Saving..." then nothing happens. Any help on this would be massively appreciated...

**Comment by Camuvingian** [comment]
If you could help me in this closed section, that would be most appreciated. I definitely cannot post in the Forum.

**Comment by objorke** [comment]
I tried myself, and it seems userecho is having some problems. But there is a post one hour ago...
Will have a quick look at your question!

**Comment by objorke** [comment]
http://discussion.oxyplot.org/topic/619659-/

sign in with Google+ dosn't seem to work

**Comment by Camuvingian** [comment]
I have attempted to sign in with GitHub. That does not work either.

**Comment by Camuvingian** [comment]
@objorke have you had any chance to take a look at this? I haveasked on SO with bounty here - http://stackoverflow.com/questions/28698703/new-plot-type-using-oxyplot
