### ISSUE TITLE
Build 546 does not work for windows phone 8.1

### ISSUE THREAD

**Issue by MannusEtten** [oxyplot/oxyplot#399]
could not install package oxyplot.core 2014.1.546 you are trying to install this package  into a project that targets windowsphoneapp, version=8.1 but the package does not containt any assembly references or content files that are compatible with that framework

:-(

**Comment by objorke** [comment]
Try to use the prerelease package `OxyPlot.WindowsUniversal` instead. I have tested it and it should work. Hopefully we can update the stable release soon!

**Comment by objorke** [comment]
Can we close this issue?

**Comment by MannusEtten** [comment]
i can't see a new version of OxyPlot Universal Apps and Oxyplot.Core in NuGet :-(

**Comment by tibel** [comment]
@MannusEtten You have to change the setting `Stable-only` to `Include Prereleases` in nuget package manager to see the new versions.

**Comment by tibel** [comment]
This issue can be closed.

**Comment by MannusEtten** [comment]
thanks I will look for that, i will also soon make new issues about the other things I found
