### ISSUE TITLE
iOS PlotView intercepts child view input

### ISSUE THREAD

**Issue by TheAlmightyBob** [oxyplot/oxyplot#400]
Sorry, it appears I introduced a small regression when refactoring the iOS gesture support to use a gesture recognizer. If there are other custom views overlaid on the PlotView, input intended for them will instead be captured by the gesture recognizer.

This can be worked around by setting a ShouldReceiveTouch delegate on the gesture recognizer to only act on the PlotView itself, but I'm guessing that should probably be the default behavior (preserving the previous behavior..).

(unless somebody thinks this new behavior is actually useful??)

**Comment by objorke** [comment]
I think this should be fixed, the `PlotView` gesture recognizer should act on itself.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
