### ISSUE TITLE
Zoom constraints

### ISSUE THREAD

**Issue by TheAlmightyBob** [oxyplot/oxyplot#401]
It would be nice to be able to specify a min/max zoom level (scale) for an axis, separate from the absolute min/max axis values.

(so that zooming could be restricted without restricting panning)

**Comment by Gaisuru** [comment]
It would be nice, but you can hack it together as is to accomplish this.

**Comment by objorke** [comment]
Good idea. Could the properties be called `MinimumRange` and `MaximumRange`, where 'range' is the difference between actual maximum and minimum? Default values `0` and `+INF`.

**Comment by tibel** [comment]
@tclaff @objorke Can this issue be closed now?

**Comment by tclaff** [comment]
Yes, it can be closed.
