### ISSUE TITLE
ColumnSeries incompatible with DateTimeAxis

### ISSUE THREAD

**Issue by camiteca** [oxyplot/oxyplot#402]
As a developer I would like to be able to show a ColumnSeries in a DateTimeAxis, like this:

![image](https://cloud.githubusercontent.com/assets/1260651/6524550/165bf674-c3fb-11e4-88dd-18ca9414fd1f.png)

![image](https://cloud.githubusercontent.com/assets/1260651/6525668/6763362e-c408-11e4-8b84-24e976d286af.png)

If I want to represent this right now, i'm obligated to create a CategoryAxis with my dates (in this case the week) and then format the label.

Is there a better aproach? Will this be supported?

**Comment by objorke** [comment]
I think `BarSeries` and `ColumnSeries` should only work with `CategoryAxis`. 

I guess the `DateTimeAxis` could be used if we defined the widths of the bars/columns (otherwise the series would not know if the bar/column should be presented as a millisecond/day/month/year...). But to keep it simple, I prefer the current approach.

**Comment by karlmtc** [comment]
I actually tried it the way you mention. My major problem is that I am not able to set the string format of the date without doing a custom LabelFormatter (datetime as "ddd" in the first case) and if i don't have a better way, I would be obligated to replicate this over all the charts of this type.

**Comment by objorke** [comment]
I think this can be related to #415

**Comment by objorke** [comment]
As shown in the example, the `StringFormat` property of the `CategoryAxis`  solves this.
Please create another issue if you need a `LinearColumnSeries` (similar to ´LinearBarSeries´) that can work with a a `LinearAxis`.
