### ISSUE TITLE
Update Plot when ItemsSource is collection and changes

### ISSUE THREAD

**Issue by MendelMonteiro** [oxyplot/oxyplot#406]
If ItemsSource implements INotifyCollectionChanged we should update the plot view when the collection changes.

**Comment by objorke** [comment]
Are you thinking in the portable code or WPF wrapper only? See also #136
#398

**Comment by MendelMonteiro** [comment]
I was thinking of doing it only for WPF.  Do you think this pattern would fit  other clients as well?

**Comment by objorke** [comment]
All the other platforms are using the portably model only!

**Comment by MendelMonteiro** [comment]
Am I right in thinking that if we want to implement this for all the client types we would move the implementation done for WPF into the OxyPlot.Series.ItemsSeries class?

**Comment by objorke** [comment]
Yes, I think it could also be implemented there.

If the model should implement the observable pattern, I think it should be done everywhere, otherwise it may create a lot of confusion...

**Comment by MendelMonteiro** [comment]
It's a pity but the current portability settings mean that INotifyCollectionChanged is not available in the portable project.  It's not supported for .NET frameworks before 4.5 and Silverlight 5.

Have you run into this in OxyPlot before?

**Comment by objorke** [comment]
Right, I guess this means it will be difficult to implement this feature... I don't want to include code that cannot be part of the portable library...

**Comment by objorke** [comment]
We could add a collection changed interface in OxyPlot.dll... And a generic list class that implements the interface and supports batch add/insert/remove... E.g. an `ObservableCollection<T>` alternative that also contains `AddRange`, `InsertRange` and `RemoveRange`...

**Comment by MendelMonteiro** [comment]
Interesting, it would be good to make it as explicit as possible in the API that you can use that interface. Maybe we could provide another alias property that is typed such as LiveItemsSource?

**Comment by tibel** [comment]
Support for `INotifyCollectionChanged` depends on #115.
