### ISSUE TITLE
Update Plot when series element in ItemsSource changes

### ISSUE THREAD

**Issue by MendelMonteiro** [oxyplot/oxyplot#407]
When the plot view is bound to a collection and one of the elements in the element's value changes we could update the plot view.

**Comment by objorke** [comment]
Related to #406 and #136

**Comment by objorke** [comment]
If this should be done, I think it should be done on all series - otherwise we need to create a lot of documentation where it is working and not...

**Comment by MendelMonteiro** [comment]
Enabling this could cause some issues with large data series as we would invalidate the plot on each property changed update.  Imagine an item which has 4 properties, each bound to a series - we would invalidate the plot 4 times for each item.

There might be some work to be done on optimising the re-draw when incremental updates are detected.

Given the amount of potential invalidations can you see a way of implementing this in a performant way?

**Comment by objorke** [comment]
- the items source could be disconnected when doing batch changes
- a transaction pattern could be used (begin/end edit on the plot model or the series)
- property changes could invalidate only and updating the plot model items could be done async, meaning that _probably_ all changes will be done before updating the model

**Comment by MendelMonteiro** [comment]
I like the third idea, pipelining the drawing steps to redraw the plot. I am going to dig into the code more to understand how the plot is invalidated.

The first two seem unnecessary as if you have a reference to the plot you can already manually invalidate it.
