### ISSUE TITLE
Color minor and major ticks differently

### ISSUE THREAD

**Issue by wmacoder** [oxyplot/oxyplot#417]
I need to color major ticks the same color thar major grid lines
and minor ticks the same color same color that minor grid lines
but I can find only one single property ticklinecolor for both ticks
can we split it?

**Comment by objorke** [comment]
Alt 1: add the properties `MinorTicklineColor` and `MajorTicklineColor` (similar to `MinorGridlineColor` and `MajorGridlineColor`) and mark `TicklineColor` obsolete.
Alt 2: add `MinorTicklineColor` only, default value `Automatic`. When set to `Automatic`, the minor tick lines should have the color specified in `TicklineColor`.
