### ISSUE TITLE
Port to DirectX

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#419]
implement
- render context for DirectX
- view for WPF?
- other platforms?

See http://discussion.oxyplot.org/topic/623652-direct3d-10-renderer-fork-of-oxyplot-ive-done-it/

**Comment by Nanako-Kbs** [comment]
I'll briefly describe current progress:
Direct3D10 is required (it works even on Intel HD Graphics though)
You can choose stroke color and stroke thickness, that's all (yeah).
There is one type of join. 
It can be multisampled.
It renders only lines, line segments and markers.
Original Shape renderer does the rest.
All calculations (clipping, screen-axis coords transformation, triangle strip creation) are mostly performed using Vertex/Geometry shaders. Tweaked versions of original routines also exist, they add some boost even without GPU acceleration, but we have to add some logic to choose between them.
Only WPF, XAML, all the sugar, but not within a design view (there is a stub for it).
WPF code and underlying series are separated, overall architecture is like original OxyPlot.
Implemented already:
- Line Series
- Scatter Series
- StairStep Series
- Linear Axis
- DateTime Axis

**Comment by issame** [comment]
what about Direct3D9 ?

**Comment by PsykotropyK** [comment]
Are you planning to implement the candlestick serie?

**Comment by wilkinscs** [comment]
Has there been any progress with this?

**Comment by objorke** [comment]
I don´t know the status of @Nanako-Kbs work. Is it in a public fork?
This feature does not have high priority from my side, sorry about that. :-)

**Comment by tibel** [comment]
Duplicates #124 Rendering by Direct2D / SharpDX
