### ISSUE TITLE
Xamarin Forms error MissingMethodException iOS.PlotViewRenderer

### ISSUE THREAD

**Issue by sirfilipef** [oxyplot/oxyplot#421]
Works fine in Android.

System.MissingMethodException: Default constructor not found for type OxyPlot.Xamarin.Forms.Platform.iOS.PlotViewRenderer

package id="OxyPlot.Core" version="2015.1.804-alpha" targetFramework="xamarinios10" 
package id="OxyPlot.Xamarin.Forms" version="2015.1.804-alpha" targetFramework="xamarinios10" 
package id="Xamarin.Forms" version="1.4.0.6341" targetFramework="xamarinios10"

**Comment by objorke** [comment]
This sounds like #348

**Comment by sirfilipef** [comment]
Sorry didnt understand, is this bug fixed? thanks

**Comment by objorke** [comment]
Maybe the problem has been reintroduced? Do we need to update the Xamarin Forms version to 1.4.0? I think it is currently at 1.3.3

**Comment by sirfilipef** [comment]
I think so, probably there is some incompatibility with the newer version of Xamarin Forms.

**Comment by kevinash** [comment]
Suggesting updating for Xamarin Forms 1.4, they updated PCL profile from 78 to 259.

**Comment by tibel** [comment]
@objorke Xamarin.Forms is updated to 1.4.1 would be great if you could create new nuget packages.

**Comment by objorke** [comment]
@sirfilipef can you test OxyPlot.Xamarin.Forms 2015.1.840-alpha? I created two new Xamarin Forms 1.4.1.6349 apps (both portable and shared) and could not reproduce this issue.

**Comment by kevinash** [comment]
Thanks! Confirmed - issue fixed in 840-alpha. Adding OxyPlot Xamarin Forms nugget package to existing shared project adds PCL library: OxyPlot.Xamarin.Forms

**Comment by kevinash** [comment]
However it is still a problem in 2015.1.843-alpha

**Comment by objorke** [comment]
I see the OxyPlot.Xamarin.Forms.dll assemblies are missing in 843-alpha. There is also a problem with iOS being shown as Unsupported.

**Comment by tibel** [comment]
@objorke compare https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2015.1.840-alpha and https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2015.1.843-alpha
In 840 everything looks good. What is the difference in 843?

**Comment by objorke** [comment]
I can only remember building 840-alpha. @mattleibow Did Xamarin build 843-alpha?

**Comment by objorke** [comment]
I built and pushed 847-alpha using the "build-mobile.cmd" and "push.cmd" command files. I am using the latest stable version of NuGet.exe and Xamarin.
