### ISSUE TITLE
Add a CONTRIBUTING.md file to describe what info should be supplied in an issue report

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#426]
see https://github.com/blog/1184-contributing-guidelines

I think an issue report should at least include:
- used platform and tools version
- used OxyPlot version
- version of dependencies (e.g. Xamarin.Forms, android sdk)
- description of the issue
- sample code to reproduce the issue

**Comment by objorke** [comment]
Yes, it would be a good idea to follow common practice!
Currently, I tried to put this into the documentation - but it could all be moved to a CONTRIBUTING.md
http://oxyplot.org/documentation/contributions
http://oxyplot.org/documentation/issues

**Comment by tibel** [comment]
What do you think of adding a common rule:
If you don't answer to a request by the developer within one month, the issue will be closed to prevent a huge list of stale issues.

**Comment by objorke** [comment]
Yes, if we cannot reproduce/need more info and get no more response I think the issue should be closed after some time. It could be an unspoken rule, or would you like to add it to the document?

**Comment by tibel** [comment]
I think it should be added to the document.
Only closing the issue without telling why it happened might be misleading.

**Comment by objorke** [comment]
Right, should comment when closing issues due to no response.
Who should close an issue, the issue reporter?

I think all information about how to contribute should be in one place, I suggest to remove from the docs and keep everything in the CONTRIBUTING.md file.

**Comment by tibel** [comment]
The issue __reporter__ can close the issue because:
- he/she verified the fix/change
- found out that it is not an OxyPlot issue but some problem in his/her code

In case the reporter does __not respond__ to a request:
- the project owner (you) are allowed to close the issue (e.g after one month)
- not sure if a contributor should be allowed to do this

Also it should be possible for someone else to __take over__ the issue from the reporter:
- he/she can reproduce the issue
- has some sample code
- has more time/information to assist in the resolution
- responds to requests by the project owner

**Comment by objorke** [comment]
Well written! I think all [team members](https://github.com/orgs/oxyplot/people) should be allowed to close issues due to no response.

**Comment by tibel** [comment]
An example: https://github.com/mathnet/mathnet-numerics/blob/master/CONTRIBUTING.md

**Comment by tibel** [comment]
Added a first version of the contribution guidelines.
