### ISSUE TITLE
PlotView not rendered

### ISSUE THREAD

**Issue by HippoBaro** [oxyplot/oxyplot#435]
I'm trying to render a simple chart on my Xamarin.Forms app.

Using the Nuget package gave me errors (much like #421 and #348), so i tried to use the source directly.
Everything compile without errors/warnings, but my plot is not rendered. I set some breakpoints to ensure the code is actually executed and it is. I used the default code provided by the documentation at oxyplot.org

Not at any point i have an exception or whatever.
Note that I only tested this on an iOS app, I don't know about Android or WP. I use Xamarin.Forms last stable update (1.4.1.6349).

Any clue ?
Thanks in advance !

**Comment by HippoBaro** [comment]
After further investigations, the problem only occur when my PlotView is not the Content of my ContentPage. If I set it as the child of a StackLayout for exemple, it doesn't appear.

Is this desired behaviour ?

**Comment by objorke** [comment]
Is Width/Height of the `PlotView` set?

**Comment by HippoBaro** [comment]
I'm... ashamed...

Indeed setting a RequestWidth/Height does work. But still, 
				VerticalOptions = LayoutOptions.Fill,
				HorizontalOptions = LayoutOptions.Fill,
should do the work no ?

Thank you for the help !

**Comment by objorke** [comment]
The `PlotView` should behave the same way as other views that do not have a minimum size. 
We have similar behavior on other XAML platforms, and from my understanding this is correct. Can anybody provide more information about this?

Can you/we close this issue?

**Comment by HippoBaro** [comment]
I have my solution so it's okay i think.
The thing that could be improve is : if I want my plot to fit the screen's width inside a Layout, I have to manually set my plotview size request to that absolute value. Problem is Xamarin.Forms do not provide such info (I can get it anyway) because it breaks the device agnostic philosophy of the technology. 

So it would be great to have LayoutOption support for OxyPlot.
