### ISSUE TITLE
Setting a custom PlotController on PlotView is ignored

### ISSUE THREAD

**Issue by monkeystador** [oxyplot/oxyplot#436]
Tested on development branch. Up-to-date 1. April .2015

I have a bit of code like this: 

```xaml
<DataTemplate>
                            <oxy:PlotView x:Uid="plot"
                                          x:Name="plot"
                                          Model="{Binding PlotModel}"
                                          Controller="{Binding Controller}">
                            </oxy:PlotView>
 </DataTemplate>
```

The Plotview fully ignores this. My ViewModel code works fine for the Model property though. 
Neither does this: 

```xaml
<DataTemplate>
                            <oxy:PlotView x:Uid="plot"
                                          x:Name="plot"
                                          Model="{Binding PlotModel}">
                           </oxy:PlotView>
<oxy:PlotView.Controller>
    <CustomPlotController/>
</oxy:PlotView.Controller>
 </DataTemplate>
```

I found that removing the default intialiser in `Oxyplot.Wpf.PlotView` non-argument constructor makes it work. But why i couldn't figure out.

**Comment by tjbobo** [comment]
Hi, I have same problem, I'am using code behind work around:

```csharp
var myController = this.PlotView.ActualController;
myController.UnbindAll();
myController.BindMouseEnter(PlotCommands.HoverPointsOnlyTrack);
```
etc.

**Comment by tibel** [comment]
I think this has to do with data templates (see #175) and there is no issue with using a custom plot controller.

@monkeystador I've updated the SimpleDemo and it works like a charm with a custom plot controller.

**Comment by classicboss302** [comment]
I am seeing something similar as well with the v2015 code. The v2014 code does not have this issue. My custom controller isn't being respected with the code below.
```xaml
<ItemsControl.ItemTemplate>
	<DataTemplate>
		<Grid>
			<oxy:PlotView Model="{Binding Plot}"
					Controller="{
						Binding CustomController,
						RelativeSource={RelativeSource Mode=FindAncestor, AncestorType={x:Type UserControl}}
					}" />
		</Grid>
	</DataTemplate>
</ItemsControl.ItemTemplate>

**Comment by classicboss302** [comment]
This is the commit that breaks this for me. While this may have to do with Data Templates, it was working before this commit and doesn't work after this commit.

https://github.com/oxyplot/oxyplot/commit/225d137b44c28b9c962c550f3d46f1b121c8024f

**Comment by classicboss302** [comment]
Some details from stepping through the code. The constructor for PlotView is setting the controller, and then a custom controller is not getting set. If the line in the constructor is commented out, then the custom controller is being set.

It seems the set here is where the problem starts as the value keeps coming back as the default Controller, and not returning the custom controller. Commenting out the SetValue also allows the custom controller to be set.

At this point, the problem gets beyond my knowledge.

```c#
        public PlotView()
        {
            this.Controller = new PlotController();
        }

        public IPlotController Controller
        {
            get
            {
                return (IPlotController)this.GetValue(ControllerProperty);
            }

            set
            {
                this.SetValue(ControllerProperty, value);
            }
        }

```

**Comment by objorke** [comment]
@monkeystador can you verify?

**Comment by objorke** [comment]
I think this issue is fixed.
