### ISSUE TITLE
Nuget install OxyPlot.Xamarin.Forms package picks wrong .DLL 

### ISSUE THREAD

**Issue by kevinash** [oxyplot/oxyplot#438]
BUG 1) Instead of OxyPlot.Xamarin.Forms.iOS (Unified, Shared iOS Forms project) the package looks for OxyPlot.Xamarin.iOS
Failed to resolve assembly: 'OxyPlot.Xamarin.iOS, Version=2015.1.804.0, Culture=neutral, PublicKeyToken=null'
BUG 2) Still missing OxyPlot.Xamarin.Forms.dll, have to manually browse for that dll

**Comment by tibel** [comment]
BUG 1: Sorry I don't understand what you mean? May you include some more details to the issue report, please.
BUG 2: Is described in #412

**Comment by objorke** [comment]
@kevinash Can you please test with OxyPlot.Xamarin.Forms 2015.1.840.alpha? I cannot reproduce this issue.

**Comment by objorke** [comment]
The latest version is now 847-alpha
