### ISSUE TITLE
Inaccurate tracker when using LogarithmicAxis

### ISSUE THREAD

**Issue by dungp** [oxyplot/oxyplot#443]
The tracker's value is way off. See sample code and screenshots below. I'm using OxyPlot for WPF version 2014.1.546.

Is there any quick fix for this? Many thanks!

```C#
        private PlotModel BuildPlotModel()
        {
            var model = new PlotModel();
            // Set up axes
            var xAxis = new LogarithmicAxis() { Position = AxisPosition.Bottom, Title = "X-Axis" };
            var yAxis = new LinearAxis() { Position = AxisPosition.Left, Title = "Y-Axis" };
            model.Axes.Add(xAxis);
            model.Axes.Add(yAxis);

            var series1 = new LineSeries();
            series1.Points.Add(new DataPoint(1, 1));
            series1.Points.Add(new DataPoint(2, 1.5));
            series1.Points.Add(new DataPoint(20, 2));
            series1.Points.Add(new DataPoint(30, 2.5));
            series1.Points.Add(new DataPoint(200, 3));
            series1.Points.Add(new DataPoint(400, 3.5));
            series1.Points.Add(new DataPoint(10000, 8));

            model.Series.Add(series1);

            return model;
        }
```

![image](https://cloud.githubusercontent.com/assets/6580106/7075996/1fbaeef2-ded4-11e4-9b8b-6d1ea57fa3e8.png)

![image](https://cloud.githubusercontent.com/assets/6580106/7076004/32a81b20-ded4-11e4-9fb3-6e3e71171cf4.png)

**Comment by dungp** [comment]
This is my finding so far:

In function GetNearestInterpolatedPointInternal in OxyPlot.Series.XYAxisSeries class, the following code from line 263-265 doesn't look to work with log axes:

```C#
double segmentLength = (sp2 - sp1).Length;
double u = segmentLength > 0 ? (spl - sp1).Length / segmentLength : 0;
dpn = new DataPoint(p1.X + (u * (p2.X - p1.X)), p1.Y + (u * (p2.Y - p1.Y)));
```

It linearly relates the ratio of screen lengths to the ratio of data, which works for linear axes but doesn't for log axes.

I think a solution could be to just inverse transform the screen point spl. I am not sure though.

**Comment by objorke** [comment]
I think you are right - the inverse transform should be used. Should not use linear interpolation in the data coordinate system.
