### ISSUE TITLE
PlotController should not intercept input per default

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#446]
Let's think about following example:
- plot model with no scollable axis (`IsPanEnabled = false`)
- using the mouse wheel on the plot view
- the plot controller sets the `args.Handled = true`
- this intercepts the event from bubbling (see `PlotBase.OnMouseWheel()`)

I think the implementation of `HandleCommand.HandleCommand()` is wrong.
It should not set `args.Handled = true` and return the value of `args.Handled`.

The responsibility for setting `args.Handled = true` should be on `IViewCommand` implementations.

**Comment by objorke** [comment]
Agree that it should be the responsibility of the commands to set `args.Handled = true`.
