### ISSUE TITLE
Support OxyPlot.Windows in Xamarin.Forms 

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#461]
Xamarin.Forms has _preview_ support for Windows (win81 and wpa81) platform (see 
https://developer.xamarin.com/guides/cross-platform/xamarin-forms/windows/).

Include the new platform when Xamarin has integrated it in the official Xamarin.Forms nuget package.

**Comment by tibel** [comment]
No universal support right now (separate win81 and wpa81).

**Comment by mattleibow** [comment]
I am looking at this, but for some reason the OnApplyTemplate method on the PlotView is not being called. I am just checking to see where the bug lies, and then will comity my changes.

**Comment by rikoivars** [comment]
Is there any progress about this functionality? 
It would be really useful, having the possibility to deploy a Xamarin app project under Windows 8.1, to be able to use the OxyPlot charts contained in that App for Win 8.1.
Indeed, it's my case, having developed a transversal App (also for Windows 8.1), which contains some OxyPlot graphics (that i can't currently use under the Windows 8.1 version of the App).

Regards.

**Comment by tibel** [comment]
Duplicate of #697

**Comment by clarkis117** [comment]
Any status update on this? I'm not seeing any of the packages on Nuget for UWP.
