### ISSUE TITLE
Xamarin Linker SDK Only targeting iOS fails under Release

### ISSUE THREAD

**Issue by rajeshxoriant** [oxyplot/oxyplot#469]
Hi,

I have used OxyPlot library to display few graphs in my iOS app which is developed in Xamarin.

When I am trying to build a package for releasing on app store, I am getting following exception

Error MT2002: Failed to resolve "System.Void OxyPlot.PlotModel::.ctor(System.String,System.String)" reference from "OxyPlot, Version=2014.1.546.0, Culture=neutral, PublicKeyToken=638079a8f0bd61e9" (MT2002)

It works perfectly in Debug mode.

I am using "Link SDK assemblies only" linker options, to keep my package size small.

Please advice.

**Comment by TWhidden** [comment]
Same issue for me.

**Comment by tibel** [comment]
This is a known issue in the latest _stable_ release.

Please try the _alpha_ version:
https://www.nuget.org/packages/OxyPlot.Xamarin.iOS/2015.1.859-alpha

or if you use Xamarin.Forms:
https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/2015.1.859-alpha

**Comment by tibel** [comment]
Similar to #479
