### ISSUE TITLE
Performance of LineSeries with Smoothing is bad

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#476]
The rendering performance and responsiveness of a plot with LineSeries and Smooth=true is very bad.
Already with a few points you see the issue.

Ideas
- don't re-calculate the smoothed points on every rendering (need a strategy when to re-calculate)
- add some collection changed event to the `Points` collection to mark series as dirty (needs re-calculate)

**Comment by tibel** [comment]
What about moving the smoothing to a separate series (see [Spline Series](http://www.highcharts.com/docs/chart-and-series-types/spline-chart))?

**Comment by objorke** [comment]
what about using [delegation](https://en.wikipedia.org/wiki/Delegation_pattern) for the interpolation feature? I think that gives more flexibility than inheritance. The same interpolation delegates can be used for both area series, line series and possibly others. It will also make it possible to use different types of interpolation methods.
