### ISSUE TITLE
Implementing IClonable 

### ISSUE THREAD

**Issue by issame** [oxyplot/oxyplot#478]
Hello,

I think that I would be useful is the PlotModel class implemented the IClonable interface, so we could copy the object and alter the copies if needed.

**Comment by tibel** [comment]
see last line at https://msdn.microsoft.com/en-us/library/system.icloneable%28v=vs.110%29.aspx

**Comment by issame** [comment]
What would you suggest if I want to copy a given PlotModel ? or just creating two from de very beginning ?

**Comment by tibel** [comment]
I think that it was never intended to copy/clone a `PlotModel` as it contains rendering (view) state information.

**Comment by objorke** [comment]
Could it copy everything but the view state information?

I would also like to see a major refactoring where the `PlotModel` is not containing any view state information... #112
