### ISSUE TITLE
Add more interpolation algorithms for LineSeries/AreaSeries smoothing

### ISSUE THREAD

**Issue by xeo-it** [oxyplot/oxyplot#494]
The Chart below is a simple AreaSeries Chart of the following values:  
0,4,100,100,100,100,100,100,100,0,0,0,0,0,0  with minimum = -10 and maximum = 110

![Chart](https://cloud.githubusercontent.com/assets/7143502/7695329/33383894-fe42-11e4-9e8b-9b362ba6d075.png)

I would expect the line to never go below 0 and above 100 but as you can see, it looks like few points have negative value and others are above 100.  
Below in red is how I would expect it to be:

![expected](https://cloud.githubusercontent.com/assets/7143502/7695381/01a0fc7a-fe43-11e4-82a3-53a08b725744.png)

**Comment by objorke** [comment]
I think this is the correct behavior of the current spline interpolation. Should other interpolators be supported?

**Comment by KaliCZ** [comment]
Yeah, we're dealing with the same issue right now, that the data actually go out of view in certain places. And the customer would really like it not to be that way. We may have to use a different tool to use if this won't get fixed soon.

**Comment by objorke** [comment]
It would be great to see more interpolation algorithms implemented! Currently we are using a cardinal (canonical) spline applied to the points in screen space:
http://en.wikipedia.org/wiki/Cubic_Hermite_spline#Cardinal_spline
https://msdn.microsoft.com/en-us/library/4cf6we5y.aspx
http://www.charlespetzold.com/blog/2009/01/Canonical-Splines-in-WPF-and-Silverlight.html

Other splines:
https://en.wikipedia.org/wiki/B-spline
http://en.wikipedia.org/wiki/Cubic_Hermite_spline
http://en.wikipedia.org/wiki/Centripetal_Catmull%E2%80%93Rom_spline
