### ISSUE TITLE
PlotView interferes with FlipView on Windows Phone/Universal

### ISSUE THREAD

**Issue by joshisunil-1983** [oxyplot/oxyplot#496]
hi,
In my windows phone app i have a flipview. This filipview contains plotview and other controls. when i am trying swipe over plotview it is not changing the view. may swipe gesture gulp by plotview and it may not reach to flipview.

thanks

**Comment by joshisunil-1983** [comment]
@tibel how can i resolve this issue.

**Comment by joshisunil-1983** [comment]
@tibel ,@objorke  please help to resolve the issue.

**Comment by objorke** [comment]
Sorry, I don't have time to look into this issue myself at the moment. The issue is tagged "help wanted" and "you take it" (an by "you" we mean anyone) - I also hope someone can look into this! :-)

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-winphone
