### ISSUE TITLE
LineSeries SMOOTH=True  will crash WinForm on rightclick

### ISSUE THREAD

**Issue by IvoTops** [oxyplot/oxyplot#499]
I have a WinForm OxyPlot graph whih works good when smooth = false for every lineseries

When I turn smooth on (set it to true when i create a lineseries) and when the graph shows I rightclick on the graph it will instantly crash. It happens in the latest stable AND alpha 2015.1.889 versions.

Without smooth the rightclick contextmenu I added shows. But when smooth is on it will give a null reference exception occurred when you rightclick on the chart. This is the stacktrace.

 	OxyPlot.dll!OxyPlot.Series.LineSeries.GetNearestPoint(OxyPlot.ScreenPoint point, bool interpolate) Line 305	C#
 	OxyPlot.dll!OxyPlot.Series.Series.HitTestOverride(OxyPlot.HitTestArguments args) Line 140	C#
 	OxyPlot.dll!OxyPlot.UIElement.HitTest(OxyPlot.HitTestArguments args) Line 64	C#
 	OxyPlot.dll!OxyPlot.Model.HitTest(OxyPlot.HitTestArguments args) Line 64	C#
 	OxyPlot.dll!OxyPlot.Model.HandleMouseDown(object sender, OxyPlot.OxyMouseDownEventArgs e) Line 87	C#
 	OxyPlot.dll!OxyPlot.ControllerBase.HandleMouseDown(OxyPlot.IView view, OxyPlot.OxyMouseDownEventArgs args) Line 83	C#
 	OxyPlot.WindowsForms.dll!OxyPlot.WindowsForms.PlotView.OnMouseDown(System.Windows.Forms.MouseEventArgs e) Line 368	C#

**Comment by IvoTops** [comment]
Can an OxyPlot developer check my fix and use it?

I looked at the code and it is missing a check for null  and it also does not return the result variable. Since I am not really githubbing I added what I think are the fixes below (two lines of code, see capital texts below between ========). I did only check LineSeries.cs and have not tested it.

        /// LINESERIES.CS - GetNearestPoint

        /// <summary>
        /// Gets the point on the series that is nearest the specified point.
        /// </summary>
        /// <param name="point">The point.</param>
        /// <param name="interpolate">Interpolate the series if this flag is set to <c>true</c>.</param>
        /// <returns>A TrackerHitResult for the current hit.</returns>
        public override TrackerHitResult GetNearestPoint(ScreenPoint point, bool interpolate)
        {
            if (interpolate)
            {
                // Cannot interpolate if there is no line
                if (this.ActualColor.IsInvisible() || this.StrokeThickness.Equals(0))
                {
                    return null;
                }

                if (!this.CanTrackerInterpolatePoints)
                {
                    return null;
                }
            }

            if (interpolate && this.Smooth && this.SmoothedPoints != null)
            {
                var result = this.GetNearestInterpolatedPointInternal(this.SmoothedPoints, point);
 
                if (result != null)   ======= CHECK FOR NULL SHOULD BE ADDED AS RESULT CAN BE NULL
                {
                    result.Text = StringHelper.Format(this.ActualCulture, this.TrackerFormatString, result.Item, this.Title, this.XAxis.Title ?? XYAxisSeries.DefaultXAxisTitle, this.XAxis.GetValue(result.DataPoint.X), this.YAxis.Title ?? XYAxisSeries.DefaultYAxisTitle, this.YAxis.GetValue(result.DataPoint.Y));
                    return result; // ======== I THINK YOU SHOULD RETURN THE RESULT HERE
                }
            }

            return base.GetNearestPoint(point, interpolate);
        }

**Comment by forum111** [comment]
No. Still not work
https://github.com/oxyplot/oxyplot/issues/931
