### ISSUE TITLE
sub/superscript in Axis titles doesn't work

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#50]
**Imported from [http://oxyplot.codeplex.com/workitem/10018](http://oxyplot.codeplex.com/workitem/10018)**

**[tan_force_dk](http://www.codeplex.com/site/users/view/tan_force_dk)** 2012-11-23 07:58
Here: <a href="http://oxyplot.codeplex.com/wikipage?title=Superscript%20and%20subscript" rel="nofollow">
http://oxyplot.codeplex.com/wikipage?title=Superscript%20and%20subscript</a> it is explained how to use super/subscript in titles, but at least for Axis titles it doesn't work.

**[objo](http://www.codeplex.com/site/users/view/objo)** 2012-12-16 10:11
this is related to <a href="http://oxyplot.codeplex.com/workitem/7717" rel="nofollow">
http://oxyplot.codeplex.com/workitem/7717</a>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-02-02 19:10
It now works for horizontal titles. Issue #7717 must be solved before it works on vertical titles.

Issue #9972 is also related to this.

**Comment by tscott98** [comment]
This appears to be fixed by #581. Suggest closing.

**Comment by tibel** [comment]
Thanks, for checking back on this.
