### ISSUE TITLE
Change in IsVisible LineSeries not reflecting on the plot.

### ISSUE THREAD

**Issue by adrianie** [oxyplot/oxyplot#505]
I am a beginner in programming, so sorry if I say something that makes no sense.

If I add a LineSeries to the PlotModel with the IsVisible property set to false and then later I change it to true, the Plot does not render the data in the LineSeries. If I do it on the other way, adding visible data and then turn the property to false it works, even if I turn it again to true.

Is this normal behaviour?

Thanks.

**Comment by tibel** [comment]
Have you called `plotModel.InvalidatePlot()` after changing `IsVisible`?

**Comment by adrianie** [comment]
That was the problem. I didn't think that PlotModel didn't realize that there was new data to plot, because though the graph didn't apper the legend did showed the name of the data with the changed visibility. 

Thank you very much.
