### ISSUE TITLE
Add a series that can display bars with a LinearAxis or a DateTimeAxis

### ISSUE THREAD

**Issue by ocoanet** [oxyplot/oxyplot#506]
I implemented a BarDataPointSeries class to display bars with a LinearAxis or a DateTimeAxis.
I can create a pull request to add this feature to OxyPlot.

I only implemented the WPF version but I can support more frameworks if needed.
It goes without saying that the series class name can be changed.

**Comment by objorke** [comment]
Yes. please create the series in the core library and include examples! :-)

**Comment by karlmtc** [comment]
I think this would close #402 as well.
