### ISSUE TITLE
OxyPlot.Xamarin.Android.2015.1.897-alpha contains no assemblies

### ISSUE THREAD

**Issue by jorisvergeer** [oxyplot/oxyplot#514]
I updated my dependencies the morning and I saw that OxyPlot.Xamarin.Android was updated but there were no assemblies in the package.

**Comment by ahmadawada11** [comment]
I have the same problem. any solution?

**Comment by tibel** [comment]
Should be fixed by pull #531

**Comment by mattleibow** [comment]
@ahmadawada11 @jorisvergeer the last few releases should be fixed - although until the fixes for #533 is merged, you will still have issues when installing the NuGet using VS. I will try and see where this bug lies.
