### ISSUE TITLE
All AppVeyor bulids are failing

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#516]
The AppVeyor builds started failing 1-2 days ago.
All while installing GTK#

See:
https://ci.appveyor.com/project/objorke/oxyplot/history

@objorke Do you have any idea what is going on?

**Comment by objorke** [comment]
gtksharp v2.12.26 was released in April, so this was surprising!
https://chocolatey.org/packages/gtksharp

I get a similar error when trying `cinst gtksharp` locally...

**Comment by tibel** [comment]
@objorke  Do you think this is a chocolatey issue?

What can be done to fix/workaround this to get builds running again?

**Comment by tibel** [comment]
Fixed by pull #527
