### ISSUE TITLE
Can't get keypress event for PlotControl

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#52]
**Imported from [http://oxyplot.codeplex.com/workitem/10020](http://oxyplot.codeplex.com/workitem/10020)**

**[mohitvashistha](http://www.codeplex.com/site/users/view/mohitvashistha)** 2012-12-21 17:04
I am tried to get the keypress event of PlotModel but I am not getting the same any how. even PreviewKeyPress is not coming.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
