### ISSUE TITLE
Transparency with Image Annotations

### ISSUE THREAD

**Issue by cfeltch537** [oxyplot/oxyplot#523]
Images lose all opacity when added as Image Annotations.

I'ts possible that I am mishandling my Image Annotaitons, but It appears as though the images from image annotations lose all opacity when added as image annotations.

**Comment by objorke** [comment]
On what platform is this happening?

**Comment by cfeltch537** [comment]
I using window, C#, WPF

**Comment by willmoore88** [comment]
I am also seeing this, windows c# wpf

**Comment by objorke** [comment]
The "ImageAnnotation" example in the example browser looks ok in WPF. Alpha channel of the png and the opacity of the `ImageAnnotation` works as expected.
Can you provide some code that reproduces the bug?

**Comment by willmoore88** [comment]
Yeah sure - I am using a bitmap though.

So firstly this is how I set the image source.

    foreach (ImageAnnotation a in CloudLayerPlotModel.Annotations)
                    {
                        a.ImageSource = Helpers.makeBitmap(allPolygons, null, Convert.ToInt16(actualWidth),     Convert.ToInt16(actualHeight), overlay);
                    }

This is the makeBitmap function. If it is called so that transparency is false and so the rectangle background is set to white, the bitmap is obviously fine and drawn with a white background. If I set the rectangle fill to transparent the annotation ends up being black.

        public static OxyImage makeBitmap(List<myScreenPoints> allPointsInfo, List<myScreenPoints> lineinfo, int arrayWidth, int arrayHeight, bool transparent = false)
        {
            // Create the bitmap we'll render to
            RenderTargetBitmap bmpLight =
                        new RenderTargetBitmap((int)arrayWidth, (int)arrayHeight, // Size
                                                                96, 96, // DPI 
                                                                PixelFormats.Pbgra32);
            StreamGeometry streamGeometry = null;
            StreamGeometryContext sgc = null;
            // The light-weight visual element that will draw the geometries
            DrawingVisual viz = new DrawingVisual();
            using (DrawingContext dc = viz.RenderOpen())
            { // The DC lets us draw to the DrawingVisual directly
                dc.DrawRectangle(transparent ? Brushes.Transparent : Brushes.White, null, new Rect(0,0,arrayWidth, arrayHeight));
                // draw any lines we have
                if (lineinfo != null)
                {
                    foreach (myScreenPoints msp in lineinfo)
                    {
                        Brush brush = (new SolidColorBrush(Color.FromArgb(msp.pointsColor.A, msp.pointsColor.R, msp.pointsColor.G, msp.pointsColor.B)));
                        Pen pen = new Pen(brush, 2);
                        for (int x = 0; x < msp.screenPoints[0].Count - 1; x++)
                        {
                            dc.DrawLine(pen, ToPoint(msp.screenPoints[0][x], false), ToPoint(msp.screenPoints[0][x + 1], false));
                        }
                    }
                }
                // draw points we have
                foreach (var allPoint in allPointsInfo)
                {
                    List<IList<ScreenPoint>> polygons = allPoint.screenPoints;

                    foreach (var polygon in polygons)
                    {
                        bool first = true;
                        streamGeometry = new StreamGeometry { FillRule = FillRule.Nonzero };
                        sgc = streamGeometry.Open();

                        foreach (var p in polygon)
                        {
                            if (first)
                            {
                                sgc.BeginFigure(Helpers.ToPoint(p, false), true, true);
                                first = false;
                            }
                            else
                            {
                                sgc.LineTo(Helpers.ToPoint(p, false), true, true);
                            }
                        }

                        sgc.Close();
                        Brush brush = (new SolidColorBrush(Color.FromArgb(allPoint.pointsColor.A, allPoint.pointsColor.R, allPoint.pointsColor.G, allPoint.pointsColor.B)));
                        Pen pen = new Pen(brush,1);
                        dc.DrawGeometry(brush, pen, streamGeometry);
                    } // the DC is closed as it falls out of the using statement
                }
            }
            // draw the visual on the bitmap
            bmpLight.Render(viz);
            using (System.IO.MemoryStream stream = new System.IO.MemoryStream())
            {
                var bitmapEncoder = new BmpBitmapEncoder();
                bitmapEncoder.Frames.Add(BitmapFrame.Create(bmpLight));
                bitmapEncoder.Save(stream);
                stream.Seek(0, System.IO.SeekOrigin.Begin);
                

                return new OxyImage(stream);
            }
        }

**Comment by willmoore88** [comment]
I have changed this to a png and you are correct, transparency works. However, I cannot see the annotation that is 'behind' this png. I am try to overlay two image annotations.

**Comment by objorke** [comment]
I think we should consider to remove support for BMPs...
PNGs (including alpha) and JPGs (no alpha) should be supported. I think we have a few issues around encoding of PNGs and getting width/height for JPGs. Do not want to add dependencies to other libraries..

**Comment by willmoore88** [comment]
Perhaps. Would you expect a bitmap image annotation to show below a png image annotation though?

**Comment by objorke** [comment]
yes, if the image with transparency is rendered after the other. Did  you check the order the annotations are added?

**Comment by willmoore88** [comment]
Yeah that was it. Thank you. Works a treat. 

Sent from Outlook Mobile




On Fri, Dec 18, 2015 at 1:07 PM -0800, "Oystein Bjorke" <notifications@github.com> wrote:












yes, if the image with transparency is rendered after the other. Did  you check the order the annotations are added?
