### ISSUE TITLE
Consider adding CollectionChanged event to ElementCollection

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#530]
It's already very good that you have introduced a custom collection. This allows easier customization for the future. One of the things I think this could be used for is to subscribe to child models. The PlotModel is not aware of any changes from the axes. I think it should or at least can be aware of this.

**Comment by tibel** [comment]
E.g. this is can be used for #476

**Comment by GeertvanHorrik** [comment]
Exactly, and for #519 . It's too complex to add this to the controller.

**Comment by GeertvanHorrik** [comment]
Going to implement this in a new PR.
