### ISSUE TITLE
Nuget Xamarin.iOS and Xamarin.Android packages corrupt

### ISSUE THREAD

**Issue by Gaisuru** [oxyplot/oxyplot#533]
When trying to install, it give the following error.
Attempting to resolve dependency 'OxyPlot.Core (= 2015.1.934-alpha)'.
'Default' tag requires a nonempty 'Extension' attribute. Line 1, position 378.

I assume it is the same as issue https://github.com/oxyplot/oxyplot/issues/184

**Comment by tibel** [comment]
@mattleibow Seems there is still an issue with the Xamarin NuGet packages.
