### ISSUE TITLE
AreaSeries crashes application when zooming in: OxyPlot.Xamarin.Android

### ISSUE THREAD

**Issue by nategraf** [oxyplot/oxyplot#544]
Using Oxyplot.Core 2015.1.950 and Oxyplot.Xamarin.Android 2015.1.950
At a certain point of zoom the application will suddenly crash. Only occurs when zooming in on the AreaSeries and does not occur on white space. 

Error output which was given when it crashed
07-21 17:52:23.874 I/art     ( 4453): Explicit concurrent mark sweep GC freed 11479(607KB) AllocSpace objects, 6(162KB) LOS objects, 61% free, 2MB/6MB, paused 457us total 16.541ms
07-21 17:52:23.884 D/Mono    ( 4453): GC_OLD_BRIDGE num-objects 1218 num_hash_entries 8380 sccs size 8380 init 0.00ms df1 30.96ms sort 1.84ms dfs2 6.42ms setup-cb 0.96ms free-data 8.12ms links 7188/7188/7226/4 dfs passes 16786/15568
07-21 17:52:23.884 D/Mono    ( 4453): GC_MINOR: (Nursery full) pause 47.84ms, total 47.96ms, bridge 52.54ms promoted 416K major 2000K los 11102K
07-21 17:52:25.474 I/art     ( 4453): Explicit concurrent mark sweep GC freed 7177(578KB) AllocSpace objects, 0(0B) LOS objects, 65% free, 2MB/6MB, paused 370us total 12.732ms
07-21 17:52:25.484 D/Mono    ( 4453): GC_OLD_BRIDGE num-objects 1066 num_hash_entries 8595 sccs size 8595 init 0.00ms df1 17.28ms sort 2.13ms dfs2 6.45ms setup-cb 0.78ms free-data 13.70ms links 7598/7598/15575/20 dfs passes 17259/16193
07-21 17:52:25.484 D/Mono    ( 4453): GC_MAJOR: (LOS overflow) pause 56.26ms, total 63.40ms, bridge 52.38ms major 2064K/2000K los 403K/14827K
07-21 17:52:27.024 E/mono-rt ( 4453): 
07-21 17:52:27.024 E/mono-rt ( 4453): Attempting native Android stacktrace:
07-21 17:52:27.024 E/mono-rt ( 4453): 
07-21 17:52:27.034 E/mono-rt ( 4453):  at ???+0 [0xb9abe2c0]
07-21 17:52:27.044 E/mono-rt ( 4453):  at ???+0 [0xc61c14]
07-21 17:52:27.054 E/mono-rt ( 4453): 
07-21 17:52:27.054 E/mono-rt ( 4453): =================================================================
07-21 17:52:27.054 E/mono-rt ( 4453): Got a SIGSEGV while executing native code. This usually indicates
07-21 17:52:27.054 E/mono-rt ( 4453): a fatal error in the mono runtime or one of the native libraries 
07-21 17:52:27.054 E/mono-rt ( 4453): used by your application.
07-21 17:52:27.054 E/mono-rt ( 4453): =================================================================
07-21 17:52:27.054 E/mono-rt ( 4453): 
07-21 17:52:27.054 F/libc    ( 4453): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x5c in tid 4560 (RenderThread)
07-21 17:52:27.054 W/libc    ( 4453): Security Level: (1), Debug inforamtion is controlled by the DUMPABLE flag.

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/29

**Comment by lkovac153** [comment]
Any progress on this issue? I am facing exact same exception and not sure if its up to my code or library.
