### ISSUE TITLE
Legend in CandleStickSeries does not scale correctly

### ISSUE THREAD

**Issue by kc1212** [oxyplot/oxyplot#554]
Hi, I noticed an issue where the legend in CandleStickSeries scales at the same rate as the graph, hence causing it to partially or completely cover the title text. Please see the screenshot (top right corner):
![oxyplot](https://cloud.githubusercontent.com/assets/1093806/9174944/f0d58fea-3f7a-11e5-8ff2-0e10410b703e.png)

I'm not sure what the correct behavior should be, but the text should be at least be in front of the Candlestick. 

I'm using version 2015.1.989-alpha in Windows Forms.

**Comment by objorke** [comment]
I guess the bug is in the width of the rendered legend:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Series/FinancialSeries/CandleStickSeries.cs#L196
