### ISSUE TITLE
CandleStick series on WPF PlotView

### ISSUE THREAD

**Issue by maurodx** [oxyplot/oxyplot#562]
Seems to be missing from WPF Series and I can't find how to add it to a WPF Plot. Is it available only on winforms?

**Comment by objorke** [comment]
I think the `Wpf.CandleStickSeries` can be implemented in a similar way as e.g.
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.Wpf/Series/BoxPlotSeries.cs

**Comment by Disin** [comment]
I can see CandleStick series both in WPF and WinForms (in example browser projects). Is this issue still active?

**Comment by Jonarw** [comment]
I think this referred to the WPF classes that could be used to define plots via XAML.
Those have been (re)moved in #1399, so I think this issue can be closed.
