### ISSUE TITLE
Xamarin Android Column Series disappear on zooming in

### ISSUE THREAD

**Issue by DevinvN** [oxyplot/oxyplot#563]
When I zoom in on the graph, columns start disappearing.
This also happens when I set the minimum and maximum of the linearaxis closer to the min and max values of the data.

I'm using OxyPlot in a Xamarin Forms application. This only happens on Android, tested on Windows Phone as well.

This is the linearaxis (gridlines markup code removed)

```
var valueAxis = new LinearAxis
{
      Minimum = minimum,
      Maximum = maximum,
      AbsoluteMaximum = maximum,
      AbsoluteMinimum = minimum,
      Position = AxisPosition.Left,
      StringFormat = "€ ##,##0",
      IsZoomEnabled = true,
      IsPanEnabled = true
};
```
 
![screenshot_2015-08-26-12-05-04](https://cloud.githubusercontent.com/assets/4228546/9490838/10414e60-4beb-11e5-98c1-2692843bdb4c.png)
![screenshot_2015-08-26-12-05-11](https://cloud.githubusercontent.com/assets/4228546/9490837/103eaeee-4beb-11e5-9df1-f6d2fa5283ba.png)

When I zoom in any further the columns disappear completely

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/20
