### ISSUE TITLE
Exception in Windows.UI.Xaml.UIElement.UpdateLayout()

### ISSUE THREAD

**Issue by AlexandrTsvetkov** [oxyplot/oxyplot#566]
I have added this in empty project windows universal app 8.1(windows phone) to MainPage.xaml file.

``` xaml
<Page
    x:Class="App5.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App5"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:windows="using:OxyPlot.Windows"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <windows:PlotView Margin="10,0,10,0"/>
    </Grid>
</Page>
```

And I have exception in UI designer in Visual studio and Blend
![13](https://cloud.githubusercontent.com/assets/6397482/9705284/7a5ed0c8-54c0-11e5-964e-a596640f1725.png)

```
Exception: Exception from HRESULT: 0x88000FA8
StackTrace
   at Windows.UI.Xaml.UIElement.UpdateLayout()
   at Microsoft.Expression.WindowsXamlPlatform.ViewObjects.WindowsUIXamlViewVisual.UpdateLayout()
   at Microsoft.Expression.WindowsXamlPlatform.Views.WindowsXamlSceneView.UpdateLayoutInternal()
   at Microsoft.Expression.DesignSurface.View.SceneView.UpdateLayout()
InnerException: None
```

When I write like this `Margin="10,0,0,0"` or this `Margin="0,0,10,0"` it works fine.

Microsoft Visual Studio Professional 2013 Version 12.0.40629.00 Update 5
Microsoft .NET Framework Version 4.5.51650
OxyPlot.Core 2015.1.1000-alpha
OxyPlot.Windows 2015.1.1000-alpha

**Comment by AlexandrTsvetkov** [comment]
I have debugged it and I have had the exception
`Windows.UI.Xaml.LayoutCycleException: A cycle occurred while laying out the GUI`
      `Message:Layout cycle detected.  Layout could not complete.`

**Comment by sumathij** [comment]
I have had the same exception while dragging from toolbox of my custom control. Is there any way to resolve this issue.?

**Comment by GeertvanHorrik** [comment]
Assuming this has been fixed in the most recent (unstable) versions available via MyGet. If not, please comment so we can re-investigate.
