### ISSUE TITLE
Android screenpoints are not in DP

### ISSUE THREAD

**Issue by Gaisuru** [oxyplot/oxyplot#580]
I am wanting to add something to the screen below the x-axis, so I use DefaultYAxis.Transform(DefaultYAxis.Minimum) to get the screen point. Ideally, it would give me screen pixels for that point within its parent view. It does this in iOS but the numbers on Android are not correct. The screen points are not accurate. I tried on two different phones with different screen densities and the numbers do not correlate.

One device with a Density of 3 returns a screen point of 155.
Second device with a Density of 2 returns a screen point of 85.
155 / 3 != 85 / 2

**Comment by objorke** [comment]
The axis transforms to OxyPlot's "screen" units that is platfrom independent. These may not be the same as the "native" units on the current render context. I think it could be the responsibility of the `PlotView` to convert to such "native" units (using the current RenderContext).

**Comment by Gaisuru** [comment]
If you multiple the screen point * the scale (which is 160/96) you get something that is full pixels. You would then have to reduce by density to get DP for android. I did notice that in this case, the DP is different based on the screen size. Which means for some reason, it is rendering the graph differently based on the screen density (which drove me nuts until i realized it).

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/28
