### ISSUE TITLE
WPF plot redraw slow when MinorGridlineStyle = LineStyle.Dot

### ISSUE THREAD

**Issue by rubear** [oxyplot/oxyplot#600]
I was plagued with slowness in my WPF application.  It was agonizingly slow just to resize the plot window.  Finally I found that if I changed the MinorGridLineStyle from "Dot" to "Solid", everything sped up by 10X

**Comment by objorke** [comment]
Right, dotted lines are slow on WPF. See also http://docs.oxyplot.org/en/latest/guidelines/performance.html
This is a WPF issue, I don´t think we can do anything about this in the OxyPlot library. I think we should close this issue.
