### ISSUE TITLE
AppVeyor urls for pull requests are wrong

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#604]
- When creating a new pull request the _Details_ url is in the old format. Something like `...2015.1...`
- When the build completes the _Details_ link on the pull request is
`https://ci.appveyor.com/project/objorke/oxyplot/build/1.0.0-PullRequest.603%2b1833+(Build+1053)`
- When checking on AppVeyor for the correct url 
`https://ci.appveyor.com/project/objorke/oxyplot/build/1.0.0-PullRequest.603+1833%20%28Build%201053%29`

The urls differ in the last to plus signs.

**Comment by objorke** [comment]
I don't find 2015.1 in the "Details" url on github. Did you correct this already?

The "build version format" in the Appveyor settings should not be used when we depend on gitversion, right?

Can we set the Appveyor "version" variable after gitversion has completed? Or is this not necessary?

Appveyor has a setting "Pull Requests do not increment build number" (A random string will be appended to build version to avoid collisions. This feature is GitHub specific.), I am trying to enable this now.

**Comment by objorke** [comment]
I see it is still wrong. Any idea how to solve this?
The "details" link on Github is now: 
`https://ci.appveyor.com/project/objorke/oxyplot/build/1.0.1055`
It should be: 
`https://ci.appveyor.com/project/objorke/oxyplot/build/1.0.0-PullRequest.606+1835%20(Build%201055)`

**Comment by objorke** [comment]
this seems to be fixed now

**Comment by objorke** [comment]
This seems to be working now, both during build and after build has completed.
