### ISSUE TITLE
OxyPlot.Xamarin.Android NuGet package 

### ISSUE THREAD

**Issue by ze-pequeno** [oxyplot/oxyplot#613]
OxyPlot.Xamarin.Android package has been unlisted from NuGet gallery. Is this package obsolete and not maintened anymore ?

**Comment by objorke** [comment]
See #612 - I am trying to build the Xamarin iOS, Android and Forms packages at the same time as the other packages. Hopefully we can get it to work soon!

**Comment by objorke** [comment]
The package is updated now.
Note that I had to change API level to 15. #614
