### ISSUE TITLE
Code generation does not work for candle stick series

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#634]
See #623

**Comment by lex2** [comment]
What's next?

**Comment by objorke** [comment]
for this issue I think we need some code that reproduces the bug!

**Comment by lex2** [comment]
my code?

**Comment by objorke** [comment]
I guess it is sufficient to create a `CandleStickSeries` with a single item to show the issue. Make it a unit test, please.

**Comment by lex2** [comment]
You dont need in my code. The problem that I described occurs in your example.
http://f2.s.qip.ru/twYEFNEf.png
![](http://f2.s.qip.ru/twYEFNEf.png)

It occurs when the open equals the close.

**Comment by lex2** [comment]
![](http://f1.s.qip.ru/twYEFNEg.png)

**Comment by lex2** [comment]
Agree with me?

**Comment by objorke** [comment]
This issue is about code generation of the items in the candle stick series.
I agree that the examples in the example library shows the issue. It is possible that this is a limitation for all series based on `ItemsSeries` and using `ItemsSource`.

**Comment by lex2** [comment]
Thanks for the reply. I hope that the problem I have encountered has been helpful.
