### ISSUE TITLE
PositionAtZeroCrossing Forces Value Axis Label

### ISSUE THREAD

**Issue by dsacharny** [oxyplot/oxyplot#635]
Hello,

If I set PositionAtZeroCrossing to true, then the value axis is displayed regardless of its visibility setting. See attached png for a screenshot. Also attached is the code that produces this state, notice that the valueAxis.IsAxisVisible = false.

![image](https://cloud.githubusercontent.com/assets/12567978/10713294/296f2ee0-7a74-11e5-881b-87039b439394.png)

            var plotModel = new PlotModel
            {
                Title = "OxyPlot in Xamarin.Forms",
                Subtitle = string.Format("OS: {0}, Idiom: {1}", Device.OS, Device.Idiom),
                Background = OxyColors.LightYellow,
                PlotAreaBackground = OxyColors.LightGray,
                PlotAreaBorderColor = OxyColors.Transparent,
            };
            var categoryAxis = new CategoryAxis { Position = AxisPosition.Bottom };
            categoryAxis.PositionAtZeroCrossing = true;
            var valueAxis = new LinearAxis { Position = AxisPosition.Left, MinimumPadding = 0 };
            valueAxis.Minimum = -14;
            valueAxis.Maximum = 14;
            valueAxis.PositionAtZeroCrossing = true;
            valueAxis.IsAxisVisible = false;
            plotModel.Axes.Add(categoryAxis);
            plotModel.Axes.Add(valueAxis);
            var series = new ColumnSeries();
            series.Items.Add(new ColumnItem { Value = 3 });
            series.Items.Add(new ColumnItem { Value = 14 });
            series.Items.Add(new ColumnItem { Value = 11 });
            series.Items.Add(new ColumnItem { Value = 12 });
            series.Items.Add(new ColumnItem { Value = 7 });
            plotModel.Series.Add(series);

            this.MainPage = new ContentPage
            {
                Padding = new Thickness(0, 20, 0, 0),
                Content = new PlotView
                {
                    Model = plotModel,
                    VerticalOptions = LayoutOptions.Fill,
                    HorizontalOptions = LayoutOptions.Fill,
                },
            }

**Comment by objorke** [comment]
I think it is the "zero"-line of the horizontal axis that is in the wrong place.
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/Rendering/HorizontalAndVerticalAxisRenderer.cs#L412

**Comment by objorke** [comment]
The changes have been merged, please verify

**Comment by objorke** [comment]
@dsacharny can you verify that the issue has been fixed?

**Comment by dsacharny** [comment]
Yes, I'm sorry for the delay - just finished a hellish semester. I'll check it out ASAP and get back to you. Thank you for looking into it!

**Comment by dsacharny** [comment]
Okay! hey works great, thank you!

**Comment by objorke** [comment]
thanks for verifying!
