### ISSUE TITLE
Null reference exception in ScatterSeries{T}

### ISSUE THREAD

**Issue by karlmtc** [oxyplot/oxyplot#636]
Pretty much like #605, the problem seems to be that we are accessing a property of ActualPoints when ActualPoints is null. Here's my stack, in case it helps.

![image](https://cloud.githubusercontent.com/assets/1260651/10732529/d17f9ab6-7bfa-11e5-8311-d9e8d4809a51.png)

**Comment by objorke** [comment]
Need more info about how to reproduce the error. The problem could be somewhere else than the location of the exception.

**Comment by karlmtc** [comment]
I'm trying to reproduce it, but i've been unsuccessful so far. I think the problem might be related to the renderization of the control. Somehow when positioning the control on the WPF layout, the "ActualPoints" is yet null and throws the exception. I'll dig into this but I haven't been able to reproduce it yet.
