### ISSUE TITLE
Update Xamarin.Forms dependency

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#638]
Latest stable release
https://www.nuget.org/packages/Xamarin.Forms/

**Comment by tibel** [comment]
maybe we should upgrade to Xamarin.Forms 2.0.0.6482 ?

**Comment by objorke** [comment]
Yes!

**Comment by objorke** [comment]
It would be great if all the example projects (including the projects in the documentation repo) were updated at the same time.

**Comment by objorke** [comment]
Latest now is 2.0.0.6490

**Comment by objorke** [comment]
I will take this issue.
