### ISSUE TITLE
MaximumPadding become useless after zoom in & out

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#64]
**Imported from [http://oxyplot.codeplex.com/workitem/10048](http://oxyplot.codeplex.com/workitem/10048)**

**[sharethl](http://www.codeplex.com/site/users/view/sharethl)** 2013-05-13 04:59
Verion: d190d7748a73 

when plot shows up, it has 30% padding, 

but once use wheel to zoom in, and out, plot's Y stopped at MaxY. 

Double click wheel reset plot, 30% padding shows up.

<pre><code>           // set x max, min
            this.XAxis.AbsoluteMaximum = dataPoints.Last().X;
            this.XAxis.AbsoluteMinimum = dataPoints.First().X;
            // set y max, min
            this.YAxis.AbsoluteMaximum = MaxY;
            this.YAxis.AbsoluteMinimum = 0;
            // set y pading
            this.YAxis.MaximumPadding = 0.3;
            this.YAxis.MinimumPadding = 0;</code></pre>

**[sharethl](http://www.codeplex.com/site/users/view/sharethl)** 2013-05-13 05:03
With this coding fixed this problem

Set padding first, then increase MaxY by same %.

<pre><code> // set x max, min
            this.XAxis.AbsoluteMaximum = dataPoints.Last().X;
            this.XAxis.AbsoluteMinimum = dataPoints.First().X;
            // set y pading
            this.YAxis.MaximumPadding = 0.3;
            this.YAxis.MinimumPadding = 0;
            // set y max, min
            this.YAxis.AbsoluteMaximum = MaxY * (this.YAxis.MaximumPadding+1);
            this.YAxis.AbsoluteMinimum = 0;</code></pre>

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
