### ISSUE TITLE
No target for 'native,Version=v0.0' under Visual Studio 2015 Ent. 

### ISSUE THREAD

**Issue by agosch** [oxyplot/oxyplot#642]
Hi, today i tried to install OxyPlot.WindowForms for my project under Visual Studio 2015 Enterprise with NuGet but everytime i try to install it, I get the following error:

> The package "OxyPlot.Core 1.0.0-unstable1873" couldn't be installed.  You try to install this package  in show, a project which refers to " native , Version = v0.0 ", the package contains no But assembly  references or content files , die compatible with this framework...

Is there any way to fix this?

**Comment by tibel** [comment]
I'm using VS 2015 Community with no problems.

That looks strange:
> " native , Version = v0.0 "

What exactly are you trying?
- project type (I suppose it's WinForms)
- .NET Framework version (OxyPlot requires at least 4.0 or newer)

**Comment by agosch** [comment]
I'm using .Net Version 4.5.2 and i'm using a Visual C++ CLR Project to create a WindowForms application.

**Comment by tibel** [comment]
OxyPlot is a .NET assembly, so it supports managed language projects.

Visual C++ CLR is a mixed mode assembly, it can contain native and manged code.
I think this is a limitation of NuGet that it is not possible to install managed assemblies into C++ projects.

Can we close this issue?

**Comment by agosch** [comment]
Yes we can close this issue, I'll use gnuplot.
