### ISSUE TITLE
Make legends open for extension

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#644]
- Add a property `Legends` to the `PlotModel`. Type `ElementCollection<Legend>` similar to `Axes` and `Series`.
- Move the current legend code into a new `Legend` class
- Refactor the layout (measure/arrange) engine to support multiple legends
- Include some examples

**Comment by objorke** [comment]
@axg1010 takes this task

**Comment by objorke** [comment]
The current legend properties in `PlotModel` should be marked obsolete, but still kept around for some time.

**Comment by objorke** [comment]
Should the legends collection be initialized with one default legend?
Or should a default legend be used if the collection is empty?
Or should we require a legend to be added, otherwise no legends will be shown? (breaking change)

**Comment by beanmf** [comment]
Suggestion on legend selection (mouse-clicks).  As legends naturally point at series and as there can be overlaid series, clicking on a legend could bring the linked series to the fore.  This is especially useful in sets of overlaid series where only the foremost is labelled, as it allows simplicity of view (reduced number of labels).  Current foremost series could correspond to the topmost legend.

**Comment by objorke** [comment]
I think clicking on legends should be covered by #315.

This issue is only covering refactoring of the legend architecture.

**Comment by objorke** [comment]
@axg1010 are you working on this one, or should I take it?

**Comment by beanmf** [comment]
Happy New Year Oystein.  Go ahead, we are still working on intelligent peak labeling.  Looking better every day.

I’d reply in OxyPlot but it doesn’t remember my login ☺

Mark

**Comment by forum111** [comment]
You may start from here. This is for axis titles or plot title but it will work on legend too.

` ChartPlot.MouseDown+= delegate(object sender, OxyMouseDownEventArgs e)
                {
                                     
                    OxyPlot.Wpf.PlotView plotView = ChartPlot.PlotView as OxyPlot.Wpf.PlotView;                                      
                    var hitPosition = VisualTreeHelper.HitTest(plotView, new Point(e.Position.X, e.Position.Y));                 
                    var selectedTextBlock = hitPosition.VisualHit as TextBlock;

                    if (selectedTextBlock != null)
                    {
                        string oldText = selectedTextBlock.Text;

                     

                    }

                };`
