### ISSUE TITLE
Cannot set LineStyle/Color on LineAnnotation by Style

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#645]
Exception when setting LineStyle or Color 
See http://discussion.oxyplot.org/topic/991150-lineannotation-set-default-style/

**Comment by objorke** [comment]
The problem seems to be wrong owner type of PathAnnotation dependency properties

**Comment by HermanEldering** [comment]
It seems like this still doesn't work, or I am doing something wrong...

    <oxy:PlotView Grid.Row="0" x:Name="plot" Model="{Binding Path=PlotModel}">
        <oxy:PlotView.Resources>
             <Style TargetType="oxy:LineAnnotation">
                <Setter Property="Color" Value="Yellow" />
                <Setter Property="LineStyle" Value="Solid" />
            </Style>
        </oxy:PlotView.Resources>
    </oxy:PlotView>

**Comment by eocron** [comment]
PlotView still doesn't have any reasonable way to change its view (colors, fonts etc) other than through some code behind hacks it seems.
