### ISSUE TITLE
Update OxyPlot component in Xamarin component store

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#650]
https://components.xamarin.com/view/oxyplot

**Comment by objorke** [comment]
- [ ] Update examples https://github.com/oxyplot/xamarin-component/tree/master/src/samples
- [ ] Update version number https://github.com/oxyplot/xamarin-component/blob/master/make.sh
- [ ] Rebuild the component

**Comment by objorke** [comment]
I think this issue must be addressed after v1.0 has been released.

**Comment by tibel** [comment]
You are right.
Also this issue is in the wrong repository (issue tracker).
It should be moved to https://github.com/oxyplot/xamarin-component/issues

**Comment by tibel** [comment]
moved issue to xamarin-component

**Comment by objorke** [comment]
thanks!
