### ISSUE TITLE
Could not load file or assembly 'OxyPlot.Wpf'

### ISSUE THREAD

**Issue by Zygonie** [oxyplot/oxyplot#651]
Hi,
I used to work with Oxyplot which is an awesome project, but I have some issue with my new projects.
First, OxyPlot.Wpf is not available anymore in nuget manager, but I can install latest STABLE version with the nuget console. I can design my GUI, but at runtime, I have this error :

'Could not load file or assembly 'OxyPlot.Wpf, PublicKeyToken=75e952ba404cdbb0' or one of its dependencies. The system cannot find the file specified.'

Setup
VS2013
.NET v4.0

Note that I have a several months old project with OxyPlot and it works perfectly. I dont know why I can get it run with new projects ?

**Comment by objorke** [comment]
When we changed to semantic versioning and changed next version number to 1.0 we had to "unpublish" all versions with greater version number at NuGet. Currently we only have "unstable" releases public. Hopefully we can release 1.0 soon! Currently we have 5 open issues

**Comment by Zygonie** [comment]
Ok thanks !
I finally found the origin of my issue....
The window I use to embed an OxyPlot control was in a WPF User Control Library project that I referenced in a simple console project. At runtime, the OxyPlot library was unable to load. However, if I referenced the OxyPlot dll in the console project tool, the dll were loaded and it worked.
Do you have an explanation for that ?

**Comment by objorke** [comment]
Is this an issue?
The latest pre-release OxyPlot.Wpf package (1.0.0-unstable1875) seems to work well (tested in VS 2015).

**Comment by Zygonie** [comment]
Probably not an issue, but probably linked to the way VS loads assemblies....

**Comment by Zygonie** [comment]
I have still the problem when I use OxyPlot.Wpf in a Debugger Visualizer.... 
The assembly is not found at realtime :(

**Comment by objorke** [comment]
Which debugger visualizer? Is the visualizer supporting PCLs? 
Need more info about how to reproduce :-)

**Comment by Zygonie** [comment]
I know two ways to reproduce the behavior:

1- Create a console application. In the same solution, create a User Custom Control Library where you have just a window control that contains an OxyPlot PlotModel. Then, in the console application, simply instanciate the window and try to show it. A "FileNotFoundException" is thrown telling that it was unable to load the OxyPlot assembly. To fix the issue, I needed to reference the OxyPlot dll in the console application too....

2- Pretty the same as before, but instead of a console application, use a custom debugger visualizer. The visualizer will also instanciate a WPF window (yes it is possible, not just winforms) that contains an OxyPlot PlotModel. The same exception is thrown. I haven't tried to manually resolve the assembly, that's my next trial.

Need more details ? Oh, and I don't know if the visualizer supports PCL, how to know ?

**Comment by objorke** [comment]
Can you do this with other Wpf Custom controls that depends on a portable class library? Is the debugger visualizer open source?

**Comment by Zygonie** [comment]
I haven't tested it with other custom controls that depend on a PCL (I don't think I have one anyway).
My debugger is not open source, but I've build a one with a console application you can look at to see what I mean [Debugger Visualizer with OxyPlot.Wpf](https://github.com/Zygonie/OxyPlotVisualizerExample)

**Comment by tibel** [comment]
Look into your `VisualizerTestApplication\bin\Debug` folder `OxyPlot.Wpf.dll` is not there.
When you copy it to this folder everything works as expected (tested with VS2015).

This might be an MSBuild issue, that some assemblies are not copied to the other project output folder.

**Comment by Zygonie** [comment]
well ok, but it is not useful. The Oxyplot.Wpf.dll is not in the GAC and for a debugger visualizer, it might not be in the application AppDomain. Take the content of the debug/release folder of the visualizer (not the test application), copy in the VS20xx/Visualizers folder, build a simple console application with a double array and put a breakpoint to use this debugger visualizer. It might not work even though the OxyPlot.Wpf.dll is in the visualizer folder.

**Comment by tibel** [comment]
I use OxyPlot WPF (latest unstable) in my projects without any issues.
So it might have something to do with DebugVisualizers 
and how Visual Studio handles assembly resolving for them.

**Comment by GeertvanHorrik** [comment]
Assuming this has been fixed in the meantime. If not, feel free to comment so we can reopen and do a new analyses.

**Comment by robiwano** [comment]
I get the same exact problem, doing a debugger visualizer.

**Comment by robiwano** [comment]
and OxyPlot.dll and OxyPlot.Wpf.dll are copied to the deployment folder.

**Comment by richard-adlz** [comment]
The debugger loads PresentationManager, which seems to have no idea where to find the OxyPlot.Wpf.dll. I assume it's to do with not being strongly typed. The solution I found (for now) is to load the OxyPlot.Wpf assembly _before_ trying to display anything.

    `Dim lType = New OxyPlot.Wpf.AngleAxis`

in the viewmodel is sufficient to get everything loaded.
