### ISSUE TITLE
Unable to install Oxyplot.Xamarin.Forms

### ISSUE THREAD

**Issue by Femilshajin** [oxyplot/oxyplot#653]
When I try to add the oxyplot package from Nuget Package. I'm encountering the following error.

Info:
Xamarin Studio
Windows Machine

Could not install package 'OxyPlot.Core 1.0.0-unstable1879'. You are trying to install this package into a project that targets 'portable-net45+dnxcore50+win+wp80+MonoAndroid10+xamarinios10+MonoTouch10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

What could be the problem how can I fix it??

**Comment by objorke** [comment]
Try removing dnxcore50 from the target frameworks.
I have tested OxyPlot.Core 1.0.0-unstable1879 with a "template-generated" Xamarin.Forms solution (portable) and did not find any issues.

**Comment by Femilshajin** [comment]
Thanks Works after removing dnxcore50..
