### ISSUE TITLE
WPF: Issue with updating ContentControl

### ISSUE THREAD

**Issue by classicboss302** [oxyplot/oxyplot#656]
I currently have an application with a ContentControl that I update the user control that is bound to it. Each user control has a ItemsControl where that I bind the plots to. A user can switch between the controls at will. Each user control has a view model where the collection of plots is stored. If plots have already been generated for a user control, and the user switches to a different control and then back, I get a crash that originates in the function below. The viewmodel should be the same as the graphs are only generated by a user clicking a button on each user control and are preserved when switching controls. I don't see this issue when using the 2014 version of OxyPlot. Best I can tell, the issue started with this commit. 

If I comment out the exception so it isn't thrown, then everything works correctly.

225d137b44c28b9c962c550f3d46f1b121c8024f

```c#
void IPlotModel.AttachPlotView(IPlotView plotView)
{
	var currentPlotView = this.PlotView;
	if (!object.ReferenceEquals(currentPlotView, null) &&
		!object.ReferenceEquals(plotView, null) &&
		!object.ReferenceEquals(currentPlotView, plotView))
	{
		throw new InvalidOperationException(
			"This PlotModel is already in use by some other PlotView control.");
	}

	this.plotViewReference = (plotView == null) ? null : new WeakReference(plotView);
}

**Comment by tibel** [comment]
Hmm, seems to be related to  #497, #264 and #456

**Comment by classicboss302** [comment]
I have updated the title to be a bit more accurate. I have also updated the description as it missed a few details.

**Comment by classicboss302** [comment]
I made small application that replicates the issue I am seeing. I don't see this if I do this for a single Plot, but when I do it for many with an ItemsControl, it causes an exception.

[TabSwitchIssue.zip](https://github.com/oxyplot/oxyplot/files/143416/TabSwitchIssue.zip)

**Comment by classicboss302** [comment]
While I can still reproduce it with the example above, I was able to resolve it by adding DI to the program.

**Comment by cabusto** [comment]
@classicboss302 May I ask how you solved this issue with DI?

**Comment by classicboss302** [comment]
Honestly not sure. I converted the program over to using DI and could no longer reproduce the issue.

**Comment by cabusto** [comment]
Interesting. I am encountering the exact same issue. Single plot, switch tabs, everything is ok. Added an ItemsControl, and I can create tabs, but no longer switch back.

Did you use a DI framework?

**Comment by classicboss302** [comment]
I used StructureMap.
