### ISSUE TITLE
DataTimeAxis ToOADate - 1 day mismatch

### ISSUE THREAD

**Issue by hooboe** [oxyplot/oxyplot#660]
I use DateTimeAxis. When I add point like this:
`lineSeries.Points.Add(new OxyPlot.DataPoint(result.StartDateTime.ToOADate(), value));`
i have 1 day mismatch between StartDateTime and axis labels on the chart.
Eg. today 2015-11-24 - ToOADateTime() function get value 42332 (the same as in Excel), but on chart the point is drawn at axis label 2015-11-25.
The tracker:
`series.TrackerFormatString = "{0}\nDate: {2:yyyy-MM-dd HH:mm}\nValue: {4:0.0000}";`
also show 2015-11-25.

OxyPlot.Wpf version 2014.1.546.0

**Comment by objorke** [comment]
We could change the [`DateTimeAxis.ToDouble`](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/DateTimeAxis.cs#L146) implementation to be compatible with [`ToOADate`](https://msdn.microsoft.com/en-us/library/system.datetime.tooadate%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396). 

Change origin to 1899-12-30?
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Axes/DateTimeAxis.cs#L33

This will be a "minor" breaking change.

**Comment by objorke** [comment]
Please include/update unit tests when making this change.
