### ISSUE TITLE
AreaSeries ConstantY2 is not implemented

### ISSUE THREAD

**Issue by less0** [oxyplot/oxyplot#662]
The default behavior of the AreaSeries is to display the area between the graph and the line between the first and the last DataPoint. If no DataPoints are provided in Points2 the behavior should be to use ConstantY2, which is not implemented, yet. 

I've already implemented a first basic version of it and I am only waiting for my you-take-it assignment.

I am using the latest unstable Version, WindowsForms, .NET 4.5.2

**Comment by objorke** [comment]
The comment on ConstantY2 should be updated
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/Series/AreaSeries.cs#L41

I think it should be "ConstantY2 is used if `ItemsSource` is set and `DataField2` is `null`, or if `ItemsSource` is `null` and `Points2` is empty."

**Comment by objorke** [comment]
An alternative could be to use `ConstantY2` if it is not NaN. But that would be a breaking change.

**Comment by objorke** [comment]
It seems `ConstantY2` is currently not used...

**Comment by objorke** [comment]
Please include examples for all cases: 
- with ItemsSource
- null ItemsSource 
- null DataField2
- empty Points2
etc.
