### ISSUE TITLE
Is this usable in production?

### ISSUE THREAD

**Issue by interdrift** [oxyplot/oxyplot#667]
Hi everyone, I was wondering if this is production ready? The status of all the nu-get packets are pre-release/unstable. Is there a stable 1.0 version ?

**Comment by objorke** [comment]
Currentlywe have 6 open issues that is tagged for v1.0:
https://github.com/oxyplot/oxyplot/milestones/v1.0

Please contribute :-)

**Comment by objorke** [comment]
Please use the forum or chat for questions :-)
