### ISSUE TITLE
Limiting the size of the legend

### ISSUE THREAD

**Issue by redcurry** [oxyplot/oxyplot#668]
I don't see a way to limit the size of the legend. The more series I add to the plot, the larger the legend becomes and the smaller the plot (specifically for an outside legend at the bottom). At the very least, I think there should be a way to specify a maximum height (or width) of the legend. This would also make `PlotModel.LegendColumnSpacing` more useful because, as far as I can tell, the only way for there to be multiple columns in the legend is if it has taken up the entire plot height.

**Comment by redcurry** [comment]
I see that there's a `PlotModel.LegendMaxWidth` but not one for height.

**Comment by objorke** [comment]
It sounds good to add a `LegendMaxHeight` similar to the existing one.
Remember to include example in a PR.

**Comment by redcurry** [comment]
I added the feature to the OxyPlot project and tested it in my own solution. Can I do a pull request as is, or do I need to test it with the other projects (Wpf, MonoTouch, Silverlight, etc.)?

**Comment by objorke** [comment]
Please include an example in the example library - then we can test on all platforms.
See https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md
