### ISSUE TITLE
EnumerableExtensions conflict with System.Linq

### ISSUE THREAD

**Issue by ulex** [oxyplot/oxyplot#677]
It's a little confusing that OxyPlot has same signature for extension method `OxyPlot.EnumerableExtensions.Reverse` with FCL method `System.Linq.Enumerable.Reverse`

Importing both OxyPlot and System.Linq namespaces force me call extension method Reverse as static method. It's looks ugly.

**Comment by objorke** [comment]
I agree on this!
The project still builds fine if EnumerableExtensions.cs is removed.
@tibel Can we remove this code?
I see it was added in https://github.com/oxyplot/oxyplot/commit/13afe3831a2bb0119ff54353d8a2eb3ea5e74e2b

**Comment by tibel** [comment]
@objorke Yes this can be removed. It was some micro-optimization for reverse enumerating `IList<T>`.
