### ISSUE TITLE
Is there a way to specify the individual bar width in LinearBarSeries?

### ISSUE THREAD

**Issue by interdrift** [oxyplot/oxyplot#678]
As far as I can tell there's only the possibility to specify the width of the whole series? I need to access the individual with of the bars.

**Comment by objorke** [comment]
Is this a question of feature request? :-)
I think this should be covered by `RectangleBarSeries`

**Comment by interdrift** [comment]
:+1: Indeed it does so in a sense lienarBarSeries is a subset RectangleBarSeries

**Comment by objorke** [comment]
The `RectangleBarSeries` contains `RectangleBarItem`s so it does not make much sense to derive `LinearBarSeries` from it.

**Comment by objorke** [comment]
I think this issue could be closed. Ok?
