### ISSUE TITLE
Add `RenderInLegend` property

### ISSUE THREAD

**Issue by ch-hristov** [oxyplot/oxyplot#679]
I would like to remove some of the series from the legend, currently I can only see that only all of the series of the PlotModel are rendered.

**Comment by objorke** [comment]
If the `Title` property is not specified, the series should not be shown in the legend.

**Comment by interdrift** [comment]
Verified, works as intended. It might be better to expose a dependancy property on Series named RenderInLegend since its a bit more intuitive.

**Comment by objorke** [comment]
This will be a breaking change. 
I see the possibility to have a title that is not shown in the legend but shown in the tracker. That's a valid enhancement issue :-)

**Comment by benjaminrupp** [comment]
I agree! I´d like to have a series not rendered in legend but in tracker.

**Comment by VisualMelon** [comment]
Can this be closed?
