### ISSUE TITLE
XAML examples shows on Android but not on iOS

### ISSUE THREAD

**Issue by DipSwitch** [oxyplot/oxyplot#689]
This is to blame to the `Center` in both `VerticalOptions` and `HorizontalOptions` if I change that to `Fill` just like in the code example it seems to work :)

    <oxy:PlotView Model="{Binding Model}" VerticalOptions="Center" HorizontalOptions="Center" />

Further more I needed to apply all the given workaround provided.

Static var in `AppDelegate` and I have an overloaded `PlotViewRenderer` with latest Xamarin and OxyPlot

    <package id="OxyPlot.Core" version="1.0.0-unstable1901" targetFramework="xamarinios10" />
    <package id="OxyPlot.Xamarin.Forms" version="1.0.0-unstable1901" targetFramework="xamarinios10" />
    <package id="OxyPlot.Xamarin.iOS" version="1.0.0-unstable1901" targetFramework="xamarinios10" />
    <package id="Xamarin.Forms" version="2.0.0.6490" targetFramework="xamarinios10" />

The example on this page in particular: http://docs.oxyplot.org/en/latest/getting-started/hello-xamarin-forms.html

**Comment by objorke** [comment]
This is Xamarin Forms, right?

**Comment by objorke** [comment]
I think you need to specify width and height if you are not using fill.
But I was surprised if this behaves different on Android and iOS

**Comment by DipSwitch** [comment]
Yes Xamarin Forms. I can check again tomorrow if it wasn't something else.
By changing the code back to Center :)

**Comment by DipSwitch** [comment]
Yup, it was really the Center.

The following shows on Android and not iOS

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:forms="clr-namespace:OxyPlot.Xamarin.Forms;assembly=OxyPlot.Xamarin.Forms"
                 x:Class="SwTestApp.UI.GraphScreen">
      <forms:PlotView x:Name="pltInput" VerticalOptions="Center" HorizontalOptions="Center"/>
    </ContentPage>

And the following works on both


    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
                 xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                 xmlns:forms="clr-namespace:OxyPlot.Xamarin.Forms;assembly=OxyPlot.Xamarin.Forms"
                 x:Class="SwTestApp.UI.GraphScreen">
      <forms:PlotView x:Name="pltInput" VerticalOptions="Fill" HorizontalOptions="Fill"/>
    </ContentPage>

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/19
