### ISSUE TITLE
CategoryAxis: How to programmatically pan with ColumnSeries

### ISSUE THREAD

**Issue by Bischi** [oxyplot/oxyplot#690]
I have a PlotView (I'm using Xamarin.Forms) and show a ColumnSeries by using a LinearAxis on the left and a CategoryAxis on the bottom.

The ColumnSeries is displayed correctly. Is there a way to pan the column bars to the left programmatically via code behind (c#)?

Currently I have a fixed number of bars (12). When new data comes in I remove the index 0 from the
columnSeries items and add the new one to the end of the list. If I Invalidate the plotView it looks like
the bars got slided to the left with one new value added. But this looks very rough because the bars get shifted by 1 bar width.

I want to pan the bars to the left before I add the new value to get a smooth shifting look. Is there a way to do this by panning the
categoryAxis somehow in code behind?

Thanks! :-)

**Comment by objorke** [comment]
I think this question belongs to the forum. Will not answer questions here :-) Only discuss issues like bugs and new features :)

**Comment by objorke** [comment]
http://discussion.oxyplot.org/topic/1065795-categoryaxis-how-to-programmatically-pan-with-columnseries-question/
