### ISSUE TITLE
All structs should follow "Struct Design" principles

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#692]
https://msdn.microsoft.com/en-us/library/ms229031.aspx
- no default constructor
- no property setter or settable field
- implement `IEquatable<T>`

This should be checked and fixed for all `struct` types in OxyPlot.
Especially `DataPoint` is violating the immutability constraint!

**Comment by objorke** [comment]
I will change the `DataPoint`.

**Comment by objorke** [comment]
Struct types:
- [ ] DataPoint
- [ ] PlotLength
- [ ] SelectionItem
- [ ] OxyColor
- [ ] OxyRect
- [ ] OxySize
- [ ] OxyThickness
- [ ] ScreenPoint
- [ ] ScreenVector
- [ ] BoxPlotItem

**Comment by objorke** [comment]
What about item types like ScatterPoint, BarItem etc. (reference types) - should they also be immutable?

**Comment by objorke** [comment]
I will change BoxPlotItem to a reference type. It is too big for a value type.

**Comment by objorke** [comment]
I think this one is complete now.
