### ISSUE TITLE
ScatterSeries should support ScatterPoint only

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#693]
`ScatterSeries` should be changed to support `ScatterPoint` type only.
No derivatives!

Similar to the other series, as a derivative makes no sense as the additional properties are not rendered anyway.

**Comment by tibel** [comment]
Just saw `ScatterErrorSeries` derives from `ScatterSeries<T>`.
Would need to merge the two series to make this change.

**Comment by objorke** [comment]
Let us clean this up before v1.0!

**Comment by interdrift** [comment]
@tibel I use a ScatterPoint derivative to store extra data for the point. It is true that those properties aren't a concern of the view but the data must be contained somewhere and easily accessible. What easier than doing (DerivativeOfScatterPoint).MyData?

**Comment by objorke** [comment]
My 2 cents for keeping it as it is:
1 You could derive a new series where you use the extra properties during rendering.
2 Extra properties can easily be shown in the tracker by the "extended" formatting syntax, e.g. {MyData:0.000}

I suggest to close this issue!

**Comment by tibel** [comment]
Ok, let's close it.
