### ISSUE TITLE
Latest build OxyPlot Target Invocation Exception 

### ISSUE THREAD

**Issue by KathirveluM** [oxyplot/oxyplot#696]
Hi,

We have added the below OxyPlot reference and controls in my sample page.

 xmlns:oxy="clr-namespace:OxyPlot.Xamarin.Forms;assembly=OxyPlot.Xamarin.Forms"

<oxy:PlotView VerticalOptions="Center" HorizontalOptions="Center" />

While Executing the Application,We are getting "Exception has been thrown by the target of an invocation."

Note: We have added the latest versions from Nuget Package Manager. 

Version: OxyPlot.Core.1.0.0-unstable1904

Ref Link: https://www.nuget.org/packages/OxyPlot.Xamarin.Forms/1.0.0-unstable1904

Kindly sugest how to resolve the same and add PieChart Control in Xamarin Forms?

**Comment by tibel** [comment]
Please provide some more details on the error:
- inner exception
- callstack

(see https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md)

**Comment by objorke** [comment]
On which platform does this happen?

See also last section on 
https://developer.xamarin.com/guides/xamarin-forms/windows/getting-started/universal/

**Comment by avinashn-rapidd** [comment]
How did you resolve this?

Thanks in Advance!
