### ISSUE TITLE
Switch to new 'dotnet' target framework monikers

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#719]
Switch to the new, simpler way of targeting versions of .NET

https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md
http://blog.nuget.org/20150729/Introducing-nuget-uwp.html

**Comment by objorke** [comment]
Shoud [this line](https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot/OxyPlot.Core.nuspec#L17) be changed?

**Comment by GeertvanHorrik** [comment]
I think this is no longer required when moving towards .NET standard? Also see #946
