### ISSUE TITLE
Does LineAnnotation work with DateTimeAxis?

### ISSUE THREAD

**Issue by joe37** [oxyplot/oxyplot#722]
The example "LineAnnotation on linear axes" does not seem to work with a DateTime x-axis (example "DateTime axis") in WPF, .NET 4.5. Am I doing something wrong? If not: is there a workaround?

**Comment by joe37** [comment]
I'm now using a LinearAxis with a LabelFormatter. That works fine.

**Comment by e23099** [comment]
We can use `DateTimeAxis.ToDouble` method to convert a datetime to the desired double value on the DateTime x-axis.
```c#
LineAnnotation selectedX = new LineAnnotation
{
    Type = LineAnnotationType.Vertical,
    StrokeThickness = 1,
    X = DateTimeAxis.ToDouble(new DateTime(2022, 1, 13)); // change to your datetime here
    Color = OxyColor.Green,
};
```
It works for me.
