### ISSUE TITLE
Axes min/max ignored

### ISSUE THREAD

**Issue by merthsoft** [oxyplot/oxyplot#727]
I have a rather large degree of variation in my data set. I need the X-Axis to go from 0 to 866, and the Y-Axis to go from 103 to 37141, is one example. However, when I add the points to a linear graph, and create the axes based on these parameters, it kind of makes it go all over the place. The X-Axis goes into the negatives on the left and thousands on the right, and the Y-Axis also starts in the negatives. Is there a way to force the graph to obey the min/max I specified in the axes?

**Comment by objorke** [comment]
Can you include some code (a `PlotModel`) that reproduces the issue?

**Comment by merthsoft** [comment]
Oh, yeah, of course. Here's some sample code:

            PlotView p = new PlotView() { Dock = DockStyle.Fill };
            PlotModel pm = new PlotModel() { PlotType = PlotType.Cartesian };
            LineSeries ls = new LineSeries();
            pm.Axes.Add(new LinearAxis() { Position = AxisPosition.Bottom, Minimum = 0, Maximum = 866, Key = "Horizontal" });
            pm.Axes.Add(new LinearAxis() { Position = AxisPosition.Left, Minimum = 103, Maximum = 37141, Key = "Vertical" });
            ls.XAxisKey = "Horizontal";
            ls.YAxisKey = "Vertical";
            pm.Series.Add(ls);
            p.Model = pm;

            Controls.Add(p);

And here is what it renders:
![form1_2016-01-09_22-26-16](https://cloud.githubusercontent.com/assets/1743796/12219811/582e2dba-b720-11e5-94a0-566e5a7eb5dc.png)

And then when I resize the window, the axes change as well. It'd like them, ideally, to stay as specified.

**Comment by interdrift** [comment]
I have had the axis min/max update accordingly through some work on the code behind:

https://github.com/interdrift/oxyplot/blob/develop/Source/OxyPlot/Axes/Axis.cs#L383

**Comment by objorke** [comment]
I think this is the desired behavior when using `PlotType.Cartesian`. See the examples I added.
Change the `PlotType` to the default `XY` to set minimum and maximum on both horizontal and vertical axes.

**Comment by merthsoft** [comment]
That seems to fix it--thanks so much!

![form1_2016-01-10_18-18-03](https://cloud.githubusercontent.com/assets/1743796/12224776/833c4432-b7c6-11e5-93b6-67a0355d96d5.png)
