### ISSUE TITLE
Area plot tracker does not work on lower boundary

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#73]
**Imported from [http://oxyplot.codeplex.com/workitem/10065](http://oxyplot.codeplex.com/workitem/10065)**

**[krafty](http://www.codeplex.com/site/users/view/krafty)** 2013-07-23 11:41
Hi, 

Tracker in the area plot is unable to pick any point on the lower boundary of the graph. It only picks and tracks the upper boundary.

Is there any workaround / parameters which I need to tweak? Please help.. 

Thanks, 

Rishikesh

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
