### ISSUE TITLE
Add Tag to DataPoint class

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#733]
I have points in time, but I also want to store some additional information in a point (for display / tracker purposes). Unfortunately there is no way to store additional (meta) data in a data point. 

Are you open to adding an `object Tag` property to the `DataPoint` class?

**Comment by tibel** [comment]
Please see my comments in #674. DataPoint is a struct and in my opinion a point in data space.
Why not create a new class to hold such data, similar to ScatterPoint.
Another possibility is to use your won class with the data-binding functionality of OxyPlot.

**Comment by GeertvanHorrik** [comment]
Makes sense, thanks!
