### ISSUE TITLE
HeatMapSeries cannot plot on Universal Windows

### ISSUE THREAD

**Issue by jayeshsolanki93** [oxyplot/oxyplot#745]
This is the model class for the plotview.
``` c#
class MainViewModel
    {
        public MainViewModel()
        {
            this.Plot = PlotHeatMap();
        }
        public PlotModel Plot { get; private set; }

        public static PlotModel PlotHeatMap()
        {
            var model = new PlotModel { Title = "FOOBAR" };
            model.Axes.Add(new LinearColorAxis
            {
                Position = AxisPosition.Right,
                Palette = OxyPalettes.Jet(500),
                HighColor = OxyColors.Gray,
                LowColor = OxyColors.Black
            });

            var data = new double[,] { { 1, 2 }, { 1, 1 }, { 2, 1 }, { 2, 2 } };

            var hs = new HeatMapSeries
            {
                Background = OxyColors.Red,
                X0 = 0,
                X1 = 2,
                Y0 = 0,
                Y1 = 3,
                Data = data,
            };
            model.Series.Add(hs);
            return model;
        }
}
```

I was looking for a solution to fix this, then I stumbled upon a similar issue on SO http://goo.gl/1LrQlb
Can you confirm if this a bug or am I missing something?

**Comment by objorke** [comment]
It seems to stop here:
https://github.com/oxyplot/oxyplot/blob/develop/Source/OxyPlot.Windows/RenderContext.cs#L792

**Comment by objorke** [comment]
- https://msdn.microsoft.com/en-us/library/windows/apps/xaml/jj709934.aspx
- http://stackoverflow.com/questions/17107576/c-sharp-windows-8-store-metro-winrt-byte-array-to-bitmapimage
- http://www.chrispeerman.info/loading-images-from-byte-arrays-in-windows-8-store-apps-winrt/

**Comment by objorke** [comment]
is it running on the right thread?

**Comment by tibel** [comment]
No it is the right thread, as `this.Dispatcher.HasThreadAccess` returns `true`.
There was a deadlock with `await` and `.Result` in the implementation.
