### ISSUE TITLE
Oxyplot.Series missing

### ISSUE THREAD

**Issue by nicolasr75** [oxyplot/oxyplot#751]
I created a new WPF application and added Oxyplot.Wpf via Nuget. Shortly after that I was provided with update OxyPlot.Core.2015.1.708-alpha. After that my "using Oxyplot.Series" does not work anymore, Intellisense tells me that Series is not part of namespace Oxyplot. What am I missing? Has there been some code restructuring?

**Comment by tibel** [comment]
The versioning schema was changed.
Latest version is 1.0.0-unstable1974

The `OxyPlot.Core.2015.1.708-alpha´ might be in your local NuGet package cache (see http://lastexitcode.com/projects/NuGet/FileLocations/).

**Comment by nicolasr75** [comment]
Thanks, that explains it. I uninstalled *.2015.* and reinstalled 1.0.0-unstable-alpha. VS keeps listing the 2015 package as an update, although I deleted the package from the cache. Not a big problem, though, now that I know where it comes from.

**Comment by objorke** [comment]
Is this issue resolved?

**Comment by nicolasr75** [comment]
I consider it solved, at least for me, knowing that 2015*... is not the up-to-date version! It remains a little irritating that VS keeps me notifying about a possible update that actually is not an update but I have no idea how to avoid that, given that semantic versioning of course treats a major version number of 2015 as newer as 1. By the way, am I supposed to close an issue when I, as the original reporter, consider it done? I assumed that is the 'priviledge' of the owner or moderator but I don't know how this is usually handled.

**Comment by objorke** [comment]
It is strange that some of the old unlisted packages sometimes show up in the NuGet listings...

We don't have any 'guidelines' regarding closing issues. For bugs and questions (like this one) I think it is great if the original reporter can close the issue. For new features, maybe an administrator should do it.

**Comment by nicolasr75** [comment]
Alright then.
