### ISSUE TITLE
OxyPlot.WindowsForms.PngExporter.Resolution has no effect

### ISSUE THREAD

**Issue by less0** [oxyplot/oxyplot#754]
The OxyPlot.WindowsForms.PngExporter class has a property Resolution, which suggests, that the exporter supports exporting in different resolutions. However, this property is not used at all, the images are always exported at the same fixed resolution. I'm using the 1.0.0-unstable1968 build from nuget.org

**Comment by objorke** [comment]
@less0 did this resolve the issue?

**Comment by objorke** [comment]
please re-open if not resolved
