### ISSUE TITLE
Example browser gone?

### ISSUE THREAD

**Issue by sleith** [oxyplot/oxyplot#763]
Hi,
I wonder why http://resources.oxyplot.org/examplebrowser/ is not available anymore?
The one at http://docs.oxyplot.org is not completed, i can't see the sample chart layouts.
please help.
thx

**Comment by objorke** [comment]
I think the Silverlight example browser is still online, but is not updated any more. 
I will delete it soon.

**Comment by sleith** [comment]
it's not online, i tried but it's not there. could you pls check?
why delete it? where i can see the samples then?

thanks :)

**Comment by objorke** [comment]
![image](https://cloud.githubusercontent.com/assets/439716/12897501/07ccee16-cea8-11e5-8eda-16a0e2dca29d.png)
Windows 10 - Internet Explorer
Silverlight is not supported in Chrome or Edge
https://support.microsoft.com/en-us/kb/3058254

I think that is good enough reason for not maintaining that page any more. :-)

**Comment by objorke** [comment]
Closing this issue - feel free to continue the discussion in the forum.

**Comment by technos12** [comment]
The example browser was the best resource to learn and I found many solutions using this. Why isn't is available any more ? I really need it.

**Comment by Soarc** [comment]
You can download source code, build it and run example browser locally.

**Comment by technos12** [comment]
A lighting fast solution... Ok I will do it this way. Thank for the advice.

**Comment by csabar** [comment]
I know there was a Windows 10 version on the Windows Store, but now even this seems to be unavailable. Why? I was able to find it on the store (link: https://www.microsoft.com/en-US/store/p/oxyplot-example-browser/9wzdncrfjff7 ) but then if I open it in store it shows that OxyPlot Example Browser is currrently not available.
