### ISSUE TITLE
RangeColorAxis doesn't render correctly

### ISSUE THREAD

**Issue by beanmf** [oxyplot/oxyplot#767]
Although the ScatterSeries with RangeColorAxis works, the RangeColorAxis doesn't render correctly when zoomed, or when used as a horizontal axis.  A small change to the logic in the Render() method will fix both of these problems.

**Comment by objorke** [comment]
Please include a screen shot.

**Comment by beanmf** [comment]
Sorry, there is no problem when zoomed.  When a RangeColorAxis is used as a horizontal axis, the axis itself renders correctly, but the color ranges don't render.  Therefore a screen shot would simply show no color ranges -- not very interesting.
