### ISSUE TITLE
Add oxyplot-contrib repository / OxyPlot.Contrib library

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#771]
Add a new portable library for possibly reusable components (axes, annotations, series).
"Relaxed" contribution rules. Almost anything can be accepted.
Build NuGet package to make it easy to use these components.

**Comment by tibel** [comment]
It would be good to have a separate repository (e.g. oxyplot-contrib) for it.

This has following benefits:
- independent versioning and updates
- separate build server config
- administration of user (commit) rights

**Comment by objorke** [comment]
agree that it should have its own repository!
but is it really a good idea? I read this
http://blog.startifact.com/posts/against-contrib.html

**Comment by tibel** [comment]
I agree that a contrib project makes only sense when it is not maintained by the same developer.

**Comment by objorke** [comment]
Agree, the contrib project should be maintained by others. Maybe every contributor could be a maintainer...
I suggest to use semantic versioning (independent as you suggest), and let it depend on the OxyPlot.Core NuGet package.

**Comment by objorke** [comment]
I added empty projects and set up the build
https://github.com/oxyplot/oxyplot-contrib
