### ISSUE TITLE
Add oxyplot-xamarin repository

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#777]
Move the OxyPlot.Xamarin.* projects and examples to its own repository.
Make this repository easier to build.
The other repository should have a NuGet dependency to OxyPlot.Core

**Comment by objorke** [comment]
I am trying to preserve git history, and have tried the following:
```
git clone https://github.com/oxyplot/oxyplot.git
cd oxyplot
git remote rm origin
git filter-branch -f --prune-empty --index-filter 'git rm --cached -r -q -- . ; git reset -q $GIT_COMMIT -- Source/OxyPlot.Xamarin* Source/Examples/Xamarin.*' -- --all
cd ..
git clone https://github.com/oxyplot/oxyplot-xamarin.git
cd oxyplot-xamarin
git remote add x ../oxyplot
git pull x develop
git remote rm x
```

**Comment by objorke** [comment]
https://ci.appveyor.com/project/objorke/oxyplot-xamarin

**Comment by objorke** [comment]
How should version numbers be set?
Should the OxyPlot.Core NuGet dependency be updated automatically?

**Comment by objorke** [comment]
The code has been moved but the build is not yet passing.
I have requested support from Xamarin regarding the license issue.

**Comment by tibel** [comment]
Build seems to work fine.
