### ISSUE TITLE
No stable OxyPlot package in NuGet

### ISSUE THREAD

**Issue by icerocker** [oxyplot/oxyplot#779]
I have to select "Include Prereleases" in NuGet manager to get OxyPlot. Is it possible to get the stable version somewhere?

**Comment by objorke** [comment]
The latest prerelease is the most stable version. We unlisted older "stable" packages when changing to semantic versioning.
There are two remaining issues for v1.0
https://github.com/oxyplot/oxyplot/milestones/v1.0

**Comment by objorke** [comment]
Please use the forum or chat for questions :-)

**Comment by icerocker** [comment]
Ok, thanks. Will try to put it in the right place next time ;)
