### ISSUE TITLE
Make OnTrackerChanged non-internal

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#785]
I am implementing a TouchTrackerManipulator (based on the TrackerManipulator but deriving from TouchManipulator instead). However, OnTrackerChanged is internal so it's impossible to complete this mission.

Are you open to making this non-internal?

**Comment by objorke** [comment]
sounds OK

**Comment by GeertvanHorrik** [comment]
Decided to keep the OnTrackerChanged protected internal to prevent any breaking changes. Introduced RaiseTrackerChanged instead which can be called (with remarks in the docs).
