### ISSUE TITLE
TouchManipulator does not start until touch is also moved

### ISSUE THREAD

**Issue by GeertvanHorrik** [oxyplot/oxyplot#786]
I am implementing a tracker using touch. When I implement my own TouchManipulator, the Started method is only called when I also move the touch a bit. But I think the start should immediately be called on "touchdown". The delta can be used to track changes.

**Comment by GeertvanHorrik** [comment]
The reason is because Windows (UWP) uses OnManipulationStarted instead of PointerPressed / PointeredMoved / PointerReleased.

**Comment by GeertvanHorrik** [comment]
Happy to do a PR, let me know if you are open to this change.

**Comment by objorke** [comment]
I think you are right - "started" should be called on touchdown. Please continue with a PR! This is UWP only, right? Does it work on other platforms (WPF, iOS, Android)?

If touch events should be handled by gesture recognizers is another issue...

**Comment by GeertvanHorrik** [comment]
For now I will focus on Windows (Since I am sure it's on there). Then we can check if we like the new behavior.

**Comment by GeertvanHorrik** [comment]
I also added the TouchTrackerManipulator by default.
