### ISSUE TITLE
Pdf export text is not rendering in unicode by default.

### ISSUE THREAD

**Issue by RhavoX** [oxyplot/oxyplot#789]
Hi,

Whenever I try to export a plot to pdf that contains a lambda sign or any special character it just renders as '?' so I guess unicode is not enabled by default. Perhaps unicode should be the default mode as I haven't found any possibility to force unicde using the functionality provided in the library and I forced it by modifying the PdfRenderContext class so that the font creation now looks like this:

`XPdfFontOptions xPdfFontOptions = new XPdfFontOptions(PdfFontEncoding.Unicode, PdfFontEmbedding.Default);`

`var font = new XFont(fontFamily, (float)fontSize * FontsizeFactor, fs, xPdfFontOptions);`

instead of:

` var font = new XFont(fontFamily, (float)fontSize * FontsizeFactor, fs);`

**Comment by objorke** [comment]
I agree Unicode should be default

**Comment by objorke** [comment]
@RhavoX thanks for pointing to the solution!
