### ISSUE TITLE
WPF BarSeriesBase ArgumentNullException

### ISSUE THREAD

**Issue by Maxima078** [oxyplot/oxyplot#790]
Hi,

I noticed a first chance exception due to null list being casted.
It happens on the "OnSizeChanged" (PlotBase.cs) when my control is loaded.

In BarSeriesBase{T}.cs::GetItems(), ActualItems is null because ItemsSourceItems is null. Thus the linq cast in GetItems() failed:

    this.ActualItems.Cast<CategorizedItem>().ToList()

I could solved this problem by calling:

    ((IPlotModel)MyPlotModel).Update(true);

Am I missing something ? Note I'm using ItemsSource property to bind my Collection. Except this exception, everything is working perfectly.

Thanks,

Max.

**Comment by objorke** [comment]
I think we need some more info about how to reproduce the error. Can you include example code - or add an example in the example library?

**Comment by objorke** [comment]
I think this bug was introduced in 6b83be9c

**Comment by objorke** [comment]
@Maxima078 can this issue now be closed?

**Comment by Maxima078** [comment]
Will it be corrected in the next release?
Yes you can close it if it's a confirmed bug.

Thank you.

**Comment by objorke** [comment]
This should be included in version 1.0.0-unstable.2027.build.1147
