### ISSUE TITLE
Plot title doesn't render in GTK if HeatMap has Labels

### ISSUE THREAD

**Issue by VisualMelon** [oxyplot/oxyplot#804]
This can be observed in the existing HeatMap examples, where you will note that only HeatMaps without labels have titles (for example, 6x6 Diagonal compared to Confusion Matrix). This doesn't appear to occur with Silverlight, WindowsForms, or PDF Rendering, where titles are rendered as they should be.

**Comment by zur003** [comment]
@VisualMelon : is this still a problem? I can't reproduce it.

**Comment by VisualMelon** [comment]
@zur003 I can no longer reproduce this with a fresh pull of Oxyplot.

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-gtksharp
