### ISSUE TITLE
PointAnnotation TouchStarted is not working properly - Xamarin Forms

### ISSUE THREAD

**Issue by CharlinAgramonte** [oxyplot/oxyplot#806]
Hi, using PointAnnotation in Xamarin Forms and when touching is not working, i have to touch the point and move me through the chart to detect the event ...
If i use others events like MouseUp, MouseDown, etc.. these not raise

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/18
