### ISSUE TITLE
Need an ability to create area plots with two polygons of different colors

### ISSUE THREAD

**Issue by olegtarasov** [oxyplot/oxyplot#819]
### Feature description

I have a use case when I need to plot an area chart with two polygons filled with different colors. First polygon is built using Points collection and ConstantY value. Second polygon is built with ConstantY and Points2 collection. Furthermore, data points in Points and Points2 collections may have identical X values. So TwoColorAreaSeries is not suitable for this task as it only has one data point collection and two polygons can't have same X values. In pull request #817 I propose a solution where AreaSeries can solve this task, meanwhile greatly improving rendering performance. With my pull request I attached an example which shows the use case I need.

If you decide to go forward with this pull request, TwoColorAreaSeries will largely become obsolete as AreaSeries will solve the same problem with more flexibility.

**Comment by objorke** [comment]
I don't think two color mode should be added to the `AreaSeries`. In my opinion this series should only do rendering of single colored areas. The outline of the area should be defined by `Points` and `Points2` or `Points` and `ConstantY`. But it would be great if the `AreaSeries` rendering was general enough to allow customizations that rendered the area by two colors, three colors or *n* colors.

Another approach could be to add support for `Points2` in the `TwoColorAreaSeries`. Is this possible?
I see `TwoColorAreaSeries` is derived from `TwoColorLineSeries` - maybe it should be derived from `AreaSeries` instead?

**Comment by objorke** [comment]
I added two `AreaSeries` to the same model to get exactly the same output as the example in #817:
```csharp
            var plotModel1 = new PlotModel { Title = "AreaSeries with different area colors" };
            var areaSeries1 = new AreaSeries
                                  {
                                      Color = OxyColors.Red,
                                      Color2 = OxyColors.Undefined,
                                      ConstantY2 = 60
                                  };
            areaSeries1.Points.Add(new DataPoint(0, 50));
            areaSeries1.Points.Add(new DataPoint(10, 40));
            areaSeries1.Points.Add(new DataPoint(20, 60));

            var areaSeries2 = new AreaSeries
                                  {
                                      Color = OxyColors.Blue,
                                      Color2 = OxyColors.Undefined,
                                      ConstantY2 = 60
                                  };
            areaSeries2.Points.Add(new DataPoint(0, 60));
            areaSeries2.Points.Add(new DataPoint(5, 80));
            areaSeries2.Points.Add(new DataPoint(20, 70));

            plotModel1.Series.Add(areaSeries1);
            plotModel1.Series.Add(areaSeries2);
            return plotModel1;
```

**Comment by objorke** [comment]
Setting `ConstantY2 = 75` gives a strange result, I think. I was expecting the property to change the colors only, and not change the area.

**Comment by olegtarasov** [comment]
Hi!

Yes, using two AreaSeries gives the desired result, but this impacts performance. I have a financial analytics app that uses at least five series on a single plot:
 
![image](https://cloud.githubusercontent.com/assets/2397857/14104149/3f7d5104-f5ac-11e5-996d-e0317f218b95.png)

So it becomes difficult even to manage all this stuff in the code. That's why I would like to have this functionality in a single series. I agree that putting this into AreaSeries isn't such a good decision as it becomes overloaded and user may have difficulties deciding what series to use for the task.

I will try to put this functionality into TwoColorAreaSeries instead and see how it goes. Also I will incorporate all the comments you left to the pull request.

**Comment by olegtarasov** [comment]
Closing the issue, PR merged. Thanks!
