### ISSUE TITLE
LogarithmicAxis Major and Minor ticks calculation

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#820]
In my opinion, the current `GetTickValues(...)` implementation in `LogarithmicAxis` is not optimal in some cases. It ignores the `Axis.IntervalLength` property and essentially produces a fixed pattern of minor and major grid lines, so it looks like this in a plot of an acoustical frequency response:
![1](https://cloud.githubusercontent.com/assets/18097859/14077401/5e3c1524-f4eb-11e5-83de-8be6689c687e.PNG)

I think something like this would be better: (maybe though rather with 1-2-5-10 spacings)
![3](https://cloud.githubusercontent.com/assets/18097859/14077403/5e3c7938-f4eb-11e5-9c93-b04a9e1b5572.PNG)

Another problem of the current implementation if you zoom out:
![2](https://cloud.githubusercontent.com/assets/18097859/14077402/5e3c59ee-f4eb-11e5-838e-7ac278cfa87d.PNG)

I suggest (and would be willing to do it myself) a rewrite of the `LogarithmicAxis.GetTickValues(...)`  method with a more sophisticated algorithm (which uses the `IntervalLength`) if you agree with me on this.

**Comment by objorke** [comment]
I agree that your suggested solution looks much better! Please go ahead and improve the algorithm!

**Comment by Jonarw** [comment]
I did some work on this and I think it it works fairly well now (see attached image). It became a lot more complex than I originally thought...
I will do some further testing of extreme cases before I make a pull request.

![log](https://cloud.githubusercontent.com/assets/18097859/14168288/c624cce8-f721-11e5-9ab7-3caf68b5946b.PNG)

If you want, you can take a look at my commit and if there is something you don't like, feel free to tell me. I do have one open question about double formatting, but I think I will open a separate issue for that, as this concerns the axis types as well.

**Comment by objorke** [comment]
Fantastic! The example above should be included in the example library!
