### ISSUE TITLE
Crash on CGContextDrawImage while trying to render a Heat Map Series

### ISSUE THREAD

**Issue by arctouch-douglaskazumi** [oxyplot/oxyplot#835]
### Steps to reproduce

1. Try to open a page that contains a Heat Map Series

Platform: Xamarin Forms 2.1 iOS build

### Expected behaviour

See the Heat Map

### Actual behaviour

The app is crashing if I try to open my page on portrait mode. If I open it in landscape and then rotate the iPad. It works. I've seen some message related to conflicting layout Constraints, but I wasn't able to get the message again.

Please find attached the output.
[crashlog.txt](https://github.com/oxyplot/oxyplot/files/200773/crashlog.txt)

**Comment by arctouch-douglaskazumi** [comment]
The seems to be related to using a PlotView with a HeatMapSeries without setting fixed height and width.  
I'm using it like the following, and it seems that adding the padding on the container fixed the issue.

<StackLayout Orientation="Horizontal" HeightRequest="{hx:Scaler ScaleHeight=400}" BackgroundColor="{StaticResource VeryLightGrey}" Padding="{hx:Scaler ScalePadding='10'}">
			<oxy:PlotView Model="{Binding PlotModel}" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand" />
		</StackLayout>

**Comment by objorke** [comment]
Moved to https://github.com/oxyplot/oxyplot-xamarin/issues/22
