### ISSUE TITLE
Standard numerical format for Axis?

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#841]
@objorke I included this in a comment to my previous pull request, but I think this should be a separate issue. The `LogarithmicAxis` example still has a small number formatting problem at the left axis:
![format4](https://cloud.githubusercontent.com/assets/18097859/14251149/e886f33e-fa81-11e5-9f4a-970ace1afb53.PNG)

The `Axis` base class deals with that formatting problem with several "RemoveDoubleNoise" functions, but I don't particularly like that solution. I think this should not be the task of the tick calculation algorithm, but of the output formatter.

I propose a standard numeric format which is used whenever the user doesn't specify one, for example `g6`. With `g6` formatting, the same plot as above looks all right:
![format2](https://cloud.githubusercontent.com/assets/18097859/14251252/62a7ee5c-fa82-11e5-9f01-18b0f1700105.PNG)

I will make a pull request for demonstration purposes.

**Comment by objorke** [comment]
agree that the "remove double noise" should be responsibility of the formatter!
I need some more time to think about the format string.
- should it be set in the constructor?
- is "g6" too small for general use? use "g16"?

**Comment by Jonarw** [comment]
Yes, we could set the `ActualStringFormat` in the constructor and only owerwrite it in `UpdateIntervals()` if `StringFormat != null`. Would probably be neater.

I think it does make sense to decrease accuracy only as far as necessary to remove double noise, which would be `g16`.
On the other hand, cases where a user needs more than 6 significant digits are rare... Small and big numbers are shown in exponential notation anyway...
