### ISSUE TITLE
Add Aliased property to LineSeries

### ISSUE THREAD

**Issue by beanmf** [oxyplot/oxyplot#843]
In the .NET version of RenderingExtensions.cs, the DrawClippedLine() and DrawClippedLineSegments() methods take a Boolean aliased parameter.  In LineSeries.cs, when the RenderLine() and RenderPoints() methods call those RenderingExtensions methods, they currently hard-code the aliased parameter as false.  In order to take advantage of the aliasing capability, we need to add an Aliased property to the LineSeries class, and use it in those method calls.

If the aliased parameter is hard-coded to false, setting the LineSeries.StrokeThickness property to values less than 1 has no effect.  Adding the Aliased property, and passing it to the RenderingExtensions methods, allows plotting of finer lines, which we need in our application.

**Comment by Jonarw** [comment]
I was experimenting with this myself, but I found the results to be unsatisfying. But see for yourself:
![capture](https://cloud.githubusercontent.com/assets/18097859/14519070/dae09896-021c-11e6-8467-b2e77465607c.PNG)

Bot lines have a (nominal) `StrokeThickness` of 0.5, but I guess on a pixel-based rendering less than 1 does not make any real sense, so... I don't think this is the solution to your problem :)

**Comment by objorke** [comment]
Which platforms can support aliased lines? I know Winforms and WPF (EdgeMode=Aliased), but what about the other platforms? We could probably add support for aliased lines even if not all platforms can support it...
