### ISSUE TITLE
WinForm: Adjust Tracker Position and add padding like WPF

### ISSUE THREAD

**Issue by linquize** [oxyplot/oxyplot#846]
### Steps to reproduce

1. Use oxyplot with WinForm such as Show Case -> Normal distribution
2. Click on the chart line
3. Tracker will appear

Platform:
.NET version: 4.5.2

### Expected behaviour

Tell us what should happen
Mouse cursor not overlap with text. WPF version does not.
Also, it should add some padding to make it looks nicer.

### Actual behaviour
Mouse cursor overlaps with text
No padding

Tell us what happens instead
Actual:
![Actual](https://cloud.githubusercontent.com/assets/791115/14408048/5e8debc6-ff16-11e5-96d9-0a5f4b2ea014.png)

Expected:
![Expected](https://cloud.githubusercontent.com/assets/791115/14408049/5e97f594-ff16-11e5-8723-aa56fead5dff.png)

**Comment by objorke** [comment]
See also #106

**Comment by tibel** [comment]
Should be fixed by #856
