### ISSUE TITLE
Remove NuGet push from `develop` CI build

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#847]
NuGet recommends not to push packages during CI.

**Comment by tibel** [comment]
CI build packages can be found at MyGet.

Add following NuGet feed to your configuration:
https://www.myget.org/F/oxyplot

**Comment by JohanLarsson** [comment]
Have you checked out [paket](https://fsprojects.github.io/Paket/)? Really nice for packaging, I have moved away from nuget.exe for all the things.

**Comment by tibel** [comment]
@JohanLarsson How is this related? Not nuget.exe is the problem but nuget.org and this will not change by using packet.

**Comment by JohanLarsson** [comment]
Probably not relevant at all, just saw nuget and knee jerk spammed paket :)
