### ISSUE TITLE
PDF export in core library

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#85]
**Imported from [http://oxyplot.codeplex.com/workitem/10091](http://oxyplot.codeplex.com/workitem/10091)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-03 09:22
Add PDF export in the core library. 

Fonts: Helvetica/Arial (Adobe type 1, no need to embed font data in the pdf file)

Images: OxyImage should support decoding of PNGs (requires an implementation of DEFLATE decomression)

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-12 22:46
The first version of the pdf export is submitted.

Limitations are

<ul>
<li>fonts limited to Helvetica, Times and Courier New and WinAnsiEncoding </li><li>clipping text not working properly yet </li><li>images (need to implement deflate for the png decoder) </li></ul>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-13 19:30
<a href="http://blogs.msdn.com/b/dotnet/archive/2013/11/13/pcl-and-net-nuget-libraries-are-now-enabled-for-xamarin.aspx" rel="nofollow">http://blogs.msdn.com/b/dotnet/archive/2013/11/13/pcl-and-net-nuget-libraries-are-now-enabled-for-xamarin.aspx</a>

<a href="https://www.nuget.org/packages/Microsoft.Bcl.Compression/" rel="nofollow">https://www.nuget.org/packages/Microsoft.Bcl.Compression/</a> contains an implementation of DEFLATE.

Or - decompression can be implemented here to avoid the dependency...

**Comment by objorke** [comment]
New issues should be created for the current limitations

**Comment by Jonarw** [comment]
Covered by #1514.
