### ISSUE TITLE
PlotView Exception with DateTime Axis  Wpf

### ISSUE THREAD

**Issue by propagation** [oxyplot/oxyplot#852]
### Steps to reproduce

1.  Create a plot with a datetime axis

### Expected behaviour

Should display a plot with datetime axis

### Actual behaviour

Exception is generated.

Can you also include a screen shot?

![image](https://cloud.githubusercontent.com/assets/18452120/14529113/dcd9a9ea-0207-11e6-8375-6afac73d4141.png)

**Comment by Jonarw** [comment]
Was introduced by https://github.com/oxyplot/oxyplot/commit/6462a92aa0ef414606f2bd01fd3032136c2bb408 . Easy fix, just use `Axis.ToDouble` instead of `Convert.ToDouble`.
