### ISSUE TITLE
Broken DateTimeAxis labels auto-format

### ISSUE THREAD

**Issue by justslon** [oxyplot/oxyplot#857]
### Steps to reproduce

1. Add DateTimeAxis with StringFormat == null

### Expected behaviour

While zooming axis labels format must change.

### Actual behaviour

ActualStringFormat equals "g6" after calling Axis.UpdateIntervals. It is "invalid" format for DateTimeAxis. I think bug was introduced with this commit: 634068013eb701c4bf8405f1ae569591d0ec08cf 4 days ago. DateTimeAxis class calls base.UpdateIntervals() method and ActualStringFormat becomes "g6", so auto-formatting code in DateTimeAxis.UpdateIntervals doesn't works properly, because ActualStringFormat != null.
![datetimeaxisbug](https://cloud.githubusercontent.com/assets/1931850/14580055/94987cea-03da-11e6-8b6d-81d1488206b8.png)

**Comment by Jonarw** [comment]
You are absolutely right. I think the `UpdateIntervals()` in `DateTimeAxis` should check `StringFormat` for `null` rather than `ActualStringFormat`.
