### ISSUE TITLE
DatetimeAxis's label doesn't show

### ISSUE THREAD

**Issue by windymonkey** [oxyplot/oxyplot#860]
### Steps to reproduce

1. Create a plot with a datetime axis

`//define datetimeaxis
 PlotModel.Axes.Add(new DateTimeAxis { Position = AxisPosition.Bottom});
`
2. Updating plot every one second

`//Add new datapoint
 line.Points.Add(new DataPoint(Axis.ToDouble(DateTime.Now), random.Next(1, 30)));`

Platform:
.NET version: 4.5
lib version: 1.0.0-unstable2100

### Expected behaviour
The plot show up with correct axis label.

### Actual behaviour
The lable is wrong, it doesn't show datetime value. I was tried the same code with lower library version(unstable2044) and it works fine???
Here the screenshot:
[](url
![datetimeaxiserror](https://cloud.githubusercontent.com/assets/7168911/14625792/5127e936-0610-11e6-874c-42162d2ab560.PNG)

@Jonarw Would you have me out of this.
Thanks

**Comment by Jonarw** [comment]
Should be fixed by https://github.com/oxyplot/oxyplot/pull/858, we just have to wait for @objorke to merge it, shouldn't be too long :)
Until that, you could set the `DateTimeAxis.StringFormat` yourself to something like `"yyyy-MM-dd"` or whatever you need.

**Comment by windymonkey** [comment]
OK, thank you @Jonarw
