### ISSUE TITLE
[StoreApps] Direct2D based rendering

### ISSUE THREAD

**Issue by tibel** [oxyplot/oxyplot#868]
Microsoft has created **Win2D** WinRT wrapper for using Direct2D in Windows Store (UAP) XAML apps. We don't want to use Win2D but SharpDX (as for WPF) for rendering, but the samples might help to create a lean and performant interop layer.

References:
- https://github.com/Microsoft/Win2D
- https://github.com/sharpdx/SharpDX-Samples/tree/master/StoreApp
- https://blogs.msdn.microsoft.com/windowsappdev/2012/03/15/combining-xaml-and-directx/
- https://msdn.microsoft.com/en-us/library/windows/apps/hh825871.aspx

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-sharpdx
