### ISSUE TITLE
Wpf: Add ActualMinimum and ActualMaximum dependency properties

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#87]
**Imported from [http://oxyplot.codeplex.com/workitem/10096](http://oxyplot.codeplex.com/workitem/10096)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-06 23:12
should use BindingMode.OneWayToSource as the ActualMinimum/Maximum properties are ReadOnly

**Comment by tibel** [comment]
This is a duplicate of  #424. This will be closed in favor of the newer issue that is driven by the community instead of an imported one.
