### ISSUE TITLE
Gridlines cropping

### ISSUE THREAD

**Issue by Soarc** [oxyplot/oxyplot#870]
# Proposal
When multiple axis are used, currently it is possible to control axis position on the plot using Start/EndPosition properties. But gridlines are rendered from one end to another (red lines on picture below). 

![image](https://cloud.githubusercontent.com/assets/3385495/14783641/13a7d458-0b02-11e6-8fa6-b137922e7b44.png)

It would be nice to have option to control gridlines length. See expected result on picture below.

![image](https://cloud.githubusercontent.com/assets/3385495/14783714/811f461a-0b02-11e6-9dc5-a511835ea156.png)

## Implementation
I suggest to add Start/EndPosition properties to Axis class with default values 0 and 1 respectively for compatibility.

**Comment by objorke** [comment]
This is a good idea, but we need to think more about how to design it! You need a array of start/end positions. Any easier solutions?

**Comment by Soarc** [comment]
We can use for the XAxis gridline YAxises start/end positions and indicate this behavior with boolean property.

**Comment by objorke** [comment]
sounds good!
