### ISSUE TITLE
oxyplot.org website unavailable - DNS problem

### ISSUE THREAD

**Issue by cjstephen** [oxyplot/oxyplot#874]
oxyplot.org and docs.oxyplot.org websites are unavailable

whois says the nameservers are  NS1.MANGO.ARVIXE.COM  NS2.MANGO.ARVIXE.COM
but the oxyplot.org hostnames cannot be resolved, so the built documentation is not accessible
This has been the case for at least a week, so presumably not a temporary outage

$ dig oxyplot.org

; <<>> DiG 9.10.3-P4 <<>> oxyplot.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 6007
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;oxyplot.org.                   IN      A

;; Query time: 47 msec
;; SERVER: 137.205.205.129#53(137.205.205.129)
;; WHEN: Wed May 04 16:16:52 BST 2016
;; MSG SIZE  rcvd: 40

$ dig docs.oxyplot.org

; <<>> DiG 9.10.3-P4 <<>> docs.oxyplot.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 38584
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;docs.oxyplot.org.              IN      A

;; Query time: 13 msec
;; SERVER: 137.205.205.129#53(137.205.205.129)
;; WHEN: Wed May 04 16:17:38 BST 2016
;; MSG SIZE  rcvd: 45

**Comment by scastria** [comment]
Anybody know the IP address of the server so we can bypass DNS in the short term?

**Comment by objorke** [comment]
http://oxyplot.github.io/
http://oxyplot.userecho.com/
Is it possible to access these by IP address?

I tried to delete the CNAME file in http://oxyplot.github.io/ to disable the redirect - does that work?
I have created a topic on userecho since I cannot log in there to change the domain redirect
http://feedback.userecho.com/topics/8738-/
The mango.arvixe.com server is out of service, I hope they can move the oxyplot.org domain to a new server soon.

**Comment by objorke** [comment]
The forum is now available at http://oxyplot.userecho.com/

**Comment by FoggyFinder** [comment]
What about the website http://resources.oxyplot.org/ ?

**Comment by objorke** [comment]
http://oxyplot.github.io/ is working now.
I am considering to move oxyplot.org to a new registrar,..

**Comment by objorke** [comment]
The resource.oxyplot.org site is discontinued. I will not host the Silverlight example browser any more.

**Comment by FoggyFinder** [comment]
Too bad

**Comment by objorke** [comment]
I have set up forwarding of oxyplot.org to http://oxyplot.github.io/

**Comment by objorke** [comment]
@FoggyFinder You can still run the Example browser on Silverlight (as well as all the other platforms) locally.

**Comment by objorke** [comment]
Moved the domain to a new registrar.
Should be working again.
