### ISSUE TITLE
Add support for Xamarin.Forms 2.2 on Android

### ISSUE THREAD

**Issue by scastria** [oxyplot/oxyplot#877]
If I upgrade to Xamarin.Forms 2.2, I cannot compile on Android.  I think it is because 2.2 requires Android API 23 which has resource changes.  I think oxyplot just needs to be recompiled with API 23 sdk and published on nuget?

**Comment by scastria** [comment]
I made a pull request to update all the files, but I guess someone in authority will have to publish the corresponding nuget packages.

https://github.com/oxyplot/oxyplot-xamarin/pull/5

**Comment by tibel** [comment]
nuspec files need to be updated too
