### ISSUE TITLE
PolarHeatMap fixed size image throws exception

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#88]
**Imported from [http://oxyplot.codeplex.com/workitem/10097](http://oxyplot.codeplex.com/workitem/10097)**

**[_Noctis_](http://www.codeplex.com/site/users/view/_Noctis_)** 2013-11-07 00:50
In the OxyPlot.WPF project, whenever I click on the PolarHeatMap fixed size image, it crashes.

Seems width is not a number :) 

Here's a screenshot

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-07 08:31
Cannot reproduce this. It seems to work fine in version 2013.2.119.1

**[_Noctis_](http://www.codeplex.com/site/users/view/_Noctis_)** 2013-11-07 10:31
Sneaky ...sneaky ... just released a new version, eh ... ?

K, will download the new one and have a look :)

Cheers

**[_Noctis_](http://www.codeplex.com/site/users/view/_Noctis_)** 2013-11-07 10:44
Getting the same in 2013.2.119.1, it's the "Debug.Assert(width >= 0, "Width should be larger than 0.");"

Also, in the mainpage, you can update the last release date ... still claiming it's sometime in september..

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-07 11:44
This is strange, I cannot reproduce this, tried both Debug or Release configurations. It also seems to work fine in Silverlight,
<a href="http://oxyplot.org/examplebrowser/" rel="nofollow">http://oxyplot.org/examplebrowser/</a>

I will see if I can get the build script to update the download release date, all this is automated.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
