### ISSUE TITLE
Remove GitVersion?

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#888]
The build fails too frequently on this build step!

**Comment by Isolocis** [comment]
I'm not certain, but maybe this has to do with the fact that some pull requests point to the develop branch of the fork instead of to a separate branch?

**Comment by tibel** [comment]
We could create an issue at https://github.com/GitTools/GitVersion to get some more details what and why it fails.

**Comment by objorke** [comment]
Yes, I agree an issue on GitVersion should be created. Can one of you do it? I have very limited time to follow it up at the moment...
The last failing build is https://ci.appveyor.com/project/objorke/oxyplot/build/1.0.1189-deggdabb
see line 1065

**Comment by GeertvanHorrik** [comment]
I think this issue has been addressed in a later version of GitVersion.

**Comment by VisualMelon** [comment]
Closing: we don't use git version anywhere anymore. Can be reopened or a new issue opened if we want to reintegrate it.
