### ISSUE TITLE
New versions on nuget.org?

### ISSUE THREAD

**Issue by Jonarw** [oxyplot/oxyplot#896]
It seems that the oxyplot package on nuget.org is no longer updated with the latest builds - version 2100 (April 11) is still listed as the most recent version, which is a shame, as this version contains some inconvenient bugs which were fixed since then. Especially the DateTimeAxis with ItemsSource is completely broken in this build.

Is there any change the nuget-package will be updated soon?

**Comment by Zeokat** [comment]
I go to post exact same Issue but you was faster than me, for example in Windows Forms package of Nuget we still have the tracker issue https://github.com/oxyplot/oxyplot/issues/846

I also need WinForms Nuget package updated because actual ones breaks functionality.

:+1:  to @Jonarw request.

**Comment by tibel** [comment]
You can use https://www.myget.org/F/oxyplot instead of the official nuget feed for pre-release packages.

**Comment by objorke** [comment]
I have created a post http://www.oxyplot.org/announcements/nuget-packages
And updated the repository readme page

**Comment by jeffklawiter** [comment]
Using the posting at http://www.oxyplot.org/announcements/nuget-packages does not work. First it asked me to login to MyGet. After doing that it just gives me a page about setting up feeds. It seems as though the feeds are not public.

using the link you posted above https://www.myget.org/F/oxyplot gives me a near empty feed

`<?xml version="1.0" encoding="utf-8"?><service xml:base="https://www.myget.org/F/oxyplot/" xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom"><workspace><atom:title>Default</atom:title><collection href="Packages"><atom:title>Packages</atom:title></collection><collection href="Screenshots"><atom:title>Screenshots</atom:title></collection></workspace></service>`

**Comment by Jonarw** [comment]
Awesome, thank you!
