### ISSUE TITLE
Position of axis title

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#9]
**Imported from [http://oxyplot.codeplex.com/workitem/9594](http://oxyplot.codeplex.com/workitem/9594)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2011-11-18 06:22
Wrong position of axis title when angle is != 0.

**[brantheman](http://www.codeplex.com/site/users/view/brantheman)** 2012-05-30 22:46
I agree. The titles are centered, when I think an angled label is expected to be mid-left oriented such that the text starts aligned with the column bar. And we don't want the text on the graph itself. Even moving it down still leaves the text way too
 far left.

**[brantheman](http://www.codeplex.com/site/users/view/brantheman)** 2012-05-30 23:30
I thought at first that this text was being rendered by the ColumnSeries RenderLabel method. That's nice because I could override that method (and use an ugly hack to get at the internal ValidItemsIndexInversion). However, that method is not hit. Rather
 it appears that the text is rendered in the HorizontalAndVerticalAxisRenderer class, and I have no way to inject my inheritor of that class. (And that class is not modular enough to overload in a decent fashion.) In general, I think OxyPlot could benefit a
 lot from an IoC approach to overriding the rendering.

**[brantheman](http://www.codeplex.com/site/users/view/brantheman)** 2012-05-31 00:25
I attempted to find all children TextBlock objects and update their transform. However, the chart is rendered in the CompositeTarget.Rendering method. I have no way to know when that is done processing. There's not a single virtual method in PlotModel
 (period) that I can override to determine when the rendering is done. Somebody throw me a bone...

**[objo](http://www.codeplex.com/site/users/view/objo)** 2012-06-04 22:25
I guess you mean the axis values (numbers, category name, date, time), not the titles?

And this is only a problem on horizontal axes?

I tried the following model:

<pre><code>    [Example("Angled axis numbers")]
    public static PlotModel AngledAxisNumbers()
    {
        var model = new PlotModel("Angled axis numbers");
        model.Axes.Add(new LinearAxis(AxisPosition.Bottom, -1, 1, "Bottom axis") { Angle = 45 });
        model.Axes.Add(new LinearAxis(AxisPosition.Left, -1, 1, "Left axis") { Angle = 45 });
        model.Axes.Add(new LinearAxis(AxisPosition.Top, -1, 1, "Top axis") { Angle = 45 });
        model.Axes.Add(new LinearAxis(AxisPosition.Right, -1, 1, "Right axis") { Angle = 45 });
        return model;
    }
</code></pre>
Is this reproducing your issue properly?

We should correct the bug on the horizontal alignment for the rotated values.

Can also make more of the rendering virtual as you suggest, that is probably a good idea!

**[brantheman](http://www.codeplex.com/site/users/view/brantheman)** 2012-06-05 19:10
Yes, the axis values should not be centered when using the Angle feature. I made a fork entitled OxyPlotTickFixes that now contains some virtual methods. Using those I was able to work around this issue with my own inheritor of CategoryAxis like this:

private class SlantCategoryAxis: CategoryAxis

{

<pre><code>public SlantCategoryAxis(): base(AxisPosition.Bottom)
{
    Angle = 25;
    IsTickCentered = false;
    AxisTickToLabelDistance = 0;
}

private class SlantRenderer: HorizontalAndVerticalAxisRenderer
{
    public SlantRenderer(IRenderContext rc, PlotModel plot) : base(rc, plot) { }

    protected override void GetAxisLabelRotatedAlignments(double angle, HorizontalTextAlign defaultHorizontalAlignment, VerticalTextAlign defaultVerticalAlignment, out HorizontalTextAlign ha, out VerticalTextAlign va)
    {
        ha = HorizontalTextAlign.Left;
        va = VerticalTextAlign.Middle;
    }
}

public override AxisRendererBase CreateRenderer(IRenderContext rc, PlotModel model)
{
    return new SlantRenderer(rc, model);
}</code></pre>
}

**[EvaldsUrtans](http://www.codeplex.com/site/users/view/EvaldsUrtans)** 2013-10-18 11:38
You can also make some changes in HorizontalAndVerticalAxisRenderer class 

If you have code:

<pre><code>CategoryAxis categoryAxis = new CategoryAxis 
{ 
    Position = AxisPosition.Bottom,
    AxislineStyle = LineStyle.Solid,
    TickStyle = TickStyle.None,
    IsPanEnabled = false,
    IsZoomEnabled = false,
    Angle = 45,
    IsTickCentered = false,
    AxisTickToLabelDistance = 10
};</code></pre>
You can add these lines in Oxyplot\Render\HorizontalAndVerticalAxisRenderer.cs:

<pre><code>var pt = new ScreenPoint();
var ha = HorizontalAlignment.Right;
var va = VerticalAlignment.Middle;
switch (axis.Position)
{
    case AxisPosition.Left:
        pt = new ScreenPoint(axisPosition + a1 - axis.AxisTickToLabelDistance, transformedValue);
        this.GetRotatedAlignments(
            axis.Angle, HorizontalAlignment.Right, VerticalAlignment.Middle, out ha, out va);
        break;
    case AxisPosition.Right:
        pt = new ScreenPoint(axisPosition + a1 + axis.AxisTickToLabelDistance, transformedValue);
        this.GetRotatedAlignments(
            axis.Angle, HorizontalAlignment.Left, VerticalAlignment.Middle, out ha, out va);
        break;
    case AxisPosition.Top:
        pt = new ScreenPoint(transformedValue, axisPosition + a1 - axis.AxisTickToLabelDistance);
        this.GetRotatedAlignments(
            axis.Angle, HorizontalAlignment.Center, VerticalAlignment.Bottom, out ha, out va);
        break;
    case AxisPosition.Bottom:
        pt = new ScreenPoint(transformedValue, axisPosition + a1 + axis.AxisTickToLabelDistance);
        this.GetRotatedAlignments(
            axis.Angle, HorizontalAlignment.Center, VerticalAlignment.Top, out ha, out va);
        break;
}

//Add following block
if(axis is CategoryAxis)
{
    if(axis.Angle != 0.0)
    {
        ha = HorizontalAlignment.Left;
        va = VerticalAlignment.Middle;
    }
}</code></pre>

**[objo](http://www.codeplex.com/site/users/view/objo)** 2014-07-10 12:15
Please create a pull request including an example!

**Comment by objorke** [comment]
I think this may be fixed with #301. See #300 and #303.

**Comment by tibel** [comment]
According to our guidelines https://github.com/oxyplot/oxyplot/blob/develop/CONTRIBUTING.md we will close this issue. Feel free to re-open, when you have new information.
