### ISSUE TITLE
poor drawing performance for large AreaSeries with many NaN points

### ISSUE THREAD

**Issue by hessbe** [oxyplot/oxyplot#902]
I have a plot with an AreaSeries which has around 200 areas separated by NaN points. This takes like 30 seconds to simply draw it once, panning and zooming is not really possible.

I've checked the code with a profiler and found the following:
Before rendering an AreaSeries, all the points must be split up into groups by NaN points. This is done with Linq (AreaSeries::Split) and generators (yield return). The resulting datatype of that list is  `IEnumerable<IEnumerable<DataPoint>>`, so a list of groups which can be each drawn as polygon.

This enumerator is used several times in the method AreaSeries::Render (Count, ElementAt), which forces the iterator to go through the list many times.
Replacing the lines (beginning of AreaSeries::Render)
`var chunkedListsOfPoints = this.Split(actualPoints, p => double.IsNaN(p.Y));`
`var chunkedListsOfPoints2 = this.Split(actualPoints2, p => double.IsNaN(p.Y));`
with 
`var chunkedListsOfPoints = this.Split(actualPoints, p => double.IsNaN(p.Y)).Select(x => x.ToList()).ToList();`
`var chunkedListsOfPoints2 = this.Split(actualPoints2, p => double.IsNaN(p.Y)).Select(x => x.ToList()).ToList();`
improves the performance significantly.

Another improvement would be to only calculate the groups if the data is actually changed, not in every draw cycle (also mentioned in #476 for other series).

With those changes, the framerate is still low but usable low (like 10fps) instead of waiting half a minute to redraw.

**Comment by hessbe** [comment]
I think this is fixed by fixing #834 as the complete rendering code was rewritten and the enumeration issue is gone

**Comment by objorke** [comment]
thanks for the notice! I will close this issue
