### ISSUE TITLE
Exception showing in realtime plot area

### ISSUE THREAD

**Issue by SquanchOn** [oxyplot/oxyplot#906]
### Steps to reproduce

1. Create multiple series which update in background worker threads
2. set the series to add new points every 100ms and redraw using Model.InvalidatePlot(true);
3. observe the plot area in view

Platform:         Windows 10 / Visual Studio 2015 / WPF
.NET version: 4.6.01038

### Expected behaviour

plot should display successfully

### Actual behaviour

updates will occasionally (maybe every 10 -20 seconds) result in the plot not being drawn, and an exception being drawn in place of the plot area

Exception shown in screenshot:

![image](https://cloud.githubusercontent.com/assets/18159747/15703083/1ef8334e-2816-11e6-9d10-51eba9665fa9.png)

**Comment by SquanchOn** [comment]
ah, managed to find help on this through an "idea" post - the solution (if anybody else has this issue) was to use lock (Model.SyncRoot) where the model was being updated

**Comment by SquanchOn** [comment]
this was the discussion that resolved the issue for me:

http://discussion.oxyplot.org/topics/78-thread-safety-and-renderpoints/

**Comment by flyaim** [comment]
great！this resolved my issue too。thanks！
