### ISSUE TITLE
This PlotModel is already in use by some other plot control

### ISSUE THREAD

**Issue by acidos** [oxyplot/oxyplot#909]
### Steps to reproduce

1. Create WindowsForm project in VisualStudio 2015 
2. Add OxyPlot.Core.2015.1.708-alpha and OxyPlot.WindowsForms.2011.10.1 through Nuget
3. Add OxyPlot.WindowsForms.dll into toolbox
4. Place Plot into Form
5. Run

Platform:
.NET version: 4.5

### Expected behaviour

Expected to see an Windows Form

### Actual behaviour

Exception in `Form1.Designer.cs` line `this.plot1.Model = plotModel2;`
`This PlotModel is already in use by some other plot control`. 

Commenting only that line helps to solve the problem.

**Comment by objorke** [comment]
The OxyPlot.WindowsForms dependency should have the same version number as the OxyPlot.Core
