### ISSUE TITLE
Margin between axis title and labels

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#91]
**Imported from [http://oxyplot.codeplex.com/workitem/10100](http://oxyplot.codeplex.com/workitem/10100)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-11-28 20:40
Specify a margin between the axis title and the labels (numeric values or category strings).

Default value can be 0 as today, but it would be nice to be able to add some more whitespace here.

**Comment by forum111** [comment]
Yes. This is a bug. 
Just set axis.Titel or plot.Title with spaces
Plot.Title = "                    MY Chart              ";

this will fix your problem when you edit title.

**Comment by ShannonZ** [comment]
How to solve it?

**Comment by VahedCivil** [comment]
Hi
You can set the AxisTitleDistance  property of LineSeries to your own value.
This is a Code Snippets of my projects. It's may be useful for you:
