### ISSUE TITLE
LogarithmicColorAxis

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#92]
**Imported from [http://oxyplot.codeplex.com/workitem/10101](http://oxyplot.codeplex.com/workitem/10101)**

**[objo](http://www.codeplex.com/site/users/view/objo)** 2013-12-02 13:18
Implement a logarithmic color axis - similar to LinearColorAxis.

**Comment by WEKarnesky** [comment]
I would also like to see this feature.  It seems relatively simple and I would do it myself, if my dev environment (at work behind very restrictive security rights) prevents me from installing the windows phone kit components required to build oxyplot.
