### ISSUE TITLE
Oxyplot lineSeries only updating when mouse is over plot

### ISSUE THREAD

**Issue by lukapi** [oxyplot/oxyplot#920]
Dear support team,
We are using Oxyplot to plot a set of Datapoints as Lineseries in a C# WPF project. We looked at your performance guidlines and keep them in mind during implementation.
Nevertheless we only faced the performance/fps we expect when we move the mouse over the running plot. When the mouse coursor is not over the running plot it looks like the plot is hanging and not updating data. 
Is this an issue related to WPF in combination with oxyplot or is there something else I can do programmaticaly regarding oxyplot?
Thanks for your supporti n advance!
Regards

**Comment by objorke** [comment]
Can you reproduce this behaviour in any of the included examples?

**Comment by lukapi** [comment]
This issue happens only when gathering live data with a light source and then trying to plot the spectrum with oxy plot. When plotting the spectrum data with offline data oxy plot works as expected.

**Comment by zigul** [comment]
Hi,
the behaviour can be reproduced by  WpfExamples.Examples.RealtimeDemo by waves simulation. The plot is freeze during moving cursor over the plot.
This can be solved by set DispatcherPriority in method BeginInvoke(Action action) in OxyPlot.Wpf.PlotBase (line 606). DispatcherPriority is set to Background now. The mouse inputs are fired with DispatcherPriority.Input (see https://msdn.microsoft.com/cs-cz/library/system.windows.threading.dispatcherpriority(v=vs.110).aspx)
My proposed solution for this is set DispatcherPriority to Loaded, it solves this issue.
Maybe the better solution is to make it configurable through some property.

**Comment by objorke** [comment]
I merged #933. Does this solve the issue? Should we add a property that defines the priority?

**Comment by lukapi** [comment]
Hi, Sorry for the late answer.
I have used the latest release and it work much better now!
Many thanks.
