### ISSUE TITLE
different axis

### ISSUE THREAD

**Issue by MannusEtten** [oxyplot/oxyplot#927]
i have three questions

1) can the control do some overflowing? we need a really long (wide) graph, will there be a scrollbar in such a way that we also can determine what is the visible range of the graph?

2) the y-axis cells can be for example be two times heigh than the x-axis width? it is not only cartesian?

3) if we export a huge graph to pdf, will it be fitted into one page or cut and distributed over several pages?

**Comment by objorke** [comment]
Please create separate issues for different topics! :-)

1) This could be a new feature. I don´t think we should use native scroll bars, but could implement something similar in portable code.
2) #86 should cover this
3) only one page is supported, use other tools to split into multiple pages

**Comment by objorke** [comment]
I added #932 for (1)
