### ISSUE TITLE
Example Browser not working

### ISSUE THREAD

**Issue by riegaz** [oxyplot/oxyplot#928]
I can't reach http://resources.oxyplot.org/examplebrowser/

Also the ExampleBrowser Application offered in the Windows store seems outdated and mouse events do not work.

**Comment by objorke** [comment]
Where did you find the link? The Silverlight example browser has been discontinued. I will remove the Windows store app, can´t spend time keeping it up to date (manual work).
Clone the repository and build yourself to try the example browsers! :-)

**Comment by riegaz** [comment]
The link is still present on Google. I see, I will build it. Thanks a lot!
