### ISSUE TITLE
Avalonia support

### ISSUE THREAD

**Issue by DraTeots** [oxyplot/oxyplot#941]
There is very promising cross platrofm UI framework called Avalonia

https://github.com/AvaloniaUI/Avalonia

> A multi-platform .NET UI framework. It can run on Windows, Linux, Mac OS X, iOS and Android. Avalonia is a multi-platform windowing toolkit - somewhat like WPF - that is intended to be multi- platform. It supports XAML, lookless controls and a flexible styling system, and runs on Windows using Direct2D and other operating systems using Gtk & Cairo.

This ticket is about adding OxyPlot support for it

**Comment by jkoritzinsky** [comment]
Hi @DraTeots I'm planning on working on this very soon (after the next Avalonia release which is within a few weeks).
