### ISSUE TITLE
Target .NET standard library for OxyPlot core

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#946]
https://docs.microsoft.com/en-us/dotnet/standard/library

**Comment by objorke** [comment]
Do we need to build for .NET standard, or can we simply add a new target moniker in the .nuspec?

**Comment by objorke** [comment]
Which netstandard? 1.1?

**Comment by clarkis117** [comment]
@objorke netstandard 1.1 would allow it to target the most platforms, but in my experience it significantly narrows the available API surface.

**Comment by GeertvanHorrik** [comment]
I suggest waiting for .NET standard 2.0

**Comment by clarkis117** [comment]
Except that would mean, the project would be abandoning older platforms that don't support .NET Standard 2.0, which is an API level not a version.

**Comment by GeertvanHorrik** [comment]
Agree, but which "older platforms" are we talking about? And it would only mean they won't get 2.0, they can always use 1.0 instead (which is also stable).

**Comment by clarkis117** [comment]
what 1.0 version are you talking about?

**Comment by GeertvanHorrik** [comment]
OxyPlot 1.0

**Comment by clarkis117** [comment]
I hope you realize that .NET Standard 2.0 isn't supported on .NET Framework 4.5.x or .NET 4.6.x

**Comment by GeertvanHorrik** [comment]
Technically speaking, I think it will be supported on all platforms that MS still supports. I believe 4.5.x isn't even supported by MS.

**Comment by clarkis117** [comment]
Extended support for .NET Framework 4.5.2 ends in 2020 with Windows 7 end of support.

**Comment by GeertvanHorrik** [comment]
But it's still possible to use OxyPlot 1.0 for people not wanting to upgrade? Or is that version really bad so it will not suffice? We are using 1.0 on a lot of projects, all working fine so not sure if you are really missing out on something.

**Comment by objorke** [comment]
In PR #1100 I suggest to change:
- OxyPlot.Core to netstandard1.0
- OxyPlot.Wpf to .NET 4.5.2
Trying to build now, need to do more testing before we merge...
