### ISSUE TITLE
TrackerHitResult.Index should be an integer (not a double)

### ISSUE THREAD

**Issue by Tominick** [oxyplot/oxyplot#953]
Hi,
I would expect the Index property for oxyplot\Source\OxyPlot\PlotController\Manipulators\TrackerHitResult.cs to be an integer, instead I got a double (it is not a big deal, just an unexpected cast ;-)).

Thanks for this beautiful chart library!

**Comment by objorke** [comment]
The reason for choosing `double` was that it is possible to return interpolated points e.g. on a `LineSeries`. I think that is a good feature, but maybe it can be implemented in other ways? Use `int` for the index + a `double` for the interpolation fraction?

**Comment by Tominick** [comment]
Thanks for the explanation. I would not change anything... Index was just an unfortunate name for my understanding.
