### ISSUE TITLE
Add support for Xamarin.Forms 2.3 on Android

### ISSUE THREAD

**Issue by prajithmp** [oxyplot/oxyplot#954]
need support for Xamarin.Forms 2.3 on Android, i am facing same issue as of 
https://github.com/oxyplot/oxyplot/issues/877 now in 2.3

**Comment by MKahmen** [comment]
@prajithmp any updates on this?

I'm stuck here, too...

**Comment by objorke** [comment]
We should move all Xamarin related issues to https://github.com/oxyplot/oxyplot-xamarin/issues

**Comment by objorke** [comment]
I added https://github.com/oxyplot/oxyplot-xamarin/issues/13
