### ISSUE TITLE
Remove support for .NET 4.0

### ISSUE THREAD

**Issue by objorke** [oxyplot/oxyplot#960]
Remove all the NET40 project files (requires manual sync)
Simplify the build and packages
Smaller solutions

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by objorke** [comment]
Can wait with this until we have released a stable package.

**Comment by psc161** [comment]
Hello,
we still have to use Visual Studio 2010 and won't be able to upgrade any time soon.
So canceling the support for .Net 4.0 will prohibit us from using newer versions of Oxyplot.

**Comment by AlexeiScherbakov** [comment]
Microsoft now is developing new build tool (.NET Core Tooling) with multi framework build function and it will eliminate all framework specific projects. So I suggest to wait until Q4 2016/Q1 2017 (https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/)

**Comment by GeertvanHorrik** [comment]
I can remove these files if you want.

**Comment by objorke** [comment]
@GeertvanHorrik thanks, but I can try to remove the files myself :-)
