### ISSUE TITLE
line annotation not moving smoothly on windows phone using touch events..

### ISSUE THREAD

**Issue by joshisunil-1983** [oxyplot/oxyplot#964]
_IF BUG, INCLUDE THIS PART:_
### Steps to reproduce
1. Add line annotation.

```
var la = new OxyPlot.Annotations.LineAnnotation { Type = OxyPlot.Annotations.LineAnnotationType.Vertical, X = DateTimeAxis.ToDouble(DictVarData.ElementAt(0).Name), Tag = model.Annotations.Count + 1 };

la.TouchStarted += (s, f) =>
            {
                la.StrokeThickness *= 1;
                model.InvalidatePlot(false);
                f.Handled = true;

            };
la.TouchDelta += (s, f) =>
            {
                la.X = la.InverseTransform(f.Position).X;
model.InvalidatePlot(false);
                f.Handled = true;
};
            la.TouchCompleted += (s, f) =>
            {
                la.StrokeThickness /= 1;
                model.InvalidatePlot(false);
                f.Handled = true;
            };
```
1. on touch delta line annotation x in changed as per position of touch.

Platform: Windows phone 8.1
.NET version: visual studio 2013
### Expected behaviour

line not moving immediately and smoothly on chart. as it moving on mouse events. line annotation should move immediately as like mouse events in example browser.
### Actual behaviour

line moving slow and screen not refreshed immediately.

@objorke @tibel @TheAlmightyBob

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-winphone
