### ISSUE TITLE
Tap event missing on Text annotation and image annotations for windows phone 8.1.

### ISSUE THREAD

**Issue by joshisunil-1983** [oxyplot/oxyplot#966]
_IF BUG, INCLUDE THIS PART:_
### Steps to reproduce
1.  Tap event missing on Text annotation and image annotations
2.   i try for test annotation and image annotation both i don't find tap event for both.

Platform:
.NET version:
### Expected behavior

Tap event needs to be defined separately for both so actions can be performed on tap of both type of annotations.
### Actual behavior

Mouse events working fine for web but mobile app not. one more thing i want to tell you about text annotation. I add two text annotations on plot and give one's text is "+" and the another's text  is "-".
But both of the annotations take different height and width.

**Comment by joshisunil-1983** [comment]
@objorke any update on issue.

**Comment by objorke** [comment]
Kamino closed and cloned this issue to oxyplot/oxyplot-winphone
