### ISSUE TITLE
WindowsPhone8.1 Support with OxyPlot.WP8

### ISSUE THREAD

**Issue by tkgdsg** [oxyplot/oxyplot#984]
### Feature description

WindowsPhone8.1 Support with OxyPlot.WP8.

At this point nuget does not install OxyPlot.WP8 package into WindowsPhone8.1 project with an error 
`"You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1'"`

% OxyPlot already supports WindowsPhone8 , so I think it's done to add a description 
`<file src="..\..\Output\WP8\OxyPlot.WP8.???" target="lib\windowsphone8.1" />`
in OxyPlot.WP8 nuspec file.

too optimistic?

**Comment by tibel** [comment]
Wrong package. For Windows Phone App 8.1 (wpa81) you have to use _OxyPlot.Windows_ package.
The _OxyPlot.WP8_ package is for Silverlight based Windows Phone projects.

**Comment by tkgdsg** [comment]
Thank you for your comment.
Exactly what you are saying...
I'm sorry for bothering you.

**Comment by objorke** [comment]
Can't the WP8 and Windows package be merged? Added #996
