### ISSUE TITLE
Would be nice to have to set Axes' names in XAML for Plot.Series

### ISSUE THREAD

**Issue by marvel16** [oxyplot/oxyplot#986]
*IF BUG, INCLUDE THIS PART:*

### Steps to reproduce

1.  unable to set axe names/units for line series
2. Launch official wpf example
3. No axe naming

Platform:
.NET version:

### Expected behaviour
Xaml properties for Plot.Series exist: e.g. XAxeName, YAxeName
### Actual behaviour
unable to set axe names/units for line series because there are no xaml properties for this

*IF IT IS A NEW FEATURE REQUEST, INCLUDE THIS PART:*

### Feature description

Write a description of the feature. How should it work? How should it look?
Include some graphics if this could help!

**Comment by objorke** [comment]
The titles and units are set on the axes, not the series.

**Comment by marvel16** [comment]
so i can't add axe scale naming for series?
E.g. i want to have there X "time, ms" Y "current, Amps" ?

**Comment by objorke** [comment]
The axis titles are set on the axes, not on the series.
Can we close this issue?

**Comment by marvel16** [comment]
Yes
